### ISSUE TITLE
module creates RT per AZ

### ISSUE THREAD

**Issue by FernandoMiguel** [terraform-aws-modules/terraform-aws-vpc#10]
I noticed my tf was creating one routing table per private AZ, while would expect it to be per group of private subnets across multiple AZs

Code issue is at:
https://github.com/terraform-aws-modules/terraform-aws-vpc/blob/master/main.tf#L48

**Comment by antonbabenko** [comment]
This can't be done automatically, because we may have multiple NAT Gateways (1 per AZ), so each subnet uses different route tables.
