### ISSUE TITLE
Error downloading modules: Error loading modules: module vpc: Error loading 

### ISSUE THREAD

**Issue by sandyws** [terraform-aws-modules/terraform-aws-vpc#100]
Error downloading modules: Error loading modules: module vpc: Error loading /root/terraform/configurations/vpcmodule/.terraform/modules/9106ddebf98a46a763539c43da7ae39f/main.tf: local.max_subnet_length: resource variables must be three parts: TYPE.NAME.ATTR in:

${var.create_vpc && local.max_subnet_length > 0 ? local.max_subnet_length : 0}

Tried providing source in different ways:

source = "github.com/terraform-aws-modules/terraform-aws-vpc//examples//complete-vpc"
source = "github.com/terraform-aws-modules/terraform-aws-vpc"

**Comment by antonbabenko** [comment]
You should use this:

```
module "vpc" {
  source = "terraform-aws-modules/vpc/aws"
  # ...
}
```

Fee free to reopen if problem persists.
