### ISSUE TITLE
Manually set NAT GATEWAY Private IP

### ISSUE THREAD

**Issue by jnaranj09** [terraform-aws-modules/terraform-aws-vpc#1003]
In the AWS provider, we can manually set a private IP address to the NAT gateway
https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/nat_gateway

I'm using temporary AWS sandboxes and sometimes the NAT GATEWAY gets the same private IP address I'm manually assigning to an EC2 instance, so the creation of the EC2 instance fails because of this.

**Comment by bryantbiggs** [comment]
This is possible by using:
```hcl
  reuse_nat_ips       = true 
  external_nat_ip_ids = [<list your EIPs>]
```
