### ISSUE TITLE
Support for instance-based NAT

### ISSUE THREAD

**Issue by booi** [terraform-aws-modules/terraform-aws-vpc#1004]
## Is your request related to a new offering from AWS?

No

## Is your request related to a problem? Please describe.

We run a number of nearly identical test environments (dev, test, demo, sandbox) which helps us test and roll out not only application code but also our infrastructure code. This does end up being fairly pricey though and one of the main costs ends up being the NAT gateway. 

## Describe the solution you'd like.

Would it be possible to have this module optionally run a small instance to do NAT instead of NAT gateway? I know it's not redundant but for many small test environments it would be completely acceptable. It could be provisioned in just 2-3 lines of cloud unit code and use natively available Amazon linux 2 images.

**Comment by bryantbiggs** [comment]
>  It could be provisioned in just 2-3 lines of cloud unit code and use natively available Amazon linux 2 images.

Do you have a reference of this implementation?
