### ISSUE TITLE
Tagging a subnet_id as 'Tier = private'

### ISSUE THREAD

**Issue by IronicBadger** [terraform-aws-modules/terraform-aws-vpc#101]
I'm using this module to create a VPC at present but need a way to loop of private subnet IDs in order to have instances spread appropriately across availability zones.

How might I go about applying the suggesting "Tier = private" as per the official docs to each private subnet? Perhaps I could apply some kind of filter to the names of the created subnets? Don't really care how I get them.

https://www.terraform.io/docs/providers/aws/d/subnet_ids.html

**Comment by antonbabenko** [comment]
This module outputs `private_subnets` which has a list of IDs of private subnets. I believe this is what you need.
