### ISSUE TITLE
support for multipe public route tables

### ISSUE THREAD

**Issue by pedrojflores** [terraform-aws-modules/terraform-aws-vpc#1020]
## Is your request related to a new offering from AWS?
Yes.  This is to better support a vpc hosting an AWS Firewall infrastructure where you need to route traffic from public subnets to an unique firewall interface on a specific az.

## Is your request related to a problem? Please describe.
Yes.  Due to this limitation I can't use this module to build my AWS Firewall Egress vpcs.

## Describe the solution you'd like.
I would like an option that when set a unique route table gets created per public subnet (per az).  Same support the module has for private subnets.

**Comment by nirmesika** [comment]
add support for adding routes to public and private subnets.

**Comment by piartz** [comment]
@pedrojflores I have created a pull request, please let me know if this is what you were looking for, and we can wait for a review. 
https://github.com/terraform-aws-modules/terraform-aws-vpc/pull/1025

Feliz año 2024!

**Comment by piartz** [comment]
Pumping up this issue as it is not stale anymore

**Comment by KevinSnyderCodes** [comment]
I've also created a pull request that expands this to both public and intra subnets: https://github.com/terraform-aws-modules/terraform-aws-vpc/pull/1051

I punted on the other subnet types as their logic was a bit more complex, but it should be possible to support multiple route tables for all subnet types.

**Comment by KevinSnyderCodes** [comment]
Not stale

**Comment by antonbabenko** [comment]
This issue has been resolved in version 5.8.0 :tada:
