### ISSUE TITLE
private_dns_only_for_inbound_resolver_endpoint value for s3 vpc endpoints is ignored.

### ISSUE THREAD

**Issue by shadow-wheel** [terraform-aws-modules/terraform-aws-vpc#1028]
## Description

This is pretty simple.  As a followup to my prior bug report in https://github.com/terraform-aws-modules/terraform-aws-vpc/issues/982, I tested the fix in https://github.com/terraform-aws-modules/terraform-aws-vpc/pull/1023 and noticed that when trying to set the following, the `private_dns_only_for_inbound_resolver_endpoint` flag was still set to false (Note: a prerequisite of this is to have an existing S3 Gateway endpoint so if testing is needed, that will need to be created first before the Interface endpoint with this flag enabled will succeed.)
```
private_dns_enabled = true
      dns_options = {
        private_dns_only_for_inbound_resolver_endpoint = true
      }
```

Upon investigation of the fix, I noticed that `dns_options` was omitted on https://github.com/terraform-aws-modules/terraform-aws-vpc/blob/e4768508a17f79337f9f1e48ebf47ee885b98c1f/modules/vpc-endpoints/main.tf#L42 so the flag passed into the module is ignored.

This can be fixed by updating to `private_dns_only_for_inbound_resolver_endpoint = try(each.value.dns_options.private_dns_only_for_inbound_resolver_endpoint, null)`

I've verified this fix locally but I don't have any experience with PRs to this repo.

- [x] ✋ I have searched the open/closed issues and my issue is not listed.

## Versions

- Module version [Required]:
v5.5.0

- Terraform version:
v1.4.6

- Provider version(s):
+ provider registry.terraform.io/hashicorp/aws v5.32.1

## Reproduction Code [Required]
```
module "vpc_endpoints" {
  source  = "terraform-aws-modules/vpc/aws//modules/vpc-endpoints"
  version = "v5.5.0"

  vpc_id             = module.vpc.vpc_id
  security_group_ids = [module.vpc_endpoints_sg.security_group_id]

  endpoints = {
    s3 = {
      service = "s3"
      service_type = "Interface"
      private_dns_enabled = true
      dns_options = {
        private_dns_only_for_inbound_resolver_endpoint = true
      }
      tags    = { Name = "s3-vpc-endpoint" }
    }
  }
}
```

explained above already.

## Expected behavior

The flag  `private_dns_only_for_inbound_resolver_endpoint` should be true

## Actual behavior

The flag  `private_dns_only_for_inbound_resolver_endpoint` is ignored

**Comment by antonbabenko** [comment]
This issue has been resolved in version 5.5.1 :tada:
