### ISSUE TITLE
NAT routing tables and associations are still created even when using `enable_nat_gateway = false`

### ISSUE THREAD

**Issue by kkonstant-in** [terraform-aws-modules/terraform-aws-vpc#1031]
## Description
We are using this module "terraform-aws-modules/vpc/aws" with `enable_nat_gateway = false` parameter, because our vpc is using a shared transit gateway from a different account with its own NAT gateways.

The issue happens when the module creates 3 extra routing tables by the number of potential NAT gateways. And tries to associate our subnets with them.
After I make the proper association TF always fails. It doesn't hurt, but every TF cloud run becomes red and annoys a lot :)

I believe it can be fixed by adding `&& var.enable_nat_gateway` condition to [the line 254](https://github.com/terraform-aws-modules/terraform-aws-vpc/blob/7666869d9ca7ff658f5bd10a29dea53bde5dc464/main.tf#L254C11-L254C11), but it has to be reviewed and checked.

## Versions

- module version:
   "~> 5.0"
- Terraform version:
   "~> 1.6.0"
- AWS Provider version(s):
   ">= 5.25.0"

## Reproduction Code [Required]
```
module "vpc" {
    source  = "terraform-aws-modules/vpc/aws"
    version = "~> 5.0"

    name = local.name
    cidr = local.vpc_cidr

    azs                 = local.azs
    private_subnets     = [for k, v in local.azs : cidrsubnet(local.vpc_cidr, 2, k)]
    public_subnets      = [for k, v in local.azs : cidrsubnet(local.vpc_cidr, 6, k + 48)]
    intra_subnets       = [for k, v in local.azs : cidrsubnet(local.vpc_cidr, 6, k + 52)]
    database_subnets    = [for k, v in local.azs : cidrsubnet(local.vpc_cidr, 6, k + 55)]
    elasticache_subnets = [for k, v in local.azs : cidrsubnet(local.vpc_cidr, 6, k + 58)]

    private_subnet_names     = ["private-apse-2a", "private-apse-2b", "private-apse-2c"]
    public_subnet_names      = ["public-apse-2a",  "public-apse-2b",  "public-apse-2c"]
    intra_subnet_names       = ["intra-apse-2a",   "intra-apse-2b",   "intra-apse-2c"]
    database_subnet_names    = ["db-apse-2a",      "db-apse-2b",      "db-apse-2c"]
    elasticache_subnet_names = ["ec-apse-2a",      "ec-apse-2b",      "ec-apse-2c"]

    enable_nat_gateway     = false

    create_egress_only_igw = false
    enable_ipv6            = false

    public_subnet_tags = {
        "subnet_type" = "public"
        "kubernetes.io/role/elb" = 1
    }

    private_subnet_tags = {
        "subnet_type" = "private"
        "kubernetes.io/role/internal-elb" = 1
    }

    tags = local.tags
}
```

## Steps to reproduce the behavior:

- Create a VPC by using the code above
- Check the routing tables and associations, you will see 3 extra tables created local.name-private-var.azs.
- Private, database and elasticache subnets get associated with these tables

## Expected behavior

I would expect 1 private routing table for this configuration and all subnets associated with it. After that I can add a route to a shared transit gateway. Shared tgw_id can also be an input for this module. But this is mostly for you to decide.

## Actual behavior

- 3 extra unintentional tables are created
- Private, database and elasticache subnets get associated with these tables

### Screenshot(s)
![Extra routing tables](https://github.com/terraform-aws-modules/terraform-aws-vpc/assets/59636371/0271dc2d-0f1c-4b41-91d5-6ad5fa999a6f)
![Expected associations](https://github.com/terraform-aws-modules/terraform-aws-vpc/assets/59636371/d7a4f8b4-46e5-4c27-9393-b4d4f3cedfc9)
![Target routes](https://github.com/terraform-aws-modules/terraform-aws-vpc/assets/59636371/e81ac3da-0591-4c13-be77-d527b3e2656b)

**Comment by lnkrishnan** [comment]
Yep - I too have observed this behavior.

**Comment by kkonstant-in** [comment]
Hi guys, is there any update on this issue?
