### ISSUE TITLE
Subnets-only deployment to existing VPC

### ISSUE THREAD

**Issue by psantus** [terraform-aws-modules/terraform-aws-vpc#1034]
## Is your request related to a problem? Please describe.
I want to be able to instantiate multiple instances of this module, in order to provide a shared VPC with account-specific subnets.
- Instance A would provide VPC and Gateways
- Instance B, C, D... would provide subnets for test, prep, prod... with their NACL, Route tables, etc. and would rely on Instance A for VPC-level resources. 

## Describe the solution you'd like.
Add several variables
```
subnets_only            = true
vpc_id                  = module.instance_a.vpc_id
egress_only_gateway_id  = module.instance_a.egress_only_internet_gateway_id
aws_internet_gateway_id = module.instance_a.igw_id
nat_gateway_ids         = module.instance_a.natgw_ids
```
Use those IDs with data instead of creating new vcc-level resources.

**Comment by Lock128** [comment]
This is required in organizations where other teams / central teams are providing the VPCs and the corresponding CIDR ranges, too.

**Comment by psantus** [comment]
@antonbabenko @bryantbiggs : would you consider reviewing my PR, if I submit one on this?
