### ISSUE TITLE
VPCs in multiple regions?

### ISSUE THREAD

**Issue by AzCii** [terraform-aws-modules/terraform-aws-vpc#104]
As far as i can see, it's not possible to create one VPC in one region, and another VPC in another region.
I know this could be solved by having a provider per region, but that does not seem to be supported by this module.

Any ideas?

**Comment by antonbabenko** [comment]
You are right, this module does not support `region name` as an argument because the module does not have `provider` block. You should specify it outside of the module like this:

```
provider "aws" {
  region = "eu-west-1"
}

module "vpc" {
  # ...
}
```

**Comment by AzCii** [comment]
Works perfectly, thank you.

```
provider "aws" {
  region = "eu-west-1"
}

provider "aws" {
  alias = "eu-central-1"
  region = "eu-central-1"
}

module "vpc_ireland" {
  ...
}

module "vpc_frankfurt" {
  providers {
    aws = "aws.eu-central-1"
  }
  ...
}
```

**Comment by videte47** [comment]
@AzCii  when I tried to implement your code snippet I get an error from terraform that is unable to get a valid cidr ```module.vpc.aws_vpc.this: expected "cidr_block" to contain a network CIDR with between 16 and 28 significant bits, got: 0```

my code snippet
```
provider ...

module "vpc_eu_central1" {
   source = "../modules/vpc_blueprint"
   providers { aws = "aws.eu-central-1"}
   cidr = "10.0.3.0/24"
}

... modules/vpc_blueprint
module "vpc" {
   ...
   cidr = "${var.cidr}"
   ...
}
```

**Comment by AzCii** [comment]
Reading the error message, I think your var.cidr might be empty or at least not containing an CIDR block

**Comment by antonbabenko** [comment]
I agree with @AzCii , variable `cidr` should be set to a valid CIDR.

**Comment by antonbabenko** [comment]
Also, `10.0.3.0/24` is a valid value for `cidr`.

**Comment by aldegoeij** [comment]
> Works perfectly, thank you.
> 
> ```
> provider "aws" {
>   region = "eu-west-1"
> }
> 
> provider "aws" {
>   alias = "eu-central-1"
>   region = "eu-central-1"
> }
> 
> module "vpc_ireland" {
>   ...
> }
> 
> module "vpc_frankfurt" {
>   providers {
>     aws = "aws.eu-central-1"
>   }
>   ...
> }
> ```

If you like me are ending up here and are on Terraform >=12, don't forget it should be:

```
  providers = {
    aws = "aws.<alias>"
  }
```

> Note the `=` sign after providers, added with TF12

**Comment by dtakis** [comment]
Do you get the following warning in the latest terraform versions?

Warning: Provider aws is undefined
│ 
│   on vpc_mods.tf line 3, in module "vpc_frankfurt":
│    3:     aws = "aws.eu-central-1"
│ 
│ Module module.vpc_frankfurt does not declare a provider named aws.
│ If you wish to specify a provider configuration for the module, add an entry for aws in the required_providers block within the module.

**Comment by antonbabenko** [comment]
@dtakis Try to write without double quotes. `aws = "aws.eu-central-1"` => `aws = aws.eu-central-1`

**Comment by dtakis** [comment]
@antonbabenko thank you! You are correct, this is the correct syntax now.

**Comment by cloudworkpro-derek** [comment]
should be 

`providers = {
    aws = aws.<alias>
  }`
