### ISSUE TITLE
Support for lifecycle ignore_changes to tags

### ISSUE THREAD

**Issue by hemalgadhiya** [terraform-aws-modules/terraform-aws-vpc#1045]
## Is your request related to a new offering from AWS?
Is this functionality available in the [AWS provider for Terraform](https://registry.terraform.io/providers/hashicorp/aws/latest/docs)? See [CHANGELOG.md](https://github.com/hashicorp/terraform-provider-aws/blob/main/CHANGELOG.md), too.
  - Yes ✅: please list the AWS provider version which introduced this functionality

## Is your request related to a problem? Please describe.

I want to able to ignore_changes to tags 

## Describe the solution you'd like.

Specifically for tags add a bool variable wether to ignore changes to tags or not

**Comment by hemalgadhiya** [comment]
@bryantbiggs terraform does support it. I don't my tags to updated
lifecycle {
    ignore_changes = [tags]
  }

**Comment by bryantbiggs** [comment]
no, it does not support variables within the lifecycle blocks as I understand it https://github.com/hashicorp/terraform/issues/33031

if we add what you have provided there 
```hcl
	lifecycle {
		ignore_changes = ["tags"]
	}
```

That will ignore tags for everyone that uses this module and that is not a behavior that the majority would welcome
