### ISSUE TITLE
add a changelog?

### ISSUE THREAD

**Issue by sysadmiral** [terraform-aws-modules/terraform-aws-vpc#105]
Hi,

Thanks for the hard work on this module.

Would it be possible to add a changelog to the module to track version differences?

Github has it's version and there is also [keepachangelog][1] which differs a little bit.

Many Thanks,

Amo

[1]: https://keepachangelog.com/en/1.0.0/ "keepachangelog.com"

**Comment by antonbabenko** [comment]
Yes, it is pretty high on my todo list but I need to find time to make it.

**Comment by kylegoch** [comment]
Yes, please. A changelog is really needed. We had been using an older version of the module, and we bumped to the new version and now the module wants to rip apart our VPC. We have no clue what changed in the module to make that action.

**Comment by antonbabenko** [comment]
Ohh, by the way, there is a CHANGELOG which was introduced in February 2019 - https://github.com/terraform-aws-modules/terraform-aws-vpc/blob/master/CHANGELOG.md

I just forgot to close this issue. Closing it now.
