### ISSUE TITLE
Allow allowed_principals for module vpc-endpoints

### ISSUE THREAD

**Issue by kotowick** [terraform-aws-modules/terraform-aws-vpc#1057]
## Is your request related to a new offering from AWS?
Is this functionality available in the [AWS provider for Terraform](https://registry.terraform.io/providers/hashicorp/aws/latest/docs)? See [CHANGELOG.md](https://github.com/hashicorp/terraform-provider-aws/blob/main/CHANGELOG.md), too.
  - Yes ✅: please list the AWS provider version which introduced this functionality

## Is your request related to a problem? Please describe.
We are using RAM to share vpcs. This means we can only create VPC interface endpoints in the acount that owns the vpcs. It looks like AWS has an option to allow external principles to discover the endpoint.

The key is `allowed_principals`

I don't see this as an option in the terraform-aws-modules/vpc/aws//modules/vpc-endpoints.

## Describe the solution you'd like.
Support for `allowed_principals`

## Describe alternatives you've considered.
No possible alternatives

**Comment by RunCor399** [comment]
I'm giving a look into this but I've noticed that the parameter `allowed_principals` you are referring to is only available when creating a resource of type `aws_vpc_endpoint_service`. However the vpc-endpoints module as of now just uses a [data block to reference existing aws_vpc_endpoint_services](https://github.com/terraform-aws-modules/terraform-aws-vpc/blob/c182453f881ae77afd14c826dc8e23498b957907/modules/vpc-endpoints/main.tf#L11). 

I was thinking that maybe an inline policy defined within the `aws_vpc_endpoint` could be leveraged instead (https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/vpc_endpoint#policy). 

Let me know your thoughts on this.
