### ISSUE TITLE
Enable the setup of fully private NAT Gateways

### ISSUE THREAD

**Issue by laserpedro** [terraform-aws-modules/terraform-aws-vpc#1060]
## Is your request related to a new offering from AWS?
  - No : the resource `aws_nat_gatway` enable the [connectivity_type](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/nat_gateway#connectivity_type) argument to be set to `private` so that not internet gateway is required when creating the private NAT gateway.

## Is your request related to a problem? Please describe.
The module enables to setup VPCs following AWS best practices and I think that it should enable to implement the private NAT Gateway [setup](https://docs.aws.amazon.com/whitepapers/latest/building-scalable-secure-multi-vpc-network-infrastructure/private-nat-gateway.html)

## Describe the solution you'd like.
Expose the variables that enables the setup referenced above. So add the `connectivity_type` and the other [arguments](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/nat_gateway#secondary_private_ip_address_count) relative to the setup of a private NAT Gateway.

**I would be glad** to create the pull request myself I you see any interest in this feature request. I believe that the fully private NAT Gateway can be a classic company setup and therefore we should enable this feature.

## Workaround 

The current workaround is to simply create the private NAT Gateway outside of the module and specifying the `connectivity_type` to `private`.

**Comment by bryantbiggs** [comment]
if you have a PR, we can take a look
