### ISSUE TITLE
Custom amount of NAT gateways

### ISSUE THREAD

**Issue by aiell0** [terraform-aws-modules/terraform-aws-vpc#1065]
## Describe the solution you'd like.
Right now there are only two options for the amount of NAT gateways I want - either one or the amount of availability zones I am using. That's a bit limiting, us-east-1 for example has 6 availability zones and that can be overkill for some organizations who are cost conscious. What if I only want 3?

## Describe alternatives you've considered.
I usually just disallow the module to create NAT gateways and create my own if I want a custom amount, and I felt that it should be in the module. The addition of the feature seemed simple enough.

## Additional context
None

**Comment by bryantbiggs** [comment]
> us-east-1 for example has 6 availability zones and that can be overkill for some organizations who are cost conscious. What if I only want 3?

How do you setup routes for this scenario? what if someone wants 2 NAT gateways, how would you setup routes for 6 subnets to 2 NAT gateways - and how do you decide which AZ/subnets to place the NAT gateways within?

**Comment by aiell0** [comment]
@bryantbiggs IMO the best approach would be to let the user configure which AZs/subnets they wanted the NAT gateways in (including having multiple in the same subnet if they wanted for whatever reason). That part could be configurable.

As far as deciding how to route private subnets to them, I think we would have to balance them within the module. For example, if you wanted 2 NAT gateways in us-east-1 and you are deploying in all 6 AZs overall, then have us-east-1a, us-east-1c, and us-east-1d route to one NAT and us-east-1b, us-east-1d, and us-east-1f route to the other one.

I took a more naive approach in my PR but if the above sounds good, I will modify it to go with the above. Let me know how that sounds!

**Comment by aiell0** [comment]
bump

**Comment by artsiommiksiuk** [comment]
Idk if it's really related but sounds very close so I'll ask/post here. I think flag for per subnet NATs creation enabling/disabling, would also be very nice to have. My use case, is that database subnet don't need internet access, therefore, I don't want NAT to be created there. I could use intra subnet for that, but intra in my semantics is for intra processing, not storage. So, simple `database_subnets_create_nat = false` would be very nice thing.
