### ISSUE TITLE
all setting of ignore_changes attribute

### ISSUE THREAD

**Issue by jwhitcraft** [terraform-aws-modules/terraform-aws-vpc#107]
It would be handy if we could set the `ignore_changes` for everything in the vpc module.  

Our use case if we use terraform to setup the VPC, and the run Kubernetes on top of the vpc, but Kubernetes adds tags to the subnets as to do look ups easier, and as such when running terraform plan or apply it will remove those tags from the VPC.

**Comment by antonbabenko** [comment]
Terraform does not allow to use variables inside `ignore_changes` configuration, which means that if we hardcode what arguments to ignore it will not work for all users who are using this module already.

I don't know a better solution to this problem other than using this module separately from K8S ("run once and forget").

**Comment by HenryCook** [comment]
I came across this problem recently and I had to implement this solution to allow me to pass in the cluster name per environment as a list. 

This does requires human intervention when we create/destroy EKS clusters but then we can continue using this module as part of a CI pipeline.

### main.tf
```
private_subnet_tags = "${merge(
  local.eks_tags,
  var.default_private_subnet_tags
)}"
```

### local.tf
```
locals {
  eks_tags = "${zipmap(
    null_resource.tags_as_list_of_maps.*.triggers.key,
    null_resource.tags_as_list_of_maps.*.triggers.value
  )}"
}

resource "null_resource" "tags_as_list_of_maps" {
  count = "${length(var.eks_clusters)}"

  triggers = {
    key   = "kubernetes.io/cluster/${element(var.eks_clusters, count.index)}"
    value = "shared"
  }
}
```

### variables.tf
```
variable "eks_clusters" {
  description = "Names of EKS clusters to add to tags"
  type        = "list"
  default     = []
}

variable "default_private_subnet_tags" {
  description = "Default tags for private subnet"
  type        = "map"

  default = {
    type = "private"
  }
}
```

### environment.tfvars
```
eks_clusters = ["name-of-cluster-1", "name-of-cluster-2"]
```
