### ISSUE TITLE
Tag private subnets separately, like first 3 as app subnets and last 3 as data subnets

### ISSUE THREAD

**Issue by apheera** [terraform-aws-modules/terraform-aws-vpc#1076]
## Is your request related to a new offering from AWS?
Is this functionality available in the [AWS provider for Terraform](https://registry.terraform.io/providers/hashicorp/aws/latest/docs)? See [CHANGELOG.md](https://github.com/hashicorp/terraform-provider-aws/blob/main/CHANGELOG.md), too.
  - Yes

## Is your request related to a problem? Please describe.
I am creating 6 Private subnets and want to tag first 3 as app subnets and rest 3 as data subnets. How can I do that?

## Describe the solution you'd like.
Either a separate tagging block based on subnet lookup or give capability to ignore tag changes within module so I can tag them separately.

## Describe alternatives you've considered.
Described them above

## Additional context
NA

**Comment by edas-smith** [comment]
Need this as well, though this PR should solve it : https://github.com/terraform-aws-modules/terraform-aws-vpc/pull/901. But it has been open for over a year now
