### ISSUE TITLE
Pass already created VPC id 

### ISSUE THREAD

**Issue by dsoamandhabhishek** [terraform-aws-modules/terraform-aws-vpc#1082]
I have an already created VPC, how do I pass the VPC id so that i can create the public and private subnets and the required components for it. I would be great if someone can provide support for this.

**Comment by zahorniak** [comment]
Hi @dsoamandhabhishek,

You can [import existing resources](https://developer.hashicorp.com/terraform/cli/import/usage) into this module and use it.
