### ISSUE TITLE
conditional operator cannot be used with list values

### ISSUE THREAD

**Issue by vaibhavmalushte** [terraform-aws-modules/terraform-aws-vpc#109]
My versions are as below 
Terraform v0.11.5
+ provider.aws v1.11.0

when run terraform plan got this error, kindly advise.

Warning: output "internet_gateway_id": must use splat syntax to access aws_internet_gateway.internet_gateway attribute "id", because it has "count" set; use aws_internet_gateway.internet_gateway.*.id to obtain a list of the attributes across all instances

Warning: output "internet_gateway_id": must use splat syntax to access aws_internet_gateway.internet_gateway attribute "id", because it has "count" set; use aws_internet_gateway.internet_gateway.*.id to obtain a list of the attributes across all instances

Error: module.vpc.output.availability_zones: At column 4, line 1: conditional operator cannot be used with list values in:

${(var.manual_azs == "1" ? var.azs : data.aws_availability_zones.available.names)}

Error: module.vpc.output.availability_zones_str: At column 14, line 1: conditional operator cannot be used with list values in:

${join(",", (var.manual_azs == "1" ? var.azs : data.aws_availability_zones.available.names))}

---------------------------------------------------------------------------------------------------
updates:

I've changed the code to 
output "availability_zones" {
  value = ["${var.azs}"]
}
output "availability_zones_str" {
  value = "${join(",", (var.azs))}"
}
and it worked, I think this is related to https://github.com/hashicorp/terraform/issues/12453

Thank you,
Vaibhav

**Comment by antonbabenko** [comment]
Please show you Terraform configuration code. Also, where does `manual_azs` come from?

**Comment by antonbabenko** [comment]
There is no output `internet_gateway_id` in this module, so I suspect you are using some other code.

Closing this issue.
