### ISSUE TITLE
VPC Endpoints do not support `ip_address_type` property

### ISSUE THREAD

**Issue by adam-sm** [terraform-aws-modules/terraform-aws-vpc#1091]
## Description

Setting the [ip_address_type](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/vpc_endpoint#ip_address_type)  property on an endpoint does not get propagated to the underlying `aws_vpc_endpoint` resource.

This means the routing tables only get propagated with the S3/DynamoDB IPv4 prefix list routes and clients using IPv6 (AWS CLI) can not route request to S3 and hang if no external egress  

- [x ] ✋ I have searched the open/closed issues and my issue is not listed.

**Comment by tokarev-artem** [comment]
Hi @adam-sm , can you check if #1096 works for you?

**Comment by tokarev-artem** [comment]
@adam-sm up

**Comment by bryantbiggs** [comment]
resolved in #1096
