### ISSUE TITLE
VPC and Transit Gateway

### ISSUE THREAD

**Issue by aleksandarzagorac** [terraform-aws-modules/terraform-aws-vpc#1094]
I would like to use this VPC module in combination with the transit gateway module (https://registry.terraform.io/modules/terraform-aws-modules/transit-gateway/aws/latest) in a way to route traffic from the private subsets (only) to the transit gateway. I did not find a solution since I can not manage the route tables for private subnets, nor can I add a new route table. Is there a way to perform this action? Even if there is a way to modify the route tables I would get a circular dependency between the vpc module and transit gateway module since the transit gateway attachments need the ids of the private subnets and the route table of the VPC would need the transit gateway ID.

**Comment by derekmckinnon** [comment]
This module outputs `private_route_table_ids` which you can use in conjunction with `aws_route` resources that you create yourself. You don't need to specify the attachment ID, you just need to specify the `transit_gateway_id`. In my configuration, I deployed the TGW ENIs into a different set of private subnets, but I don't know if that is a strict requirement.
