### ISSUE TITLE
Checkov Scan Findings for "terraform-aws-vpc" Repository

### ISSUE THREAD

**Issue by m5jain** [terraform-aws-modules/terraform-aws-vpc#1099]
## Description

While running the Checkov scanning tool for the "terraform-aws-vpc" repo, we identified several issues, which are attached. Please review them.

- [X] ✋ I have searched the open/closed issues and my issue is not listed.

## Versions

- Module version [Required]: v5.8.1
- Terraform version: v1.8.4
- Provider version(s): aws 5.52.0

## Reproduction Code [Required]

Run the Checkov tool on the module as suggested on the Checkov official page: https://www.checkov.io/7.Scan%20Examples/Terraform%20Plan%20Scanning.html

## Expected behavior
There should not be any findings in the output.

## Actual behavior
We encountered the following findings:
     ID: CKV_AWS_356
      ID: CKV_AWS_111
      ID: CKV2_AWS_11
      ID: CKV2_AWS_12

### Terminal Output Screenshot(s)
Refer to the attached file for the line numbers where the issues are located.

[vpc_fingings.txt](https://github.com/user-attachments/files/16029278/vpc_fingings.txt)

**Comment by bryantbiggs** [comment]
@m5jain please stop opening these issues for checkov results

https://github.com/terraform-aws-modules/terraform-aws-iam/issues/494#issuecomment-2196753394
