### ISSUE TITLE
symlink error during terraform  get

### ISSUE THREAD

**Issue by piusranjan** [terraform-aws-modules/terraform-aws-vpc#110]
when I am running terraform  get  in below folder , I am getting error
/home/vagrant/streams/learning/tfm/lab/terraform-aws-vpc/examples/simple-vpc

Error: Error loading modules: error downloading 'file:///home/vagrant/streams/learning/tfm/lab/terraform-aws-vpc': symlink /home/vagrant/streams/learning/tfm/lab/terraform-aws-vpc .terraform/modules/a083b5b9dd7e90361acfae606df96064: protocol error

Terraform version : 0.11.5.

I am using vagrant box 

Linux vagrantbox 3.10.0-514.2.2.el7.x86_64 #1 SMP Tue Dec 6 23:06:41 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
Thanks,
Pius

**Comment by antonbabenko** [comment]
Apparently, symlinks are not set up properly in your Vagrant box. Try to remove `/home/vagrant/streams/learning/tfm/lab/terraform-aws-vpc/examples/simple-vpc/.terraform` directory and run `terraform init` once more.

**Comment by piusranjan** [comment]
@antonbabenko  after changing source as  below , the symlink error disappeared . But I am getting a different error now.
Error downloading modules: Error loading modules: host registry.terraform.io does not provide Terraform modules
source  = "terraform-aws-modules/vpc/aws"

**Comment by antonbabenko** [comment]
Reading [this issue](https://github.com/hashicorp/terraform/issues/16751) and wonder if network connection is working well from your Vagrant box.

Does this work - `curl https://registry.terraform.io/v1/modules/terraform-aws-modules/vpc/aws`?

**Comment by piusranjan** [comment]
Yes this is working . Below is the response                                                                                                                  
                                                                         
{"id":"terraform-aws-modules/vpc/aws/1.26.0","owner":"antonbabenko","namespace":"terraform-aws-modules","name":"vpc","version":"1.26.0","provider":"aws","description":"Terraform module which creates VPC resources on AWS","source":"https://github.com/terraform-aws-modules/terraform-aws-vpc","published_at":"2018-03-06T14:43:33.325028Z","downloads":107083,"verified":true,"root":{"path":"","name":"vpc","readme":"AWS VPC Terraform module\n========================\n\n[![Help Contribute to Open Source](https://www.codetriage.com/terraform-aws-modules/terraform-aws-vpc/badges/users.svg)](https://www.codetriage.com/terraform-aws-modules/terraform-aws-vpc)\n\nTerraform module which creates VPC resources on AWS.\n\nThese types of resources are supported:\n\n* [VPC](https://www.terraform.io/docs/providers/aws/r/vpc.html)\n* [Subnet](https://www.terraform.io/docs/providers/aws/r/subnet.html)\n* [Route](https://www.terraform.io/docs/providers/aws/r/route.html)\n* [Route table](https://www.terraform.io/docs/providers/aws/r/route_table.html)\n* [Internet Gateway](https://www.terraform.io/docs/providers/aws/r/internet_gateway.html)\n* [NAT Gateway](https://www.terraform.io/docs/providers/aws/r/nat_gateway.html)\n* [VPN Gateway](https://www.terraform.io/docs/providers/aws/r/vpn_gateway.html)\n* [VPC Endpoint](https://www.terraform.io/docs/providers/aws/r/vpc_endpoint.html) (S3 and DynamoDB)\n* [RDS DB Subnet Group](https://www.terraform.io/docs/providers/aws/r/db_subnet_group.html)\n* [ElastiCache Subnet Group](https://www.terraform.io/docs/providers/aws/r/elasticache_subnet_group.html)\n* [Redshift Subnet Group](https://www.terraform.io/docs/providers/aws/r/redshift_subnet_group.html)\n* [DHCP Options Set](https://www.terraform.io/docs/providers/aws/r/vpc_dhcp_options.html)\n* [Main VPC Routing Table](https://www.terraform.io/docs/providers/aws/r/main_route_table_assoc.html)\n* [Default VPC Routing Table](https://www.terraform.io/docs/providers/aws/r/default_route_table.html)\n* [Default VPC](https://www.terraform.io/docs/providers/aws/r/default_vpc.html)\n\nUsage\n-----\n\n```hcl\nmodule \"vpc\" {\n  source = \"terraform-aws-modules/vpc/aws\"\n\n  name = \"my-vpc\"\n  cidr = \"10.0.0.0/16\"\n\n  azs             = [\"eu-west-1a\", \"eu-west-1b\", \"eu-west-1c\"]\n  private_subnets = [\"10.0.1.0/24\", \"10.0.2.0/24\", \"10.0.3.0/24\"]\n  public_subnets  = [\"10.0.101.0/24\", \"10.0.102.0/24\", \"10.0.103.0/24\"]\n\n  enable_nat_gateway = true\n  enable_vpn_gateway = true\n\n  tags = {\n    Terraform = \"true\"\n    Environment = \"dev\"\n  }\n}\n```\n\nExternal NAT Gateway IPs\n------------------------\n\nBy default this module will provision new Elastic IPs for the VPC's NAT Gateways.\nThis means that when creating a new VPC, new IPs are allocated, and when that VPC is destroyed those IPs are released.\nSometimes it is handy to keep the same IPs even after the VPC is destroyed and re-created.\nTo that end, it is possible to assign existing IPs to the NAT Gateways.\nThis prevents the destruction of the VPC from releasing those IPs, while making it possible that a re-created VPC uses the same IPs.\n\nTo achieve this, allocate the IPs outside the VPC module declaration.\n```hcl\nresource \"aws_eip\" \"nat\" {\n  count = 3\n\n  vpc = true\n}\n```\n\nThen, pass the allocated IPs as a parameter to this module.\n```hcl\nmodule \"vpc\" {\n  source = \"terraform-aws-modules/vpc/aws\"\n\n  # The rest of arguments are omitted for brevity\n\n  enable_nat_gateway  = true\n  single_nat_gateway  = false\n  reuse_nat_ips       = true                      # \u003
...
......

**Comment by antonbabenko** [comment]
Good, closing this issue, because it is not related to the Terraform module itself but rather to Vagrant setup.

**Comment by isaccavalcante** [comment]
If anyone come across this in the future, [this solution](https://github.com/hashicorp/vagrant/issues/6024#issuecomment-364913733) worked for me.
