### ISSUE TITLE
Alternate or optional Private Nat gateways

### ISSUE THREAD

**Issue by brackend** [terraform-aws-modules/terraform-aws-vpc#1103]
## Is your request related to a new offering from AWS?
Is this functionality available in the [AWS provider for Terraform](https://registry.terraform.io/providers/hashicorp/aws/latest/docs)? See [CHANGELOG.md](https://github.com/hashicorp/terraform-provider-aws/blob/main/CHANGELOG.md), too.
  - No 🛑: please wait to file a request until the functionality is avaialble in the AWS provider
  

## Is your request related to a problem? Please describe.

NAT gateway is public.  There is no private NAT gateway
## Describe the solution you'd like.

Create option to choose between private and public NAT gateway or
options to create 2 nat gateways - one private, one public.

**Comment by charlierm** [comment]
This would be really useful for us, we're currently creating outside of the module and adding the routes in.

**Comment by saedx1** [comment]
The answer to the first question about this being available in the provider is definitely a **_Yes_**, it's been supported since 3.45.0 by the provider.
