### ISSUE TITLE
Support secondary ip addresses for nat gateway

### ISSUE THREAD

**Issue by AlexisColes** [terraform-aws-modules/terraform-aws-vpc#1108]
## Is your request related to a new offering from AWS?
The functionality is there, I don't know when it was introduced, but I presume for at least a year.

## Is your request related to a problem? Please describe.
We are being rate limited by github based on IP address from one of our aws accounts, in order to work around this problem we added secondary ip addresses to our natgateways.  We have no way of configuring the vpc module to reflect this desired configuration.

## Describe the solution you'd like.
Expose configuration for secondary ip addresses to allow more than 1 ip address to be configured per nat-gateway

## Describe alternatives you've considered.
configuring the nat-gateway outside of this module.

**Comment by tkatrichenko** [comment]
Duplicate https://github.com/terraform-aws-modules/terraform-aws-vpc/issues/1005?

**Comment by flaviomoringa** [comment]
I'm also waiting for this for a while. I see it being worked on here: https://github.com/terraform-aws-modules/terraform-aws-vpc/pull/1109 but not moving forward. This is actually a big pain point for us right now ;-(

**Comment by flaviomoringa** [comment]
@bryantbiggs  @AlexisColes  Is there something that can be done to unblock the merge? The current issue with the computed values as keys in maps could maybe be fixed in another way?

Thanks

**Comment by flaviomoringa** [comment]
Please re-open this issue. This is really needed. Thanks.
