### ISSUE TITLE
Deprecated and update syntax in Terraform VPC resource parameters and variable declarations

### ISSUE THREAD

**Issue by darren-wong-IAG** [terraform-aws-modules/terraform-aws-vpc#1113]
## Description

Deprecated and update syntax in Terraform VPC resource parameters and variable declarations

If your request is for a new feature, please use the `Feature request` template.

- [x] ✋ I have searched the open/closed issues and my issue is not listed.

## ⚠️ Note

Before you submit an issue, please perform the following first:

1. Remove the local `.terraform` directory (! ONLY if state is stored remotely, which hopefully you are following that best practice!): `rm -rf .terraform/`
2. Re-initialize the project root to pull down modules: `terraform init`
3. Re-attempt your terraform plan or apply and check if the issue still persists

## Versions

- Module version [Required]:

v5.12.1

- Terraform version:

1.9.1

- Provider version(s):

v5.62.0

## Reproduction Code [Required]

`module "vpc" {
  source  = "terraform-aws-modules/vpc/aws"
  version = "~> 3.0" 

  name = "my-vpc"
  cidr = "10.0.0.0/24"

  azs             = ["eu-west-2a", "eu-west-2b"]
  private_subnets = ["10.0.0.0/26", "10.0.0.64/26"
  ]
  public_subnets  = ["10.0.0.128/26","10.0.0.192/26" ]

  enable_nat_gateway = true
  enable_vpn_gateway = false

  tags = {
    Terraform = "true"
    Environment = "dev"

  }
}`

### Terminal Output Screenshot(s)

`╷
│ Warning: Argument is deprecated
│ 
│   with module.vpc.aws_eip.nat,
│   on .terraform/modules/vpc/main.tf line 1013, in resource "aws_eip" "nat":
│ 1013:   vpc = true
│ 
│ use domain attribute instead
╵
╷
│ Error: Unsupported argument
│ 
│   on .terraform/modules/vpc/main.tf line 35, in resource "aws_vpc" "this":
│   35:   enable_classiclink             = null # https://github.com/hashicorp/terraform/issues/31730
│ 
│ An argument named "enable_classiclink" is not expected here.
╵
╷
│ Error: Unsupported argument
│ 
│   on .terraform/modules/vpc/main.tf line 36, in resource "aws_vpc" "this":
│   36:   enable_classiclink_dns_support = null # https://github.com/hashicorp/terraform/issues/31730
│ 
  )
│ An argument named "enable_classiclink_dns_support" is not expected here.
    
╵
╷
}
│ Error: Unsupported argument
│ 
│   on .terraform/modules/vpc/main.tf line 1246, in resource "aws_default_vpc" "this":
│ 1246:   enable_classiclink   = null # https://github.com/hashicorp/terraform/issues/31730
│ 
│ An argument named "enable_classiclink" is not expected here.
╵`

**Comment by bryantbiggs** [comment]
You need to upgrade your module version to resolve that warning
