### ISSUE TITLE
Include names for db/redshift subnet groups in output 

### ISSUE THREAD

**Issue by CaliRobC** [terraform-aws-modules/terraform-aws-vpc#112]
Elasticache outputs the subnet group name which is simply the var.name but it is not outputted for redshift or db subnet groups which is needed for the graph dependencies per https://github.com/hashicorp/terraform/issues/5899 when destroying infrastructure. 

`output "db_subnet_group_name" {
  description = "Name of db subnet group"
  value       = "${element(concat(aws_db_subnet_group. database.*.name, list("")), 0)}"
}`

**Comment by antonbabenko** [comment]
I don't understand exactly what is the problem? Could you paste the code which fails and provide the details of how it fails?

**Comment by CaliRobC** [comment]
This was a while back so my memory on it is not so good but I remember I had to modify the module to output the db_subnet_group_name so that I can reference it in my rds deployment to tie the two resources together and have them destroyed properly.  Just thought that the module should output the db/redshift_subnet_group_names.  I was new to terraform then so I might have been wrong.  Feel free to close this.

**Comment by antonbabenko** [comment]
Yes, there is `database_subnet_group` in outputs which can be used as an argument to RDS, and `redshift_subnet_group` - to Redshift.

Closing now, but feel free to open new issues if you find something bad.
