### ISSUE TITLE
Conditionally enable private and public subnet tags

### ISSUE THREAD

**Issue by kaykhan** [terraform-aws-modules/terraform-aws-vpc#1145]
## Is your request related to a problem? Please describe.

We make use of both terraform-aws-vpc and terraform-aws-eks modules.

In our terraform-aws-vpc module we declare a set of tags

```
module "vpc" {
  source  = "terraform-aws-modules/vpc/aws"
  version = "5.7.1"
  ..

  tags = {
    Terraform                                 = "true"
    Environment                               = local.workspace
    "kubernetes.io/cluster/${local.k8s_name}" = "shared"
  }

  // to be removed
  //public_subnet_tags = {
  //  "kubernetes.io/cluster/${local.k8s_name}" = "shared"
  //  "kubernetes.io/role/elb"                  = "1"
  //  "karpenter.sh/discovery"                  = local.k8s_name
  //}

  //private_subnet_tags = {
  //  "kubernetes.io/cluster/${local.k8s_name}" = "shared"
  //  "kubernetes.io/role/internal-elb"         = "1"
  //  "karpenter.sh/discovery"                  = local.k8s_name
  //}
}
```

When using plugins such as aws-load-balancer-controller we need to append tags to the subnets https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.1/deploy/subnet_discovery/#subnet-auto-discovery - similarly with karpenter https://karpenter.sh/docs/concepts/nodeclasses/#examples

Now we have opted to add these additional tags outside of the terraform-aws-vpc module using the resource aws_ec2_tag.

We have a problem where the terraform-aws-vpc module detects a drift in the tag and attempts to remove the tags that have been appended outside of terraform-aws-vpc module.

Im interesting to know if others have come across this issue and how they resolved it.

## Describe the solution you'd like.

This only affects aws_subnet resource , i wonder if its worth creating a PR updating this module to conditionally apply tags to the aws_subnet resource.

var.enable_public_subnet_tags (default = true)
var.enable_private_subnet_tags (default = true)

https://github.com/terraform-aws-modules/terraform-aws-vpc/blob/master/main.tf#L114-L125

The assumption is by conditionally enabling tags i can set this to false and handle the creation of subnet tags using `aws_ec2_tag`

## Describe alternatives you've considered.

1.

The first idea we had is to update our declared terraform-aws-vpc module and include the missing tags so it stops complaining. This is straight forward and simple.

It feels like we are having to apply tags again despite the fact that we have already defined them outside of this module
can be quite annoying to maintain if you have multiple clusters

2.

Declare a common tag in terraform-aws-vpc that all k8s clusters use and therefore we don't need to append any unique values to the tag. This i believe would work for karpenter but i believe aws-load-balancer-controller is looking for the cluster-name https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.1/deploy/subnet_discovery/#common-tag

## Additional context

This issue has been raised in the past https://github.com/terraform-aws-modules/terraform-aws-vpc/issues/986 although the solution was to blanket ignore tags which would affect existing usage. And we are not able to dyanmcially apply ignore_changes in the lifecycle https://github.com/terraform-aws-modules/terraform-aws-vpc/issues/1124.

**Comment by bryantbiggs** [comment]
it is not possible for multiple sources to modify the same argument within Terraform - there can only be one owner. Therefore you have two options (they can be used independently or together):
1. Provide all of the tags that should be applied to your subnets from the VPC module (if that is what created the subnets)
2. Pass the subnets that the AWS load balancer controller and Karpenter should use to the controllers in lieu of subnet discovery

Closing this out since there aren't any module level changes that would support the scenario described

**Comment by kaykhan** [comment]
It looks like its possible to just set a common tag in the subnet once

```
  public_subnet_tags = {
    "kubernetes.io/role/elb" = "1"
    "karpenter.sh/discovery" = true
  }

  private_subnet_tags = {
    "kubernetes.io/role/internal-elb" = "1"
    "karpenter.sh/discovery"          = true
  }
  ```
