### ISSUE TITLE
ignore_tags_changes module argument

### ISSUE THREAD

**Issue by bogdanstate** [terraform-aws-modules/terraform-aws-vpc#1148]
## Is your request related to a new offering from AWS?
Is this functionality available in the [AWS provider for Terraform](https://registry.terraform.io/providers/hashicorp/aws/latest/docs)? See [CHANGELOG.md](https://github.com/hashicorp/terraform-provider-aws/blob/main/CHANGELOG.md), too.
  - Yes ✅: please list the AWS provider version which introduced this functionality

3.5.0

## Is your request related to a problem? Please describe.

My team uses Terraform workspaces to manage different replicas of the same EKS cluster (e.g. prod vs. a copy of prod + a new feature). All clusters live in the same VPC, managed using this (awesome!) module (thank you!).

Adding a new cluster in a new workspace requires adding new subnet tags into the VPC. These are managed using [aws_ec2_tag](https://registry.terraform.io/providers/hashicorp/aws/3.1.0/docs/resources/ec2_tag) resources.

The use of these `aws_ec2_tag` resources conflicts with the VPC module, which constantly tries to overwrite those tags. I am able to partially get around this by using the solution recommended in [this issue](https://github.com/terraform-aws-modules/terraform-aws-vpc/issues/408) -- use `ignore_tags` in the `aws` TF provider.

The problem is the following: if I use `ignore_tags` in the aws TF provider, I get the problem described [there](https://registry.terraform.io/providers/hashicorp/aws/latest/docs#key_prefixes-1):
> If any resource configuration still has a tag matching one of the prefixes configured in the tags argument, it will display a perpetual difference until the tag is removed from the argument or [ignore_changes](https://www.terraform.io/docs/configuration/meta-arguments/lifecycle.html#ignore_changes) is also used.

This is a problem because our CI/CD process checks for a clean `terraform plan`. And in general, it's bad practice to have a terraform plan that is practically a no-op but has suggested changes.

## Describe the solution you'd like.

Rather than a generic, parameterized lifecycle argument discussed in #408, a single boolean input variable called `ignore_tags_changes`. Setting this variable to `true` would add a lifecycle directive to ignore changes to all tags in the VPC. This is a simple but effective solution that ensures `ignore_tags` on the `aws` provider can be used and result in a clean plan for this module.

## Describe alternatives you've considered.

The easiest alternative involves changing our CI to accept a "dirty" plan. It would probably be easier to implement that, but doing so breaks one of the key invariants you get with terraform -- that the config and cloud are in sync if and only if the plan contains no changes.

## Additional Context

Reading through [this response](https://stackoverflow.com/questions/62427931/terraform-conditionally-apply-lifecycle-block) makes me realize adding a "conditional lifecycle" block inside the module could be quite tricky since it's not a supported feature for terraform.

**Comment by bryantbiggs** [comment]
This is not something Terraform supports
