### ISSUE TITLE
Error decoding timeout: Timeout Key (create) is not supported

### ISSUE THREAD

**Issue by erran** [terraform-aws-modules/terraform-aws-vpc#115]
After upgrading `terraform-aws-modules/vpc/aws` we're seeing the following error in builds related to #113.

```
terraform init
- module.vpc
  Found version 1.30.0 of terraform-aws-modules/vpc/aws on registry.terraform.io
  Getting source "terraform-aws-modules/vpc/aws"
```
```
terraform plan
...
module.vpc.aws_route.private_nat_gateway[2]: [ERR] Error decoding timeout: Timeout Key (create) is not supported
```

**Comment by antonbabenko** [comment]
Erran, make sure you are using AWS provider version [1.11.0](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#1110-march-09-2018) at least.

**Comment by erran** [comment]
@antonbabenko no problem, shouldn't we update the required version of the provider for this module in that case? 😉 

https://github.com/terraform-aws-modules/terraform-aws-vpc/blob/55b5991c2b89d41639c4cad960cea42826c4743a/main.tf#L2

**Comment by antonbabenko** [comment]
No, Terraform version can be like that, but the version of Terraform AWS provider is important.

**Comment by erran** [comment]
Oops, you're 💯 right. 😓 My mistake — I read that as `provider "aws" { version = "> 0.10.3" }` at first.

Should we document for users somewhere that this module requires a minimum version of the aws provider?

**Comment by antonbabenko** [comment]
Yes, we probably should but I don't have time to make it properly and automatically (yet). Also I don't want to update this information manually every time and verify which version is required.
