### ISSUE TITLE
VPC Endpoints should add Name tag by default

### ISSUE THREAD

**Issue by aldenquimby** [terraform-aws-modules/terraform-aws-vpc#1150]
## Is your request related to a new offering from AWS?
No

## Is your request related to a problem? Please describe.
When adding vpc-endpoints, I currently add a tag for Name on each, like this:
```tf
    execute-api = {
      service = "execute-api"
      tags    = { Name = "execute-api-vpc-endpoint" }
    }
    textract-fips = {
      service = "textract-fips"
      tags    = { Name = "textract-fips-vpc-endpoint" }
    }
    transcribe = {
      service = "transcribe"
      tags    = { Name = "transcribe-vpc-endpoint" }
    }
```

## Describe the solution you'd like.
It would be nice if Name tags were auto-added if `service` is specified, so I could do this instead:
```tf
    execute-api = {
      service = "execute-api"
    }
    textract-fips = {
      service = "textract-fips"
    }
    transcribe = {
      service = "transcribe"
    }
```

## Describe alternatives you've considered.
Manually specifying Names works, it's just verbose

## Additional context
- The security group within the vpc-endpoints module already auto-adds a Name tag, which is nice:
https://github.com/terraform-aws-modules/terraform-aws-vpc/blob/9ffd9c66f3d7eb4b5bc2d7bc7d049f794b127693/modules/vpc-endpoints/main.tf#L68-L72

**Comment by sebastianczech** [comment]
@aldenquimby I prepared PR #1151 , which I hope resolves your problem

**Comment by aldenquimby** [comment]
@sebastianczech excellent! Thank you. Exactly what I was hoping for
