### ISSUE TITLE
How can I add custom routes table for vpc_peering_connection_id 

### ISSUE THREAD

**Issue by Vad1mo** [terraform-aws-modules/terraform-aws-vpc#116]
Im trying to figure out how it would be possible to add custom route entry.
I did try to override it however it wasn't possible as variables aren't available. 

Are thy any other solutions how this could be achieved?
```
resource "aws_route_table" "private" {
...
...
  route {
    ipv6_cidr_block = "172.16.99.0/24"
    vpc_peering_connection_id  = "pcx-908cdasdf"
```

**Comment by antonbabenko** [comment]
This module outputs `private_route_table_ids` which you can use and add `aws_route` resources like this:
```
resource "aws_route" "vpc_peering" {
  count = 3

  route_table_id = "${element(module.vpc.private_route_table_ids, count.index)}"
  ipv6_cidr_block = "::/0"
  vpc_peering_connection_id  = "pcx-908cdasdf"
}
```
