### ISSUE TITLE
Too many NAT gateways created

### ISSUE THREAD

**Issue by sc250024** [terraform-aws-modules/terraform-aws-vpc#117]
Not sure whether to file this under "feature", or "bug"; I suppose it depends on how a person views subnetting in AWS VPC.

Basically, I have 6 private subnets calculated from a base /16 prefix, and being created in the `eu-west-1` region as follows:

```
    private_subnets = [
        "${cidrsubnet(var.cidr_block, 7, 7)}",
        "${cidrsubnet(var.cidr_block, 7, 8)}",
        "${cidrsubnet(var.cidr_block, 7, 9)}",
        "${cidrsubnet(var.cidr_block, 4, 13)}",
        "${cidrsubnet(var.cidr_block, 4, 14)}",
        "${cidrsubnet(var.cidr_block, 4, 15)}",
    ]
```

In the module definition, I have also specified to use all 3 availability zones `eu-west-1a`, `eu-west-1b`, and `eu-west-1c`. The module then generates 6 NAT gateways that look like this:

```
  + module.vpc.aws_route.private_nat_gateway[X]
      id:                                     <computed>
      destination_cidr_block:                 "0.0.0.0/0"
      destination_prefix_list_id:             <computed>
      egress_only_gateway_id:                 <computed>
      gateway_id:                             <computed>
      instance_id:                            <computed>
      instance_owner_id:                      <computed>
      nat_gateway_id:                         "${element(aws_nat_gateway.this.*.id, count.index)}"
      network_interface_id:                   <computed>
      origin:                                 <computed>
      route_table_id:                         "${element(aws_route_table.private.*.id, count.index)}"
      state:                                  <computed>
```

My question: isn't one NAT gateway per private subnet a bit excessive? If the number of availability zones is defined by `${length(var.azs)}`, then shouldn't only `${length(var.azs)}` number of NAT gateways be created, and added to the route tables?

This is especially true as a person's user account is charged per hour that each NAT gateway instance is running: https://aws.amazon.com/vpc/pricing/#natgatewaypricing

My info:
Terraform v0.11.7
Provider.aws v1.14.0
Module version: 1.30.0

**Comment by sc250024** [comment]
As a follow-up, I went through the instructions titled **External NAT Gateway IPs** on the page [https://registry.terraform.io/modules/terraform-aws-modules/vpc/aws/1.30.0](https://registry.terraform.io/modules/terraform-aws-modules/vpc/aws/1.30.0) as well. The module still creates 6 NAT gateways, only now 3 of them have the following error in the AWS console:

```
Elastic IP address [eipalloc-xxxxxxxxxxxxxxxxx] is already associated
```

**Comment by robh007** [comment]
#83 Looks to have switched to use the max_subnet_length, IMHO that's incorrect. You'd either create a single NGW or if your thinking about AZ failure you would create a NGW per AZ within that region. Again there's some assumptions made with subnets and AZs. Irrespective of how many private subnets you have as this shouldn't influence the number of NGWs created.

**Comment by antonbabenko** [comment]
I remember we've had some discussion about this in the past. It has been evolving, and I tend to agree that after #83 is merged it is a good time to reconsider a number of NAT gateways created.

I see that there are these options:
1. Single NAT - `single_nat_gateway = true`
1. One NAT per subnet - this is how it is implemented now (`single_nat_gateway = false`)
1. One NAT per AZ - proper solution in principle, but harder to implement/maintain in Terraform code.

The solution with one NAT per subnet can still be helpful for situations when EIP of NAT gateway should be whitelisted on corp firewall and, at the same time, not all subnets in that AZ should have access to corp network. So, this module needs to maintain all 3 scenarios.

Can somebody come up with a PR to support these scenarios?

**Comment by sc250024** [comment]
@antonbabenko Yes, I'll come up with a PR. Thanks for the input!

**Comment by sc250024** [comment]
https://github.com/terraform-aws-modules/terraform-aws-vpc/pull/129 created
