### ISSUE TITLE
EIP get deleted with reuse_nat_ips set to true

### ISSUE THREAD

**Issue by JoostSaanen** [terraform-aws-modules/terraform-aws-vpc#118]
Tested with Terraform version:
`0.11.0 and 0.11.7`

my vpc.tf looks like:

```
resource "aws_eip" "nat" {
  count = 1
  vpc = true
}

module "vpc" {
  source = "terraform-aws-modules/vpc/aws"
  name   = "${var.application}"
  cidr   = "10.0.0.0/16"

  azs             = ["eu-west-2a", "eu-west-2b"]
  private_subnets = ["10.0.1.0/24", "10.0.2.0/24"]
  public_subnets  = ["10.0.101.0/24", "10.0.102.0/24"]

  enable_nat_gateway  = true
  single_nat_gateway  = true
  reuse_nat_ips       = true

  external_nat_ip_ids = ["${aws_eip.nat.*.id}"]

  tags = {
    Environment = "${var.env}"
    Terraform   = "true"
    Client      = "${var.client}"
  }
}
```

When I do `terraform apply` a new EIP is created – like expected. But when I do a `terraform destroy` the EIP is deleted. Terraform should keep it, right? Is there something wrong in my config? I can't get my head around it.

**Comment by FernandoMiguel** [comment]
If you destroy, it's gone.
Only if you keep it in another state

Also keep in mind that unused EIP cost a considerable amount of money

--
Fernando Miguel

**Comment by JoostSaanen** [comment]
Thx @FernandoMiguel but what do you mean with 'keep it in another state'?

**Comment by FernandoMiguel** [comment]
In another terraform remote state, another terraform app.

--
Fernando Miguel

**Comment by JoostSaanen** [comment]
Ok, clear! Thx again
