### ISSUE TITLE
Feature Request: Output counts of public/private_route_table_ids

### ISSUE THREAD

**Issue by kinghuang** [terraform-aws-modules/terraform-aws-vpc#119]
The vpc module currently outputs `private_route_table_ids` and `public_route_table_ids`. However, the limitation on computing counts makes it inconvenient to use these ids to add route table rules later on.

It would be useful if the vpc module outputted counts for `private_route_table_ids` and `public_route_table_ids`, perhaps as `private_route_table_ids_count` and `public_route_table_ids_count`.

```
output "private_route_table_ids_count" {
  description = "Count of private route tables"
  value       = "${local.nat_gateway_count}"
}

output "public_route_table_ids_count" {
  description = "Count of public route tables"
  value       = "${var.create_vpc && length(var.public_subnets) > 0 ? 1 : 0}"
}
```

Then, I would be able to the counts with the id lists to add routes, like in the following.

```
module "vpc" {
  source  = "terraform-aws-modules/vpc/aws"
  …
}

resource "aws_route" "private_vgw_route" {
  count = "${module.vpc.private_route_table_ids_count"

  route_table_id = "${module.vpc.private_route_table_ids[count.index]}"
  destination_cidr_block = "10.20.30.40/16"
  gateway_id = "${module.vpc.vgw_id}"
}
```

**Comment by nunofernandes** [comment]
You can do that using the lenght function:
```
module "vpc" {
  source  = "terraform-aws-modules/vpc/aws"
  …
}

resource "aws_route" "private_vgw_route" {
  count = "${length(module.vpc.private_route_table_ids)}"

  route_table_id = "${module.vpc.private_route_table_ids[count.index]}"
  destination_cidr_block = "10.20.30.40/16"
  gateway_id = "${module.vpc.vgw_id}"
}
```

**Comment by antonbabenko** [comment]
King, I think the solution described by @nunofernandes is the best one (especially since it is already available).

**Comment by gadelkareem** [comment]
I am getting ` value of 'count' cannot be computed` when using @nunofernandes  example since those tables do not exist yet.
