### ISSUE TITLE
Is there a way to import existing vpc to this module

### ISSUE THREAD

**Issue by rverma-nikiai** [terraform-aws-modules/terraform-aws-vpc#124]
We already have a vpc in our environment. Just wondering if its possible to import the existing vpc to this module.

**Comment by thiagonache** [comment]
You will need to play with variables and terraform import commands. It's possible, but there's no unique command to perform the whole import.
I.E.:
module "vpc" {
  source = "terraform-aws-modules/vpc/aws"

  name = "my-vpc"
  cidr = "172.31.0.0/16"

  azs             = ["us-west-2a", "us-west-2b"]
  private_subnets = ["172.31.1.0/24", "172.31.2.0/24"]
  public_subnets  = ["172.31.101.0/24", "172.31.102.0/24",]

  enable_nat_gateway = true
  enable_vpn_gateway = true

}

terraform import module.vpc.aws_vpc.this vpc-bba62bdc

run plan again if you are unsure about which resources are pending.

I hope that helped.

**Comment by cornfeedhobo** [comment]
What someone can do is post a bare terraform state with all the resources made. Obviously scrubbed accordingly.
I've found this to be an amazing help when importing something.

**Comment by antonbabenko** [comment]
Check this for example - https://github.com/terraform-aws-modules/terraform-aws-vpc/issues/5#issuecomment-335787341.

Closing this issue as it has been already described.

**Comment by antonbabenko** [comment]
@christoph-buente Try escape arguments in command line, like this:

    terraform import "module.vpc.aws_subnet.public[0]" "subnet-0f0a41b10b373951d"


More here - https://github.com/hashicorp/terraform/issues/18810

**Comment by christoph-buente** [comment]
Awesome, that worked. Thank you!
