### ISSUE TITLE
Any way to configure database subnets to be the private subnets?

### ISSUE THREAD

**Issue by geoffreywiseman** [terraform-aws-modules/terraform-aws-vpc#128]
I've typically built VPCs where the RDS subnets *are* the private subnets. I can imagine that some people prefer to have their RDS instances separated, but ... that seems like added complexity without a lot of added value for my usage. I can, of course, just create the db subnet on my own, which is what I'll probably do in the meantime, but, seems like an option that some people might like to use.

**Comment by murarisumit** [comment]
@geoffreywiseman here by private subnet for RDS you mean subnets without nat gateway ?

**Comment by antonbabenko** [comment]
You can create a full range of subnets using this module. `database_subnets` are just like private_subnets but with additional `aws_db_subnet_group` created for them. Check [complete-vpc](https://github.com/terraform-aws-modules/terraform-aws-vpc/blob/master/examples/complete-vpc/main.tf) for example.

This module can't create `aws_db_subnet_group` for other types of subnets. If you want to do this, you should get outputs from this module and make it outside of this module.
