### ISSUE TITLE
Error when creating tags in route table

### ISSUE THREAD

**Issue by marcread** [terraform-aws-modules/terraform-aws-vpc#136]
I'm running into an error that I think is a bug, or a feature not enabled yet.

The error I am seeing is this:
Error: aws_route.ReadNetOHIOPrivateRT: : invalid or unknown key: tags

Background:
I'm using Terraform v0.11.7 and provider.aws v1.21.0

I'm trying to create a route table and add a tag to it.  I'm using the same format for a tag that I am using on the VPC and subnets.

```
resource "aws_internet_gateway" "internet-gateway" {
  vpc_id = "${aws_vpc.vpc.id}"

  tags {
    Name = "ReadNetOHIO_IGW"
  }
}

# Give the VPC internet access on it's main route table
resource "aws_route" "ReadNetOHIOPublicRT" {
  route_table_id         = "${aws_vpc.vpc.main_route_table_id}"
  destination_cidr_block = "0.0.0.0/0"
  gateway_id             = "${aws_internet_gateway.internet-gateway.id}"

  tags {
    Name = "ReadNetOHIOPublicRT"
  }
}
```

This will produce the error "Error: aws_route.ReadNetOHIOPrivateRT: : invalid or unknown key: tags" however if i run terraform plan with out the route table tags then it will create with out an issue.

```
resource "aws_route" "ReadNetOHIOPublicRT" {
  route_table_id         = "${aws_vpc.vpc.main_route_table_id}"
  destination_cidr_block = "0.0.0.0/0"
  gateway_id             = "${aws_internet_gateway.internet-gateway.id}"
}

# Give the VPC route table for private subnets
resource "aws_route" "ReadNetOHIOPrivateRT" {
  route_table_id         = "${aws_vpc.vpc.main_route_table_id}"
  destination_cidr_block = "10.0.0.0/16"
}
```

are tags on vpc route tables not supported?

**Comment by tomweston** [comment]
I'm also getting `invalid or unknown key: tags` on the aws_eip module:

module.vpc.aws_eip.nat[0]
module.vpc.aws_eip.nat[1]
module.vpc.aws_eip.nat[2]

when trying to deploy the complete-vpc example in 1.34.0

**Comment by antonbabenko** [comment]
[aws_route](https://www.terraform.io/docs/providers/aws/r/route.html) does not have `tags` argument, so the error is correct.
