### ISSUE TITLE
Interpolation errors when public subnet list is empty

### ISSUE THREAD

**Issue by ndegory** [terraform-aws-modules/terraform-aws-vpc#139]
Terraform 0.11.7
terraform-aws-modules/terraform-aws-vpc 1.32.0 to 1.34.0

I ran into this error when I define database_subnet (and no public_subnet or private_subnet) for the vpc module:

```
Error: module.vpc.aws_subnet.public: 1 error(s) occurred:

* module.vpc.aws_subnet.public: At column 21, line 1: list "var.public_subnets" does not have any elements so cannot determine type. in:

${var.public_subnets[count.index]}
```

With version 1.31.0 the issue doesn't occur, the VPC is created with the db subnets.

**Comment by antonbabenko** [comment]
This code works as expected:

```hcl
module "vpc" {
  source = "terraform-aws-modules/vpc/aws"

  name = "simple-example"

  cidr = "10.0.0.0/16"

  azs               = ["eu-west-1a", "eu-west-1b", "eu-west-1c"]
  database_subnets  = ["10.0.101.0/24", "10.0.102.0/24", "10.0.103.0/24"]
}
```

Try to use to the latest version. If you still have problems, please provide terraform code you have.

**Comment by dennybaa** [comment]
@antonbabenko Would you please clarify what means "works as expected"?
Does this mean we can't create a VPC with only private networks ? What is expected? 

```
module "vpc" {
  source = "terraform-aws-modules/vpc/aws"

  name = "${var.project["environment"]}.${var.project["name"]}.${var.region}.vpc"
  cidr = "${var.cidr}"

  azs  = "${local.zones}"
  private_subnets = "${data.null_data_source.subnets.*.outputs.subnet}"
  public_subnets   = []

  enable_nat_gateway = false
  enable_vpn_gateway = false
}
```

**Comment by dennybaa** [comment]
akey, got ya. nothing can be computed, since requires azs to be countable...

**Comment by antonbabenko** [comment]
yes, you are right. TBH I am looking forward to getting this properly supported natively in Terraform so that we don't have to have this as a limitation.
