### ISSUE TITLE
Need ability to assign ASN to a VGW

### ISSUE THREAD

**Issue by Vermyndax** [terraform-aws-modules/terraform-aws-vpc#149]
The Terraform resource aws_vpn_gateway supports the ability to assign an ASN. In our environment, we need this ability to use a Cisco transit VPC solution.

A variable for input and using it in the [resource](https://www.terraform.io/docs/providers/aws/r/vpn_gateway.html) should resolve it.

**Comment by antonbabenko** [comment]
@Vermyndax Thank you for this feature request.

I have opened a pull-request #159, but unfortunately, Terraform 0.11 gives this error:
> Error: module.vpc.aws_vpn_gateway.this: "amazon_side_asn" ("") must be a 64-bit integer

And I don't know better workaround to get this feature implemented.

**Comment by nichtraunzer** [comment]
Wouldn't it make sense to set it with AMazons default ASN (which is 64512 according to
https://docs.aws.amazon.com/cli/latest/reference/ec2/create-vpn-gateway.html )

**Comment by nichtraunzer** [comment]
Hi Anton, any plans to work on that from  your side or shall we provide a change ?

**Comment by antonbabenko** [comment]
Yes, please provide a change. I will try to merge it asap.

Best regards,
Anton.

1 жовт. 2018 р. о 14:37 Erhard <notifications@github.com> пише:
