### ISSUE TITLE
Not able to add subnet specific tags.

### ISSUE THREAD

**Issue by ashish235** [terraform-aws-modules/terraform-aws-vpc#151]
Hi,

When I 'm trying to add tags to specific subnets, I 'm getting the below error. 

Pieces from my tf file. - 
```hcl
module "vpc" {
  source = "terraform-aws-modules/vpc/aws"
  version = "1.37.0"

  private_subnet_tags = {
      Tier = "Private"
  }
}
```

When I run apply, I get the below error.
➜  Production git:(master) ✗ terraform apply

Error: Unknown root level key: private_subnet_tags

Regards,
Ashish

**Comment by antonbabenko** [comment]
Hi @ashish235 !

I have slightly edited code in your question, but I don't know what the problem is.

You should, of course, specify all required arguments which VPC module expects but tagging should be working. Please check examples for more details.
