### ISSUE TITLE
Adding secondary CIDR Blocks

### ISSUE THREAD

**Issue by JohnnyC08** [terraform-aws-modules/terraform-aws-vpc#160]
I've come across an use case where I want to add a secondary CIDR Block and create new subnets with those blocks. I created my VPC with the module so I want to see if I can leverage it to do that.

With `aws_vpc_ipv4_cidr_block_association` we can associate new CIDR blocks, so maybe we can accept a list of `secondary_cidr_blocks` in the module definition and use the length to know how many associations to make.

Now the part I could use some guidance on is how to handle the dependency case. If I'm adding extra CIDR blocks and subnets. I want the vpc created and then the secondary associations created and then everything else created. 

I can take care of this if I get some guidance on how to handle the dependency structure of ensuring the VPC is created and then the associations occur. Maybe we can abstract the vpc resource to an inner module that takes the vpc information and the secondary cidr blocks, then the rest of the main file can reference that module.

Anyways, tell me what you think.

**Comment by matthiasr** [comment]
@JohnnyC08 please do! I also need this and am about to re-do it based on your notes

**Comment by antonbabenko** [comment]
[v1.41.0](https://github.com/terraform-aws-modules/terraform-aws-vpc/releases/v1.41.0) has been released.
