### ISSUE TITLE
Timeouts when creating route

### ISSUE THREAD

**Issue by 4dz** [terraform-aws-modules/terraform-aws-vpc#165]
This is really a reoccurrence of #102 

Occasionally (rarely, but enough to cause us issues) when creating a VPC, it fails because AWS takes too long to create the route.

"Eventual Consistency" means AWS does eventually create it, sometime after the `apply` failed - at which point we have the problems described. (Cannot apply, cannot destroy)

`aws_route.private_nat_gateway.0: Error creating route: RouteAlreadyExists: The route identified by 0.0.0.0/0 already exists`

The only way to fix is to manually destroy the routes, as I haven't been able to successfully import them.

Our use case is that we create and destroy environments quite regularly (development envs primarily)

Is there any way to either increase the 5m timeout? Either via a variable, or else just for all users of the module?

**Comment by antonbabenko** [comment]
Thanks for reporting the issue (if it is an issue).

You should be able to import it like this `terraform import module.vpc.aws_route.private_nat_gateway ...` (see more [here](https://www.terraform.io/docs/providers/aws/r/route.html#import)).

It is not possible to use variables in `timeouts` so we have to use some hardcoded value (5 minutes, we have now, sounds like a lot). You can give it a try if you fork this module and increase this timeout to see if it helps, but it does not sound right to have this timeout increased anyway.

@smihajlovic-frame do you have any ideas about this problem? Does it continue to work for your setup still?

@4dz could you please paste the whole `module` block with all parameters (replace sensitive values) but keep parameters. It may be an edge-case scenario which is not related to timeouts but related to the way/sequence of resources modified by Terraform. Also, please, provide output of `terraform apply`.

**Comment by 4dz** [comment]
Thanks for the quick reply.  

OK, the  module.

`module "vpc" {
  source  = "terraform-aws-modules/vpc/aws"
  version = "1.12.0"

  name                         = "${var.client}-${var.environment}"
  enable_nat_gateway           = true
  single_nat_gateway           = true
  reuse_nat_ips                = "${length(var.external_nat_ip_id) > 0 ? true : false}"
  external_nat_ip_ids          = "${compact(list(var.external_nat_ip_id))}"
  enable_dns_support           = true
  enable_dns_hostnames         = true
  tags                         = "${var.tags}"
  cidr                         = "10.0.0.0/16"
  azs                          = "${var.azs}"
  private_subnets              = "${var.private_subnets}"
  public_subnets               = "${var.public_subnets}"
  database_subnets             = "${var.database_subnets}"
  create_database_subnet_group = false

  private_subnet_tags = {
    "Subnet Tier" = "private"
  }

  public_subnet_tags = {
    "Subnet Tier" = "public"
  }

  database_subnet_tags = {
    "Subnet Tier" = "database"
  }
}`

**Embarrassed**  First thing i notice is the 5m timeout was added in v 1.30.0 so it may be that we are on the old 2m default timeout.

Here's the error - but clearly we need to upgrade and see if that fixes it!


`2 error(s) occurred:

* module.environment.module.vpc.aws_route.private_nat_gateway[0]: 1 error(s) occurred:

* aws_route.private_nat_gateway.0: Error creating route: RouteAlreadyExists: The route identified by 0.0.0.0/0 already exists.
	status code: 400, request id: 7744388d-0285-45f6-911f-8cee9f40c3d0
* module.environment.aws_lb.public_alb: 1 error(s) occurred:

* aws_lb.public_alb: Error creating Application Load Balancer: InvalidSubnet: VPC vpc-09ec55e3893ec2e01 has no internet gateway
	status code: 400, request id: b5ecf42d-b5d0-11e8-9248-a163286b8660`

**Comment by antonbabenko** [comment]
Yes, try to upgrade the module. The overall configuration looks fine.

**Comment by adamrt** [comment]
@4dz Can this be closed?

**Comment by 4dz** [comment]
Thanks guys.  This appears to ha e been fixed with the newer version 1.30+
