### ISSUE TITLE
Problem trying to create multiple private subnets with only one route table

### ISSUE THREAD

**Issue by mebuffet** [terraform-aws-modules/terraform-aws-vpc#169]
First of all, thanks for this module.

About my issue,  for each private subnet created, a respective route table is created too.

Isn't a "real problem" but there's a way to create (with this module) "N" private subnets with only one route table and associate all of them (something like what occurs with the public subnet module) without creating one route table for each private subnet? Or deleting the another seven route tables without use (using the module, without using the terraform resource type)?

**Comment by antonbabenko** [comment]
Hi Maiki,

I am not sure I understand the question entirely, but there is a way to create one routing table for all private routes OR separate routing tables for database, elasticache, redshift like this:

```hcl
  create_database_subnet_route_table    = true
  create_elasticache_subnet_route_table = true
  create_redshift_subnet_route_table    = true
```

You can see example code [here](https://github.com/terraform-aws-modules/terraform-aws-vpc/tree/master/examples/vpc-separate-private-route-tables).

**Comment by mebuffet** [comment]
Hello again Anton, so, I will try explain better my doubt:

These subnets are for EC2 (application).
`private_subnets = [A, B, C]`

So, this function will create the route_tables A, B and C, correct? I need that each EC2 be created at a different private subnet, but, use the same route table.  For example, 1 EC2 at subnet A, 1 at B and 1 at C, but creating only one route table (avoiding create "unnecessary" resources like additional route tables).

I appreciate your workaround, but, there isn't a feature/option or a way to do it like this?
`only_one_private_subnet_for_all_private_subnets = true`

Thanks again for your support.

**Comment by antonbabenko** [comment]
Few facts:
1. Subnets are AZ-aware and can't span multiple AZ.
1. `single_nat_gateway = true` will create single route table and a single NAT gateway.
1. This module may create free resources but it has several ways to control a number of paid resources (eg, NAT gateways)

Hope it helps.

**Comment by mebuffet** [comment]
I see... I was trying to do something different, like without any nat gateway (only using our VPN).

So, the approach using the nat can be helpful. Thanks.
