### ISSUE TITLE
NAT Gateway for each private network

### ISSUE THREAD

**Issue by s7anley** [terraform-aws-modules/terraform-aws-vpc#17]
Hi, I'm just curious, what is the benefit of having NAT gateway associated with each private network instead of having just one?

Thanks!

**Comment by antonbabenko** [comment]
It is a design pattern for high availability. When AZ, where NAT gateway is deployed, is failing you will still have other NAT gateways working as they should and traffic in other unaffected AZs is going through as expected.

In practice, it can be expensive, underutilized and not feasible to have several NAT gateways even for production environments.

**Comment by s7anley** [comment]
Thanks for the clarification.
