### ISSUE TITLE
Add routes to a route table if there are multiple route tables?

### ISSUE THREAD

**Issue by veilig2000** [terraform-aws-modules/terraform-aws-vpc#172]
I might be missing something obvious, but is it possible to dynamically add multiple routes to a route table (private in my case) and still not know how many "private" route tables are created?

I'm still fleshing out how to make this work, but in my example what I want to happen is - if the *.tfvars file has a list of `private_routes`, then it will create them - but what route table do they go to?  If there is only one route table created - easier, but w/ the variable `module.vpc.private_route_table_ids` being a list - and if there are multiple route tables created - how can I know which index I want to assign the routes to?

I'm trying to solve where different environment have different routes that need to be assigned. 

```
resource "aws_route" "vpc_peering" {
  count = "${length(var.private_routes)}"

  route_table_id = "????"
  destination_cidr_block = "${var.private_routes[count.index]}"
}
```

**Comment by su-sfeng** [comment]
@veilig2000 hello, did you come up a right tf file? I am trying to resolve the same issue. If you could share your solution, that'll be wonderful! Thanks!.
