### ISSUE TITLE
Feature Request: Configure network ACLs for subnets

### ISSUE THREAD

**Issue by kinghuang** [terraform-aws-modules/terraform-aws-vpc#173]
One of the most common things I do after creating a VPC with this module is configure network ACLs for public/private/intra subnets. It would be useful if this module provided a way to conveniently configure ACLs, too.

**Comment by okonon** [comment]
Oh man this feature could have saved me a lot of headaches! can't wait!

**Comment by deitch** [comment]
Yes, please. I have a terraform module I wrote with a client a while back that looks very similar, albeit missing much of the extended functionality here. I would love to retire it in favour of this module, but need custom ACLs.

**Comment by antonbabenko** [comment]
There is support for Network ACL rules since [v1.60.0](https://github.com/terraform-aws-modules/terraform-aws-vpc/releases/v1.60.0) if you are using Terraform 0.11.

If you are using Terraform 0.12 you can use any version `~> 2.0`.
