### ISSUE TITLE
Exclude Database, ElastiCache, s3 resources

### ISSUE THREAD

**Issue by pocheptsov** [terraform-aws-modules/terraform-aws-vpc#18]
Hey,
I would recommend excluding from this module Database, ElastiCache, s3 resources cause they're not direct VPC responsibilities and more related to the app stack. Still, you can create a set of smaller modules or use different naming to give a context that module can create much broader resource infrastructure.

**Comment by antonbabenko** [comment]
I completely understand where you are coming from, it has been named "VPC" because most of the resources created by this module are manageable under "VPC" in AWS Console. Also, all potentially unnecessary resources are disabled by default.
