### ISSUE TITLE
module.vpc.aws_redshift_subnet_group.redshift: only lowercase alphanumeric characters and hyphens allowed in "name"

### ISSUE THREAD

**Issue by Miyurz** [terraform-aws-modules/terraform-aws-vpc#180]
Looks like this is coming from `vim modules/terraform-aws-vpc/main.tf +220`

terraform and provider information:
```
$ terraform version
Terraform v0.11.7
+ provider.aws v1.40.0
```

<img width="877" alt="screenshot 2018-10-16 at 2 27 53 pm" src="https://user-images.githubusercontent.com/2662752/47005177-d53e0300-d150-11e8-97dc-89b87c0f8acc.png">

**Comment by Miyurz** [comment]
This PR fixed it https://github.com/terraform-aws-modules/terraform-aws-vpc/pull/181

**Comment by antonbabenko** [comment]
[v1.47.0](https://github.com/terraform-aws-modules/terraform-aws-vpc/releases/tag/v1.47.0) has it fixed.
