### ISSUE TITLE
Feature Request: Use existing VPC id

### ISSUE THREAD

**Issue by Binternet** [terraform-aws-modules/terraform-aws-vpc#182]
I need to use an existing VPC since I have a VPC peering setup already, it could be nice if I could use `existing_vpc_id` as an input and all the other resources will be created on that VPC.

**Comment by lukvdborne** [comment]
I'd suggest you use `terraform import`: https://www.terraform.io/docs/providers/aws/r/vpc.html#import

**Comment by Binternet** [comment]
@lukvdborne hmm, it will give me the state of a given VPC id, but how can I make the module work with this vpc and avoid creating a new vpc?

**Comment by lukvdborne** [comment]
@Binternet, you can define
```hcl
resource "aws_vpc" "my_vpc" { ... }
```
with all the parameters as you have currently defined them already. Try to match them as close as possible.

Then you can run `terraform import aws_vpc.my_vpc vpc-abcdef123` where `vpc-abcdef123` is the VPC ID that already exists. Terraform will then pretend it has created that VPC and include it in its state file. This will cause 2 things to happen:

1. It won't try to create a new VPC
2. You can then reference your VPC attributes as per usual, using something like 
```hcl 
vpc_id = "${aws_vpc.my_vpc.id}"
```
or
```hcl
 vpc_id = "${module.vpc.vpc_id}"
```
if you imported the resources into the module (`terraform import module.vpc.aws_vpc.this vpc-abcdef123`)

Do note that if the attributes in your VPC resource definition don't match your actual VPC attributes, terraform will try to change them into whatever your defined, so make sure to run `terraform plan` after the import to see where the mismatches are and to either correct them in your definition or to apply them so the reality will match your definition. 

Also note that a VPC contains a lot of sub resources. If you want to have them all managed in Terraform, you're going to have to import them individually, one by one.

If you choose to import the resources into the definitions of this module, you are definitely going to have to import them all (think subnets, route tables, routes, various gateways).

Hope this helps.

**Comment by Binternet** [comment]
Will the `terraform-aws-vpc` module create the subnets and other resources for the existing VPC id?

Just to make sure I got it right:
```terraform
resource "aws_vpc" "my_vpc" { ... }
```

and then
```
module "vpc" {
  source  = "terraform-aws-modules/vpc/aws"
  ...
}
````

I'm not sure that can work, I really think about checking out the module and replacing the [local vpc_id](https://github.com/terraform-aws-modules/terraform-aws-vpc/blob/master/main.tf#L10) var into a user-input variable, this way the `terraform-aws-vpc` module can get an existing VPC id and keep creating resources on that vpc.

**Comment by lukvdborne** [comment]
No, you have to choose. Either you import it into this module or you don't use this module and import it into a bare resource. It can work. You can always hardcode the vpc_id in some variable, but then you're not managing your VPC with Terraform.

Either way, a new attribute existing_vpc_id doesn't make much sense. That's the same as just hardcoding it in a custom variable.

**Comment by Binternet** [comment]
hmm, why not? this way I am making this module available to use with an existing vpc_id and letting it do all the rest of the resources creation.

I think i'll go with this -
Checking out this module into my terraform project - only `main.tf`, `variables.tf` and `output.tf`, modifying the local vpc_id so it will be equal to `${var.existing_vpc_id}` (input) and letting the module do all the rest while using the provided vpc id.

I don't understand why this option doesnt make any sense...

**Comment by antonbabenko** [comment]
@Binternet Thanks for opening this feature request. Open issues are the best indicators of what the community wants!

I think it makes sense to add support for BYOR ("bring your own resources") to this module just for VPC. There are a couple of things to consider - introduced complexity (how more complex the module will become?) and flexibility (will all other features continue to work?).

As a potential issue, it can be that a resource `aws_vpc_ipv4_cidr_block_association` (which expands IPv4 CIDR range of the VPC) cannot be used together with VPC which is created outside of a module. It has to be checked.

I don't have time to work on this feature myself and verify it thoughtfully before 1st of November, but after that, I expect to have some time every week to dedicate to any outstanding issues in terraform-aws-modules (thanks to my potential supporters!).

**Comment by Binternet** [comment]
Hey @antonbabenko,
First of all - thank you for your great work on this module!

In any event - like I mentioned earlier - i copied the `.tf` files of the module, and changed the `local.vpc_id` to:
```
locals {
...
vpc_id = "${var.vpc_id}"
}
```

and then injected my existing vpc_id into that module, while keeping all the other variables the way I want (private/public subnets etc'), it looks like its working fine for now.

That about creating a PR that supports `existing_vpc_id` but I think i'll do more damage than contribution =)

**Comment by antonbabenko** [comment]
"it looks like its working fine for now" - this is a key :)

I have described the potential issue in my previous comment which has to be investigated and verified in order to not break existing code.

**Comment by Binternet** [comment]
@antonbabenko I see, but I am not using any secondary cidr blocks so it should be OK.

Besides, from what I see in the code - the `aws_vpc_ipv4_cidr_block_association` was also modified to use
```
vpc_id = "${var.vpc_id}"
```

So even if I do decide to use `secondary_cidr_blocks` that shouldn't be an issue.

**Comment by lukvdborne** [comment]
@Binternet well yeah, of course that works, but there are several issues.

The first being that you now have to maintain your own fork of this module. That's unnecessary hassle that can and should therefore be avoided. Having a customisable var implies that it should be user-transformable, but it isn't. There's a reason that the id is an output only, not an input, even in the core `aws_vpc` resource.

Secondly, what you did is basically perform a `terraform import` in a very roundabout way. So you might also just have run `terraform import module.vpc.aws_vpc.this vpc-abcdef123` and have gotten the same result. 

Note that you may now have duplicate resources within your VPC. The ones that were manually created by you or automatically by AWS upon VPC creation on the one hand, and the VPC resources that Terraform will have terraformed on the other. Think subnets, route tables, gateways. Existing resources may now make use of the "original" VPC resources, whilst new resource may be terraformed for using the new VPC resources.

**Comment by Binternet** [comment]
@lukvdborne That's exactly what I want to achieve.

If I am importing a resource, and even if a vpc resource is defined in terraform, it could be eventually get destroyed and that I cannot afford on this specific case.

I want the VPC (and vpc entity only!) to be outside of terraform's scope since I am _manually_ creating a VPC and adding a vpc peering to it (which requires approval on the other side...), it want it to stick and terraform should not manage these two resources. (vpc + peering).

All the other resources, such as routing tables, subnets etc' can be created/destroyed by terraform and I am fine with it.

So the way I see it - except for creating a "custom" module based on this module, I don't see a problem.

**Comment by LuluGO** [comment]
@lukvdborne thanks for that solution, would that work for a vpc in a different region that is already defined? looking at ways on how to do that ...

**Comment by devendhirababu** [comment]
Hello All,

I would like to create my existing VPC and related resources (subnet, SG, route table, NACL, IGW, NAT- instance) into the other region by using terraform import. The VPC consists of multiple CIDR and subnets in a different availability zone. I want to replicate the same set of resources in the other region please provide your suggestion/guidance to achieve.

**Comment by dieend** [comment]
I was able to import my existing VPC to this module.
This is how it looks like:
```
locals {
  cidr_block = "10.0.0.0/16"
  azs             = ["us-west-2a", "us-west-2b", "us-west-2c"]
}

resource "null_resource" "cidr_subnet" {
  count = "${length(local.azs)}"

  triggers {
    value     = "${cidrsubnet(local.cidr_block, 8, count.index)}"
  }
}


module "vpc" {
  source = "terraform-aws-modules/vpc/aws"

  name = "datainfra"
  cidr = "${local.cidr_block}"

  azs = "${local.azs}"
  public_subnets  = "${null_resource.cidr_subnet.*.triggers.value}"
  public_dedicated_network_acl = "true"

  assign_generated_ipv6_cidr_block = "false"
  instance_tenancy = "default"

  enable_nat_gateway = "false"
  enable_vpn_gateway = "false"
  enable_dns_support = "true"
  enable_dns_hostnames = "true"

  tags = {
    Terraform = "true"
    Environment = "Production"
    Name = "Test"
  }
}
```
Importing is the right approach to it and make everything shorter and maintainable.
My suggestion is to list all the resource that currently exists (I made barebone resource definition and use `terraform state mv` just to be safe, and compare the output whether it's correct or not). And be sure to look at main.tf, because that way you can understand how the resource actually being created.

**Comment by tcarecolin** [comment]
Thank you @Binternet for asking this question !

I currently ran into exactly same issue, i was about to manage to import my existing VPC so i could deploy new modules on it using tf, but how about the destroy ? would this solution let tf to destroy only the created ressources and let VPC as is ?
Thanks

**Comment by Binternet** [comment]
@tcarecolin As far as I know, tf only destroys resources that are listed on the state file therefore only the ones that were imported or created by tf, but since this is a non-trivial decision - you should get a second opinion on that ;-)

**Comment by sunmakrules** [comment]
@mosaic-Jason-Brody-Stewart-Stroeh Can you share the solution your figured out. Also, if it works  then the issue can be closed.

**Comment by mosaic-Jason-Brody-Stewart-Stroeh** [comment]
In short scraped out some sensitive information but below is what I did.....

main.tf
... 
terraform {
  required_version = ">= 0.12.6"
}

provider "aws" {
  region = "*******"
}

resource "random_id" "random" {
  byte_length = 3
}

resource "aws_security_group" "kafka-sg" {
  name        = "kafka"
  description = "SG for new kafka cluster"
  vpc_id      = "${var.aws_vpc_id}"

  egress {
    from_port   = 0
    to_port     = 0
    protocol    = "****"
    cidr_blocks = ["***********"]
  }
}

resource "aws_security_group_rule" "ingress_kafka" {
  count = "${length(var.kafka_ports)}"

  type        = "ingress"
  protocol    = "tcp"
  cidr_blocks = ["${var.incoming_cidr}"]
  from_port   = "${element(var.kafka_ports, count.index)}"
  to_port     = "${element(var.kafka_ports, count.index)}"

  security_group_id = "${aws_security_group.kafka-sg.id}"
}

resource "aws_kms_key" "kafka-kms" {
  description = "kafka-kms"
}

locals {
  cluster_name = "${var.cluster_name}-${(var.uniq_id == "random" ? random_id.random.b64_url : var.uniq_id)}"
}

resource "aws_msk_cluster" "kafka" {
  cluster_name           = "${local.cluster_name}"
  kafka_version          = "${var.kafka_version}"
  number_of_broker_nodes = "${var.number_of_broker_nodes}"

  broker_node_group_info {
    instance_type   = "${var.instance_type}"
    ebs_volume_size = "${var.ebs_volume_size}"

    client_subnets = [
      "${var.subnet_ids.subnet1}",
      "${var.subnet_ids.subnet2}",
      "${var.subnet_ids.subnet3}"
    ]

    security_groups = ["${aws_security_group.kafka-sg.id}"]
  }

  encryption_info {
    encryption_at_rest_kms_key_arn = "${aws_kms_key.kafka-kms.arn}"
  }

  tags = {
    Name = "${local.cluster_name}"
  }
}

output "zookeeper_connect_string" {
  value = "${aws_msk_cluster.kafka.zookeeper_connect_string}"
}

output "bootstrap_brokers_tls" {
  description = "TLS connection host:port pairs"
  value       = "${aws_msk_cluster.kafka.bootstrap_brokers_tls}"
}

variables.tf
....
variable "aws_vpc_id" {
  description = "The ID of the testing VPC network."
  type        = string
  default     = "vpc-***********"
}

variable "subnet_ids" {
  description = "VPC subnet IDs"
  type        = "map"
  default = {
    subnet1 = "subnet-*******"
    subnet2 = "subnet-*******"
    subnet3 = "subnet-*******"
  }
}

# incoming traffic source
variable "incoming_cidr" {
  default = "************"
}

# incoming ports (WIP)
variable "kafka_ports" {
  default = ["2181", "2888", "3888", "9092", "9094"]
}

# cluster name
variable "cluster_name" {
  default = "kafka"
}

# cluster id, "random" for random"
variable "uniq_id" {
  default = "random"
}

# cluster name
variable "kafka_version" {
  default = "2.2.1"
}

variable "number_of_broker_nodes" {
  default = "3"
}

variable "instance_type" {
  default = "kafka.m5.large"
}

variable "ebs_volume_size" {
  default = "20"
}

**Comment by sunmakrules** [comment]
> Hey @antonbabenko,
> First of all - thank you for your great work on this module!
> 
> In any event - like I mentioned earlier - i copied the `.tf` files of the module, and changed the `local.vpc_id` to:
> 
> ```
> locals {
> ...
> vpc_id = "${var.vpc_id}"
> }
> ```
> 
> and then injected my existing vpc_id into that module, while keeping all the other variables the way I want (private/public subnets etc'), it looks like its working fine for now.
> 
> I thought about creating a PR that supports `existing_vpc_id` but I think i'll do more damage than contribution =)

Hi @Binternet , I want to achieve the same thing exactly. I tried using the example "manage_default_vpc" which doesn't really work. Can you explain it in a little more detail of how you achieved the same? TIA.

**Comment by Binternet** [comment]
@sunmakrules Sure.
Like I said - I copied the entire module files into my machine instead of remotly invoking the module and just replaced the `vpc_id` local var to `var` reference. 

Here's the module usage:
```
module "vpc" {
  source = "../provider/aws/modules/vpc" <-- Note this, it is a local reference
  vpc_id = "${var.vpc_id}"
  name   = "${var.vpc_name}"

  azs            = ["${var.aws_region}a", "${var.aws_region}b", "${var.aws_region}c"]
  intra_subnets  = "${var.intra_subnets}"
  public_subnets = "${var.public_subnets}"

  enable_nat_gateway = false

  tags = {
    Terraform = "true"
    Env       = "${var.env}"
  }
}
```

And in `providers/aws/modules/vpc/main.tf`:

```
locals {
  max_subnet_length = "${max(length(var.private_subnets), length(var.elasticache_subnets), length(var.database_subnets), length(var.redshift_subnets))}"
  nat_gateway_count = "${var.single_nat_gateway ? 1 : (var.one_nat_gateway_per_az ? length(var.azs) : local.max_subnet_length)}"

  vpc_id = "${var.vpc_id}"  <-- Note this
}
```

Hope this helps

**Comment by Prasanthmv** [comment]
How can I get vpcid in prod_subnets I this structure?

module "vpc" {
  source = "./modules/vpc"
}

module "prod_subnets" {
  source = "./modules/vpc/modules/subnets/production"
}

**Comment by rashidhamid139** [comment]
Thank you @Binternet for asking this question !

My use case matches almost with the same question, I have an existing VPC peering setup, So what I need to do is to take vpc id of one vpc and validate peering exists between the two VPC's. How can I validate this??

**Comment by mericano1** [comment]
I have the same problem. Would using the data source be an option at all ? https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/vpc 

The problem I have is that the VPC is shared and the lifecycle (destroy, etc) is managed separately
