### ISSUE TITLE
"Private" Route Tables are created even when they are not needed/used

### ISSUE THREAD

**Issue by heathryu** [terraform-aws-modules/terraform-aws-vpc#184]
I see that there's recently been an introduction of input flags such as:
- create_database_subnet_route_table
- create_elasticache_subnet_route_table
- create_redshift_subnet_route_table

I think the module is currently not handling the Route Table creations correctly depending on the setup.

Example settings to reproduce:
1. Declare 'database' Subnets for your VPC, but not the 'private' Subnets
2. Set the value of **create_database_subnet_route_table** to true

Expected Behaviour:
Only the 'database' Route Table should be created and associated to the 'database' Subnets

Actual Behaviour:
The module not only creates 'database' Route Table but also 3 'private' Route Tables that are not associated to any subnets

**Comment by evairmarinho** [comment]
Hi! My code changes suggestions :)
###  Currently: 
https://github.com/terraform-aws-modules/terraform-aws-vpc/blob/57ba0ef08063390636daedcf88f71443281c2b84/main.tf#L8
### Proposal:

An initial change would be to modify the logic of `local.nat_gateway_count`. 
Change proposal
```hcl
nat_gateway_count = var.single_nat_gateway ? 1 : var.one_nat_gateway_per_az ? length(var.azs) : !var.single_nat_gateway && !var.enable_nat_gateway ? 0 : local.max_subnet_length
```

**Comment by Andor** [comment]
#543

**Comment by bryantbiggs** [comment]
hi all, this should be addressed in the next version which is under development here [https://github.com/clowdhaus/terraform-aws-vpc-v4/tree/main/modules/subnets](https://github.com/clowdhaus/terraform-aws-vpc-v4/tree/main/modules/subnets?rgh-link-date=2022-03-09T22%3A03%3A36Z)
