### ISSUE TITLE
Changing public subnets count forces recreation of nat gateway(s)

### ISSUE THREAD

**Issue by ebarault** [terraform-aws-modules/terraform-aws-vpc#186]
First create a simple vpc with 2 AZs, 2 private subnets, and a single NAT gateway

```
module "vpc" {
 ...
  cidr = "10.0.0.0/16"

  azs             = ["eu-west-1a", "eu-west-1b"]
  private_subnets = ["10.0.1.0/24", "10.0.2.0/24"]
  public_subnets  = ["10.0.101.0/24", "10.0.102.0/24"]

  enable_nat_gateway = true
  single_nat_gateway = true

}
```

Then try adding a new public subnet (this would go in the first of the 2 AZs)

```
module "vpc" {
 ...
  cidr = "10.0.0.0/16"

  azs             = ["eu-west-1a", "eu-west-1b"]
  private_subnets = ["10.0.1.0/24", "10.0.2.0/24"]
  public_subnets  = ["10.0.101.0/24", "10.0.102.0/24", "10.0.103.0/24"]

  enable_nat_gateway = true
  single_nat_gateway = true
}
```

Terraform plan triggers recreation of the unique NAT Gateway:

```
-/+ module.vpc.aws_nat_gateway.this (new resource required)
      id:                              "nat-00742d4e975c21572" => <computed> (forces new resource)
      allocation_id:                   "eipalloc-47750969" => "eipalloc-47750969"
      network_interface_id:            "eni-b75397e8" => <computed>
      private_ip:                      "172.40.0.101" => <computed>
      public_ip:                       "52.47.133.72" => <computed>
      subnet_id:                       "subnet-3c76a455" => "${element(aws_subnet.public.*.id, (var.single_nat_gateway ? 0 : count.index))}" (forces new resource)
```

The following expression `${element(aws_subnet.public.*.id, (var.single_nat_gateway ? 0 : count.index))}"` would trigger recreation of NAT Gateways anytime as it has to be computed even when `single_nat_gateway = true` and the first item of the `aws_subnet.public.*.id` list does not change.

**Comment by gordonbondon** [comment]
Same happens if `private_subnets` list is changed. As a workaround I had to manually create and import `aws_eip` for new nat gateway. With this import only route tables and endpoint associations were recreated, which is not that problematic.

**Comment by bugre** [comment]
Hi @gordonbondon ,
I'm facing similar problem, could you explain the steps/commands you've used to create/import the aws_eip "manually" as you mention?
Thanks

**Comment by gordonbondon** [comment]
@bugre I've just looked in terraform plan at what parameters are set for new eip, and created it manually. Then I've imported it as described here https://www.terraform.io/docs/providers/aws/r/eip.html#import

**Comment by gordonbondon** [comment]
I had to go through this issue once more so for completeness here’s and order of commands I had to apply to be able to add new private/public subnet:
```
terraform plan -target module.vpc
terraform plan -target module.vpc.aws_eip.nat
terraform apply -target module.vpc.aws_eip.nat
terraform plan -target module.vpc
terraform plan -target module.vpc.aws_subnet.private
terraform apply -target module.vpc.aws_subnet.private
terraform plan -target module.vpc
terraform plan -target module.vpc.aws_subnet.public
terraform apply -target module.vpc.aws_subnet.public
terraform plan -target module.vpc
terraform plan -target module.vpc.aws_nat_gateway.this
terraform apply -target module.vpc.aws_nat_gateway.this
terraform plan -target module.vpc
terraform plan -t module.vpc.aws_route_table.private
terraform plan -target module.vpc.aws_route_table.private
terraform apply -target module.vpc.aws_route_table.private
terraform plan -target module.vpc
terraform apply -target module.vpc
```

**Comment by ebarault** [comment]
indeed this is a lovely solution to a by-design problem @gordonbondon 👍 

I documented the approach in our codebase, only one step is mandatory in our case: creating the private subnets separately, then we can apply our whole module, and the NAT GW does not get be recreated

**Comment by bryantbiggs** [comment]
hey all - thanks for the submission. this would be quite difficult to codify in terraform to handle this appropriately within the module. I think the solution that @gordonbondon has proposed is the most appropriate solution at this time - adding/removing subnets should not be happening that frequently and so manually interacting with the statefile to get around this issue would be the quickest approach
