### ISSUE TITLE
Error running terraform init using latest version

### ISSUE THREAD

**Issue by trentpack-Allegiant** [terraform-aws-modules/terraform-aws-vpc#192]
2018/12/13 09:46:34 [DEBUG] fetching "https://api.github.com/repos/terraform-aws-modules/terraform-aws-vpc/tarball/v1.49.0?archive=tar.gz" with key "1.automation_testing;../../aws_vpc|aws_vpc;terraform-aws-modules/vpc/aws.1.49.0"
  Found version 1.49.0 of terraform-aws-modules/vpc/aws on registry.terraform.io
  Getting source "terraform-aws-modules/vpc/aws"
2018/12/13 09:46:35 [DEBUG] plugin: waiting for all plugin processes to complete...
Error downloading modules: Error loading modules: chtimes .terraform/modules/dda9a93f3111945faf6385486787a18d/terraform-aws-modules-terraform-aws-vpc-44bb589/.circleci/config.yml: invalid argument

**Comment by trentpack-Allegiant** [comment]
Found that moving to 386 version of terraform binary and rm -rf ~/.terraform.d fixed the problem.

**Comment by antonbabenko** [comment]
Good. Closing this issue.
