### ISSUE TITLE
Bug: NAT gateway missing from private subnet route tables

### ISSUE THREAD

**Issue by bflugon** [terraform-aws-modules/terraform-aws-vpc#206]
I just used this module to create a new VPC with NAT Gateways in each AZ. The problem is that the route tables for the private subnets doesn't have the NAT gateways included. This is most likely related to https://github.com/terraform-aws-modules/terraform-aws-vpc/blob/master/main.tf#L99 where `nat_gateway_id = ` is missing.

**Comment by chicken231** [comment]
Are you explicitly setting these three variables like this?:

```
enable_nat_gateway = true
single_nat_gateway = false
one_nat_gateway_per_az = true
```

Today, I've been making tweaks to my VPC config with module version `1.53.0`, and with those three definitions above, the route table for my private subnets reference a NAT gateway as expected.

But my problem is, with the above config, I can't reach anything in my **EKS** cluster from the internet.
I'm having to stick with this for now:

```
enable_nat_gateway = true
single_nat_gateway = true
one_nat_gateway_per_az = false
```

While I don't see the symptoms you're describing, something ain't right.

**Comment by bflugon** [comment]
No, I only set the options that wasn't set by default. I can try setting all options explicitly later this week to see if that fixes the problem.

**Comment by antonbabenko** [comment]
@bflugon `nat_gateway_id` does not set on `aws_route_table`, but rather on individual `aws_route`: https://github.com/terraform-aws-modules/terraform-aws-vpc/blob/8e2f50e6c8f8fd8b0abcaf2c4150d7446276fcaa/main.tf#L321-L331

**Comment by bflugon** [comment]
The problem disappeared with my current configuration, so I'm closing this issue.
