### ISSUE TITLE
Feature Requeest - AWS Transit Gateway Support

### ISSUE THREAD

**Issue by Jeeppler** [terraform-aws-modules/terraform-aws-vpc#207]
AWS announced a new product during re:Invent 2018 called [Transit Gateway](https://aws.amazon.com/transit-gateway/). Transit Gateway (TGW) acts as a hub between connected VPC's and supports VPN as well.

The VPC reference architecture from AWS suggests to have separate subnets just for the TGW endpoints [1]. 

![tgw_vpc_architecture](https://user-images.githubusercontent.com/2007739/52001734-c53efa80-2485-11e9-81e4-b0e0c28ea96c.png)

It would be nice if this module could support the creation of separate TGW subnets and have in general TGW support.

[1]: AWS re:Invent 2018: [NEW LAUNCH!] Introducing AWS Transit Gateway (NET331)  https://youtu.be/yQGxPEGt_-w?t=24m51s

**Comment by antonbabenko** [comment]
Yes, this would be a great addition to this module. PR is welcome.

**Comment by Jeeppler** [comment]
@antonbabenko I am not able to create a PR for the Transit Gateway feature.  However, I would be really happy if somebody else wants to take on the task.

**Comment by antonbabenko** [comment]
You should fork this repository, add required code and submit a pull-request into this repository.

**Comment by tbugfinder** [comment]
IMHO, terraform-aws-providers still lacks a few TGW details, however we could start with an implementation to start with.

**Comment by tbugfinder** [comment]
Do you think the TGW should be part of the terraform-aws-vpc module as it is with the "VPC service" ?

**Comment by antonbabenko** [comment]
TBH I have not been thinking about this feature so much yet, but I think it makes sense to be part of this module in the first place. This module can handle the creation of TGW, routes, route tables, VPC attachments.

Also, it should be possible to attach other resources to it outside of the module, if users want.

**Comment by Jeeppler** [comment]
At the very least this module should be able to create subnets for the TGW endpoins.

**Comment by alex-goncharov** [comment]
Personally, I do not think that TGW itself has a place in this module, given that multiple VPC's share one or more TGW's. Then, there are TGW routing tables, which, i think, belong to TGW and are also "shared" among VPC's. It is also possible that TGW and routing tables are in different account.

What could be a part of this module are VPC attachments to the TGW as well as additional routes that point to a given TWG. I looked at it and it seems (at least until tf 12) that using route table IDs to populate additional routes elsewhere is easier than passing routing information into module.

**Comment by mehstg** [comment]
So I am currently using Transit Gateway alongside this module. One thing that would be worthwhile to have is the ability to pass in routes to the VPC module. After adding a VPC to the transit link, I need to add the routes in to the private subnet route tables....it is not currently possible to do this

**Comment by Jeeppler** [comment]
@mehstg are you deploying your network interfaces in separate subnets in the VPC?

**Comment by mehstg** [comment]
I am not. My instances are split out in to private/public/database

**Comment by zelig81** [comment]
What is absent the most - possibility to get multiple results TGW resources (tgw, attachments, transit route tables) using data provider aws. I had to use External data source with python scripts to get mapping of the needed resources IDs for further use in AWS data source with 'count'...

**Comment by antonbabenko** [comment]
There is now [terraform-aws-transit-gateway module](https://github.com/terraform-aws-modules/terraform-aws-transit-gateway) which allows you to make TGW resources and attach multiple VPC into it.

Check [examples there](https://github.com/terraform-aws-modules/terraform-aws-transit-gateway/blob/master/examples/complete/main.tf).

Closing this issue, because there is not much what this VPC module can/should be doing in regards to integration with TGW.
