### ISSUE TITLE
One NAT Gateway per subnet question

### ISSUE THREAD

**Issue by nshenry03** [terraform-aws-modules/terraform-aws-vpc#208]
For https://github.com/terraform-aws-modules/terraform-aws-vpc#one-nat-gateway-per-subnet-default, the module will determine the number of NAT Gateways to create based on the the max() of the private subnet lists (database_subnets, elasticache_subnets, private_subnets, and redshift_subnets). See https://github.com/terraform-aws-modules/terraform-aws-vpc/blob/master/main.tf#L6 ...

Is this what is desired, even though only `database_subnets` and `private_subnets` have routes through the NAT Gatways (similar to `intra_subnets`, `elasticache_subnets` and `redshift_subnets` do not have routes to the internet)?

Also, should we include `database_subnets` in this list if `create_database_internet_gateway_route` is `true`?

**Comment by bryantbiggs** [comment]
@nshenry03 please update to the latest as there have been a number of changes, specifically around managing routes/route tables for database subnets. you can respond here if you are still facing an issue and I can re-open or feel free to open a new issue
