### ISSUE TITLE
Logic Error in interface endpoint creation (e.g. public subnet)

### ISSUE THREAD

**Issue by tbugfinder** [terraform-aws-modules/terraform-aws-vpc#210]
https://github.com/terraform-aws-modules/terraform-aws-vpc/blob/8e2f50e6c8f8fd8b0abcaf2c4150d7446276fcaa/main.tf#L416-L426

I tried to create endpoints within public_subnets but this is not possible as per the given code. I even cannot use the vpc module just as a helper as "create_vpc=true" is required for it.

I cannot use public_subnet_ids as input as I don't know it beforehand.

**Comment by antonbabenko** [comment]
This is the intended behavior and design.

If you want to create it without VPC, or in public subnet for any reason, you have to add resource `aws_vpc_endpoint` outside of the module.
