### ISSUE TITLE
Feature Request - TGW + Single INET VPC architecture = No multiple IGW

### ISSUE THREAD

**Issue by aacecandev** [terraform-aws-modules/terraform-aws-vpc#216]
Hi every one, 

I have faced a lack of module functionality while working with the new AWS Transit Gateway. Let me explain:

I am trying to develop an architecture with a central Transit Gateway that replaces the peerings that allow communication between my VPCs, and although I have successfully done so using HCL's own modules for this, I would like to improve the architecture by enabling a VPC whose mission is to act as a single exit point to the public Internet.

A small example of the model I am trying to achieve:

![architecture diagram](https://user-images.githubusercontent.com/21305300/52729027-a9287680-2fb8-11e9-861f-6a7934ac393f.jpg)

The main motivation to develop this infrastructure is to have a central I/O point to the public Internet, through a single AWS Internet Gateway, in such a way that if you wanted to control traffic through ACLs, implement Firewalls, or any other control measure, you would have to act only at that central point. This central point, to which VPC-1, VPC-2 and VPC-3 would be connected through the TGW, is the INET VPC, which would be the only one that would have an IGW in its public subnets.

The functionality I would like to have is the ability, through a flag controlled by a Boolean, that IGWs would not be created in each of the public subnets of the VPC, but would be optional.

To be more precise I think that it should be possible to apply in the creation of IGW, [in this line](https://github.com/terraform-aws-modules/terraform-aws-vpc/blob/master/main.tf#L64)

Could it be possible to work into this feature?

Best regards!

**Comment by tbugfinder** [comment]
Isn't using only private subnets in VPC-1, VPC-2, VPC-3 an option an just use public subnets in the INET VPC?
Which impact would that have?

**Comment by aacecandev** [comment]
Hi @tbugfinder,

It is not an option, I have to use nat gateway for my private subnets just for only certains instances.

Best regards!

**Comment by antonbabenko** [comment]
@aacecandev I have good news for you :)

There is now [terraform-aws-transit-gateway module](https://github.com/terraform-aws-modules/terraform-aws-transit-gateway) which allows you to make TGW resources and attach multiple VPC into it. Check [examples there](https://github.com/terraform-aws-modules/terraform-aws-transit-gateway/blob/master/examples/complete/main.tf#L23-L57).

Closing this issue, because there is not much what VPC module can/should be doing in regards to integration with TGW.

Ref #207 , #241
