### ISSUE TITLE
Feature request - VPN Gateway

### ISSUE THREAD

**Issue by bcenker** [terraform-aws-modules/terraform-aws-vpc#22]
I see there is a separate repo for terraform-aws-vpn-gateway - would it make sense to include the vpn gateway in the vpc module, given that is is managed under the VPC console and a vpn gateway would only be created within a VPC?  I haven't been able to think of a scenario where a vpn gateway resource would be created outside the scope of the vpc it was going to be attached to.  Route-table-propagation could then be refactored as a true/false flag instead of having to define a vpn gateway elsewhere and pass it in as a variable.  I can submit a PR for this if it makes sense.

**Comment by antonbabenko** [comment]
Yes, it makes sense to be included into this VPC module. This is the code we've from before - https://github.com/terraform-community-modules/tf_aws_vpn_gw

PS: Earlier today I have written a list of things to consider when implementing [VPC log feature](https://github.com/terraform-aws-modules/terraform-aws-vpc/issues/23). It is pretty similar to the one needed for VPN Gateway.

It would be awesome if you can work on it. Let me know if you have other questions.

**Comment by antonbabenko** [comment]
Done in [v1.1.0](https://registry.terraform.io/modules/terraform-aws-modules/vpc/aws/1.1.0). Thanks @bcenker
