### ISSUE TITLE
Extend VPC Endpoint for execute-api

### ISSUE THREAD

**Issue by tharun-allu** [terraform-aws-modules/terraform-aws-vpc#224]
Extend VPC Endpoint to execute-api service. I might be able to contribute if no one else is working on this already.

**Comment by tharun-allu** [comment]
submitted https://github.com/terraform-aws-modules/terraform-aws-vpc/pull/225 for review

**Comment by antonbabenko** [comment]
Resolved in #225.

https://github.com/terraform-aws-modules/terraform-aws-vpc/releases/v1.58.0
