### ISSUE TITLE
Terraform 0.12 Support

### ISSUE THREAD

**Issue by sc250024** [terraform-aws-modules/terraform-aws-vpc#227]
Greetings,

I'm assuming no one is working on converting this module to be compatible with Terraform 0.12 yet. If you are, please comment here. Otherwise, I wouldn't mind taking on this task since 0.12 is now in beta.

Cheers!

**Comment by antonbabenko** [comment]
Hi Scott!

I've been working on it for a while and expecting to release an update (WIP) during this week.

Will keep this issue open for a while.

**Comment by sc250024** [comment]
Sweet, thanks @antonbabenko . Let me know if you need help testing / upgrading. Cheers!

**Comment by antonbabenko** [comment]
https://github.com/terraform-aws-modules/terraform-aws-vpc/pull/228 - draft

**Comment by Spechal** [comment]
Would it be safe to assume that since I am using 0.12 I could run into issues?

Fighting something weird; I can SSH into boxes but they can't see or ping each other. Already looked at the SGs, routes and all of that.  It all appears fine ... just curious since I saw this issue ticket.

**Comment by antonbabenko** [comment]
[v2.0.0](https://github.com/terraform-aws-modules/terraform-aws-vpc/releases/v2.0.0) has been released.

Thanks to everyone involved, and please report if you find any issues.
