### ISSUE TITLE
module.vpc.aws_route_table_association.public: 3 error(s) occurred

### ISSUE THREAD

**Issue by carlosafpcapital** [terraform-aws-modules/terraform-aws-vpc#230]
Error: Error running plan: 3 error(s) occurred:

* module.vpc.aws_route_table_association.public: 3 error(s) occurred:

* module.vpc.aws_route_table_association.public[0]: element: element() may not be used with an empty list in:

${element(aws_subnet.public.*.id, count.index)}
* module.vpc.aws_route_table_association.public[1]: element: element() may not be used with an empty list in:

${element(aws_subnet.public.*.id, count.index)}
* module.vpc.aws_route_table_association.public[2]: element: element() may not be used with an empty list in:

${element(aws_subnet.public.*.id, count.index)}
* module.vpc.aws_nat_gateway.this: 1 error(s) occurred:

* module.vpc.aws_nat_gateway.this: element: element() may not be used with an empty list in:

${element(aws_subnet.public.*.id, (var.single_nat_gateway ? 0 : count.index))}
* aws_instance.bastion: 1 error(s) occurred:

* aws_instance.bastion: At column 28, line 1: list "module.vpc.public_subnets" does not have any elements so cannot determine type. in:

${module.vpc.public_subnets[0]}

--------------------My file configuration ----
# VPC
module "vpc" {
  source                    = "modules/vpc"

  name                      = "${var.app_name} VPC"
  cidr                      = "10.0.0.0/16"
  map_public_ip_on_launch   = false

  azs                       = "${data.aws_availability_zones.available.names}"
  private_subnets           = ["10.0.1.0/24", "10.0.2.0/24", "10.0.3.0/24"]
  public_subnets            = ["10.0.101.0/24", "10.0.102.0/24", "10.0.103.0/24"]

  enable_nat_gateway        = true
  single_nat_gateway        = false
  one_nat_gateway_per_az    = true
  enable_vpn_gateway        = false
  enable_dns_support        = true
  enable_dns_hostnames      = true

  tags = {
    Terraform = "true"
    Environment = "dev"
  }
}

**Comment by carlosafpcapital** [comment]
@antonbabenko pls i need your help

**Comment by antonbabenko** [comment]
I am not sure I understand the whole picture. You wrap this module and put it in "modules/vpc" which has some issues (eg, `aws_instance.bastion`)

I don't have a possibility to help in details, but I recommend to try to call this module first to create all required resources before you can use them in other modules (eg, to launch bastion hosts).

**Comment by bryantbiggs** [comment]
closing this for now but please feel free to respond or open a new issue with more information so we can help @carlosafpcapital
