### ISSUE TITLE
Compulsory Name Module Parameter

### ISSUE THREAD

**Issue by Tensho** [terraform-aws-modules/terraform-aws-vpc#232]
I wonder is it eligible to leave `name` module parameter blank? Module variable `name` has an empty string as a default value (documentation states it as not required either), but when I plan/apply such configuration the next error appears:

    Error: module.vpc.aws_db_subnet_group.database: only lowercase alphanumeric characters, hyphens, underscores, periods, and spaces allowed in "name"

from this place:

https://github.com/terraform-aws-modules/terraform-aws-vpc/blob/b5b23cdd5b52a0ab29018c4ecb27e722648e0d62/main.tf#L223

**Comment by antonbabenko** [comment]
`name` and most (if not all) arguments have defaults because the creation of many resources (including VPC) can be disabled. If the creation of the resource is disabled then the default value will be provided.
