### ISSUE TITLE
Refer to AZ in Tag

### ISSUE THREAD

**Issue by Tensho** [terraform-aws-modules/terraform-aws-vpc#233]
Is it possible somehow to refer the specific AZ from `azs` list in tag declaration? Pseudo-code:
```
  database_subnet_tags = {
    Name = "RDS ${var.azs[count.index]}"
  }
```
As you may guess I 'd like to generate custom tag value with interpolated AZ.

**Comment by antonbabenko** [comment]
Currently, there is no such possibility provided. It is almost always possible to filter by tag and by other attributes (eg, az) simultaneously to get a specific resource.
