### ISSUE TITLE
module.vpc.aws_vpc_dhcp_options.this: aws_vpc_dhcp_options.this: diffs didn't match during apply

### ISSUE THREAD

**Issue by svaitsis** [terraform-aws-modules/terraform-aws-vpc#244]
Hello,

I got the following issue and I think it would be good to report. I got this during a change I tried to apply for the dhcp options.

=====

Error: Error applying plan:

1 error(s) occurred:

module.vpc.aws_vpc_dhcp_options.this: aws_vpc_dhcp_options.this: diffs didn't match during apply. This is a bug with Terraform and should be reported as a GitHub Issue.

Please include the following information in your report:
    Terraform Version: 0.11.13
    Resource ID: aws_vpc_dhcp_options.this
    Mismatch reason: attribute mismatch: domain_name
    Diff One (usually from plan): *terraform.InstanceDiff{mu:sync.Mutex{state:0, sema:0x0}, Attributes:map[string]*terraform.ResourceAttrDiff{"domain_name_servers.1":*terraform.ResourceAttrDiff{Old:"", New:"10.1.2.2", NewComputed:fa
lse, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:true, Sensitive:false, Type:0x0}, "domain_name_servers.2":*terraform.ResourceAttrDiff{Old:"", New:"10.1.101.2", NewComputed:false, NewRemoved:false, NewExtra:interface {
}(nil), RequiresNew:true, Sensitive:false, Type:0x0}, "tags.%":*terraform.ResourceAttrDiff{Old:"3", New:"3", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "domain_nam
e_servers.#":*terraform.ResourceAttrDiff{Old:"1", New:"4", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:true, Sensitive:false, Type:0x0}, "owner_id":*terraform.ResourceAttrDiff{Old:"320292863862", New
:"", NewComputed:true, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "domain_name_servers.0":*terraform.ResourceAttrDiff{Old:"AmazonProvidedDNS", New:"10.1.1.2", NewComputed:false, NewR
emoved:false, NewExtra:interface {}(nil), RequiresNew:true, Sensitive:false, Type:0x0}, "domain_name":*terraform.ResourceAttrDiff{Old:"ops.ieccloud.net.", New:"", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), Requ
iresNew:true, Sensitive:false, Type:0x0}, "tags.Environment":*terraform.ResourceAttrDiff{Old:"ops", New:"ops", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "domain_n
ame_servers.3":*terraform.ResourceAttrDiff{Old:"", New:"10.1.102.2", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:true, Sensitive:false, Type:0x0}, "tags.Terraform":*terraform.ResourceAttrDiff{Old:"tr
ue", New:"true", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "tags.Name":*terraform.ResourceAttrDiff{Old:"vpc-euw1-ops", New:"vpc-euw1-ops", NewComputed:false, NewR
emoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}}, Destroy:false, DestroyDeposed:false, DestroyTainted:false, Meta:map[string]interface {}(nil)}
    Diff Two (usually from apply): *terraform.InstanceDiff{mu:sync.Mutex{state:0, sema:0x0}, Attributes:map[string]*terraform.ResourceAttrDiff{"owner_id":*terraform.ResourceAttrDiff{Old:"", New:"", NewComputed:true, NewRemoved:false
, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "tags.Terraform":*terraform.ResourceAttrDiff{Old:"", New:"true", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensit
ive:false, Type:0x0}, "tags.Name":*terraform.ResourceAttrDiff{Old:"", New:"vpc-euw1-ops", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "tags.Environment":*terraform.
ResourceAttrDiff{Old:"", New:"ops", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "tags.%":*terraform.ResourceAttrDiff{Old:"", New:"3", NewComputed:false, NewRemoved:
false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "domain_name_servers.2":*terraform.ResourceAttrDiff{Old:"", New:"10.1.101.2", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), Require
sNew:true, Sensitive:false, Type:0x0}, "domain_name_servers.#":*terraform.ResourceAttrDiff{Old:"", New:"4", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:true, Sensitive:false, Type:0x0}, "domain_name_
servers.0":*terraform.ResourceAttrDiff{Old:"", New:"10.1.1.2", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:true, Sensitive:false, Type:0x0}, "domain_name_servers.1":*terraform.ResourceAttrDiff{Old:""
, New:"10.1.2.2", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:true, Sensitive:false, Type:0x0}, "domain_name_servers.3":*terraform.ResourceAttrDiff{Old:"", New:"10.1.102.2", NewComputed:false, NewRem
oved:false, NewExtra:interface {}(nil), RequiresNew:true, Sensitive:false, Type:0x0}}, Destroy:false, DestroyDeposed:false, DestroyTainted:false, Meta:map[string]interface {}(nil)}

Also include as much context as you can about your config, state, and the steps you performed to trigger this error.

Thx

**Comment by bryantbiggs** [comment]
hi @svaitsis - we currently do not support terraform v0.11.x and your output seems to indicate this is an issue with terraform and therefore not with the module. I'm going to close this out for now, but feel free to respond or open a new issue if necessary
