### ISSUE TITLE
ecr_api and ecr_dkr details not exposed as outputs

### ISSUE THREAD

**Issue by markmsmith** [terraform-aws-modules/terraform-aws-vpc#246]
There are currently options to create VPN Endpoints for the ECR API and the ECR Docker Registry, controlled by `enable_ecr_api_endpoint` and `enable_ecr_dkr_endpoint`. 
 
Unfortunately, [the PR that added these](https://github.com/terraform-aws-modules/terraform-aws-vpc/pull/213/files) forgot to add output entries for their details, like there are for the other VPN Endpoint options, so other modules can't reference them.

**Comment by antonbabenko** [comment]
Good catch! Fixed in [v1.61.0](https://github.com/terraform-aws-modules/terraform-aws-vpc/releases/v1.61.0).
