### ISSUE TITLE
enable_ecs_endpoint request

### ISSUE THREAD

**Issue by BrianMusson** [terraform-aws-modules/terraform-aws-vpc#254]
Hi, I would like to request an endpoint creation setting for ECS. It should be a boolean like:
enable_ssm_endpoint
enable_ec2_endpoint

Thanks!

**Comment by DrFaust92** [comment]
Pull Request: #261

**Comment by antonbabenko** [comment]
This feature is available in [v1.66.0](https://github.com/terraform-aws-modules/terraform-aws-vpc/releases/v1.66.0).
