### ISSUE TITLE
Feature Request: Specific Subnet tag of same type subnets

### ISSUE THREAD

**Issue by morihaya** [terraform-aws-modules/terraform-aws-vpc#259]
Hi there. Thank you for great module "terraform-aws-vpc" , It's helped me. so thanks.
I think, it's great if you can tag subnets more finely like below.

```
private_subnet_tags = {
  type = "map"

  subnet[0] = {
    "kubernetes.io/cluster/eks-dev"     = "share"
  }
  subnet[1] = {
    "kubernetes.io/cluster/eks-stg"     = "share"
  }
  subnet[3] = {
    "kubernetes.io/cluster/eks-prd"     = "share"
  }
}
```

**Comment by mwthink** [comment]
+1 This is crucial for running multiple EKS clusters in the same VPC provisioned by this module, less diffs always be found or implementing some other "creative" solutions.

**Comment by mwthink** [comment]
Alternatively, the module could accept `eks_subnets` and a matching list of `eks_cluster_names` to achieve the same result. 

For anyone unfamiliar with EKS, there are some simple tags that must be applied to subnets for it to work properly (see them [here](https://docs.aws.amazon.com/eks/latest/userguide/network_reqs.html)). EKS itself will add these tags itself when provisioning (At least to the private subnets it's provided), but this causes terraform to detect diffs (And delete the tags) every single time.

**Comment by antonbabenko** [comment]
@morihaya Thanks for this idea and info regarding EKS expectations (@mwthink). I think this should be rather possible to achieve using Terraform 0.12.

If anyone can write at least the initial pull-request it would be great.

I can't guarantee when I will have time to prioritize this feature myself because I am busy with all other upgrades of terraform-aws-modules to 0.12.

**Comment by skang0601** [comment]
I'll take a crack at this later this week. This is something I"m going to need for my use case.

**Comment by skang0601** [comment]
So I was thinking a little about this, would something simple as this suffice?
```resource "aws_subnet" "private" {
  count = var.create_vpc && length(var.private_subnets) > 0 ? length(var.private_subnets) : 0

  vpc_id            = local.vpc_id
  cidr_block        = var.private_subnets[count.index]
  availability_zone = element(var.azs, count.index)

  tags = merge(
    {
      "Name" = format(
        "%s-${var.private_subnet_suffix}-%s",
        var.name,
        element(var.azs, count.index),
      )
    },
    var.tags,
    lookup(var.private_subnet_tags, "global", {}),
    lookup(var.private_subnet_tags, count.index, {}),
  )
}```

Unfortunately this would be a breaking change but I'm currently at a loss on how to implement this otherwise.

**Comment by ozbillwang** [comment]
@morihaya 

Your case is very special and not best practices.

For example, how should you allow production to run in one subnet only?

I dont' recommend any PRs for this type of use case.

**Comment by fams** [comment]
> @morihaya
> 
> Your case is very special and not best practices.
> 
> For example, how should you allow production to run in one subnet only?
> 
> I dont' recommend any PRs for this type of use case.

Well, eks use case is not very special. is a common one. 
We are dealing with this here. Is there any other way to do this?
Maybe an optional lifecycle ignore.tags ?

**Comment by ozbillwang** [comment]
@fams 

I managed EKS as well, there will be better solution for this requirement.

**Comment by xposix** [comment]
Yeah, I agree with @ozbillwang, that subnet distribution is not great.
On a separate note, I'm having the same issue where the VPC is deployed by another department and every time they deploy any change in subnets, their deployment deletes the EKS tags and breaks everything. 

I'm not able to add lifecycle unfortunately.

**Comment by bryantbiggs** [comment]
> I'm not able to use lifecycle because this module doesn't support it.

@xposix - modules don't support lifecycle behaviors outside of what is defined within the module

**Comment by xposix** [comment]
I ended up using triggers against a timestamp to ensure it always run and executing the AWS CLI command to set the tags :( 
```
resource "null_resource" "subnet_tags" {
  triggers = {
    cluster_id     = module.eks-cluster.cluster_id
    public_subnets = join(" ", data.terraform_remote_state.networking.outputs.public_subnets.*)
    timestamp      = timestamp()
  }
  count = length(data.terraform_remote_state.networking.outputs.public_subnets)
  provisioner "local-exec" {
    command = "aws ec2 create-tags --resources ${self.triggers.public_subnets} --tags Key=kubernetes.io/cluster/${self.triggers.cluster_id},Value='shared'"
  }

  provisioner "local-exec" {
    when = destroy
    command = "aws ec2 delete-tags --resources ${self.triggers.public_subnets} --tags Key=kubernetes.io/cluster/${self.triggers.cluster_id},Value='shared'"
  }
}
```

**Comment by raelga** [comment]
@xposix check https://www.terraform.io/docs/providers/aws/index.html#ignore_tag_prefixes.

> ignore_tag_prefixes - (Optional) NOTE: This functionality is in public preview and there are no compatibility promises with future versions of the Terraform AWS Provider until a general availability announcement. List of resource tag key prefixes to ignore across all resources handled by this provider (see the Terraform multiple provider instances documentation for more information about additional provider configurations). This is designed for situations where external systems are managing certain resource tags. It prevents Terraform from returning any tag key matching the prefixes in any tags attributes and displaying any configuration difference for those tag values. If any resource configuration still has a tag matching one of the prefixes configured in the tags argument, it will display a perpetual difference until the tag is removed from the argument or ignore_changes is also used. This functionality is only supported in the following resources:

`ignore_tag_prefixes = ["kubernetes.io/cluster"]` in the `provider` does the trick.

**Comment by jtackaberry** [comment]
PSA for those wondering why things broke in v2.57 of the provider, this is the new syntax:

```
  ignore_tags {
    key_prefixes = ["kubernetes.io/cluster/"]
  } 
```

**Comment by maxbrunet** [comment]
Still relevant for [EKS CNI custom networking](https://docs.aws.amazon.com/eks/latest/userguide/cni-custom-network.html) and other mechanisms using tags for partitioning+discovery.
I will try to propose a PR without any breaking changes next week.

**Comment by bryantbiggs** [comment]
FYI - there is work underway to look at making this possible for users in the next version of the module. you can track it here [clowdhaus/terraform-aws-vpc-v4](https://github.com/clowdhaus/terraform-aws-vpc-v4) if interested
