### ISSUE TITLE
 Unknown token: 2:23 IDENT max

### ISSUE THREAD

**Issue by nodesocket** [terraform-aws-modules/terraform-aws-vpc#267]
When running `terraform init` I am getting:

```
Error downloading modules: Error loading modules: module vpc: Error parsing .terraform/modules/b7ccc849f6df97c277b2bf6e0054b489/terraform-aws-modules-terraform-aws-vpc-cf7a124/main.tf: At 2:23: Unknown token: 2:23 IDENT max
```

**Comment by cmeisinger** [comment]
That's a terraform .12 thing.  If you're using pre .12, you'll want to use a version of the VPC module that begins with 1.x, not 2.x.

**Comment by antonbabenko** [comment]
Make sure to include `version = "~> 1.66.0"` in your module block to pin the version of the module.

Master branch (default) is now Terraform 0.12 compatible.

After this, remove the content of `.terraform` folder.

**Comment by stephenmathieson** [comment]
Even with the version pinned, I'm still seeing this error:

```
$ terraform init
Initializing modules...
- module.db
  Found version 1.27.0 of terraform-aws-modules/rds/aws on registry.terraform.io
  Getting source "terraform-aws-modules/rds/aws"
- module.base_vpc
  Getting source "github.com/terraform-aws-modules/terraform-aws-vpc"
Error downloading modules: Error loading modules: module base_vpc: Error parsing .terraform/modules/fbc9842da926d9e51326d371c2f90cf0/main.tf: At 2:23: Unknown token: 2:23 IDENT max
```

Seems [this line](https://github.com/terraform-aws-modules/terraform-aws-vpc/blob/v1.66.0/main.tf#L6) is the culprit:

```tf
locals {
  max_subnet_length = max(
    length(var.private_subnets),
    length(var.elasticache_subnets),
    length(var.database_subnets),
    length(var.redshift_subnets),
  )
  # ...
}
```

**Comment by shelbyspees** [comment]
Posting here because I just came across this same error. Each time I ran `terraform init` using v0.10.6, it alternated between the `2:23 IDENT max` error message that's in the issue title and this error message:
```
Error downloading modules: Error loading modules: module vpc: invalid source string: terraform-aws-modules/vpc/aws
```

Turns out it was a syntax error? My colleague got a better description for the error message using v0.12:
```console
$ terraform-0.12.0 init
Initializing modules...
Downloading github.com/terraform-aws-modules/terraform-aws-vpc for vpc.vpc...
- vpc.vpc in .terraform/modules/vpc.vpc
There are some problems with the configuration, described below.
The Terraform configuration must be valid before initialization so that
Terraform can determine which modules and providers need to be installed.
Error: Invalid single-argument block definition
  on ../../modules/tx-vpc/main.tf line 50, in resource "aws_vpc_peering_connection" "qa-vpc-platform":
  50:   accepter      { allow_remote_vpc_dns_resolution = true,
Single-line block syntax can include only one argument definition. To define
multiple arguments, use the multi-line block syntax with one argument
definition per line.
Error: Invalid single-argument block definition
  on ../../modules/tx-vpc/main.tf line 53, in resource "aws_vpc_peering_connection" "qa-vpc-platform":
  53: 
  54: 
An argument definition on the same line as its containing block creates a
single-line block definition, which must also be closed on the same line.
Place the block's closing brace immediately after the argument definition.
```

Before he got a chance to act on it, I reformatted the block locally:
```diff
-  accepter      { allow_remote_vpc_dns_resolution = true,
-                  allow_classic_link_to_remote_vpc = true,
-                  allow_vpc_to_remote_classic_link = true }
-  requester     { allow_remote_vpc_dns_resolution = true
-                  allow_classic_link_to_remote_vpc = true,
-                  allow_vpc_to_remote_classic_link = true }
+  accepter {
+    allow_remote_vpc_dns_resolution = true,
+    allow_classic_link_to_remote_vpc = true,
+    allow_vpc_to_remote_classic_link = true
+  }
+  requester {
+    allow_remote_vpc_dns_resolution = true
+    allow_classic_link_to_remote_vpc = true,
+    allow_vpc_to_remote_classic_link = true
+  }
```

Then I was able to successfully run a `terraform init` using v0.10.6.

**Comment by FernandoMiguel** [comment]
Make sure you pin this module version to 2.x

You are probably downloading version 3.0.1 which is for terraform 0.12, and
your state file is too old for that

--
Fernando Miguel

**Comment by sun4ezzz** [comment]
Faced with the same issue and still can't resolve it.
```
 terraform --version
Terraform v0.11.10
```
Changed version for aws provider to 1.60, removed the .terraform directory and ran terraform init, but got the same error:
```
 terraform init
Initializing modules...
- module.vpc
Error downloading modules: Error loading modules: module vpc: Error parsing .terraform/modules/2b0dfe72e06da71d934d6da6693d5852/terraform-aws-modules-terraform-aws-vpc-e99089a/main.tf: At 2:23: Unknown token: 2:23 IDENT max
```
Kindly please advise on this.

**Comment by antonbabenko** [comment]
@shelbyspees This VPC module does not create `aws_vpc_peering_connection` resources, so it is a problem in another module (`modules/tx-vpc`).

**Comment by truptirr** [comment]
I am running Terraform v0.11.13 version, and i am getting the same error  **" Unknown token: 2:23 IDENT max"**

I clone https://github.com/terraform-aws-modules/terraform-aws-vpc.git on my local system and trying to run module source as below.

module "vpc" {
  source = "./../../terraform-modules/aws/vpc"
  name = "my-vpc"
  cidr = "10.0.0.0/16"
}

But it works fine when i change source to below.

module "vpc" {
  source = "terraform-aws-modules/vpc/aws"
  version = "1.66.0"
  name = "my-vpc"
  cidr = "10.0.0.0/16"
}

Is there anything missing in my setup?

**Comment by antonbabenko** [comment]
Yes, make sure that you are using the correct version of the module which you are referencing locally as "./../../terraform-modules/aws/vpc".

If you clone it, make sure to checkout the correct tag. For example: `git checkout v1.66.0`

`master` branch is not compatible with your version of Terraform 0.11.

**Comment by truptirr** [comment]
Thank you Antonbabenko. 
After performing checkout issue is fixed.

**Comment by nitinpatil1992** [comment]
There is issue with version of terraform utility and parsing the variable with older version!

```
✗ terraform --version
Terraform v0.11.13

Your version of Terraform is out of date! The latest version
is 0.12.5. You can update by downloading from www.terraform.io/downloads.html
```
and my `main.tf` looks like this
```
module "vpc" {
  source = "terraform-aws-modules/vpc/aws"
  ...
}
```

when I did `terraform init`,  latest version of `terraform-aws-modules/vpc/aws` got downloaded. 
I looked into the module under `.terraform` and found out the below snippet

```
locals {
  max_subnet_length = max(
    length(var.private_subnets),
    length(var.elasticache_subnets),
    length(var.database_subnets),
    length(var.redshift_subnets),
  )
  nat_gateway_count = var.single_nat_gateway ? 1 : var.one_nat_gateway_per_az ? length(var.azs) : local.max_subnet_length
```
But the terraform  0.12.5  looks variables like `"${max(...)"` This is why it is giving error like `Unknown token: 2:23 IDENT max `

I make some modifications as above and looked fine. 
But better approach that I followed to get older version of `terraform-aws-modules/vpc/aws:v1.50.0`

Here is code snippet for working module

```
module "vpc" {
  source = "terraform-aws-modules/vpc/aws"
  version = "~> v1.50.0"
  name = "${var.name}"
  cidr = "${var.cidr}"
  ...
```
 💥
```
✗ terraform init     
Initializing modules...
- module.vpc

Initializing the backend...

Initializing provider plugins...
- Checking for available provider plugins on https://releases.hashicorp.com...
- Downloading plugin for provider "aws" (1.60.0)...

Terraform has been successfully initialized!

You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.
````

**Comment by samsquire** [comment]
If you manage the path variable with bashrc, check you do not have a symlink of /usr/bin/terraform to an old terraform
