### ISSUE TITLE
Adding ec2 instances to subnets

### ISSUE THREAD

**Issue by horsey** [terraform-aws-modules/terraform-aws-vpc#27]
Hello, 
I've been experimenting with the vpc module to modularise my Terraform code in general. On creation of the VPC with a public and private subnets, I wish to launch instances in these subnets. 

The subnets variable itself is a Terraform list and does this mean I have to actually dereference individual elements of the subnets to actually launch instances using the `aws_instance' resource?

**Comment by antonbabenko** [comment]
Hi,

You need to use [element() interpolation function](https://www.terraform.io/docs/configuration/interpolation.html) to pick single subnet to provide to `aws_instance`, like this:

```
module "vpc" {
  # ... omitted
}

resource "aws_instance" "this" {
  subnet_id = "${element(module.vpc.public_subnets, 0)}"
  # ... omitted 
}
```
