### ISSUE TITLE
Terraform 0.12 + vpc module v2.2

### ISSUE THREAD

**Issue by marcincuber** [terraform-aws-modules/terraform-aws-vpc#271]
I am trying to upgrade my terraform but I am stuck at the following;
```
resource "aws_eks_cluster" "cluster" {
  enabled_cluster_log_types = ["api", "audit", "authenticator", "controllerManager", "scheduler"]
  name                      = "${var.cluster_name}-${var.environment}"
  role_arn                  = aws_iam_role.cluster.arn
  version                   = var.eks_version

  vpc_config {
    subnet_ids              = [module.vpc.public_subnets, module.vpc.private_subnets]
    security_group_ids      = [aws_security_group.cluster.id]
    endpoint_private_access = "true"
    endpoint_public_access  = "true"
  }
}
```

I am getting the error `Inappropriate value for attribute "subnet_ids": element 0: string required.` 

Could someone advise what is the current way of referencing all subnets and passing them into subnet_ids variable? 

Thanks

**Comment by marcincuber** [comment]
Found the solution to be ```subnet_ids = flatten([module.vpc.public_subnets, module.vpc.private_subnets])```.

**Comment by antonbabenko** [comment]
It can be also like this - `subnet_ids = concat(module.vpc.public_subnets, module.vpc.private_subnets)`

**Comment by sonianara** [comment]
I'm getting the same error doing something like this: 
```
subnet_ids = ["${aws_subnet.priv_subnet.*.id}"]
```
Anyone have any idea how to resolve this?

**Comment by antonbabenko** [comment]
@sonianara You can always unwrap value between `[` and `]` to make it like this:
```terraform
subnet_ids = "${aws_subnet.priv_subnet.*.id}"
```

**Comment by ammartaj53** [comment]
@antonbabenko it worked like a charm

**Comment by ozgiat** [comment]
@antonbabenko You saved me hours...
Can you explain whats the difference with [] and without ?

**Comment by antonbabenko** [comment]
`[]` - this adds a wrapping type list, so the type of the produced variable becomes `list of lists`.

**Comment by JPalmerGithub** [comment]
--- antonbabenko commented Nov 8, 2019
--- [] - this adds a wrapping type list, so the type of the produced variable becomes list of lists.
One big Thank You from here too, Sir

**Comment by AdeOpe** [comment]
OMG! i cannot say thank you enough for this page!

**Comment by demisx** [comment]
Should the docs be updated? I was running into the same error trying to create a NLB: https://www.terraform.io/docs/providers/aws/r/lb.html

**Comment by AkinJimoh** [comment]
Any idea how you would retrieve subnet IDs using **for_each** as opposed to **count**? 

```
resource "aws_instance" "k8s" {
for_each = var.profiles
ami = data.aws_ami.latest-ubuntu.id
instance_type = "t2.medium"
iam_instance_profile = "${each.value}"
subnet_id = ??????????????
vpc_security_group_ids = [var.security_group]
key_name = var.keyname
```

And this is because I'm creating similar instances but need to assign them different instance profiles.

Ideally, I'd have done something like

subnet_id = element(var.subnets, count.index )

to place the instances in different subnets but I don't think count and for_each can be used in the same block definition.

I have to subnets and 4 instances and would like to loop through the subnets, placing each instance in one.

**Comment by sikemullivan** [comment]
I needed a combination of the answers above. 

`subnet_ids  = concat("${aws_subnet.private.*.id}", "${aws_subnet.public.*.id}")`

**Comment by vaibhavjpr** [comment]
> I'm getting the same error doing something like this:
> 
> ```
> subnet_ids = ["${aws_subnet.priv_subnet.*.id}"]
> ```
> 
> Anyone have any idea how to resolve this?

I tried like this.

resource "aws_db_subnet_group" "dbsubnet" {
  name       = "testcluster"
  **subnet_ids = flatten(["${aws_subnet.private.*.id}"])   -- this one**
  tags = {
    Name = "My DB subnet group"
  }
}

**Comment by antonbabenko** [comment]
Try this syntax: `subnet_ids = aws_subnet.priv_subnet.*.id`

**Comment by alxsbn** [comment]
Error still prevalent in v0.14.5 with aws_vpc_endpoint

**Comment by andrewrotherham** [comment]
Removing the brackets has done the trick, but I'm still wondering why one is a list here but the other is a string. Shouldn't they both be stings? This code does work...but why does V need the square brackets but subnet_ids doesn't?
vpc_config {
    security_group_ids = ["${aws_security_group.demo-cluster.id}"]
    subnet_ids         = "${aws_subnet.demo.*.id}"

**Comment by Jonas-Noh** [comment]
i really want to found this problem, thank a lot.

**Comment by pete198016** [comment]
Hello,

#terraform provider 3.55.0

resource "aws_vpc_endpoint" "example" {
  service_name      = aws_vpc_endpoint_service.example.service_name
  #subnet_ids        = [module.vpc.natgwsub_subnets.*.id]
  subnet_ids        = module.vpc.natgwsub_subnets
  vpc_endpoint_type = aws_vpc_endpoint_service.example.service_type
  vpc_id            = module.vpc.vpc_id
}


With subnet_ids i need to choose one subnet only - gateway load balancer requirement.
Tried many ways and i can't choose just one.

Example error:

Error: Incorrect attribute value type
on hub-eu/asg.hub-eu.tf line 117, in resource "aws_vpc_endpoint" "example":
  subnet_ids        = module.vpc.natgwsub_subnets[0]
Inappropriate value for attribute "subnet_ids": set of string required.

module.vpc.natgwsub_subnets[0] ##that part is using vpc module on github
Anyone can help ?

**Comment by mkatajah** [comment]
> Hello,
> 
> #terraform provider 3.55.0
> 
> resource "aws_vpc_endpoint" "example" {
> service_name = aws_vpc_endpoint_service.example.service_name
> #subnet_ids = [module.vpc.natgwsub_subnets.*.id]
> subnet_ids = module.vpc.natgwsub_subnets
> vpc_endpoint_type = aws_vpc_endpoint_service.example.service_type
> vpc_id = module.vpc.vpc_id
> }
> 
> With subnet_ids i need to choose one subnet only - gateway load balancer requirement.
> Tried many ways and i can't choose just one.
> 
> Example error:
> 
> Error: Incorrect attribute value type
> on hub-eu/asg.hub-eu.tf line 117, in resource "aws_vpc_endpoint" "example":
> subnet_ids = module.vpc.natgwsub_subnets[0]
> Inappropriate value for attribute "subnet_ids": set of string required.
> 
> Anyone can help ?

I encountered similar issue. You can try this:  subnet_ids = toset([element(module.vpc.natgwsub_subnets.*.id,0)])
