### ISSUE TITLE
Ability to name resources

### ISSUE THREAD

**Issue by horsey** [terraform-aws-modules/terraform-aws-vpc#28]
Hello, 
I think it would be very useful if resource names are exposed as variables so that resource names can be appropriately set when the resources are created.
I understand that we can set tags to filter resources, but naming resources appropriately is a nice to have feature.

**Comment by antonbabenko** [comment]
What kind of resources you'd like to give names to? Most of the resources in this module support tags but don't have a concept of a name.

**Comment by horsey** [comment]
`aws_subnet` for example gets default name like "Private Subnet", "Public Subnet" etc. When there are too many subnets with the same names, it can get confusing on the AWS console.

**Comment by antonbabenko** [comment]
Tag "Name" for subnets looks like this - `your-vpc-name-public-eu-west-1b`, which is pretty descriptive and visible if you enable to show Name tag in AWS console.
