### ISSUE TITLE
suffix for other resources  than subnets

### ISSUE THREAD

**Issue by smalchow** [terraform-aws-modules/terraform-aws-vpc#284]
Dears,

we were wondering why sometimes there are "suffixes" we can use for tags and sometimes not, wouldn't it be consistent to use this everywhere. As far as we can see it is only in subnets.

For example we have this in subnets

<-- snip -->
resource "aws_subnet" "public" {
  count = var.create_vpc && length(var.public_subnets) > 0 && (false == var.one_nat_gateway_per_az || length(var.public_subnets) >= length(var.azs)) ? length(var.public_subnets) : 0

  vpc_id                  = local.vpc_id
  cidr_block              = element(concat(var.public_subnets, [""]), count.index)
  availability_zone       = element(var.azs, count.index)
  map_public_ip_on_launch = var.map_public_ip_on_launch

  tags = merge(
    {
      "Name" = format(
        "%s-${var.public_subnet_suffix}-%s",
        var.name,
        element(var.azs, count.index),
      )
    },
    var.tags,
    var.public_subnet_tags,
  )
}
<-- snip --> 

but this for aws_eip

<-- snip -->

resource "aws_eip" "nat" {
  count = var.create_vpc && var.enable_nat_gateway && false == var.reuse_nat_ips ? local.nat_gateway_count : 0

  vpc = true

  tags = merge(
    {
      "Name" = format(
        "%s-%s",
        var.name,
        element(var.azs, var.single_nat_gateway ? 0 : count.index),
      )
    },
    var.tags,
    var.nat_eip_tags,
  )
}

<-- snip --> 

However, the tag should probably also include the "AZ", at least if there are multiple nat gateways (and EIPS) and then the suffix makes sense as well.

This would be an easy way to not have to override the complete name

Cheers
Soeren

**Comment by antonbabenko** [comment]
Hi Soeren,

Thanks for opening this issue.

There always has to be a valid use-case (a pain, a blocker, life-saver) for what we have in this module.

Is this a blocker or just "cool" feature to have? I don't think this is a blocker, so I am going to close this issue.

I'd rather focus us on harder tasks - IPv6 (hi @StephenKing), Transit Gateway, individual names for subnets...

**Comment by smalchow** [comment]
Hi Anton

i disagree, this is not only "cool", currently the "name" tag produces always that same name for several different resources, or alternatively if we overwrite the tag, then we (potentially) loose the availability zone in the name (which is not implemented everywhere as far as i can see).

The question would be, if we do the changes ourselves, would you accept them ?

Meaning we would implement the "suffix" strategy for all resources to get this optional name tag part ?

Cheers
Soeren

**Comment by antonbabenko** [comment]
@smalchow Yes, such PR will be accepted.
