### ISSUE TITLE
Create new subnet forces new resource on existing ec2 instance

### ISSUE THREAD

**Issue by runtman** [terraform-aws-modules/terraform-aws-vpc#289]
Hello, so we are using this module for some time now and want to create 2 more private subnets.

It would seem when we try to run a plan if wishes to destroy the ec2 instances and rebuild them despite the subnet_id being used is the same, for example here is part of the plan:

```
subnet_id:                                 "subnet-c37ac88b" => "${element(module.vpc.private_subnets, 0)}" (forces new resource)
```

But when I look at the subnet itself, in the console it's returning the same value:

```
└─ $ ▶ terraform console
> element(module.vpc.private_subnets,0)
subnet-c37ac88b

```

I do notice later in the plan route tables for these subnets are re-created, in the past this has not caused instances to rebuild though. 

I can get around it by using ignore_changes, but i'd like to get to the bottom of why this is happening.

Edit: some more code for debug purposes:

```
variable "private_subnet_cidr_block" {
  description = "App Subnet block"
  default = ["10.28.0.64/27", "10.28.0.96/27", "10.28.4.0/22", "10.28.8.0/22"]
}
```

10.28.4, 10.28.8 are the new subnets being created.

**Comment by dpiddockcmp** [comment]
This is a long standing "feature" of TF 0.11 where a list with an unknown element causes all items in the list to act unknown. Changelog claims this has finally been fixed in 0.12.0.

You should be able to work around the issue by doing targetted resource updates: `terraform apply -target=module.vpc.private_subnets.2`

**Comment by runtman** [comment]
Interesting, so yes this one VPC was built pre 0.12 and the ones it hasn't happened on was post 0.12.

Can you do target deployment in a `plan`?

**Comment by dpiddockcmp** [comment]
`plan` also supports the `-target=` option

**Comment by runtman** [comment]
Just so I am clear, you recommend running the subnet creation separately then running the entire plan from then should be ok?

**Comment by dpiddockcmp** [comment]
If you create your new subnets using `-target=` then terraform shouldn't want to recreate the ec2 instance on the next `plan`.

I guess `ignore_changes` is another option that involves code changes.

**Comment by runtman** [comment]
I appreciate your responses, thanks :)
