### ISSUE TITLE
assume role

### ISSUE THREAD

**Issue by ayotec2015** [terraform-aws-modules/terraform-aws-vpc#290]
HI 

Thanks for your previous assistance. 

I have been able to setup the EKS environment. Only issue I have left is I am not able to assume role of the cluster. 

I am guessing thats what this error message means 

You must be logged in to the server (the server has asked for the client to provide credentials)

**Comment by antonbabenko** [comment]
Unfortunately, I can't help with this.

Please ask general questions on forums like stackoverflow or https://discuss.hashicorp.com .
