### ISSUE TITLE
Add tags to VPC endpoints

### ISSUE THREAD

**Issue by nunofernandes** [terraform-aws-modules/terraform-aws-vpc#291]
Now that the terraform aws module [supports](https://github.com/terraform-providers/terraform-provider-aws/pull/8674) tags in the vpc endpoint, this module should use that to add tags in those resources.

**Comment by antonbabenko** [comment]
This has been implemented in [v2.12.0](https://github.com/terraform-aws-modules/terraform-aws-vpc/releases/v2.12.0) which has been just released.
