### ISSUE TITLE
vpn Access

### ISSUE THREAD

**Issue by ayotec2015** [terraform-aws-modules/terraform-aws-vpc#294]
HI, 

I have been using your environment for a while now and it all seems fine. I am working what if I wanted to add a client VPN to this so I can access the environment on my laptop over VPN. 

I don't want to use Site to Site. I would rather the client connection. Please can you advise on how best to go about this ? 

Thanks

**Comment by antonbabenko** [comment]
Hi,

Unfortunately, I don't have enough experience building VPNs and can't really help.

Please ask this question on stackoverflow or https://discuss.hashicorp.com
