### ISSUE TITLE
Network Interfaces were not getting deleted

### ISSUE THREAD

**Issue by SubhakarKotta** [terraform-aws-modules/terraform-aws-vpc#296]
Terraform Version:
0.12.2

Please find the attached debug log

"module.cluster.aws_security_group.workers[0] (destroy)" not able destroy and is waiting on some resource (Network Interface) and not able to find the reason why that Network Interface was not getting deleted.

Debug Log Path:
[https://drive.google.com/open?id=1JTQvWtYmeTP25A8LDF5EbGfEsAi4LPcs
](https://drive.google.com/open?id=1JTQvWtYmeTP25A8LDF5EbGfEsAi4LPcs
)

module.cluster.null_resource.tags_as_list_of_maps[0]: Refreshing state... [id=477747191525697648]
module.pega.module.files.null_resource.start: Refreshing state... [id=477747191525697648]
module.db.module.db_instance.data.aws_iam_policy_document.enhanced_monitoring: Refreshing state...
module.cluster.data.aws_ami.eks_worker: Refreshing state...
module.cluster.data.aws_iam_policy_document.cluster_assume_role_policy: Refreshing state...
module.vpc.aws_vpc.this[0]: Refreshing state... [id=vpc-0e69a5ec18d180e16]
module.db.module.db_parameter_group.aws_db_parameter_group.this[0]: Refreshing state... [id=cert-demo-cluster-20190627114759123900000001]
module.certificates.data.aws_route53_zone.wildcard_zone: Refreshing state...
module.cluster.data.aws_iam_policy_document.workers_assume_role_policy: Refreshing state...
module.cluster.data.aws_region.current: Refreshing state...
module.cluster.data.aws_caller_identity.current: Refreshing state...
module.cluster.aws_iam_role.cluster[0]: Refreshing state... [id=cert-demo-cluster20190627114759128300000002]
module.cluster.aws_iam_role_policy_attachment.cluster_AmazonEKSServicePolicy[0]: Refreshing state... [id=cert-demo-cluster20190627114759128300000002-20190627114802505600000003]
module.cluster.aws_iam_role_policy_attachment.cluster_AmazonEKSClusterPolicy[0]: Refreshing state... [id=cert-demo-cluster20190627114759128300000002-20190627114802554900000004]
module.cluster.aws_security_group.cluster[0]: Refreshing state... [id=sg-0a7a166da401afb13]
aws_security_group.sec_grp_rds: Refreshing state... [id=sg-0f7d6df1512675911]
module.vpc.aws_internet_gateway.this[0]: Refreshing state... [id=igw-0f179056bbfd5c899]
module.vpc.aws_route_table.public[0]: Refreshing state... [id=rtb-014c4d2d5decee860]
module.vpc.aws_subnet.public[0]: Refreshing state... [id=subnet-06abaf144f74dcc23]
module.vpc.aws_subnet.public[1]: Refreshing state... [id=subnet-0c6c2e5975b7d6c90]
module.vpc.aws_route_table_association.public[0]: Refreshing state... [id=rtbassoc-0b51188d33593f2fe]
module.vpc.aws_route_table_association.public[1]: Refreshing state... [id=rtbassoc-07a54055da7d6710b]
module.db.module.db_subnet_group.aws_db_subnet_group.this[0]: Refreshing state... [id=cert-demo-cluster-20190627114825359400000007]
module.vpc.aws_route.public_internet_gateway[0]: Refreshing state... [id=r-rtb-014c4d2d5decee8601080289494]
module.cluster.aws_security_group_rule.cluster_egress_internet[0]: Refreshing state... [id=sgrule-2867915294]
module.cluster.aws_eks_cluster.this: Refreshing state... [id=cert-demo-cluster]
module.cluster.data.template_file.kubeconfig: Refreshing state...
module.cluster.data.aws_iam_policy_document.worker_autoscaling: Refreshing state...
module.cluster.aws_iam_role.workers[0]: Refreshing state... [id=cert-demo-cluster20190627115759610300000009]
module.cluster.aws_security_group.workers[0]: Refreshing state... [id=sg-02a43e2af835ac480]
module.cluster.local_file.kubeconfig[0]: Refreshing state... [id=b977d37414673540b8d042b8e601af64eeca2539]
module.cluster.aws_iam_policy.worker_autoscaling[0]: Refreshing state... [id=arn:aws:iam::045654838477:policy/eks-worker-autoscaling-cert-demo-cluster2019062711575961670000000a]
module.certificates.aws_acm_certificate.wildcard_cert: Refreshing state... [id=arn:aws:acm:us-west-2:045654838477:certificate/e6feeed7-5b26-46e5-b4d8-1478cb684687]
module.db.module.db_instance.aws_db_instance.this[0]: Refreshing state... [id=cert-demo-cluster]
module.cluster.data.template_file.userdata[0]: Refreshing state...
module.cluster.aws_iam_role_policy_attachment.workers_AmazonEC2ContainerRegistryReadOnly[0]: Refreshing state... [id=cert-demo-cluster20190627115759610300000009-2019062711580300510000000e]
module.cluster.aws_iam_role_policy_attachment.workers_AmazonEKSWorkerNodePolicy[0]: Refreshing state... [id=cert-demo-cluster20190627115759610300000009-2019062711580291530000000d]
module.cluster.aws_iam_instance_profile.workers[0]: Refreshing state... [id=cert-demo-cluster2019062711580195000000000b]
module.cluster.aws_iam_role_policy_attachment.workers_AmazonEKS_CNI_Policy[0]: Refreshing state... [id=cert-demo-cluster20190627115759610300000009-2019062711580291100000000c]
module.cluster.aws_security_group_rule.workers_ingress_cluster_https[0]: Refreshing state... [id=sgrule-3541975220]
module.cluster.aws_security_group_rule.cluster_https_worker_ingress[0]: Refreshing state... [id=sgrule-1431011586]
module.cluster.aws_security_group_rule.workers_ingress_self[0]: Refreshing state... [id=sgrule-2433296678]
module.cluster.aws_security_group_rule.workers_egress_internet[0]: Refreshing state... [id=sgrule-1388892896]
module.cluster.aws_security_group_rule.workers_ingress_cluster[0]: Refreshing state... [id=sgrule-1222101361]
aws_security_group_rule.allow-workers-nodes-communications: Refreshing state... [id=sgrule-2931962113]
module.cluster.data.template_file.worker_role_arns[0]: Refreshing state...
module.cluster.aws_launch_configuration.workers[0]: Refreshing state... [id=cert-demo-cluster-020190627115812194200000010]
module.cluster.aws_iam_role_policy_attachment.workers_autoscaling[0]: Refreshing state... [id=cert-demo-cluster20190627115759610300000009-2019062711580393650000000f]
module.cluster.data.template_file.config_map_aws_auth: Refreshing state...
module.cluster.local_file.config_map_aws_auth[0]: Refreshing state... [id=d54562e35fada472c594e8926eb56cd2d3000b64]
module.cluster.null_resource.update_config_map_aws_auth[0]: Refreshing state... [id=48416910012784529]
module.certificates.aws_route53_record.wildcard_cert_validation: Refreshing state... [id=ZCQV0SSFIMZ43__cfe8f8374031a620887eec02c07ed8aa.cert-demo-cluster-web.dev.pega.io._CNAME]
module.cluster.aws_autoscaling_group.workers[0]: Refreshing state... [id=cert-demo-cluster-020190627115816484000000011]
module.certificates.aws_acm_certificate_validation.wildcard_cert: Refreshing state... [id=2019-06-27 12:00:16 +0000 UTC]
kubernetes_service_account.super-user: Refreshing state... [id=kube-system/super-user]
kubernetes_cluster_role_binding.super-user: Refreshing state... [id=super-user]
module.pega.null_resource.wait: Refreshing state... [id=8108712238980971434]
module.pega.kubernetes_service_account.tiller: Refreshing state... [id=kube-system/tiller]
module.pega.kubernetes_cluster_role_binding.tiller: Refreshing state... [id=tiller]
module.pega.data.helm_repository.incubator: Refreshing state...
module.pega.data.helm_repository.stable: Refreshing state...
module.pega.data.helm_repository.pega: Refreshing state...
module.pega.helm_release.dashboard[0]: Refreshing state... [id=dashboard]
module.pega.helm_release.aws-alb-ingress-controller[0]: Refreshing state... [id=aws-alb-ingress-controller]
module.pega.helm_release.pega: Refreshing state... [id=pega]
module.pega.null_resource.delete_ingress: Refreshing state... [id=7972380693630059657]
module.pega.local_file.alb_ingress_hostname: Refreshing state... [id=58b2f7fc2960a438ddbc041a7f93621c43ba7459]
module.pega.module.files.null_resource.shell: Refreshing state... [id=48416910012784529]
module.pega.module.files.null_resource.contents: Refreshing state... [id=8108712238980971434]
module.certificates.aws_route53_record.route: Refreshing state... [id=ZCQV0SSFIMZ43_cert-demo-cluster-web.dev.pega.io_A]
module.certificates.aws_route53_record.route: Destroying... [id=ZCQV0SSFIMZ43_cert-demo-cluster-web.dev.pega.io_A]
module.certificates.aws_acm_certificate_validation.wildcard_cert: Destroying... [id=2019-06-27 12:00:16 +0000 UTC]
module.pega.null_resource.delete_ingress: Destroying... [id=7972380693630059657]
aws_security_group_rule.allow-workers-nodes-communications: Destroying... [id=sgrule-2931962113]
module.pega.null_resource.delete_ingress: Provisioning with 'local-exec'...
module.pega.null_resource.delete_ingress (local-exec): Executing: ["/bin/sh" "-c" "      kubectl delete ingress pega-web -n pega --kubeconfig=./kubeconfig_cert-demo-cluster \\\n      && kubectl delete ingress pega-stream -n pega --kubeconfig=./kubeconfig_cert-demo-cluster \\\n      && sleep 60\n"]
module.certificates.aws_acm_certificate_validation.wildcard_cert: Destruction complete after 0s
module.certificates.aws_route53_record.wildcard_cert_validation: Destroying... [id=ZCQV0SSFIMZ43__cfe8f8374031a620887eec02c07ed8aa.cert-demo-cluster-web.dev.pega.io._CNAME]
module.pega.helm_release.dashboard[0]: Destroying... [id=dashboard]
aws_security_group_rule.allow-workers-nodes-communications: Destruction complete after 2s
module.pega.null_resource.delete_ingress (local-exec): ingress.extensions "pega-web" deleted
module.pega.null_resource.delete_ingress (local-exec): ingress.extensions "pega-stream" deleted
module.pega.helm_release.dashboard[0]: Destruction complete after 4s
module.certificates.aws_route53_record.route: Still destroying... [id=ZCQV0SSFIMZ43_cert-demo-cluster-web.dev.pega.io_A, 10s elapsed]
module.pega.null_resource.delete_ingress: Still destroying... [id=7972380693630059657, 10s elapsed]
module.certificates.aws_route53_record.wildcard_cert_validation: Still destroying... [id=ZCQV0SSFIMZ43__cfe8f8374031a620887eec02...rt-demo-cluster-web.dev.pega.io._CNAME, 10s elapsed]
module.certificates.aws_route53_record.route: Still destroying... [id=ZCQV0SSFIMZ43_cert-demo-cluster-web.dev.pega.io_A, 20s elapsed]
module.pega.null_resource.delete_ingress: Still destroying... [id=7972380693630059657, 20s elapsed]
module.certificates.aws_route53_record.wildcard_cert_validation: Still destroying... [id=ZCQV0SSFIMZ43__cfe8f8374031a620887eec02...rt-demo-cluster-web.dev.pega.io._CNAME, 20s elapsed]
module.certificates.aws_route53_record.route: Still destroying... [id=ZCQV0SSFIMZ43_cert-demo-cluster-web.dev.pega.io_A, 30s elapsed]
module.pega.null_resource.delete_ingress: Still destroying... [id=7972380693630059657, 30s elapsed]
module.certificates.aws_route53_record.wildcard_cert_validation: Still destroying... [id=ZCQV0SSFIMZ43__cfe8f8374031a620887eec02...rt-demo-cluster-web.dev.pega.io._CNAME, 30s elapsed]
module.certificates.aws_route53_record.route: Still destroying... [id=ZCQV0SSFIMZ43_cert-demo-cluster-web.dev.pega.io_A, 40s elapsed]
module.pega.null_resource.delete_ingress: Still destroying... [id=7972380693630059657, 40s elapsed]
module.certificates.aws_route53_record.wildcard_cert_validation: Still destroying... [id=ZCQV0SSFIMZ43__cfe8f8374031a620887eec02...rt-demo-cluster-web.dev.pega.io._CNAME, 40s elapsed]
module.certificates.aws_route53_record.wildcard_cert_validation: Destruction complete after 40s
module.certificates.aws_acm_certificate.wildcard_cert: Destroying... [id=arn:aws:acm:us-west-2:045654838477:certificate/e6feeed7-5b26-46e5-b4d8-1478cb684687]
module.certificates.aws_route53_record.route: Destruction complete after 41s
module.pega.module.files.null_resource.contents: Destroying... [id=8108712238980971434]
module.pega.module.files.null_resource.contents: Destruction complete after 0s
module.pega.module.files.null_resource.shell: Destroying... [id=48416910012784529]
module.pega.module.files.null_resource.shell: Provisioning with 'local-exec'...
module.pega.module.files.null_resource.shell (local-exec): Executing: ["/bin/sh" "-c" ":"]
module.pega.module.files.null_resource.shell: Provisioning with 'local-exec'...
module.pega.module.files.null_resource.shell (local-exec): Executing: ["/bin/sh" "-c" "rm \".terraform/modules/pega.files/matti-terraform-shell-resource-a39ec5f/stdout.477747191525697648\""]
module.pega.module.files.null_resource.shell (local-exec): rm: can't remove '.terraform/modules/pega.files/matti-terraform-shell-resource-a39ec5f/stdout.477747191525697648': No such file or directory

module.pega.module.files.null_resource.shell: Provisioning with 'local-exec'...
module.pega.module.files.null_resource.shell (local-exec): Executing: ["/bin/sh" "-c" "rm \".terraform/modules/pega.files/matti-terraform-shell-resource-a39ec5f/stderr.477747191525697648\""]
module.pega.module.files.null_resource.shell (local-exec): rm: can't remove '.terraform/modules/pega.files/matti-terraform-shell-resource-a39ec5f/stderr.477747191525697648': No such file or directory

module.pega.module.files.null_resource.shell: Provisioning with 'local-exec'...
module.pega.module.files.null_resource.shell (local-exec): Executing: ["/bin/sh" "-c" "rm \".terraform/modules/pega.files/matti-terraform-shell-resource-a39ec5f/exitstatus.477747191525697648\""]
module.pega.module.files.null_resource.shell (local-exec): rm: can't remove '.terraform/modules/pega.files/matti-terraform-shell-resource-a39ec5f/exitstatus.477747191525697648': No such file or directory

module.pega.module.files.null_resource.shell: Destruction complete after 0s
module.pega.module.files.null_resource.start: Destroying... [id=477747191525697648]
module.pega.module.files.null_resource.start: Destruction complete after 0s
module.certificates.aws_acm_certificate.wildcard_cert: Destruction complete after 2s
module.pega.null_resource.delete_ingress: Still destroying... [id=7972380693630059657, 50s elapsed]
module.pega.null_resource.delete_ingress: Still destroying... [id=7972380693630059657, 1m0s elapsed]
module.pega.null_resource.delete_ingress: Destruction complete after 1m5s
module.pega.helm_release.pega: Destroying... [id=pega]
module.pega.helm_release.pega: Destruction complete after 3s
module.pega.helm_release.aws-alb-ingress-controller[0]: Destroying... [id=aws-alb-ingress-controller]
module.pega.helm_release.aws-alb-ingress-controller[0]: Destruction complete after 1s
module.pega.kubernetes_cluster_role_binding.tiller: Destroying... [id=tiller]
module.pega.kubernetes_cluster_role_binding.tiller: Destruction complete after 2s
module.pega.kubernetes_service_account.tiller: Destroying... [id=kube-system/tiller]
module.pega.kubernetes_service_account.tiller: Destruction complete after 0s
module.pega.null_resource.wait: Destroying... [id=8108712238980971434]
module.pega.null_resource.wait: Destruction complete after 0s
kubernetes_cluster_role_binding.super-user: Destroying... [id=super-user]
kubernetes_cluster_role_binding.super-user: Destruction complete after 0s
kubernetes_service_account.super-user: Destroying... [id=kube-system/super-user]
kubernetes_service_account.super-user: Destruction complete after 1s
module.cluster.null_resource.update_config_map_aws_auth[0]: Destroying... [id=48416910012784529]
module.vpc.aws_route.public_internet_gateway[0]: Destroying... [id=r-rtb-014c4d2d5decee8601080289494]
module.cluster.aws_security_group_rule.workers_egress_internet[0]: Destroying... [id=sgrule-1388892896]
module.cluster.null_resource.update_config_map_aws_auth[0]: Destruction complete after 0s
module.vpc.aws_route_table_association.public[1]: Destroying... [id=rtbassoc-07a54055da7d6710b]
module.cluster.aws_security_group_rule.cluster_egress_internet[0]: Destroying... [id=sgrule-2867915294]
module.vpc.aws_route_table_association.public[0]: Destroying... [id=rtbassoc-0b51188d33593f2fe]
module.cluster.aws_security_group_rule.cluster_https_worker_ingress[0]: Destroying... [id=sgrule-1431011586]
module.cluster.aws_iam_role_policy_attachment.workers_AmazonEKS_CNI_Policy[0]: Destroying... [id=cert-demo-cluster20190627115759610300000009-2019062711580291100000000c]
module.cluster.aws_security_group_rule.workers_ingress_cluster[0]: Destroying... [id=sgrule-1222101361]
module.cluster.aws_security_group_rule.workers_ingress_self[0]: Destroying... [id=sgrule-2433296678]
module.db.module.db_instance.aws_db_instance.this[0]: Destroying... [id=cert-demo-cluster]
module.cluster.aws_iam_role_policy_attachment.workers_AmazonEKS_CNI_Policy[0]: Destruction complete after 1s
module.cluster.aws_iam_role_policy_attachment.workers_AmazonEKSWorkerNodePolicy[0]: Destroying... [id=cert-demo-cluster20190627115759610300000009-2019062711580291530000000d]
module.vpc.aws_route_table_association.public[1]: Destruction complete after 1s
module.cluster.aws_iam_role_policy_attachment.workers_autoscaling[0]: Destroying... [id=cert-demo-cluster20190627115759610300000009-2019062711580393650000000f]
module.vpc.aws_route_table_association.public[0]: Destruction complete after 1s
module.cluster.aws_autoscaling_group.workers[0]: Destroying... [id=cert-demo-cluster-020190627115816484000000011]
module.vpc.aws_route.public_internet_gateway[0]: Destruction complete after 1s
module.cluster.aws_security_group_rule.workers_ingress_cluster_https[0]: Destroying... [id=sgrule-3541975220]
module.cluster.aws_iam_role_policy_attachment.workers_AmazonEKSWorkerNodePolicy[0]: Destruction complete after 1s
module.cluster.aws_iam_role_policy_attachment.workers_AmazonEC2ContainerRegistryReadOnly[0]: Destroying... [id=cert-demo-cluster20190627115759610300000009-2019062711580300510000000e]
module.cluster.aws_iam_role_policy_attachment.workers_autoscaling[0]: Destruction complete after 1s
module.vpc.aws_internet_gateway.this[0]: Destroying... [id=igw-0f179056bbfd5c899]
module.cluster.aws_iam_role_policy_attachment.workers_AmazonEC2ContainerRegistryReadOnly[0]: Destruction complete after 1s
module.vpc.aws_route_table.public[0]: Destroying... [id=rtb-014c4d2d5decee860]
module.cluster.aws_security_group_rule.cluster_egress_internet[0]: Destruction complete after 3s
module.cluster.aws_iam_policy.worker_autoscaling[0]: Destroying... [id=arn:aws:iam::045654838477:policy/eks-worker-autoscaling-cert-demo-cluster2019062711575961670000000a]
module.cluster.aws_security_group_rule.workers_egress_internet[0]: Destruction complete after 3s
module.cluster.aws_iam_policy.worker_autoscaling[0]: Destruction complete after 1s
module.cluster.aws_security_group_rule.cluster_https_worker_ingress[0]: Destruction complete after 5s
module.cluster.aws_security_group_rule.workers_ingress_self[0]: Destruction complete after 5s
module.vpc.aws_route_table.public[0]: Destruction complete after 3s
module.cluster.aws_security_group_rule.workers_ingress_cluster[0]: Destruction complete after 8s
module.db.module.db_instance.aws_db_instance.this[0]: Still destroying... [id=cert-demo-cluster, 10s elapsed]
module.cluster.aws_security_group_rule.workers_ingress_cluster_https[0]: Destruction complete after 10s
module.cluster.aws_autoscaling_group.workers[0]: Still destroying... [id=cert-demo-cluster-020190627115816484000000011, 10s elapsed]
module.vpc.aws_internet_gateway.this[0]: Still destroying... [id=igw-0f179056bbfd5c899, 10s elapsed]
module.db.module.db_instance.aws_db_instance.this[0]: Still destroying... [id=cert-demo-cluster, 20s elapsed]
module.cluster.aws_autoscaling_group.workers[0]: Still destroying... [id=cert-demo-cluster-020190627115816484000000011, 20s elapsed]
module.vpc.aws_internet_gateway.this[0]: Still destroying... [id=igw-0f179056bbfd5c899, 20s elapsed]
module.db.module.db_instance.aws_db_instance.this[0]: Still destroying... [id=cert-demo-cluster, 30s elapsed]
module.cluster.aws_autoscaling_group.workers[0]: Still destroying... [id=cert-demo-cluster-020190627115816484000000011, 30s elapsed]
module.vpc.aws_internet_gateway.this[0]: Still destroying... [id=igw-0f179056bbfd5c899, 30s elapsed]
module.db.module.db_instance.aws_db_instance.this[0]: Still destroying... [id=cert-demo-cluster, 40s elapsed]
module.cluster.aws_autoscaling_group.workers[0]: Still destroying... [id=cert-demo-cluster-020190627115816484000000011, 40s elapsed]
module.vpc.aws_internet_gateway.this[0]: Still destroying... [id=igw-0f179056bbfd5c899, 40s elapsed]
module.db.module.db_instance.aws_db_instance.this[0]: Still destroying... [id=cert-demo-cluster, 50s elapsed]
module.cluster.aws_autoscaling_group.workers[0]: Still destroying... [id=cert-demo-cluster-020190627115816484000000011, 50s elapsed]
module.vpc.aws_internet_gateway.this[0]: Still destroying... [id=igw-0f179056bbfd5c899, 50s elapsed]
module.vpc.aws_internet_gateway.this[0]: Destruction complete after 55s
module.db.module.db_instance.aws_db_instance.this[0]: Still destroying... [id=cert-demo-cluster, 1m0s elapsed]
module.cluster.aws_autoscaling_group.workers[0]: Still destroying... [id=cert-demo-cluster-020190627115816484000000011, 1m0s elapsed]
module.db.module.db_instance.aws_db_instance.this[0]: Still destroying... [id=cert-demo-cluster, 1m10s elapsed]
module.cluster.aws_autoscaling_group.workers[0]: Still destroying... [id=cert-demo-cluster-020190627115816484000000011, 1m10s elapsed]
module.db.module.db_instance.aws_db_instance.this[0]: Still destroying... [id=cert-demo-cluster, 1m20s elapsed]
module.cluster.aws_autoscaling_group.workers[0]: Destruction complete after 1m19s
module.cluster.null_resource.tags_as_list_of_maps[0]: Destroying... [id=477747191525697648]
module.cluster.aws_launch_configuration.workers[0]: Destroying... [id=cert-demo-cluster-020190627115812194200000010]
module.cluster.null_resource.tags_as_list_of_maps[0]: Destruction complete after 0s
module.cluster.aws_launch_configuration.workers[0]: Destruction complete after 1s
module.cluster.aws_iam_instance_profile.workers[0]: Destroying... [id=cert-demo-cluster2019062711580195000000000b]
module.cluster.aws_security_group.workers[0]: Destroying... [id=sg-02a43e2af835ac480]
module.cluster.aws_iam_instance_profile.workers[0]: Destruction complete after 2s
module.cluster.aws_iam_role.workers[0]: Destroying... [id=cert-demo-cluster20190627115759610300000009]
module.cluster.aws_iam_role.workers[0]: Destruction complete after 4s
module.db.module.db_instance.aws_db_instance.this[0]: Still destroying... [id=cert-demo-cluster, 1m30s elapsed]
module.cluster.aws_security_group.workers[0]: Still destroying... [id=sg-02a43e2af835ac480, 10s elapsed]
module.db.module.db_instance.aws_db_instance.this[0]: Still destroying... [id=cert-demo-cluster, 1m40s elapsed]
module.cluster.aws_security_group.workers[0]: Still destroying... [id=sg-02a43e2af835ac480, 20s elapsed]
module.db.module.db_instance.aws_db_instance.this[0]: Still destroying... [id=cert-demo-cluster, 1m50s elapsed]
module.cluster.aws_security_group.workers[0]: Still destroying... [id=sg-02a43e2af835ac480, 30s elapsed]
module.db.module.db_instance.aws_db_instance.this[0]: Destruction complete after 1m53s
module.db.module.db_subnet_group.aws_db_subnet_group.this[0]: Destroying... [id=cert-demo-cluster-20190627114825359400000007]
module.db.module.db_parameter_group.aws_db_parameter_group.this[0]: Destroying... [id=cert-demo-cluster-20190627114759123900000001]
aws_security_group.sec_grp_rds: Destroying... [id=sg-0f7d6df1512675911]
module.db.module.db_subnet_group.aws_db_subnet_group.this[0]: Destruction complete after 1s
module.db.module.db_parameter_group.aws_db_parameter_group.this[0]: Destruction complete after 1s
aws_security_group.sec_grp_rds: Destruction complete after 2s
module.cluster.aws_security_group.workers[0]: Still destroying... [id=sg-02a43e2af835ac480, 40s elapsed]
module.cluster.aws_security_group.workers[0]: Still destroying... [id=sg-02a43e2af835ac480, 50s elapsed]
module.cluster.aws_security_group.workers[0]: Still destroying... [id=sg-02a43e2af835ac480, 1m0s elapsed]
module.cluster.aws_security_group.workers[0]: Still destroying... [id=sg-02a43e2af835ac480, 1m10s elapsed]
module.cluster.aws_security_group.workers[0]: Still destroying... [id=sg-02a43e2af835ac480, 1m20s elapsed]
module.cluster.aws_security_group.workers[0]: Still destroying... [id=sg-02a43e2af835ac480, 1m30s elapsed]
module.cluster.aws_security_group.workers[0]: Still destroying... [id=sg-02a43e2af835ac480, 1m40s elapsed]
module.cluster.aws_security_group.workers[0]: Still destroying... [id=sg-02a43e2af835ac480, 1m50s elapsed]
module.cluster.aws_security_group.workers[0]: Still destroying... [id=sg-02a43e2af835ac480, 2m0s elapsed]
module.cluster.aws_security_group.workers[0]: Still destroying... [id=sg-02a43e2af835ac480, 2m10s elapsed]
module.cluster.aws_security_group.workers[0]: Still destroying... [id=sg-02a43e2af835ac480, 2m20s elapsed]
module.cluster.aws_security_group.workers[0]: Still destroying... [id=sg-02a43e2af835ac480, 2m30s elapsed]
module.cluster.aws_security_group.workers[0]: Still destroying... [id=sg-02a43e2af835ac480, 2m40s elapsed]
module.cluster.aws_security_group.workers[0]: Still destroying... [id=sg-02a43e2af835ac480, 2m50s elapsed]
module.cluster.aws_security_group.workers[0]: Still destroying... [id=sg-02a43e2af835ac480, 3m0s elapsed]
module.cluster.aws_security_group.workers[0]: Still destroying... [id=sg-02a43e2af835ac480, 3m10s elapsed]
module.cluster.aws_security_group.workers[0]: Still destroying... [id=sg-02a43e2af835ac480, 3m20s elapsed]
module.cluster.aws_security_group.workers[0]: Still destroying... [id=sg-02a43e2af835ac480, 3m30s elapsed]
module.cluster.aws_security_group.workers[0]: Still destroying... [id=sg-02a43e2af835ac480, 3m40s elapsed]
module.cluster.aws_security_group.workers[0]: Still destroying... [id=sg-02a43e2af835ac480, 3m50s elapsed]
module.cluster.aws_security_group.workers[0]: Still destroying... [id=sg-02a43e2af835ac480, 4m0s elapsed]
module.cluster.aws_security_group.workers[0]: Still destroying... [id=sg-02a43e2af835ac480, 4m10s elapsed]
module.cluster.aws_security_group.workers[0]: Still destroying... [id=sg-02a43e2af835ac480, 4m20s elapsed]
module.cluster.aws_security_group.workers[0]: Still destroying... [id=sg-02a43e2af835ac480, 4m30s elapsed]
module.cluster.aws_security_group.workers[0]: Still destroying... [id=sg-02a43e2af835ac480, 4m40s elapsed]
module.cluster.aws_security_group.workers[0]: Still destroying... [id=sg-02a43e2af835ac480, 4m50s elapsed]
module.cluster.aws_security_group.workers[0]: Still destroying... [id=sg-02a43e2af835ac480, 5m0s elapsed]
module.cluster.aws_security_group.workers[0]: Still destroying... [id=sg-02a43e2af835ac480, 5m10s elapsed]
module.cluster.aws_security_group.workers[0]: Still destroying... [id=sg-02a43e2af835ac480, 5m20s elapsed]
module.cluster.aws_security_group.workers[0]: Still destroying... [id=sg-02a43e2af835ac480, 5m30s elapsed]
module.cluster.aws_security_group.workers[0]: Still destroying... [id=sg-02a43e2af835ac480, 5m40s elapsed]
module.cluster.aws_security_group.workers[0]: Still destroying... [id=sg-02a43e2af835ac480, 5m50s elapsed]
module.cluster.aws_security_group.workers[0]: Still destroying... [id=sg-02a43e2af835ac480, 6m0s elapsed]
module.cluster.aws_security_group.workers[0]: Still destroying... [id=sg-02a43e2af835ac480, 6m10s elapsed]
module.cluster.aws_security_group.workers[0]: Still destroying... [id=sg-02a43e2af835ac480, 6m20s elapsed]
module.cluster.aws_security_group.workers[0]: Still destroying... [id=sg-02a43e2af835ac480, 6m30s elapsed]
module.cluster.aws_security_group.workers[0]: Still destroying... [id=sg-02a43e2af835ac480, 6m40s elapsed]
module.cluster.aws_security_group.workers[0]: Still destroying... [id=sg-02a43e2af835ac480, 6m50s elapsed]
module.cluster.aws_security_group.workers[0]: Still destroying... [id=sg-02a43e2af835ac480, 7m0s elapsed]
module.cluster.aws_security_group.workers[0]: Still destroying... [id=sg-02a43e2af835ac480, 7m10s elapsed]
module.cluster.aws_security_group.workers[0]: Still destroying... [id=sg-02a43e2af835ac480, 7m20s elapsed]
module.cluster.aws_security_group.workers[0]: Still destroying... [id=sg-02a43e2af835ac480, 7m30s elapsed]
module.cluster.aws_security_group.workers[0]: Still destroying... [id=sg-02a43e2af835ac480, 7m40s elapsed]
module.cluster.aws_security_group.workers[0]: Still destroying... [id=sg-02a43e2af835ac480, 7m50s elapsed]
module.cluster.aws_security_group.workers[0]: Still destroying... [id=sg-02a43e2af835ac480, 8m0s elapsed]
module.cluster.aws_security_group.workers[0]: Still destroying... [id=sg-02a43e2af835ac480, 8m10s elapsed]
module.cluster.aws_security_group.workers[0]: Still destroying... [id=sg-02a43e2af835ac480, 8m20s elapsed]
module.cluster.aws_security_group.workers[0]: Still destroying... [id=sg-02a43e2af835ac480, 8m30s elapsed]
module.cluster.aws_security_group.workers[0]: Still destroying... [id=sg-02a43e2af835ac480, 8m40s elapsed]
module.cluster.aws_security_group.workers[0]: Still destroying... [id=sg-02a43e2af835ac480, 8m50s elapsed]
module.cluster.aws_security_group.workers[0]: Still destroying... [id=sg-02a43e2af835ac480, 9m0s elapsed]
module.cluster.aws_security_group.workers[0]: Still destroying... [id=sg-02a43e2af835ac480, 9m10s elapsed]
module.cluster.aws_security_group.workers[0]: Still destroying... [id=sg-02a43e2af835ac480, 9m20s elapsed]
module.cluster.aws_security_group.workers[0]: Still destroying... [id=sg-02a43e2af835ac480, 9m30s elapsed]
module.cluster.aws_security_group.workers[0]: Still destroying... [id=sg-02a43e2af835ac480, 9m40s elapsed]
module.cluster.aws_security_group.workers[0]: Still destroying... [id=sg-02a43e2af835ac480, 9m50s elapsed]
module.cluster.aws_security_group.workers[0]: Still destroying... [id=sg-02a43e2af835ac480, 10m0s elapsed]

Error: DependencyViolation: resource sg-02a43e2af835ac480 has a dependent object
	status code: 400, request id: 4ce80b5b-32a8-4ca1-a9e4-5e9ab131d3e3

**Comment by antonbabenko** [comment]
Hi,

I am not sure this issue is related to this module, so I am going to close this issue here.

Please ask such questions in the other places.
