### ISSUE TITLE
purposeless aws_route.database_nat_gateway

### ISSUE THREAD

**Issue by tushar00jain** [terraform-aws-modules/terraform-aws-vpc#308]
this resource is not utilised in any route table association and is a duplicate of aws_route.private_nat_gateway

**Comment by tushar00jain** [comment]
https://github.com/terraform-aws-modules/terraform-aws-vpc/pull/309

**Comment by bryantbiggs** [comment]
Though it may not be used by many, it still is a valid resource to provide NAT translation for traffic originating in the database subnets and therefore it will be kept in scope of the module
