### ISSUE TITLE
amazon_side_asn recreating VPC resources?

### ISSUE THREAD

**Issue by geoffreywiseman** [terraform-aws-modules/terraform-aws-vpc#310]
Trying to upgrade to Terraform v0.12, which means that I'm running apply on some projects that haven't needed much attention recently, and with the VPC project, I'm seeing that Terraform wants to recreate a bunch of VPC resources. On a quick scan, it looks like it might come down to this:

```
      amazon_side_asn:                "7224" => "64512" (forces new resource)
```

And all the resources that this forces a re-creation on.

That seems to be related to this:
https://github.com/terraform-providers/terraform-provider-aws/issues/5263

I don't see any issues in the VPC modules addressing this. What can I do to make my vpc module config happy without recreating things that basically haven't changed?  Am I missing any issues/documentation about this?

**Comment by geoffreywiseman** [comment]
Ok, I took another look at this, and I can just add this to the VPC block:
```hcl
amazon_side_asn = 7224
```

That updates the VPC block to use the ASN that Amazon used when the VPC was created, which stops the recreation of the gateway, which fixes everything else that was getting re-created. So if anyone else hits this error

**Comment by DrFaust92** [comment]
closing this, if the issue persists in the latest version of the module please open a new issue
