### ISSUE TITLE
aws_vpc_endpoint_route_table_association: InvalidVpcEndpointId.Malformed: expecting 'vpce-

### ISSUE THREAD

**Issue by spetran** [terraform-aws-modules/terraform-aws-vpc#312]
Hey!

Trying to add our manually created VPC into Terraform*, every import goes well, till we are trying to import manually created aws_vpc_endpoint_route_table_association.public_s3

*adding our manually created VPC to TF by using module:
```
module "vpc" {
  source  = "terraform-aws-modules/vpc/aws"
  version = "~> 1.46.0"
...
}
```

When we are importing 'aws_vpc_endpoint_route_table_association', unfortunately we get following error: 

```
Error: module.vpc.aws_vpc_endpoint_route_table_association.public_s3 (import id: rtbassoc-999b9cf): 1 error occurred:
	* import module.vpc.aws_vpc_endpoint_route_table_association.public_s3 result: rtbassoc-999b9cf: aws_vpc_endpoint_route_table_association.public_s3: InvalidVpcEndpointId.Malformed: Invalid Id: '' (expecting 'vpce-...; the Id may only contain lowercase alphanumeric characters and a single dash')
	status code: 400, request id: 2ff61888-01cb-4476-b834-f389f5697133
```

The same happens when we try to change import id into required vpce:

```
Error: module.vpc.aws_vpc_endpoint_route_table_association.public_s3 (import id: vpce-999ca99d): 1 error occurred:
	* import module.vpc.aws_vpc_endpoint_route_table_association.public_s3 result: vpce-999ca99d: aws_vpc_endpoint_route_table_association.public_s3: InvalidVpcEndpointId.Malformed: Invalid Id: '' (expecting 'vpce-...; the Id may only contain lowercase alphanumeric characters and a single dash')
	status code: 400, request id: 9ed351f6-4085-4bf8-a0da-968536c64259
```

In the attachment you can find the log from debugging (TRACE).

When provide `terraform plan`, the output for this resource looks like this:

```
   + module.vpc.aws_vpc_endpoint_route_table_association.public_s3
       id:                      <computed>
       route_table_id:          "rtb-e0a97999"
       vpc_endpoint_id:        "vpce-999ca99d"
```

Do you think it might be bug? Any idea/help, please? Thanks a lot!

[when_vpce_id_used.txt](https://github.com/terraform-aws-modules/terraform-aws-vpc/files/3482669/when_vpce_id_used.txt)
[when_rt_associ_used.txt](https://github.com/terraform-aws-modules/terraform-aws-vpc/files/3482670/when_rt_associ_used.txt)

**Comment by bryantbiggs** [comment]
@spetran we can close this as it was an upstream AWS provider issue that has since been resolved, correct? 

https://github.com/terraform-providers/terraform-provider-aws/issues/9693#issuecomment-540731993

**Comment by DrFaust92** [comment]
closing this, @spetran please re-open if you are still having issues
