### ISSUE TITLE
Elasticache and RDS subnets not created on VPC creation

### ISSUE THREAD

**Issue by joawan** [terraform-aws-modules/terraform-aws-vpc#313]
Using verison 2.9.0, there are no subnet groups created on vpc creation.

Attempts with `create_elasticache_subnet_group = true` also fail.

**Comment by antonbabenko** [comment]
Hi Joakim!

Elasticache and RDS subnets should be created iа CIDR blocks are defined, like this:

https://github.com/terraform-aws-modules/terraform-aws-vpc/blob/40821bbe9469438a5c439c88109b4664e1a929bf/examples/complete-vpc/main.tf#L20-L21

Here is the condition for the creation of elasticache subnet group:
https://github.com/terraform-aws-modules/terraform-aws-vpc/blob/40821bbe9469438a5c439c88109b4664e1a929bf/main.tf#L396

**Comment by joawan** [comment]
Is it possible to reuse the existing private subnets?

**Comment by antonbabenko** [comment]
No, it is not possible.
