### ISSUE TITLE
Outputs for Secrets Manager VPC Endpoint

### ISSUE THREAD

**Issue by galindro** [terraform-aws-modules/terraform-aws-vpc#318]
There is no Secrets Manager VPC Endpoint outputs, according to README.md. Is it possible to add these outputs (like `vpc_endpoint_cloudtrail_id`, `vpc_endpoint_dynamodb_id`, etc...)? I would like to be able to get the endpoint id.

**Comment by antonbabenko** [comment]
There are `vpc_endpoint_cloudtrail_id` and `vpc_endpoint_dynamodb_id` in the outputs in the README.md - https://github.com/terraform-aws-modules/terraform-aws-vpc#outputs

Though there are some more VPC endpoints missing (eg, #311) which I will review and merge now.

**Comment by galindro** [comment]
Yeah @antonbabenko, I know that there are vpc_endpoint_cloudtrail_id and vpc_endpoint_dynamodb_id already available in outputs. I've just used them as an example.

**Comment by antonbabenko** [comment]
I've just added all missing outputs for all VPC endpoints in 8436162 and released [v2.11.0](https://github.com/terraform-aws-modules/terraform-aws-vpc/releases/v2.11.0).

Thank you for opening this issue!
