### ISSUE TITLE
Constrain AWS provider for compatibility

### ISSUE THREAD

**Issue by brandoconnor** [terraform-aws-modules/terraform-aws-vpc#32]
This module is now incompatible with older versions of the AWS provider (e.g. 0.1.4). I haven't tested whether it's possible or it works to constrain a provider within a module but I would think it does. If not, a note in the documentation would suffice.

AWS provider version 0.1.4 yields:

```
1 error(s) occurred:

* module.vpc.aws_nat_gateway.this: : invalid or unknown key: tags
```

I would guess this is common across a few old versions.

**Comment by antonbabenko** [comment]
Good point. I was thinking about this myself for some time and think that adding to README is the best option for now.
