### ISSUE TITLE
v1.70: incorrect sagemaker resource naming

### ISSUE THREAD

**Issue by klebediev** [terraform-aws-modules/terraform-aws-vpc#321]
Hi!
After upgrading module from `1.67` to `1.70` started getting this error:
```
Error: Error asking for user input: Error parsing address 'module.vpc.aws_vpc_endpoint.sagemaker.runtime': Unexpected value for InstanceType field: "runtime"
```
Looks like it relates to a typo in name of resource (`sagemaker.runtime` vs `sagemaker_runtime`):
https://github.com/terraform-aws-modules/terraform-aws-vpc/blob/79d3a3560a39545a099820f48c3e051db4baf1dc/vpc-endpoint.tf#L916

@DrFaust92

**Comment by DrFaust92** [comment]
It was a mixup on my part as there is not uniform way that Endpoints are named.

some are "endpoint-name" and some are "endpoint.name".

**Comment by antonbabenko** [comment]
@klebediev Please use [v1.71.0](https://github.com/terraform-aws-modules/terraform-aws-vpc/releases/v1.71.0).

**Comment by klebediev** [comment]
Thanks, guys!
