### ISSUE TITLE
Unable to create VPC endpoints

### ISSUE THREAD

**Issue by KursLabIgor** [terraform-aws-modules/terraform-aws-vpc#325]
I need to create VPC endpoints. I statred from s3 endpoint. 
According to this file [https://github.com/terraform-aws-modules/terraform-aws-vpc/blob/terraform011/vpc-endpoint.tf](url) I need to specify two parameters. I set bot. plan tells me that *Infrastructure is up-to-date* 
What i missed? 

Thanks

**Comment by antonbabenko** [comment]
Please take a look at the example - https://github.com/terraform-aws-modules/terraform-aws-vpc/blob/terraform011/examples/complete-vpc/main.tf

For S3 VPC endpoint, you need to specify `enable_s3_endpoint = true`
