### ISSUE TITLE
Re-use private subnets in subnet groups?

### ISSUE THREAD

**Issue by muffy** [terraform-aws-modules/terraform-aws-vpc#327]
Rather than creating new subnets for each type of subnet group, we'd like to create the elasticache, redshift, and db subnet groups using the private subnets already created by the module.

**Comment by dbirks** [comment]
I ended up making a separate resource to create the db subnet group.

```
resource "aws_db_subnet_group" "db-subnet-group" {
  name       = "${var.env}-db-subnet-group"
  subnet_ids = module.vpc.private_subnets
}
```
I also would like support for that in this module though.
