### ISSUE TITLE
Feature request: Reuse externally created NAT gateways

### ISSUE THREAD

**Issue by Dzhuneyt** [terraform-aws-modules/terraform-aws-vpc#328]
The documentation provides examples on how to reuse elastic IPs for the NAT gateways that the module will create. I am sure this is a common use case.

But another common use case is where I create and manage the NAT gateways themselves outside of the module. In that case, it would be useful if I can pass the NAT gateway IPs as an input parameter, preventing this module from creating NAT gateways but still create the necessary route tables for the subnet<>NAT gateway association to work.

**Comment by Dzhuneyt** [comment]
@antonbabenko @DrFaust92 I could contribute with some code here if you think you need help. Let me know.

**Comment by antonbabenko** [comment]
I guess you are talking about externally created NAT instances, not NAT Gateways, right? NAT gateways can't be shared across VPCs using [AWS RAM](https://aws.amazon.com/ram/) if I remember correctly.

If this is the case, then both `aws_route.private_nat_gateway` and `aws_route.database_nat_gateway` should be updated to support `instance_id`.

To be honest, I am a bit skeptical to introduce such complexity into the module since nobody asked for this before. Could you explain in more detail how the solution will work?

**Comment by phamthaibaoduy** [comment]
@antonbabenko 
Hi, I have this exact problem today.
I'm trying to import 1 existing VPC with this module, but there is no way to reuse an existing NAT instance.

**Comment by Dzhuneyt** [comment]
Initially, when I opened this request, I thought simply creating a NAT gateway and reusing it across multiple VPCs was possible, to reach a final goal - cost-effectiveness. However, now that I know that it's not possible to reuse a NAT gateway across multiple VPCs, the closest thing that allows saving money is reusing a NAT instance, so we could reuse this ticket as a way to track such progress.

Do you have any plans for introducing such a feature? I'm sure a lot of server administrators that use this module would benefit from the savings (sacrificing slightly the high availability the NAT gateway provides)>

**Comment by phamthaibaoduy** [comment]
@Dzhuneyt I found this module which might be what you need 
https://github.com/int128/terraform-aws-nat-instance

**Comment by bryantbiggs** [comment]
hello all - thanks for the suggestion here. as Anton said, I don't think the added complexity is  worthwhile to take on for this module. this seems to be a very specific use case, and in my opinion, a use case that does not align with best practices in the cloud/AWS. if there is a strong interest from more in the community using this module, and why this is beneficial, then we could look at possibly revisiting

**Comment by antonbabenko** [comment]
Closing this issue, because adding this feature to the module will be too complex to support.
