### ISSUE TITLE
create_public_redshift, does not attach igw if create_redshift_subnet_route_table = true

### ISSUE THREAD

**Issue by michaeljoy** [terraform-aws-modules/terraform-aws-vpc#330]
It appears that even in the latest v2.15 module, if you set ```create_database_subnet_route_table = true```, setting ```enable_public_redshift = true``` does nothing expected. There is no igw attached to the redshift subnet routing table, which means that redshift is not publicly accessible when this is desired in some edge cases.

We probably need to mimic the ```create_database_internet_gateway_route``` behavior here and add ```create_redshift_internet_gateway``` for when a dedicated subnet routing table is preferable to sharing the public table.

The logic behavior issue seems to be around here, however I'd suggest we make this more uniform and in line with the db route table behavior for consistency : 

https://github.com/terraform-aws-modules/terraform-aws-vpc/blob/ee192c5d2baa50629304f1da1ada7816ecd39e62/main.tf#L934

https://github.com/terraform-aws-modules/terraform-aws-vpc/blob/ee192c5d2baa50629304f1da1ada7816ecd39e62/main.tf#L944

**Comment by michaeljoy** [comment]
I will add that var.redshift_subnets is 6, and > 0 in this test case

**Comment by antonbabenko** [comment]
Please take a look at `examples/complete` and show the exact parameters you are providing, what you got, and what did you expect.

**Comment by bryantbiggs** [comment]
closing for now - please feel free to respond or open a new issue with more context and info so we can help troubleshoot
