### ISSUE TITLE
create default vpc security group for vpc interface endpoints

### ISSUE THREAD

**Issue by aavileli** [terraform-aws-modules/terraform-aws-vpc#332]
A default security group should be created for the vpc and associated to interface vpc endpoints if one is not supplied.

**Comment by antonbabenko** [comment]
Hi Ashley,

This is not always a good idea to assume anything and create resources on behalf of a user. This module requires you to create a security group and pass it as an argument. More transparency is better.

Closing this issue.

**Comment by aavileli** [comment]
Absolutely agree but when using an upstream module with terragrunt . This will create a circular dependency as the VPC needs to be created first then an SG needs to be added to the module which requires the VPC id.
Therefore asked if a parameter could be set which would create a default SG to be attached to the VPC endpoint. The module encapsulates creation of VPC and endpoints.

**Comment by antonbabenko** [comment]
You are right, I didn't think about this use-case though I felt that creation of VPC endpoints _should_ also be available outside of this module (separate `terraform-aws-module`, for eg).

The flow to do this now is by calling the same VPC module with different arguments:
VPC (without VPC endpoints) => SG => VPC (with VPC endpoints)

If we create a temporary SG together with the VPC and use it for VPC endpoints it will be fine for the first run, but after that user will still prefer to set another security group and get rid of temporary SG - which will still result in a two-step execution.

Do you have ideas on how to solve this and have a single step execution?

**Comment by aavileli** [comment]
I think creation of VPC endpoints should be out of this module. But if it encapsulates creation of the VPC and endpoints, then there could be a boolean flag for vpc endpoints use default security group for vpc endpoints. 

Then in the vpc-endpoints.tf this could be added

data "aws_security_group" "default" {
  name   = "default"
  vpc_id = aws_vpc.id
}

security_group_ids = var.use_default_security_group == true ? data.aws_security_group.default.vpc_id : var.ssm_endpoint_security_group_ids 

To fix my issue with circular dependency in terragrunt I have now created a quirk fix by encapsulated your module into another module where I can create SG dependency to your module.

**Comment by antonbabenko** [comment]
I think until VPC endpoints are not externalized into a separate module, there will be a need in a quirk fix as you described. Maybe you can open a PR and describe in README your solution? It would definitely help some people.

**Comment by tomalok** [comment]
I may be in a similar dependency loop, but with regards to `..._endpoint_subnet_ids`.

My `vpc` module creates `public_subnets`, but I'm not seeing how to use the module-generated subnet IDs as input to `..._endpoint_subnet_ids`...  If there's no way to do this, then there's essentially no way to currently use endpoints with anything other than `private_subnets`.

**Comment by hansarh** [comment]
@antonbabenko I have a question regarding the workflow you described:

The flow to do this now is by calling the same VPC module with different arguments:
VPC (without VPC endpoints) => SG => VPC (with VPC endpoints)

how can the call for the "VPC(with VPC endpoints)" be excecuted when the module does not have some identifier for the created VPC as input?

**Comment by macunha1** [comment]
In case you have missed it, the PR https://github.com/terraform-aws-modules/terraform-aws-vpc/pull/354 solves the issue mentioned. I was going through some old opened PR and stepped into this

> This module requires you to create a security group and pass it as an argument. More transparency is better.

There's a feature toggle (disabled by default) that must be specified by the user to have this security group working. Plus, during the implementation I found that https://github.com/terraform-aws-modules/terraform-aws-vpc/blob/master/examples/complete-vpc/main.tf#L5-L8 suggests the usage of a circular reference and fixed it.

```hcl
data "aws_security_group" "default" {
  name   = "default"
  vpc_id = module.vpc.vpc_id
}

module "vpc" {
# ...
  ssm_endpoint_security_group_ids  = [data.aws_security_group.default.id]
# ...
  ssmmessages_endpoint_security_group_ids  = [data.aws_security_group.default.id]
```
Not just once, but **many** times the default AWS SG is referenced inside the module responsible for creating it (???)

We could merge the PR and close this issue at the same time

**Comment by polymorcodeus** [comment]
We ran into the original problem (terragrunt with circular dependency) - however, we didn't want to leverage the default security group.

I've updated our variables.tf and vpc-endpoints.tf to look similar.
```
variable "vpc_id" {
  description = "VPC Id - used in conjuction with create_vpc set to false and creating endpoints."
  type        = string
  default     = ""
}

# VPC Endpoint for EC2
data "aws_vpc_endpoint_service" "ec2" {
  count = (length(var.vpc_id) > 0 || var.create_vpc) && var.enable_ec2_endpoint ? 1 : 0

  service = "ec2"
}

resource "aws_vpc_endpoint" "ec2" {
  count = (length(var.vpc_id) > 0 || var.create_vpc) && var.enable_ec2_endpoint ? 1 : 0

  vpc_id            = length(var.vpc_id) > 0 && !var.create_vpc ? var.vpc_id : local.vpc_id
...
```
Then you can just create your endpoints separately.
```
module "vpc_endpoints" {
  source  = "../modules/network/vpc"

  create_vpc = false
  vpc_id      = module.vpc.vpc_id

  enable_ec2_endpoint                     = true
  ec2_endpoint_security_group_ids         = [module.ssl_sg.this_security_group_id]
  ec2_endpoint_subnet_ids                 = module.vpc.private_subnets

  tags = {
    Source = "terraform_base-module-vpc_endpoints"
  }
}
```
The update accommodates the original intent to be able to call everything inside the single module call, but will allow you to build dependency mappings appropriately with terragrunt and keep everything inside a single module build.

If there is interest I can initiate a PR with my proposed changes. Just figuring out how to do testing and the like, relatively new on the TF scene.

**Comment by antonbabenko** [comment]
@polymorcodeus I like the approach you are describing here with conditional creation. Though you should do a small workaround which Terragrunt does not ask you to worry about. It is related to the usage of computed values in `count`. So that if a user sets `vpc_id = module.vpc.vpc_id` Terraform will raise an error.

The solution is to introduce another boolean variable (`use_existing_vpc_id_for_endpoints = true`, for e.g.) and compare it inside `count`, and `vpc_id` which you have already added inside resources.

Please open a PR (also update an example and README) and @DrFaust92 or I will take a look into it.

**Comment by ianrodrigues** [comment]
I enjoy @polymorcodeus approach, but I still think it may be confusing at first. Didn't you guys considered a brand new `terraform-aws-vpc-endpoints` module?

**Comment by kclinden** [comment]
Did this ever get resolved? it doesn't look like the `use_existing_vpc_id_for_endpoints` ever made it into relase.

**Comment by bryantbiggs** [comment]
I believe if you update to v3.0+ this shouldn't be an issue anymore now that the VPC endpoints are created as part of a sub-module
