### ISSUE TITLE
Incorrect endpoint service for AWS Transfer

### ISSUE THREAD

**Issue by zswanson** [terraform-aws-modules/terraform-aws-vpc#334]
The service name specified in the endpoints.tf for AWS Transfer is incorrect. 

`data "aws_vpc_endpoint_service" "transfer" {
  count = var.create_vpc && var.enable_transfer_endpoint ? 1 : 0

  service = "transfer"
}`

This needs to be `transfer.server`. I had a lot of trouble getting this module to work and eventually with AWS Tech Support worked out that this was part of the problem. (The other part was that their endpoint for the transfer service had gone offline) As it is right now, this data lookup *does* respond with an endpoint ID, but it will be incorrect and the AWS Transfer server will reject the endpoint ID during a terraform apply, stating that it doesn't meet a regex requirement. 

AWS support responded to me:
>  Please note that "com.amazonaws.us-east-1.transfer" is for another AWS service and not for AWS SFTP. We need to choose the Service Name - com.amazonaws.us-east-1.transfer.server to create a VPC endpoint for AWS SFTP

**Comment by DrFaust92** [comment]
the "transferserver" endpoint is what you are looking for, it uses the "transfer.server"
as you said transfer is another service.

**Comment by antonbabenko** [comment]
Here is the code @DrFaust92 is pointing to:
https://github.com/terraform-aws-modules/terraform-aws-vpc/blob/417a3c9629cb45e44395aee30c2ce48e55e60d52/vpc-endpoints.tf#L298-L318

**Comment by zswanson** [comment]
I see, thanks for clarifying. Confusing API naming on their part.
