### ISSUE TITLE
Clone Repo

### ISSUE THREAD

**Issue by abhinavkorpal** [terraform-aws-modules/terraform-aws-vpc#339]
when I clone terraform-aws-vpc in local. main.tf, variable.tf turns red with error. Any idea what is the issue ?

**Comment by antonbabenko** [comment]
Well, don't clone this repo. :)

Use it as described in provision instructions here - https://registry.terraform.io/modules/terraform-aws-modules/vpc/aws or clone it locally and use a relative or absolute path in `source`.

Please ask general questions about Terraform on forums like - https://discuss.hashicorp.com/ and stackoverflow.
