### ISSUE TITLE
How does the DNS options works ?

### ISSUE THREAD

**Issue by rgarrigue** [terraform-aws-modules/terraform-aws-vpc#342]
Hi

Configuring the DNS options, I end up with the following `resolv.conf`

```
domain dev.company
search dev.company
nameserver 127.0.0.1
nameserver 9.9.9.9
nameserver 91.239.100.100
```

I'ld like to specify the search field differently, like this

```
domain dev.company
search node.dev.company service.dev.company
nameserver 127.0.0.1
nameserver 9.9.9.9
nameserver 91.239.100.100
```

Is it possible ? If not, is it a limitation of your module, or underlying AWS's VPC parameters ?

Best regards,

**Comment by bryantbiggs** [comment]
hello @rgarrigue - thanks for submitting this issue. you can set multiple search domains by specifying them under `domain_name` with a space between each. see below which should meet your needs:

```hcl
resource "aws_vpc_dhcp_options" "foo" {
  domain_name          = "node.dev.company service.dev.company"
  domain_name_servers  = ["127.0.0.1", "9.9.9.9", "91.239.100.100"]
  ntp_servers          = ["127.0.0.1"]
  netbios_name_servers = ["127.0.0.1"]
  netbios_node_type    = 2
}
```

Results in:
<img width="398" alt="image" src="https://user-images.githubusercontent.com/10913471/72220400-5637a600-351e-11ea-8c10-7d2e89601619.png">

**Comment by bryantbiggs** [comment]
also, just want to note that I don't believe this is the appropriate route for DHCP option sets. Option sets are 1:1 to VPC so you should only really need to use `dev.company` and not need the specificity of `service.dev.company` or `node.dev.company`. Anything traffic looking to resolve `dev.company` will be routed to the name servers provided so I would recommend just using `dev.company` for domain attribute

**Comment by bryantbiggs** [comment]
@antonbabenko we can close
