### ISSUE TITLE
Single private_nat_gateway

### ISSUE THREAD

**Issue by anub1s187** [terraform-aws-modules/terraform-aws-vpc#344]
Error: Error in function call

  on .terraform/modules/vpc/terraform-aws-modules-terraform-aws-vpc-5358041/main.tf line 905, in resource "aws_route" "private_nat_gateway":
 905:   route_table_id         = element(aws_route_table.private.*.id, count.index)
    |----------------
    | aws_route_table.private is empty tuple
    | count.index is 0

Call to function "element" failed: cannot use element function with an empty
list.

Trying to use single NAT gateway

  private_subnets = module.shared_vars.private_vpcs
  public_subnets  = module.shared_vars.public_vpcs

  enable_nat_gateway = true
  single_nat_gateway = true

**Comment by L1kbezZz** [comment]
Hey, @anub1s187. I assume that you've found the solution or root cause, could you please share the solution?

**Comment by jross-ai** [comment]
Hey, @L1kbezZz did you ever find a solution to this problem? I am also struggling with a similar issue.
