### ISSUE TITLE
Registry Documentation Incorrect

### ISSUE THREAD

**Issue by lw-trectenwald** [terraform-aws-modules/terraform-aws-vpc#345]
The ([TF registry documentation for 2.17.0](https://registry.terraform.io/modules/terraform-aws-modules/vpc/aws/2.17.0)) is incorrect.

It states that there are 8 required variables:

```text
module "vpc" {
  source  = "terraform-aws-modules/vpc/aws"
  version = "2.17.0"
  # insert the 8 required variables here
}
```

Passing only `cidr` will allow the module to run properly (and that is required, yet is not listed as one of the 8).

Thanks!

**Comment by antonbabenko** [comment]
Thanks for the report. This seems to be a valid issue for the Terraform Registry. Closing this one here.
