### ISSUE TITLE
Feature: expose the db_subnet_group_name as an output

### ISSUE THREAD

**Issue by gwvandesteeg** [terraform-aws-modules/terraform-aws-vpc#346]
When creating an RDS cluster and you want to provide it access to the DB subnet group, you need to specify the subnet group name which is not being exposed from the outputs.

Please add (i'll put together a PR when i can).

**Comment by dpiddockcmp** [comment]
It's exposed as `database_subnet_group`
https://github.com/terraform-aws-modules/terraform-aws-vpc/blob/v2.17.0/outputs.tf#L131..L134
https://www.terraform.io/docs/providers/aws/r/db_subnet_group.html#id
