### ISSUE TITLE
Feature request: "propagate_intra_route_tables_vgw"

### ISSUE THREAD

**Issue by paullschock** [terraform-aws-modules/terraform-aws-vpc#352]
I am utilizing intra_subnets as a part of a use-case where I am exposing AWS services to a private (non-internet connected) network connected to AWS via a virtual gateway interface (by way of direct connect private vif) and would like to be able to optionally propagate learned routes to intra_subnets.

Following from how this is done for private subnets, I think the following would work (assuming additional variable added):
```
resource "aws_vpn_gateway_route_propagation" "intra" {
  count = "${var.create_vpc && var.propagate_intra_route_tables_vgw && (var.enable_vpn_gateway || var.vpn_gateway_id != "") ? length(var.intra_subnets) : 0}"

  route_table_id = "${element(aws_route_table.intra.*.id, count.index)}"
  vpn_gateway_id = "${element(concat(aws_vpn_gateway.this.*.id, aws_vpn_gateway_attachment.this.*.vpn_gateway_id), count.index)}"
}
```

Put together a more complete commit in a branch here https://github.com/paullschock/terraform-aws-vpc/commit/2da6b56cc7e0e367c4775f6ea1cf62dc3afaf6d4

**Comment by DrFaust92** [comment]
@antonbabenko , does this make sense to you given the "closed" nature of the intra subnets? i can open a PR if you are ok with it.

**Comment by antonbabenko** [comment]
Yes, I think this is a valid case even for "closed" subnets as intra.

Please open PR only to the master branch. We need to stop adding new features for Terraform 0.11 users.

**Comment by DrFaust92** [comment]
Will do

**Comment by antonbabenko** [comment]
[v2.32.0](https://github.com/terraform-aws-modules/terraform-aws-vpc/releases/v2.32.0) of this module has been just released.
