### ISSUE TITLE
kitchen tests failing on terraform011 

### ISSUE THREAD

**Issue by paullschock** [terraform-aws-modules/terraform-aws-vpc#353]
When pulling down latest on branch 'terraform011' kitchen tests do not pass. 

Failure here:
```
vpc 'test-example'
  is expected to exist
  is expected to be available
  is expected to have tag "Name"
  is expected to have tag "Owner"
  is expected to have tag "Environment"
  is expected to have route table "test-example-public"
  is expected to have route table "test-example-private-eu-west-1a" (FAILED - 1)
  is expected to have route table "test-example-private-eu-west-1b" (FAILED - 2)
```

For complete run details see here:
https://gist.github.com/paullschock/8d1a83497b4cde85801b28bc3aea0934

My read of this shows me two issues with ``"aws_route_table" "private"``:

1. 
L105:
```
tags = "${merge(map("Name", (var.single_nat_gateway ? "${var.name}-${var.private_subnet_suffix}" : format("%s-${var.private_subnet_suffix}-%s", var.name, element(var.azs, count.index)))), var.tags, var.private_route_table_tags)}"
```
When ``var.single_nat_gateway`` is true (it would be per [here](https://github.com/terraform-aws-modules/terraform-aws-vpc/blob/master/examples/test_fixture/main.tf#L16)), the route table is not created with the suffix

2. 
L101:
```
count = "${var.create_vpc && local.max_subnet_length > 0 ? local.nat_gateway_count : 0}"
```
Since ``local.nat_gateway_count`` will end up evaluating to 1 (given the value of ``var.single_nat_gateway``) there would only be a single route table created which would appear destined for failure given the [test parameters](https://github.com/terraform-aws-modules/terraform-aws-vpc/blob/master/test/integration/default/test_vpc.rb#L19) pull 2 AZs and then loops through them for should_have route table (at least in my lay interpretation). 

I tried the following on my branch to get the tests to pass: https://github.com/paullschock/terraform-aws-vpc/commit/6690ddd7913f54d969ed54ff994e7556a0b0f952, but it would seem reasonable only a single route table is created when there is only a single nat_gateway?

**Comment by DrFaust92** [comment]
tf 11 is not actively maintained so ill close this.
