### ISSUE TITLE
Re-adding S3 endpoint

### ISSUE THREAD

**Issue by vitalibystritski** [terraform-aws-modules/terraform-aws-vpc#356]
If the S3 endpoint is removed and re-added again, getting the following error:
------------
* module.vpc.data.aws_vpc_endpoint_service.s3: 1 error(s) occurred:

* module.vpc.data.aws_vpc_endpoint_service.s3: data.aws_vpc_endpoint_service.s3: error reading VPC Endpoint Service (com.amazonaws.us-east-1.s3): InvalidServiceName: The Vpc Endpoint Service 'com.amazonaws.us-east-1.s3' does not exist
	status code: 400, request id: eedbd020-888b-45c0-858a-009884d75617
----------

**Comment by jimsparkman** [comment]
I am seeing this and I did not remove the endpoint, just adding infra associated w/ vpc.

**Comment by ryanmckeague** [comment]
I am having this same issue.

**Comment by jimsparkman** [comment]
I wonder if this is residual effects of aws API issues earlier today: https://status.aws.amazon.com/

**Comment by jeffgran** [comment]
I am seeing this issue when running `plan` and I have made zero changes to anything. I agree it seems likely caused by the aws issues today.

**Comment by vitalibystritski** [comment]
I was suspecting the issue with aws too, and did check the services status: all is green.

**Comment by vitalibystritski** [comment]
Interesting: meanwhile on Twitter from @awssupport
Our services have now been fully restored in all regions. 🗺 If you're still facing issues, these troubleshooting steps & resources are always available

**Comment by jimsparkman** [comment]
This now working for me.

**Comment by bryantbiggs** [comment]
is this still a relevant issue or can we close @vitalibystritski ?

**Comment by bryantbiggs** [comment]
@antonbabenko I think we can close
