### ISSUE TITLE
One subnet per availability zone

### ISSUE THREAD

**Issue by tomasbackman** [terraform-aws-modules/terraform-aws-vpc#358]
There is an option to limit the amount of nat gateways to the availability zones.
It would be cool if the amount of subnets could be limited in the same way.

I think it would be useful to avoid accidentaly creating too many (like have..)

**Comment by bryantbiggs** [comment]
hello @tomasbackman - this is something that is already available today. the number of subnets is based off the number of availability zones and CIDR blocks passed in to `azs` and `xxx_subnets` respectively:

To create 3 subnets (each) spread across 3 availability zones (full module definition not shown for brevity):
```hcl
module "vpc" {
  source = "terraform-aws-modules/vpc/aws"
  
  azs                 = ["eu-west-1a", "eu-west-1b", "eu-west-1c"]
  private_subnets     = ["20.10.1.0/24", "20.10.2.0/24", "20.10.3.0/24"]
  public_subnets      = ["20.10.11.0/24", "20.10.12.0/24", "20.10.13.0/24"]
}
```

To create 1 subnet (each) in 1 availability zone (full module definition not shown for brevity):
```hcl
module "vpc" {
  source = "terraform-aws-modules/vpc/aws"

  azs                 = ["eu-west-1a"]
  private_subnets     = ["20.10.1.0/24"]
  public_subnets      = ["20.10.11.0/24"]
}
```

**Comment by tomasbackman** [comment]
Well yes @bryantbiggs with a well defined input like that it is possible. But I would like it much more generic/dynamic. For example Im using a module that can be deployed in different regions so the availability zones are not known in advance and we cant really use that as a set input. Instead we start with finding out, (using data "aws_availability_zones") and then generate a list from there, in some regions there are 6azs, in others there are only 2..
So it would be nice to be able to generate the subnets from that list instead of having to define them in advance. 
However now when I look at it I see some problem with what cidr ranges to use for those generated subnets, even if it would be ok to use the same ranges for all the regions.. it is probably possible to have some pattern as extra input variable. But I do not remember exactly what I was thinking of back in November =)

**Comment by bryantbiggs** [comment]
hello @tomasbackman - yes, unfortunately that would be quite complex to understand what an end users requirements are in terms of mapping CIDR ranges to AZs, plus several strong assumptions in order to enforce this mapping so I don't think it would be something feasible for this project to try to wrap in for such a select use case

**Comment by tomasbackman** [comment]
Yeah, it could be, so unless someone comes up with a smart simple way to do it, it is probably not worth it. It is just a "nice to have"

**Comment by antonbabenko** [comment]
@tomasbackman You can do it like this (see line 21-22):
https://github.com/antonbabenko/terraform-best-practices-workshop/blob/ce8cc6e5cb0efa33fbab64acf04d8af34eeb1a2a/bootstrap-workshop-jsonnet/vpc-with-defaults/vpc.tf

If you want to skip some AZs, you can use [blacklisted_names](https://www.terraform.io/docs/providers/aws/d/availability_zones.html#argument-reference), for example.

**Comment by tomasbackman** [comment]
Ah of course. You are right.
Basically just move the logic I was thinking of one level "up" to  my code and use it as input.
It does not need to be more complicated than this. Thank you @antonbabenko this will work fine.
