### ISSUE TITLE
The name "for_each" is reserved for use in a future version of Terraform

### ISSUE THREAD

**Issue by edgarcolque** [terraform-aws-modules/terraform-aws-vpc#361]
.terraform/modules/vpc/terraform-aws-modules-terraform-aws-vpc-d97bf1c/main.tf line 996, in resource "aws_customer_gateway" "this":
 996:   for_each = var.customer_gateways

The name "for_each" is reserved for use in a future version of Terraform.

**Comment by antonbabenko** [comment]
You are using master branch or `v2` of this module which requires Terraform 0.12.

You need to use a correct version of the module as described here: https://github.com/terraform-aws-modules/terraform-aws-vpc#terraform-versions

**Comment by johndesp** [comment]
We are using the master branch and TFE 12.2 and we are getting the same error. We don't get this error when running on TFE 12.21 . We can't upgrade to 12.21 yet.
Any ideas on how we can get around the following error?

The name "for_each" is reserved for use in a future version of Terraform.

**Comment by dpiddockcmp** [comment]
`for_each` was added in TF 0.12.6. You must use 0.12.6 or later. Ideally much later as there were quite some interesting bugs in the early releases.

Currently only one resource currently uses `for_each`: `aws_customer_gateway.this`. Two options here:
- the resource was added in 2.20.0 of the module. Pin your module definition to version 2.19.0
- if you need other changes added after 2.20.0, you can fork the module and remove the `aws_customer_gateway` resource locally
