### ISSUE TITLE
The name "for_each" is reserved for use in a future version of Terraform.

### ISSUE THREAD

**Issue by Noam-greenberrg** [terraform-aws-modules/terraform-aws-vpc#364]
Hi 
when using the last ver we are getting this error 

 996:   for_each = var.customer_gateways

The name "for_each" is reserved for use in a future version of Terraform.

Terraform v0.12.5
+ provider.aws v2.40.0
+ provider.random v2.2.1
+ provider.template v2.1.2

Your version of Terraform is out of date! The latest version
is 0.12.16. You can update by downloading from www.terraform.io/downloads.html

**Comment by dpiddockcmp** [comment]
`for_each` was added in Terraform 0.12.6. Please update your Terraform

**Comment by Noam-greenberrg** [comment]
HI 
My ver is ":0.12.16." so ...

**Comment by dpiddockcmp** [comment]
Your original post says that you're using Terraform 0.12.5.

**Comment by Noam-greenberrg** [comment]
yes you are correct
i will upgrade and test

**Comment by xanderflood** [comment]
I am currently getting this same message with:

```
$ terraform version
Terraform v0.12.13
+ provider.template v2.1.2
```

I use for_each in several places in my config, but this error only appears when I attempt to use it with a module. Is for_each currently unsupported with modules?

**Comment by antonbabenko** [comment]
`for_each` is a reserved name for an argument but it is used inside of a module itself.

Make sure that your wrapping module (if you make it) does not have `for_each` as an argument, empty cache folder `.terraform`.

**Comment by janjagusch** [comment]
> I am currently getting this same message with:
> 
> ```
> $ terraform version
> Terraform v0.12.13
> + provider.template v2.1.2
> ```
> 
> I use for_each in several places in my config, but this error only appears when I attempt to use it with a module. Is for_each currently unsupported with modules?

This feature is not supported yet. More details [here](https://www.hashicorp.com/blog/hashicorp-terraform-0-12-preview-for-and-for-each/)

> For a long time, users have wished to be able to use the count meta-argument within module blocks, allowing multiple instances of the same module to be created more easily.
> 
>  Again, we have been laying the groundwork for this during Terraform 0.12 development and expect to complete this work in a later release. Along with count, module blocks will also accept the new for_each argument described for resources above, with similar results.
>
> This feature is particularly complicated to implement within Terraform's existing architecture, so some more work will certainly be required before we can support this. To avoid further breaking changes in later releases, 0.12 will reserve the module input variable names count and for_each in preparation for the completion of this feature.

**Comment by antonbabenko** [comment]
I am closing this issue because it is not related to the module itself.

**Comment by AndrewSav** [comment]
@janjagusch depending on the lay out of the module you can pass for_each content as an input variable to it:

```hcl
variable "my_for_each" { 
  type = map
  default = {}
}
```

Then in a resource you just assign it like this:

```hcl
resource "vsphere_virtual_machine" "machine" {
  for_each         = var.my_for_each
  ...
```
When you use (call) the module you need to pass my_for_each similar to this:

```hcl
  my_for_each         = { 
    key1: value1, 
    key2: value2,
   ...
  }
 ...
```
Etc.
