### ISSUE TITLE
Can not download module  VPC module

### ISSUE THREAD

**Issue by akomlik** [terraform-aws-modules/terraform-aws-vpc#380]
starting around Jan  9 20:00 UTC 2020 I can no longer use the module:

`Initializing modules...`
`Downloading terraform-aws-modules/vpc/aws 2.21.0 for vpc...`

`Error: Failed to download module`

`Could not download module "vpc" (main.tf:47) source code from`
`"https://api.github.com/repos/terraform-aws-modules/terraform-aws-vpc/tarball/v2.21.0//*?archive=tar.gz":`
`Error opening a gzip reader for /tmp/getter934953722/archive: EOF.`

**Comment by KetsuN** [comment]
Seeing the same.

**Comment by light-blink** [comment]
works: 
https://api.github.com/repos/terraform-aws-modules/terraform-aws-vpc/tarball/v2.21.0?archive=tar.gz
```15:34 $ curl -LI https://api.github.com/repos/terraform-aws-modules/terraform-aws-vpc/tarball/v2.21.0?archive=tar.gz
HTTP/1.1 302 Found
Server: GitHub.com
Date: Thu, 09 Jan 2020 20:34:51 GMT
Content-Type: text/html;charset=utf-8
Content-Length: 0
Status: 302 Found
X-RateLimit-Limit: 60
X-RateLimit-Remaining: 60
X-RateLimit-Reset: 1578605631
Cache-Control: public, must-revalidate, max-age=0
Expires: Thu, 09 Jan 2020 20:34:51 GMT
Location: https://codeload.github.com/terraform-aws-modules/terraform-aws-vpc/legacy.tar.gz/v2.21.0
Access-Control-Expose-Headers: ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type
Access-Control-Allow-Origin: *
Strict-Transport-Security: max-age=31536000; includeSubdomains; preload
X-Frame-Options: deny
X-Content-Type-Options: nosniff
X-XSS-Protection: 1; mode=block
Referrer-Policy: origin-when-cross-origin, strict-origin-when-cross-origin
Content-Security-Policy: default-src 'none'
X-GitHub-Request-Id: C49E:5BAA:2B4959:6EE95A:5E178E6B

HTTP/1.1 200 OK
Access-Control-Allow-Origin: https://render.githubusercontent.com
Content-Security-Policy: default-src 'none'; style-src 'unsafe-inline'; sandbox
Strict-Transport-Security: max-age=31536000
Vary: Authorization,Accept-Encoding
X-Content-Type-Options: nosniff
X-Frame-Options: deny
X-XSS-Protection: 1; mode=block
ETag: W/"d35c5aa390ed18647a9f7260641eb00662cf78bf099350a647f41b5316c8ddef"
Content-Type: application/x-gzip
Content-Disposition: attachment; filename=terraform-aws-modules-terraform-aws-vpc-v2.21.0-0-gb76606e.tar.gz
X-Geo-Block-List:
Date: Thu, 09 Jan 2020 20:26:59 GMT
X-Varnish: 94485595 92572153
Age: 472
Via: 1.1 varnish-v4
Accept-Ranges: bytes
X-GitHub-Request-Id: C4A0:65D2:19BE:39AA:5E178E6C
```

doesn't work:
https://api.github.com/repos/terraform-aws-modules/terraform-aws-vpc/tarball/v2.21.0//*?archive=tar.gz 404s

```
15:34 $ curl -IL https://api.github.com/repos/terraform-aws-modules/terraform-aws-vpc/tarball/v2.21.0//*?archive=tar.gz
HTTP/1.1 302 Found
Server: GitHub.com
Date: Thu, 09 Jan 2020 20:35:10 GMT
Content-Type: text/html;charset=utf-8
Content-Length: 0
Status: 302 Found
X-RateLimit-Limit: 60
X-RateLimit-Remaining: 60
X-RateLimit-Reset: 1578605631
Cache-Control: public, must-revalidate, max-age=0
Expires: Thu, 09 Jan 2020 20:35:10 GMT
Location: https://codeload.github.com/terraform-aws-modules/terraform-aws-vpc/legacy.tar.gz/v2.21.0//*
Access-Control-Expose-Headers: ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type
Access-Control-Allow-Origin: *
Strict-Transport-Security: max-age=31536000; includeSubdomains; preload
X-Frame-Options: deny
X-Content-Type-Options: nosniff
X-XSS-Protection: 1; mode=block
Referrer-Policy: origin-when-cross-origin, strict-origin-when-cross-origin
Content-Security-Policy: default-src 'none'
X-GitHub-Request-Id: C4A1:32F1:434934:A2BE47:5E178E7E

HTTP/1.1 404 Not Found
Content-Length: 15
Access-Control-Allow-Origin: https://render.githubusercontent.com
Content-Security-Policy: default-src 'none'; style-src 'unsafe-inline'; sandbox
Strict-Transport-Security: max-age=31536000
Vary: Authorization,Accept-Encoding
X-Content-Type-Options: nosniff
X-Frame-Options: deny
X-XSS-Protection: 1; mode=block
Date: Thu, 09 Jan 2020 20:35:10 GMT
X-Varnish: 63742695
Age: 0
Via: 1.1 varnish-v4
X-GitHub-Request-Id: C4A2:35CE:3313:7166:5E178E7E
```

**Comment by akomlik** [comment]
It looks like other modules can not be downloaded either
`"https://api.github.com/repos/terraform-aws-modules/terraform-aws-autoscaling/tarball/v3.4.0//*?archive=tar.gz":`
`Error opening a gzip reader for /tmp/getter137776929/archive: EOF.`

**Comment by antonbabenko** [comment]
I think it is either related to GitHub service availability or Terraform bug which was fixed in 0.12.19 (released yesterday).

See my comment here for more details - https://github.com/terraform-aws-modules/terraform-aws-rds/issues/185#issuecomment-572072223

**Comment by akomlik** [comment]
Confirmed, upgrade to TF 0.12.19 resolves this problem
`Initializing modules...`
`Downloading terraform-aws-modules/vpc/aws 2.21.0 for vpc...`
`- vpc in .terraform/modules/vpc/terraform-aws-modules-terraform-aws-vpc-2417f60`

**Comment by martinsenabulele** [comment]
Error: Failed to download module

Could not download module "security-group"

**Comment by martinsenabulele** [comment]
C:\Users\User\Desktop\aws_services\main>terraform init
Initializing modules...
Downloading terraform-aws-modules/security-group/aws 3.7.0 for security-group...

Error: Failed to download module

Could not download module "security-group" (module.tf:1) source code from
"git::https://github.com/terraform-aws-modules/terraform-aws-security-group?ref=v3.7.0":
error downloading
'https://github.com/terraform-aws-modules/terraform-aws-security-group?ref=v3.7.0':
git must be available and on the PATH.


Error: Failed to download module

Could not download module "security-group" (module.tf:1) source code from
"git::https://github.com/terraform-aws-modules/terraform-aws-security-group?ref=v3.7.0":
error downloading
'https://github.com/terraform-aws-modules/terraform-aws-security-group?ref=v3.7.0':
git must be available and on the PATH.

**Comment by rajkumarta** [comment]
I am also getting the same above issue. Any solution is appreciated. 
Thanks

**Comment by akki-sap** [comment]
> https://api.github.com/repos/terraform-aws-modules/terraform-aws-vpc/tarball/v2.21.0?archive=tar.gz

this worked for me... but what does it do?

**Comment by akki-sap** [comment]
> > https://api.github.com/repos/terraform-aws-modules/terraform-aws-vpc/tarball/v2.21.0?archive=tar.gz
> 
> this worked for me... but what does it do?

NO, it didnt work...... any solution?

I am using:

module "vpc" {
  source  = "terraform-aws-modules/vpc/aws"
  version = "2.44.0"
.........

Error -->

rror: Failed to download module
│
│ Could not download module "vpc" (resources.tf:34) source code from
│ "git::https://github.com/terraform-aws-modules/terraform-aws-vpc?ref=v2.0.0": error downloading
│ 'https://github.com/terraform-aws-modules/terraform-aws-vpc?ref=v2.0.0': git.exe exited with 1: error launching git: The     
│ system cannot find the path specified.

**Comment by bryantbiggs** [comment]
I think its right there in your error message `git.exe exited with 1: error launching git`

**Comment by akki-sap** [comment]
thanks. but i have alreayd installed git and set environment variable PATH as well. Any suggestions?
