### ISSUE TITLE
Unable to Download Module from Registry

### ISSUE THREAD

**Issue by timbrammer** [terraform-aws-modules/terraform-aws-vpc#381]
```
module "vpc" {
      source  = "terraform-aws-modules/vpc/aws"
}
```

As of yesterday, using this module produces the following results when doing an init - 

```
Error: Failed to download module

Could not download module "vpc" (main.tf:15) source code from
"https://api.github.com/repos/terraform-aws-modules/terraform-aws-vpc/tarball/v2.21.0//*?archive=tar.gz":
Error opening a gzip reader for
/var/folders/rx/g2r7g1551q1d12_vskwrn9593nwb0x/T/getter145464997/archive: EOF.
```

Other modules download without issue.

Using TF 0.12.18 on OSX

**Comment by timbrammer** [comment]
Other modules are failing to download as well.

**Comment by antonbabenko** [comment]
Update Terraform to the latest and check this comment - https://github.com/terraform-aws-modules/terraform-aws-rds/issues/185#issuecomment-572072223
