### ISSUE TITLE
Create multiple VPCs using the module

### ISSUE THREAD

**Issue by jmukhtar** [terraform-aws-modules/terraform-aws-vpc#389]
Hi, I am a bit newbie on the module side of the terraform and it might be more information required as compared to issues. Apolgoies for that in advance

What i am trying to do is create 2 different VPCs using this module. Is it possible, and I am sure it's would you mind sharing some information to do it please?

**Comment by bryantbiggs** [comment]
hello @jmukhtar - yes it is possible. I would recommend you instantiate two module resources, one for each vpc you would like to create, in order to keep things simple. pseudocode example shown below:

```hcl
module "vpc1" {
  source = "terraform-aws-modules/vpc/aws"
  name = "simple-example1"
  cidr = "10.0.0.0/16"
  ...
}

module "vpc2" {
  source = "terraform-aws-modules/vpc/aws"
  name = "simple-example2"
  cidr = "10.1.0.0/16"
  ...
}
```

**Comment by bryantbiggs** [comment]
@antonbabenko we can close

**Comment by KhoaNPA** [comment]
Hi, I had the same problem but if I want to create 10 VPCs at the same time. Is there any function like 'for', or anything else?
Thank you.

**Comment by antonbabenko** [comment]
@KhoaNPA This feature should be available in the upcoming major release of Terraform 0.13.

**Comment by arashboustani** [comment]
Hi All, Is this feature available now after about 2+ years?

**Comment by antonbabenko** [comment]
@arashboustani See one solution above - https://github.com/terraform-aws-modules/terraform-aws-vpc/issues/389#issuecomment-578404430

And you can also use `for_each` in `module` block since Terraform 0.13.

**Comment by arashboustani** [comment]
@antonbabenko thanks for the quick reply. Do you have any example by any chance?

**Comment by arashboustani** [comment]
the pseudocode in the [comment#389](https://github.com/terraform-aws-modules/terraform-aws-vpc/issues/389#issuecomment-578404430) does not work for me!

`module "vpc1" {
  source  = "terraform-aws-modules/vpc/aws"
  version = "3.14.0"
  name = "dmz"
  cidr = "10.10.0.0/16"

  azs             = ["us-east-1a", "us-east-1b"]
  public_subnets  = ["10.10.1.0/24", "10.10.2.0/24"]
  private_subnets = ["10.10.3.0/24", "10.10.4.0/24"]


  enable_nat_gateway = true
  enable_vpn_gateway = true

  tags = {
    Name= "dmz"
    Terraform = "true"
    Environment = "dmz"
    Facing= "public"
  }
}
module "vpc2" {
  source  = "terraform-aws-modules/vpc/aws"
  version = "3.14.0"
  name = "production"
  cidr = "10.11.0.0/16"

  azs             = ["us-east-1a", "us-east-1b"]
  private_subnets = ["10.11.1.0/24", "10.11.2.0/24"]

  enable_nat_gateway = true
  enable_vpn_gateway = true

  tags = {
    Name= "production"
    Terraform = "true"
    Environment = "production"
    Facing= "private"
  }
}`

**Comment by arashboustani** [comment]
Well, the following works fine. sharing for future engineers.
```locals {
 vpc_list = {
   "dmz" = { 
    #    vpc_vpc_id = "dmz-net10"
       vpc_cidr = "10.10.0.0/16", 
       azs             = ["us-east-1a", "us-east-1b"]
       vpc_public_subnets  = ["10.10.1.0/24", "10.10.2.0/24"], 
       vpc_private_subnets = ["10.10.3.0/24", "10.10.4.0/24"], 
       vpc_enable_nat_gateway = true, 
       vpc_enable_vpn_gateway = true,
       vpc_tags = {
           Name= "dmz"
           Terraform = "true"
           Environment = "dmz"
           Facing= "public/private"
           }
       },
   "prod" = {
    #    vpc_vpc_id = "prod-net11"
       vpc_cidr = "10.11.0.0/16", 
       azs             = ["us-east-1a", "us-east-1b"]
       vpc_public_subnets  = [],
       vpc_private_subnets = ["10.11.1.0/24", "10.11.2.0/24"], 
       vpc_enable_nat_gateway = false, 
       vpc_enable_vpn_gateway = false,
       vpc_tags = {
           Name= "prod"
           Terraform = "true"
           Environment = "prod"
           Facing= "private"
           }
   },
   "stage" = {
    #    vpc_vpc_id = "stage-net12"
       vpc_cidr = "10.12.0.0/16", 
       azs             = ["us-east-1a", "us-east-1b"]
       vpc_public_subnets  = [],
       vpc_private_subnets = ["10.12.1.0/24", "10.12.2.0/24"], 
       vpc_enable_nat_gateway = false, 
       vpc_enable_vpn_gateway = false,
       vpc_tags = {
           Name= "stage"
           Terraform = "true"
           Environment = "stage"
           Facing= "private"
           }
   },
      "dev" = {
    #    vpc_vpc_id = "dev-net13"
       vpc_cidr = "10.13.0.0/16", 
       azs             = ["us-east-1a", "us-east-1b"]
       vpc_public_subnets  = [],
       vpc_private_subnets = ["10.13.1.0/24", "10.13.2.0/24"], 
       vpc_enable_nat_gateway = false, 
       vpc_enable_vpn_gateway = false,
       vpc_tags = {
           Name= "dev"
           Terraform = "true"
           Environment = "dev"
           Facing= "private"
           }
   },
 }
}

module "vpc" {
  source = "terraform-aws-modules/vpc/aws"
  version = "3.14.0"
  for_each = local.vpc_list
  name = each.key
  cidr =each.value.vpc_cidr
  azs = each.value.azs
  public_subnets  = each.value.vpc_public_subnets
  private_subnets = each.value.vpc_private_subnets
  enable_nat_gateway = each.value.vpc_enable_nat_gateway
  enable_vpn_gateway = each.value.vpc_enable_vpn_gateway
  tags = each.value.vpc_tags
}```

**Comment by bryantbiggs** [comment]
Don't do this, you're not gaining anything but complexity

**Comment by arashboustani** [comment]
@bryantbiggs what do you recommend? not using modules and simply use write the codes by myself?

**Comment by bryantbiggs** [comment]
Just use 4 independent module definitions

**Comment by arashboustani** [comment]
do you mean like my [previous comment](https://github.com/terraform-aws-modules/terraform-aws-vpc/issues/389#issuecomment-1112588415)

**Comment by natashachaika** [comment]
how to setup cidr_blocks to multiple vpcs create with for_each?
