### ISSUE TITLE
I don't get the reason of concat here.  

### ISSUE THREAD

**Issue by tayyaba21** [terraform-aws-modules/terraform-aws-vpc#393]
[what purpose does this concat serve here?](https://github.com/terraform-aws-modules/terraform-aws-vpc/blob/080faed258a8257a5a4e520a72dd20117b3730ec/main.tf#L287)

**Comment by antonbabenko** [comment]
Hi @malasami,

I thought that this should be for the reason that public subnets with just IPv6 can be created without specifying IPv4 CIDR blocks.

Well, this is probably not needed and can be removed.

Thanks for the report!
