### ISSUE TITLE
[Q] Question on how security group of a VPC can be retrieved before it gets created.

### ISSUE THREAD

**Issue by oonisim** [terraform-aws-modules/terraform-aws-vpc#397]
This is a re-post of [Terraform - why this is not causing circular dependency?](https://stackoverflow.com/questions/60348519/terraform-why-this-is-not-causing-circular-dependency) but if you could kindly help, please advise.

The example https://github.com/terraform-aws-modules/terraform-aws-vpc/blob/v2.21.0/examples/complete-vpc/main.tf has the code below.

It seemed to me there is a circular dependency but it just works. 

```
data "aws_security_group" "default" {
  name   = "default"
  vpc_id = module.vpc.vpc_id   # <----- Refer to VPC ID before it is created?
}

module "vpc" {
  source = "../../"

  name = "complete-example"

...
 # VPC endpoint for SSM
  enable_ssm_endpoint              = true
  ssm_endpoint_private_dns_enabled = true
  ssm_endpoint_security_group_ids  = [data.aws_security_group.default.id] # <-----  Not a circular dependency?
...
```

Kindly help understand why this work without causing circular dependency issue.

**Comment by DrFaust92** [comment]
If you look at it from a module perspective it does look like a circular dependency, but a module is just a convenient wrapper of multiple resources.

if you look at the graph of deps it would look like this in the case you are referring:

![Untitled Diagram (3)](https://user-images.githubusercontent.com/33663870/85208036-f5ff2880-b335-11ea-922e-2c06fb81d7a1.jpg)

**Comment by DrFaust92** [comment]
hey @oonisim, closing this issue. let me know if still having issues with this an reopen if needed
