### ISSUE TITLE
VPC module name changed in the migration which forces a teardown/rebuild of any VPCs

### ISSUE THREAD

**Issue by cmeisinger** [terraform-aws-modules/terraform-aws-vpc#4]
in https://github.com/terraform-aws-modules/terraform-aws-vpc/commit/97c5f73b13f4f67fa972203ebd228058c835db95 the module name changed from "mod" to "this."

As someone who is coming over from the old repo, this forces me to tear down all existing VPCs that utilize this module and rebuild for the change.

As a full break in backwards compat, I would consider this a bug.

**Comment by cmeisinger** [comment]
Are there any ideas on how to work around this?

**Comment by antonbabenko** [comment]
Yes, there is a lot of changes, not just in naming. This is a major release.

There is no automatic workaround about this other than update `tfstate` file using [terraform state mv](https://www.terraform.io/docs/commands/state/mv.html) commands.

Let me know if you need help doing this.

**Comment by cmeisinger** [comment]
So I worked through it and have updated the remote states.  All is well.

While my fixup example is specific to my use-case, I'm going to include the commands I ran (as of TF 0.10.6) for anyone else that runs into the same problems.

Also it's in my opinion you should REALLY make a mention of this somewhere between the two repos.  It's an absolute breakage in backwards compat for someone following the deprecation notice to this repository.

All in all though, thank you for putting this together.  I don't want to come off as crappy and negative, cause what you've done is pretty great.   Thanks for your work. :)

```terraform state mv module.vpc.aws_vpc.mod module.vpc.aws_vpc.this
terraform state mv module.vpc.aws_internet_gateway.mod module.vpc.aws_internet_gateway.this
terraform state mv module.vpc.aws_nat_gateway.natgw[0] module.vpc.aws_nat_gateway.this[0]
terraform state mv module.vpc.aws_nat_gateway.natgw[1] module.vpc.aws_nat_gateway.this[1]
terraform state mv module.vpc.aws_eip.nateip[0] module.vpc.aws_eip.nat[0]
terraform state mv module.vpc.aws_eip.nateip[1] module.vpc.aws_eip.nat[1]
```

**Comment by cmeisinger** [comment]
Plz mark as resolved/closed. :)

**Comment by antonbabenko** [comment]
Totally agree, so I will update README with details to upgrade.
