### ISSUE TITLE
database_route_table_tags: Name doesn't overwrite default

### ISSUE THREAD

**Issue by bazfire** [terraform-aws-modules/terraform-aws-vpc#406]
Using following in module "vpc" does not overwrite calculated Name tag:

  database_route_table_tags = {
    Name = "rt-db-simple-example"
  }

This works fine for public and private route tables but not for database route table. 
Believe it is the order of the maps in the merge on lines 184-191 in main.tf.  var.database_route_table_tags should be last allowing users wishes to rule.

**Comment by DrFaust92** [comment]
opened #458 to address this
