### ISSUE TITLE
Feature request: optional lifecycle

### ISSUE THREAD

**Issue by jgournet** [terraform-aws-modules/terraform-aws-vpc#408]
Hi there,

Thanks for the great module !

I saw a mention to that in another issue, so creating a specific ticket for that specific request:
Could we add an optional lifecycle property, at least in subnets ? (I guess it should be added mostly everywhere).
This would allow us to add:
```
resource "aws_vpc" "example" {
  # ... other configuration ...

  lifecycle {
    ignore_changes = [tags]
  }
}
```

Use case:
This is so we can add new kubernetes clusters, by adding new tags on the subnets, like:
kubernetes.io/cluster/my_cluster = "shared"

**Comment by antonbabenko** [comment]
Hi @jgournet !

`lifecycle` meta-arguments  is not possible to parametrize with variable (an error will be `Variables may not be used here.`), so it can't be part of the reusable module.

Closing this issue.

**Comment by dpiddockcmp** [comment]
Take a look at the `ignore_tags` and `ignore_tag_prefixes` "preview" options on the aws provider. It looks like they were implemented specifically for this common request:
https://www.terraform.io/docs/providers/aws/#ignore_tag_prefixes

**Comment by antonbabenko** [comment]
Very good point @dpiddockcmp !

**Comment by gswallow** [comment]
I knew of `ignore_tags` but didn't realize that it was a setting you change at the provider level until just now.  That is amazing.
