### ISSUE TITLE
Customer gateway is mandatory issue.

### ISSUE THREAD

**Issue by pratapcp** [terraform-aws-modules/terraform-aws-vpc#417]
Hi  i am trying to create VPC netwoking infrastructure. i amusing the version 2.21.0. Our infra doesnt need a customer gateway. But the module expecting the customer gateway variables . else throwing this error.
19:57:23  Error: Reference to undeclared resource
19:57:23  
19:57:23    on .terraform/modules/network.infra-vpc.vpc/main.tf line 998, in resource "aws_customer_gateway" "this":
19:57:23   998:   bgp_asn    = each.value["bgp_asn"]
19:57:23  
19:57:23  A managed resource "each" "value" has not been declared in
19:57:23  network.infra-vpc.vpc.

Request you to guide me on this.

**Comment by antonbabenko** [comment]
Hi @pratapcp !

Please double check that you are not specifying `customer_gateways` arguments into your `module` block.

If the problem persists show us the whole `module` block you use.

**Comment by bryantbiggs** [comment]
closing out for now, feel free to respond here with more context so we can better assist
