### ISSUE TITLE
TFE 12.2 with terraform-aws-vpc master - getting "for_each" error

### ISSUE THREAD

**Issue by johndesp** [terraform-aws-modules/terraform-aws-vpc#419]
We are using the master branch and TFE 12.2 and we are getting the "for_each" error. We don't get this error when running on TFE 12.21 . We can't upgrade to 12.21 yet.
Any ideas on how we can get around the following error?

The name "for_each" is reserved for use in a future version of Terraform.

thanks

JD

**Comment by dpiddockcmp** [comment]
`for_each` was added in TF 0.12.6. You must use 0.12.6 or later. Ideally much later as there were quite some interesting bugs in the early releases. I have no idea how this relates to TFE versions. 

Currently only one resource currently uses for_each: `aws_customer_gateway.this`. Two options here:
- the resource was added in 2.20.0 of the module. Pin your module definition to version 2.19.0
- if you need other changes added after 2.20.0, you can fork the module and remove the aws_customer_gateway resource locally

**Comment by johndesp** [comment]
Yep..I just figured that out as well..looking at versions.  Thanks so much. thanks.
