### ISSUE TITLE
Add ability to store VPC flow logs on S3

### ISSUE THREAD

**Issue by ToROxI** [terraform-aws-modules/terraform-aws-vpc#423]
I think it would be grate to have ability to store VPC flow logs on S3 out of the box.

**Comment by antonbabenko** [comment]
This feature is already supported. See examples in `examples/vpc-flow-logs/s3.tf`:

https://github.com/terraform-aws-modules/terraform-aws-vpc/blob/d9e7a6f871a02b13b5b89a8e126ea4092cd5b006/examples/vpc-flow-logs/s3.tf#L4-L21

**Comment by ToROxI** [comment]
@antonbabenko , I planed to implement this the same way as VPC Flow logs to CloudWatch and create RP.
Do you think this would be redundant functionality?

**Comment by antonbabenko** [comment]
I think VPC flow logs support in this module is already complete - it supports both saving to Cloudwatch Logs and S3 bucket (see examples).

What else do you think is missing?

**Comment by ToROxI** [comment]
Ok, I got your point. Sorry for disturbance!
Have a nice day!
