### ISSUE TITLE
S3 VPC Endpoint for public subnets

### ISSUE THREAD

**Issue by alexisgunst** [terraform-aws-modules/terraform-aws-vpc#427]
Hello there,

Can someone explain to me why S3 Endpoint is enabled for public subnets?
As far as I understand AWS, this is not necessary. Or at least, it should be an option.

Would it be possible to add an extra variable like `enable_public_s3_endpoint` ?

https://github.com/terraform-aws-modules/terraform-aws-vpc/blob/23b0a02d2a3225a05ddf5f31d9a32728bf5505c3/vpc-endpoints.tf#L32-L37

**Comment by DrFaust92** [comment]
I can open a PR to the `enable_public_s3_endpoint` flag with default to `true` not to break the module but the main reason to a VPC Endpoint in a public subnet is probably compliance/security
you can restrict access to bucket based on vpc endpoint id
