### ISSUE TITLE
VPC limit exceeded

### ISSUE THREAD

**Issue by Yukesh91** [terraform-aws-modules/terraform-aws-vpc#429]
Hi All,

   I tried creating vpc using VPC module in terraform. I used a region only one VPC is available. But I observed below error. Any ideas on this..??

VPC module
----------------------------------------------------
module "vpc" {
        version = "2.23.0"
        source = "terraform-aws-modules/vpc/aws"
        name = "${var.cluster_name}-vpc"
        cidr = var.vpc_cidr
        azs = ["${var.aws_region}a", "${var.aws_region}b"]
        private_subnets = var.private_subnets
        public_subnets = var.public_subnets
        enable_dns_hostnames = true
        enable_dns_support = true
        enable_nat_gateway = true
        one_nat_gateway_per_az = true
        #single_nat_gateway = true

        tags = "${merge(local.common_tags, map("Name", "${var.cluster_name}"))}"
}

----------------------------------------------------

Error observed:
----------------------------------------------------------
Error: Error creating VPC: VpcLimitExceeded: The maximum number of VPCs has been reached.
	status code: 400, request id: 9559ac7e-6c55-46ff-89ca-becbe10b30dd

  on .terraform/modules/vpc/terraform-aws-vpc-2.23.0/main.tf line 29, in resource "aws_vpc" "this":
  29: resource "aws_vpc" "this" {

Error: Error creating EIP: AddressLimitExceeded: The maximum number of addresses has been reached.
	status code: 400, request id: 678a0803-be58-4e9c-8bb4-03c3345390d8

  on .terraform/modules/vpc/terraform-aws-vpc-2.23.0/main.tf line 857, in resource "aws_eip" "nat":
 857: resource "aws_eip" "nat" {

Error: Error creating EIP: AddressLimitExceeded: The maximum number of addresses has been reached.
	status code: 400, request id: c232c962-74e3-4848-bf40-9713e3cc8205

  on .terraform/modules/vpc/terraform-aws-vpc-2.23.0/main.tf line 857, in resource "aws_eip" "nat":
 857: resource "aws_eip" "nat" {

---------------------------------------------------------

NOTE:
   * Currently only one vpc is allocated in that region.

**Comment by dpiddockcmp** [comment]
Everything in AWS has a limit. By default you are limited to 5 VPCs per region. See documentation about VPC limits: [here](https://docs.aws.amazon.com/vpc/latest/userguide/amazon-vpc-limits.html)

Create support tickets through the AWS console to request increases in your limits.

**Comment by akellehe** [comment]
I exceeded my quota and got this same error. I requested a quota increase, it went from pending -> completed and when I send a CLI request (via the aws cli) for my quota details it confirms I have a new quota of 10 (was 5). 

Before I requested the quota increase I only had 3 active VPCs, but was still getting this error. I hit 5 once ever (the limit before I requested an increase). So there's that.
