### ISSUE TITLE
Bespoke Private Routes

### ISSUE THREAD

**Issue by DanielJeyesMoon** [terraform-aws-modules/terraform-aws-vpc#436]
Hi guys,

We have been utlizing your module and now have a use case to add a private route to a transite gateway. From what I can see it does not look possible to add a bespoke private route, is this something you think that the module could benefit with?

Regards

Daniel

**Comment by rpatrick2282** [comment]
I would agree we are using a TGW and have need to add to the created route tables. It would be great if this were added

**Comment by dys152** [comment]
Agree with the above, we connect a Transit Gateway into the private subnets so being able to add routes using the module would be far easier.

**Comment by patricknazar** [comment]
Same, I need to add a route for VPC peering.

**Comment by bryantbiggs** [comment]
hi all, I think the route (no pun intended!) @patricknazar sounds like the best approach. this module has grown quite large and complex so we are very cautious now when taking on additional functionality. however, that said, we are always open for ideas/suggestions and the best way to demonstrate how you think this might work would be through a PR. thanks and looking forward to any input you may have!

**Comment by rgarrigue** [comment]
@bryantbiggs maybe provide an example for those cases ? It'll help peoples understanding the module limitation & save them time providing a solution

**Comment by bryantbiggs** [comment]
@rgarrigue PRs are always welcomed! we can't fully document all the use cases as it would get quite cumbersome, but if you know enough about Terraform you should be able to quickly identify that you can hook into the module and provide additional routes as needed
