### ISSUE TITLE
VPC Endpoint policy

### ISSUE THREAD

**Issue by brijshah** [terraform-aws-modules/terraform-aws-vpc#437]
I notice the module doesnt create a [policy](https://www.terraform.io/docs/providers/aws/r/vpc_endpoint.html#policy) for an endpoint. Is this something that will be added in a future release, or can be added?

**Comment by instantlinux** [comment]
Please escalate: I created internal support request [zendesk #32372](https://support.hashicorp.com/hc/requests/32372) which couldn't be resolved without creating code that would in essence be the PR to fix this.
