### ISSUE TITLE
Module Issues with AP-EAST-1

### ISSUE THREAD

**Issue by AaronForce1** [terraform-aws-modules/terraform-aws-vpc#439]
Module is not compatible with `ap-east-1`. 

**Reproduce Steps:**
1. Clone https://github.com/hashicorp/learn-terraform-provision-eks-cluster
2. Attempt to change `variable region` and `provider "aws"` to `ap-east-1` in `vpc.tf`, which uses the module "vpc".
3. Failure. However works correctly on any other region.

**Comment by antonbabenko** [comment]
Cold you share the whole plan and failure?

**Comment by DrFaust92** [comment]
@AaronForce1, is the region enabled in your account? according to https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/using-regions-availability-zones.html its not available by default.

**Comment by AaronForce1** [comment]
> @AaronForce1, is the region enabled in your account? according to https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/using-regions-availability-zones.html its not available by default.

Region is enabled. Had similar issues previously with certain ansible scripts too. Worried that it's not fully supported across aws automation tooling.

**Comment by bryantbiggs** [comment]
I wouldn't say the module isn't compatible but that the region isn't compatible for the services which you are trying to deploy, unfortunately not all regions are the same - especially with ap-east-1 which is operated by an AWS affiliate. if you do not object, I think we can close out this issue as there isn't much we will be able to do from a module perspective (not with at least seeing the full error output)
