### ISSUE TITLE
Add MSK client subnets

### ISSUE THREAD

**Issue by Stratouklos** [terraform-aws-modules/terraform-aws-vpc#442]
# Problem
MSK has specific [client subnet requirements](https://docs.aws.amazon.com/msk/1.0/apireference/clusters.html#clusters-prop-brokernodegroupinfo-clientsubnets) that are difficult to satisfy with generic `private_subnets`.

We need an easy mechanism to select 2 to 3 subnets in unique AZs other than `us-east-1e` and earmark them for MSK use.

# Proposed Solution
Add `msk_subnets` in the same way we have `elasticache_subnets` and `redshift_subnets`.

# Alternative solutions
Introduce a mechanism to add snet specific tags #259 
Generalize subnet config as maps as in #379 
Add AZ tags to all subnets by merging #426

**Comment by antonbabenko** [comment]
Hi @Stratouklos !

Thanks for opening this issue and proposing this feature.

I'd like to note that `elasticache_subnets` and `redshift_subnets` are special types of resources (a group of subnets organized as `aws_elasticache_subnet_group`, in case of elasticache).

In case of MSK, there is no need for a similar `subnet_group`-type of resource and aws_subnets should be created as normal `private_subnets`.

I also agree that we need to have support for more granular types of subnets (maybe within private_subnets or as a separate group with special needs for routes and routing tables). #379 and other PRs are still relevant.

**Comment by Stratouklos** [comment]
Closing, in hopes that one of the alternatives will soon be implemented and released. For now I solved this by having the MSK module manage it's own subnets.
