### ISSUE TITLE
vpc.aws_route_table_association missing output for depends_on dependency

### ISSUE THREAD

**Issue by digitalassembly** [terraform-aws-modules/terraform-aws-vpc#443]
Hi there,

First of all, thanks for putting together this module, it saves us a lot of time. 

We are having an issue when we setup a new resource that depends on routing tables associated by your module when we want to destroy our infrastructure. 

The issue is that prior we can delete our application resources, even though we have set a depends on the vpc.id , the vpc.aws_route_table_association.private and vpc.aws_route_table_association.public are deleted first, so all internal and external communication from and to our application is stopped which blocks us to terminate our applications accordingly.

We tried to find an output on your module that we could expose as "depends_on" for both vpc.aws_route_table_association.private and vpc.aws_route_table_association.public to our resource but it doesn't seem to exist yet.

**Comment by DrFaust92** [comment]
fixed by #398
