### ISSUE TITLE
Failure to apply complete-vpc on terraform cloud in aws

### ISSUE THREAD

**Issue by andrewhoplife** [terraform-aws-modules/terraform-aws-vpc#444]
I am using an unmodified main.tf in the complete-vpc example and I can get it to work when running locally but it fails when run on TF Cloud with the following error messages: 
 
Terraform v0.12.24
Configuring remote state backend...
Initializing Terraform configuration...
2020/05/12 22:43:44 [DEBUG] Using modified User-Agent: Terraform/0.12.24 TFC/aedd0bdf32
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.

------------------------------------------------------------------------

Error: expected "cidr_block" to contain a network Value with between 16 and 28 significant bits, got: 0

  on main.tf line 29, in resource "aws_vpc" "this":
  29: resource "aws_vpc" "this" {

Needless to say the cidr block is the defaults and is confirmed to be the same as my local runs. I created a TF support ticket who will be looking at this as well and will update if they provide any feedback. The initial feedback was that perhaps it has something to do with the this statement in the parent module.

**Comment by andrewhoplife** [comment]
I believe I found the source of this issue, closing.

**Comment by andrewhoplife** [comment]
Hashicorp got back to me to set the module path in the General tab of the Workspace and this fixed my issue. Sorry for the noise!

**Comment by aldegoeij** [comment]
> I believe I found the source of this issue, closing.

How did you fix it? 😇
