### ISSUE TITLE
feature request: allow disabling generation of igw

### ISSUE THREAD

**Issue by gwvandesteeg** [terraform-aws-modules/terraform-aws-vpc#446]
Use cases:

1) Internet traffic is routed via an Egress VPC via a transit gateway (for outbound content filtering), but there are still the distinction of a "public" and a "private" network inside the VPC.
2) Alternatively the traffic for the "public" network is routed via a DirectConnect (great way of bringing publicly routed IPs into your VPC onto the EC2 hosts without NAT involved).

Solution:
Leave the default behaviour as is but add an additional check to the igw creation to also check for `disable_igw_creation` (default of `false`).

**Comment by DrFaust92** [comment]
Hey @gwvandesteeg , im looking into add support for this feature. is this also relevant for the egress only igw?
