### ISSUE TITLE
Required variables not required

### ISSUE THREAD

**Issue by tscully49** [terraform-aws-modules/terraform-aws-vpc#452]
I could be wrong, but I think the documentation on https://registry.terraform.io/modules/terraform-aws-modules/vpc/aws/2.38.0 might be incorrect in relation to the variables it claims are "required".  It states a handful of variables are required, but if they are left out, the module still seems to run.  I'm assuming this would be an extremely quick update if they are incorrectly stated as required.

**Comment by antonbabenko** [comment]
Hi @tscully49 !

There is an issue in the Terraform Registry - https://github.com/hashicorp/terraform/issues/21417

We can't do anything about this in the module.
