### ISSUE TITLE
VPC Module failing Module.vpc.private_subnets is empty tuple

### ISSUE THREAD

**Issue by SunnyOswal** [terraform-aws-modules/terraform-aws-vpc#456]
Module Version: "2.39.0"
Terraform v0.12.26
+ provider.aws v2.66.0

For resource: aws_instance
  subnet_id              = module.vpc.private_subnets[0]

Error:
-----------------

on main.tf line 60, in resource "aws_instance" "web2":
60: subnet_id = module.vpc.private_subnets[0]
|----------------
| module.vpc.private_subnets is empty tuple

**Comment by antonbabenko** [comment]
Hi,

This module is not related to an error you have.

You can see some related examples here - https://github.com/terraform-aws-modules/terraform-aws-ec2-instance/blob/master/examples/basic/main.tf#L85

**Comment by SunnyOswal** [comment]
Thanks a lot. Below works fine:
subnet_id              = tolist(module.vpc.private_subnets)[0]
