### ISSUE TITLE
Error creating `module.vpc.module.vpc.aws_elasticache_subnet_group.elasticache`

### ISSUE THREAD

**Issue by yujunz** [terraform-aws-modules/terraform-aws-vpc#463]
```
1 error occurred:
	* module.vpc.module.vpc.aws_elasticache_subnet_group.elasticache: 1 error occurred:
	* aws_elasticache_subnet_group.elasticache: Error creating CacheSubnetGroup: InvalidParameterValue: The parameter CacheSubnetGroupName is not a valid identifier. Identifiers must begin with a letter; must contain only ASCII letters, digits, and hyphens; and must not end with a hyphen or contain two consecutive hyphens.
	status code: 400, request id: 73ef3146-adb3-4d30-94f5-5405c10a4457
```

We may need to normalize the name for elaticache subnet group

**Comment by bryantbiggs** [comment]
thanks @yujunz - however, I don't think we want to take on input validation in this module and modify inputs to meet the AWS API standards. there are a lot of inputs in this module that would fall under this category and instead I think its better left up to the users to ensure they provide the proper input. @antonbabenko / @DrFaust92 - thoughts?

**Comment by yujunz** [comment]
My use case is that we have a variable set as the basename for different types of resources. Given the facts, AWS has different restrictions on each, it must be transformed somewhere. 

I agree it can be done in user side. But what would be the downside to make it in module level?  @bryantbiggs

**Comment by bryantbiggs** [comment]
we would be adding unnecessary complexity to the module that is already rather complex and it goes against the declarative nature of terraform - users would not be aware that their naming conventions are in correct for the AWS API requirements (I haven't tested but this also may lead to diffs in each plan/apply for the name change)

**Comment by DrFaust92** [comment]
i agree with @bryantbiggs, this is a custom logic that should be handled on the user side
