### ISSUE TITLE
Inappropriate value for attribute "subnet_id": string required

### ISSUE THREAD

**Issue by Chaz0r** [terraform-aws-modules/terraform-aws-vpc#464]
Hey Guys, I get the following error while upgrading to Terraform 0.12.
My current Terraform version is 0.12.28, my AWS provider is 2.47.0.

After upgrading to 0.12 I got plenty of errors like **Inappropriate value for attribute "subnet_id": string required**
After looking through the issues here I was able to solve 99% of them with the flatten function. But I have 2 errors missing where it doesn't work:

My efs looks like this:
```
resource "aws_efs_mount_target" "ecs_efs_target" {
    count           = length(var.internal_subnet_ids)
    file_system_id  = aws_efs_file_system.main.id
    subnet_id       = flatten(var.internal_subnet_ids)
    security_groups = [aws_security_group.efs.id]
}
```
Here I get the error vor subnet_id and Terraform tells me that the value I place into subnet_id is a **list of tuple with 1 element**. The original value for this looks like this:
```
output "internal_subnets" {
  value = [aws_subnet.internal.*.id]
}
```

I place this value via my following module into the efs resource:

```
module "efs" {
  source              = "../stack/efs"
  environment         = module.stack.environment
  cluster             = module.stack.cluster
  internal_subnet_ids = module.stack.internal_subnets
  vpc_id              = module.stack.vpc_id
}
```

Any ideas how to fix that?

I get another error like this in my bastion. Here Terraform expects a string again but tells me it got **a tuple with 2 elements**. 
I wasn't able to completely figure out the origin value but the bastion instance itself looks like this:

```
resource "aws_instance" "bastion" {  
  ami                    = data.aws_ami.ubuntu.id  
  source_dest_check      = false  
  instance_type          = var.instance_type  
  subnet_id              = var.subnet_id  
  key_name               = var.key_name  
  vpc_security_group_ids = split(",", var.security_groups)  
  monitoring             = true  
  user_data              = data.template_file.cloud_config.rendered  
  
  tags = {  
    Name        = "bastion"  
    Environment = var.environment  
  }  
}
```

I will update if I figure out more details.

Any ideas how two fix those two issues?

**Comment by Chaz0r** [comment]
Fixed it. I head to pull the specific values out of the lists and tuples and then it worked.

**Comment by Aabhusan** [comment]
hello @Chaz0r 
I am also getting the same error of inappropriate value for the attribute subnet id: string required
actually, I am using data source "aws_subnet_ids" for getting the value of the subnet.

This is my code:
data "aws_vpc" "public" {
    default  = true
}

data "aws_subnet_ids" "public" {
  vpc_id = data.aws_vpc.public.id
  tags = {
    "Name" = "public-subnet-1"
  }
}

resource "aws_instance" "ec2_server" {
   
    ami             = "ami-09a6a7e49bd29554b"
    subnet_id   = flatten(data.aws_subnet_ids.public.ids)
    security_groups = [ aws_security_group.ec2_server_sg.id ]
    instance_type   = "t3a.small"
    key_name        = aws_key_pair.ec2_server.id
    associate_public_ip_address = true
    root_block_device {
      volume_type = "gp2"
      delete_on_termination = true
      volume_size   = 10
      
    }

    tags = {
      Name = "${var.stage}_ec2_server"
      key_name = aws_key_pair.ec2_server.id
       
    }
}

please help me

**Comment by antonbabenko** [comment]
@Aabhusan `flatten(data.aws_subnet_ids.public.ids)` returns a list, but `subnet_id` expects single string. If you need to create multiple instances, you can pass a list into `subnet_ids`.

**Comment by edikoston** [comment]
já eu fiz assim.
Obrigado @antonbabenko @Aabhusan

1º )
data "aws_vpc" "vpc_id" { }

2º )
data "aws_subnet_ids" "SUB_ID" {
  vpc_id = data.aws_vpc.vpc_id.id
} 


resource "aws_instance" "webserver" {
  count = 2
  ami                    = var.AMIS
  instance_type     = var.INSTANCE_TYPE
  key_name          = var.KEY_NAME
  user_data           = var.USER_DATA
  subnet_id           =  flatten(data.aws_subnet_ids.SUB_ID.ids)[count.index]
  security_groups = ["${aws_security_group.SG001.id}"]
  tags = {
    "Name" = "web-${count.index +1}"
  }
}
