### ISSUE TITLE
private_subnet_suffix and public_subnet_suffix do not work

### ISSUE THREAD

**Issue by juris** [terraform-aws-modules/terraform-aws-vpc#466]
I'm trying to use this module to create a VPC. Everything is working except suffixes for private/public subnets. Public and private subnets just get tags I've defined in locals section.
```
module "vpc" {
  source  = "terraform-aws-modules/vpc/aws"
  version = "v2.44.0"

  name = var.name

  cidr            = var.cidr
  azs             = var.azs
  private_subnets = var.private_subnets
  public_subnets  = var.public_subnets

  private_subnet_suffix = "int"
  public_subnet_suffix  = "ext"

  enable_dns_hostnames = true
  enable_dns_support   = true

  enable_nat_gateway = true
  single_nat_gateway = true

  tags = local.tags
}
```

```
➜ terraform version
Terraform v0.12.28
+ provider.aws v2.68.0
```

**Comment by gregmoy** [comment]
db and elasticache do not work either.

**Comment by gregmoy** [comment]
https://github.com/terraform-aws-modules/terraform-aws-vpc/pull/475

**Comment by DrFaust92** [comment]
Hey @gregmoy, does the `local.tags` map contains a tag with the key `Name` by any chance?

**Comment by gregmoy** [comment]
@DrFaust92 Yeah we were using the tags from https://github.com/cloudposse/terraform-null-label and it appears to include Name as one of the keys. 

It still doesn't make sense to let the tags override Name though. I can't think of a case where someone would want all of their assets named the same exact thing...

**Comment by DrFaust92** [comment]
I know we have some overrides in our implementation, i'll check and get back to you. you might be right and i'm missing something here.

**Comment by gugaiz** [comment]
If you are using the examples provided here, probably #495 will solve your issue

**Comment by nahueloyha** [comment]
Hi, I'm having this exact same issue, just created this [PR](https://github.com/terraform-aws-modules/terraform-aws-vpc/pull/712) that seems to solve it.
