### ISSUE TITLE
Tags for security group are not working 

### ISSUE THREAD

**Issue by sagar-jani** [terraform-aws-modules/terraform-aws-vpc#470]
I have a default security group configured as :
```
data "aws_security_group" "security_group" {
  name   = "default"
  vpc_id = module.home-protec-vpc.vpc_id
}
```

And tags are configured as :
 ```
default_security_group_tags = {
    AppName = "TestSG"
  }
```

But the tags are not created, is there something missing ?

**Comment by DrFaust92** [comment]
hey @sagar-jani, what version of the aws provider are you using?

**Comment by c0ntax** [comment]
@DrFaust92  I have this issue as well. My aws provider is  2.70.0 and this module's version is 2.44.0. I believe that this was also a bug for previous versions of both the provider and module.

**Comment by c0ntax** [comment]
Possibly related, but assigning `default_security_group_name` also seems to have no effect

**Comment by c0ntax** [comment]
Oops. Put this one down to user error on my part. I hadn't set `manage_default_security_group` to `true`. Ignore me. I shall go away now. ;-)

**Comment by sagar-jani** [comment]
Thanks @c0ntax , I have tried setting it to `manage_default_security_group`. But it gives me below error :
```
Error: Invalid dynamic for_each value

  on .terraform/modules/home-protec-vpc/terraform-aws-vpc-2.44.0/main.tf line 77, in resource "aws_default_security_group" "this":
  77:     for_each = var.default_security_group_egress
    |----------------
    | var.default_security_group_egress is null

Cannot use a null value in for_each.

Releasing state lock. This may take a few moments..
```

**Comment by DrFaust92** [comment]
see example usage from the complete example:

https://github.com/terraform-aws-modules/terraform-aws-vpc/blob/master/examples/complete-vpc/main.tf#L109-112

**Comment by DrFaust92** [comment]
Related https://github.com/terraform-providers/terraform-provider-aws/issues/14631

**Comment by trallnag** [comment]
I think such dependencies should be pointed out in the variables documentation

**Comment by bryantbiggs** [comment]
hi @trallnag - what dependencies should be called out? 

closing this out for now as this appears to be an upstream issue with the AWS provider
