### ISSUE TITLE
nat gatawey route in database route table gets added to private route table and deployment fails

### ISSUE THREAD

**Issue by rodrigoechaide** [terraform-aws-modules/terraform-aws-vpc#488]
When specifying the following option:

```
create_database_nat_gateway_route = true
```
I get the following error:

```
Error: Error creating route: RouteAlreadyExists: The route identified by 0.0.0.0/0 already exists.
        status code: 400, request id: 5d67eed5-683e-48bc-91e6-4c541c06de23

  on .terraform\modules\vpc\terraform-aws-vpc-2.44.0\main.tf line 958, in resource "aws_route" "private_nat_gateway":
 958: resource "aws_route" "private_nat_gateway" {
```

The same happens if I deploy the vpc with this option first:

```
create_database_nat_gateway_route = false
```

and then modify it and turn it into `true`:

```
create_database_nat_gateway_route = true
```

It seems that the module instead of adding the nat gateway route to the database route table it gets added to the private route table which by default already has a default route to the nat gateway. I have only experienced this deploying only one NAT gateway in the VPC. I have not tried with more than one NAT gateway.

**Comment by antonbabenko** [comment]
Hi @rodrigoechaide !

Such issue has been already fixed in https://github.com/terraform-aws-modules/terraform-aws-vpc/pull/476, please make sure that you are using version [v2.48.0](https://github.com/terraform-aws-modules/terraform-aws-vpc/releases/v2.48.0) of this module.

Closing this one.

**Comment by rodrigoechaide** [comment]
Hi @antonbabenko! Many thanks for the answer, I will update the module to version [v2.48.0 ](https://github.com/terraform-aws-modules/terraform-aws-vpc/releases/v2.48.0)
