### ISSUE TITLE
Create CodeDeploy VPC Endpoint resource

### ISSUE THREAD

**Issue by eliasbedmar** [terraform-aws-modules/terraform-aws-vpc#489]
On 11 Aug 2020, AWS released CodeDeploy VPC Endpoints ([announcement](https://aws.amazon.com/about-aws/whats-new/2020/08/aws-codedeploy-now-supports-deployments-to-virtual-private-cloud-endpoints/
)) which is currently not supported by this module.

**Comment by antonbabenko** [comment]
This feature has been added in #501 

[v2.50.0](https://github.com/terraform-aws-modules/terraform-aws-vpc/releases/v2.50.0) has been just released.
