### ISSUE TITLE
Module terraform requirements

### ISSUE THREAD

**Issue by sysadmiral** [terraform-aws-modules/terraform-aws-vpc#49]
This module requires terraform 0.10.13 but there is no corresponding version in the official download repository or on the terraform github release page.

This module should require version 0.11+ and only in the release of this module that introduces locals.

**Comment by FernandoMiguel** [comment]
someone posted about this earlier
https://github.com/terraform-aws-modules/terraform-aws-vpc/pull/48

**Comment by antonbabenko** [comment]
Fixed in [v1.12.0](https://github.com/terraform-aws-modules/terraform-aws-vpc/releases/tag/v1.12.0)
