### ISSUE TITLE
Add tag inputs for endpoints

### ISSUE THREAD

**Issue by Velgus** [terraform-aws-modules/terraform-aws-vpc#498]
It would be nice to be able to add additional tags to endpoint resources (ie. those created from `enable_s3_endpoint`, `enable_kms_endpoint`, `enable_dynamodb_endpoint`, etc.)

**Comment by DrFaust92** [comment]
Hey @Velgus there is the `vpc_endpoint_tags` variable to add tags to additional tags to all vpc endpoints.

**Comment by Velgus** [comment]
Thanks for the info. That definitely helps for the specific needs I have.

You may close the issue if that is considered sufficient for most people, but there may still be some value for being able to tag the different endpoint types on a more granular level.

**Comment by DrFaust92** [comment]
Thanks @Velgus, Closing this for now. When a specific use case is raises it can be discussed.
