### ISSUE TITLE
cannot create customer gateway without BGP asn

### ISSUE THREAD

**Issue by davidkarlsen** [terraform-aws-modules/terraform-aws-vpc#500]
I have a VPC where the customer gateways do not support BGP, hence no BGP ASN, which does not seem possible:

```
Error: Invalid index

  on .terraform/modules/core_networking/main.tf line 1054, in resource "aws_customer_gateway" "this":
1054:   bgp_asn    = each.value["bgp_asn"]
    |----------------
    | each.value is map of string with 1 element

The given key does not identify an element in this collection value.

Releasing state lock. This may take a few moments...
```

```
...
enable_vpn_gateway = true
  customer_gateways = {
    customer_gw_1 = var.cgw1
  }
```

```
variable "cgw1" {
  description = "on-prem customer gateway endpoint 1"
  default = {
    ip_address = "xxxx"
    # bgp_asn    = "65000"
  } 
}
```

**Comment by antonbabenko** [comment]
Hi @davidkarlsen !

`bgp_asn` - (Required) The gateway's Border Gateway Protocol (BGP) Autonomous System Number (ASN).

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/customer_gateway

Since `bgp_asn` is required, I don't know what we can do about it.

**Comment by davidkarlsen** [comment]
Doh - you are right. I also checked in the console where it is required too. Weird - but that's just how it is. Although I guess ppl prefer BGP anyways nowaday.

Sorry for the noise!
