### ISSUE TITLE
Modifying single_nat_gateway destroys existing nat gatway

### ISSUE THREAD

**Issue by dudicoco** [terraform-aws-modules/terraform-aws-vpc#506]
I've created a VPC with `single_nat_gateway=true`. When attempting to change to `single_nat_gateway=false` the plan shows the following:
```
  # module.vpc.aws_nat_gateway.this[0] must be replaced
-/+ resource "aws_nat_gateway" "this" {
      ~ allocation_id        = "eipalloc-xxxxx" -> (known after apply) # forces replacement
      ~ id                   = "nat-xxxx" -> (known after apply)
      ~ network_interface_id = "eni-xxxx" -> (known after apply)
      ~ private_ip           = "10.2.211.24" -> (known after apply)
      ~ public_ip            = "xx.xx.xx.xx" -> (known after apply)
        subnet_id            = "subnet-xxxx"
```
Since `module.vpc.aws_eip.nat[0]` has not been changed I would expect `module.vpc.aws_nat_gateway.this[0]` not to be changed as well.

This is related to the code here: https://github.com/terraform-aws-modules/terraform-aws-vpc/blob/master/main.tf#L934-L937

And here: https://github.com/terraform-aws-modules/terraform-aws-vpc/blob/master/main.tf#L906-L911

Any ideas?
Thanks

**Comment by DrFaust92** [comment]
Hey,

did you change to using multiple NATs? count is tricky and if that's the case it won't keep order when changing count.
If you have multiple NATs then the count of EIP also changed. we can assume order of these as well and that's probably why you get this result.

I can't verify this at the moment but that's my theory.

@antonbabenko I don't see a direct action item but it may ease the pain when upgrading to reduce downtime but adding `create_before_destroy` for NATs and EIPs to prevent downtime and network failures, WDYT?

**Comment by dudicoco** [comment]
@DrFaust92 thanks, i've ended up creating the other nat gateways manually and importing them into the state.
However, I imported the other nat gateways and EIPs into resources `[1]` and `[2]`, so i'm not sure this is related to count ordering.

**Comment by antonbabenko** [comment]
@DrFaust92 We need to be very careful with `create_before_destroy` for NAT gateways in particular when they reuse existing IP addresses (what IP will it use to a new NAT and to an old one?). It is not very trivial task yet, but can be much easier when we replace `count` with `for_each`.

I think there is not much we can do here from the current code point of view but we can document the procedure @dudicoco did (see previous comment).

**Comment by vavvolo** [comment]
Changing the NAT gateway config like below generates the right plan (the existing NAT gateway is not destroyed).

```
resource "aws_nat_gateway" "this" {
  count = var.create_vpc && var.enable_nat_gateway ? local.nat_gateway_count : 0

  allocation_id = element(
    var.reuse_nat_ips ? var.external_nat_ip_ids : aws_eip.nat.*.id,
    var.single_nat_gateway ? 0 : count.index,
  )
```

I tested this on Terraform 0.13.6

* create new VPC from scratch, 2 pub subnets, 2 private subnets, single NAT
* set `single_nat_gateway` to `false`
* set `single_nat_gateway` back to `true`
* destroy VPC

I suppose the original Terraform bug that required the `local.nat_gateway_ips` workaround is now fixed?

**Comment by MrAtheist** [comment]
Any updates on this...?

Im switching from single to multi NATGW setup and recreating `aws_nat_gateway.this[0]` would basically cease the outgoing traffic during which the apply is doing its thing. Also, is there a guarantee that the new NATGW[0] will be hooked up to `aws_eip.nat[0]`?

I have whitelisted `aws_eip.nat[0]` somewhere else and it's kinda not cool to have the traffic stopped... even for < 10 seconds. Is there a bool i can set to skip the destroy?

**Comment by m1keil** [comment]
Yep, I would document this. Going from:

```
  enable_nat_gateway     = true
  single_nat_gateway     = true
  one_nat_gateway_per_az = false
```

to:

```
  enable_nat_gateway     = true
  single_nat_gateway     = false
  one_nat_gateway_per_az = true
```

will cause an interruption of about 90-120 seconds due to the recreation of the existing single NAT gateway. This is still the case in the latest (v3.2.0).

**Comment by bryantbiggs** [comment]
hi all, this should be addressed in the next version which is under development here https://github.com/clowdhaus/terraform-aws-vpc-v4/tree/main/modules/subnets
