### ISSUE TITLE
Lambda VPC Endpoint

### ISSUE THREAD

**Issue by aiell0** [terraform-aws-modules/terraform-aws-vpc#533]
## Introduction
AWS recently accounced [PrivateLink support for Lambda](https://aws.amazon.com/blogs/aws/new-use-aws-privatelink-to-access-aws-lambda-over-private-aws-network/). This will add the endpoint so that it can be created through this module.

## Pull Request
https://github.com/terraform-aws-modules/terraform-aws-vpc/pull/534

**Comment by bryantbiggs** [comment]
thanks @aiell0 🎉 - closed by #534
