### ISSUE TITLE
Request - How To Create Custom Subnets

### ISSUE THREAD

**Issue by buddwm** [terraform-aws-modules/terraform-aws-vpc#539]
There doesn't appear to be a way to create a custom subnet with this module.  For example, we like to define our subnets as follows:

private_subnet
dns_private_subnet (for private DNS)
public_subnet
dns_public_subnet (for public DNS)

Is there any way we can define these types of subnets with this module, and if not, can this functionality be added?

**Comment by bryantbiggs** [comment]
hi @buddwm - unfortunately, no - not at the moment. this would be quite a large undertaking and a significant breaking change, but thats not to say its impossible nor out of the question either
