### ISSUE TITLE
Error: Failed to download module

### ISSUE THREAD

**Issue by jigneshpatel7** [terraform-aws-modules/terraform-aws-vpc#547]
Error: Failed to download module

Could not download module "vpc" (resources.tf:23) source code from
"git::https://github.com/terraform-aws-modules/terraform-aws-vpc?ref=v2.64.0":
error downloading
'https://github.com/terraform-aws-modules/terraform-aws-vpc?ref=v2.64.0': git
must be available and on the PATH.

Error: Failed to download module

Could not download module "vpc" (resources.tf:23) source code from
"git::https://github.com/terraform-aws-modules/terraform-aws-vpc?ref=v2.64.0":
error downloading
'https://github.com/terraform-aws-modules/terraform-aws-vpc?ref=v2.64.0': git
must be available and on the PATH.

**Comment by bryantbiggs** [comment]
hi @jigneshpatel7 - this looks like a local git issue not a module issue
