### ISSUE TITLE
Accessing private subnet id

### ISSUE THREAD

**Issue by mozinrat** [terraform-aws-modules/terraform-aws-vpc#55]
Was expecting to access private subnet id as $module.vpc.private_subnets.*.id, but its not working.
How should I be able to access the subnet id.

**Comment by antonbabenko** [comment]
You should be able to access them like this:

```hcl
module "my_application" {
  source = "./my_application"

  subnets = "${module.vpc.private_subnets}"
}

module "vpc" {
  source = "terraform-aws-modules/vpc/aws"

  name = "my-example"

  cidr = "10.10.0.0/16"

  azs             = ["eu-west-1a", "eu-west-1b", "eu-west-1c"]
  private_subnets = ["10.10.1.0/24", "10.10.2.0/24", "10.10.3.0/24"]
}
```

See [these outputs](https://github.com/terraform-aws-modules/terraform-aws-vpc/blob/master/examples/complete-vpc/outputs.tf#L8-L11) from examples.
