### ISSUE TITLE
stop using required_providers in versions.tf

### ISSUE THREAD

**Issue by jan-cipa** [terraform-aws-modules/terraform-aws-vpc#556]
please do not use *required_providers* block in versions.tf as it collides with terraform 0.13+ if you have required_providers set in top module (for example to use in-house providers) it complains 

> Error: Duplicate required providers configuration
>   on versions.tf line 4, in terraform:
>    4:   required_providers {
> 
> A module may have only one required providers configuration. The required
> providers were previously configured at main_providers.tf:4,3-21.

see https://github.com/hashicorp/terraform/issues/25364 for referrence.

**Comment by bryantbiggs** [comment]
hi @jan-cipa - my apologies but I do not quite follow. We set the min required versions so that users are aware of what versions are supported - this is a common practice.

**Comment by savar** [comment]
for the sake of documentation, see 
https://github.com/gruntwork-io/terragrunt/issues/1374#issuecomment-714602538
and
https://stackoverflow.com/a/66771271
to get an idea how to do that with terragrunt and terraform
