### ISSUE TITLE
Release EIP on destroy

### ISSUE THREAD

**Issue by chrislujan** [terraform-aws-modules/terraform-aws-vpc#557]
I noticed when I have the following configs enabled, the EIP for the nat gateway is not released upon destroying the vpc.

```
enable_nat_gateway = true
single_nat_gateway = true
one_nat_gateway_per_az = false
```

Am I overlooking a configuration? If not, this would be a nice feature to have.

**Comment by antonbabenko** [comment]
EIP is managed by this module and will be released on the deletion of the NAT gateway.

The problem is probably in something else.
