### ISSUE TITLE
No option in Terraform to put the Name for the VPC flow log

### ISSUE THREAD

**Issue by anjuls** [terraform-aws-modules/terraform-aws-vpc#558]
In the AWS console, I am getting an option to provide the name to my VPC flow log. It is not available in the Terraform yet.

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/flow_log

**Comment by antonbabenko** [comment]
Hi! You can set argument `vpc_flow_log_tags = { Name = "something" }`. It is already supported by the module.

**Comment by anjuls** [comment]
Ok. I think I am raising this issue in wrong repo . I'm looking for name attribute natively supported by AWS. We can do this by managing them through tags but that is not what I am looking for. 

Thank you, we can close this issue.
