### ISSUE TITLE
Im getting dms_endpoint error after upgrading module.

### ISSUE THREAD

**Issue by indreek** [terraform-aws-modules/terraform-aws-vpc#565]
Error: Invalid operand

  on .terraform/modules/vpc/vpc-endpoints.tf line 1538, in data "aws_vpc_endpoint_service" "dms":
1538:   count = var.create_vpc && var.dms_endpoint_subnet_ids ? 1 : 0

Unsuitable value for right operand: bool required.

**Comment by indreek** [comment]
most probably line 1538 should be 

```
count = var.create_vpc && var.enable_dms_endpoint ? 1 : 0
```

**Comment by antonbabenko** [comment]
Please use [v2.68.0](https://github.com/terraform-aws-modules/terraform-aws-vpc/releases/v2.68.0) instead.
