### ISSUE TITLE
AWS Managed Active Directory Support

### ISSUE THREAD

**Issue by kclinden** [terraform-aws-modules/terraform-aws-vpc#569]
How can this module be used when AWS Managed Active directory is also deployed and managed with Terraform? 

The DHCP Options need to be configured to be the AWS Managed AD Domain and DC ip addresses, but the VPC needs to exist first.

**Comment by bryantbiggs** [comment]
hi @kclinden - I would suggest:
1. Deploy your VPC with the default DHCP option set
2. Deploy your AWS Managed Active Directory
3. Update your VPC to use an updated DHCP option set that points to your new AD
