### ISSUE TITLE
S3 Endpoint Now Support Interface and Gateway

### ISSUE THREAD

**Issue by marcelobartsch** [terraform-aws-modules/terraform-aws-vpc#570]
Seems like AWS has release S3 endpoint with Gateway and Interface breaking the code in 
data "aws_vpc_endpoint_service" "s3" {
  count = var.create_vpc && var.enable_s3_endpoint ? 1 : 0

  service = "s3"
}

as it now returns:
Error: multiple VPC Endpoint Services matched; use additional constraints to reduce matches to a single VPC Endpoint Service

**Comment by andormarkus** [comment]
Open PR
https://github.com/terraform-aws-modules/terraform-aws-vpc/pull/573
https://github.com/terraform-aws-modules/terraform-aws-vpc/pull/572

**Comment by antonbabenko** [comment]
Fixed in #573 .

[v2.69.0](https://github.com/terraform-aws-modules/terraform-aws-vpc/releases/v2.69.0) has been just released.
