### ISSUE TITLE
AWS S3 Endpoints now support Interface type

### ISSUE THREAD

**Issue by eriepasquare** [terraform-aws-modules/terraform-aws-vpc#571]
It appears that AWS released (at least in our accounts) a second endpoint type for S3 Endpoints... until now S3 Endpoints only supported Gateway, but now they support an S3 endpoint of type Interface.  Because of this, the vpc module is throwing the following error:

Error: multiple VPC Endpoint Services matched; use additional constraints to reduce matches to a single VPC Endpoint Service

The data source for s3 endpoint needs to include an additional filter to ensure a single record is returned:

https://github.com/terraform-aws-modules/terraform-aws-vpc/blob/a78cee91b4a2c798c0bdabff1d48987bfd89ca25/vpc-endpoints.tf#L4-L8

Should now include:

```terraform
data "aws_vpc_endpoint_service" "s3" {
  count = var.create_vpc && var.enable_s3_endpoint ? 1 : 0

  service = "s3"
  service_type = "Gateway"
}
```

**Comment by rogersd** [comment]
Also related: https://github.com/terraform-aws-modules/terraform-aws-vpc/issues/445

**Comment by michaelhelmick** [comment]
@rogersd thanks for this. Literally, just had a colleague trying to implement something and came across this error. Will have him try it (judging by the 👍🏻) looks like it should work.

**Comment by vadanx** [comment]
Yep. This broke our pipelines. Exact same problem.

**Comment by 123BLiN** [comment]
yep, but fix does not work with old aws provider looks like?
```
Error: "service_type": this field cannot be set

  on .terraform/modules/vpc/vpc-endpoints.tf line 4, in data "aws_vpc_endpoint_service" "s3":
   4: data "aws_vpc_endpoint_service" "s3" {
```

**Comment by 123BLiN** [comment]
hey @antonbabenko minimal AWS provider version should be increased probably as well, but I've not discovered correct version yet, it is definetly doesn't work with 2.70 (see above)

**Comment by pib** [comment]
They added service_type in 3.10.0

**Comment by antonbabenko** [comment]
Good point, I will update the required version constraint now.

**Comment by antonbabenko** [comment]
#574 => [v2.70.0](https://github.com/terraform-aws-modules/terraform-aws-vpc/releases/v2.70.0) has been just released.

**Comment by dgonzalez** [comment]
So that means it is broken for providers prior to 3.10?

**Comment by antonbabenko** [comment]
Yes, data-source was not available in prior versions.

There are two workarounds we can have in the code:
1. Don't use data-source `aws_vpc_endpoint_service` but require users to provide [service_name](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/vpc_endpoint#service_name) explicitly.
2. Require users to create S3 VPC endpoint resources outside of the module if they can't upgrade to 3.10+.

PS: 3.10 has been released 5 months ago.

What do you think about this?

**Comment by dgonzalez** [comment]
sounds reasonable. Will need to look into our codebase as this can be tricky but...

**Comment by marpada** [comment]
@antonbabenko  thank you for being awesome!

**Comment by michaelhelmick** [comment]
> sounds reasonable. Will need to look into our codebase as this can be tricky but...

Agreed. Upgrading seems to be non-trivial, you will have to remove the VPC endpoint resource from Terraform code and the tfstate then apply changes, upgrade your Terraform version, fix any syntax issues, upgrade your AWS provider version, fix any issues and then re-add the VPC endpoint resource.

Also, not mentioned, looks like AWS provider 3.10 requires Terraform version >= 0.12.21

Hoping this helps anybody trying to figure out how to overcome this issue.

**Comment by dgonzalez** [comment]
It turns out it is a big issue for us. We have several third party modules and we are upgrading from terraform 12.x which is causing mayhem. We have elevated the request to AWS to remove the PrivateLink interface to S3 so we can plan again otherwise we are effectively blocked on the infrastructure side.

**Comment by dgonzalez** [comment]
I dont see any obvious option to remove the PrivateLink interface from the UI.

**Comment by dgonzalez** [comment]
Why do you need to remove the box endpoint and then readd it?
