### ISSUE TITLE
Error from AWS when planning

### ISSUE THREAD

**Issue by CaptainCuddleCube** [terraform-aws-modules/terraform-aws-vpc#576]
Hey all,
I'm pulling my hair out in frustration, and I don't know if anyone could help? 

I'm getting this error message:
```
Error: multiple VPC Endpoint Services matched; use additional constraints to reduce matches to a single VPC Endpoint Service

  on .terraform/modules/vpc/vpc-endpoints.tf line 4, in data "aws_vpc_endpoint_service" "s3":
   4: data "aws_vpc_endpoint_service" "s3" {
``` 

My environment:
```
Terraform v0.12.29
+ provider.aws v2.70.0
+ provider.random v3.0.1
+ provider.template v2.2.0
``` 

And I'm using `terraform-aws-modules/vpc/aws` version  "2.38.0"

**Comment by haidaraM** [comment]
See https://github.com/terraform-aws-modules/terraform-aws-vpc/issues/571 and update the module to 2.70 and aws provider to >= 3.10

**Comment by CaptainCuddleCube** [comment]
Thank you for the fast response! I missed the closed ticket!
