### ISSUE TITLE
 Error: multiple VPC Endpoint Services matched; use additional constraints to reduce matches to a single VPC Endpoint Service

### ISSUE THREAD

**Issue by e-moshaya** [terraform-aws-modules/terraform-aws-vpc#577]
AWS have just released a new feature in [S3 (PrivateLink)](https://aws.amazon.com/about-aws/whats-new/2021/02/amazon-s3-now-supports-aws-privatelink/) which means that multiple results are now being returned when searching for the S3 endpoint service.

Error: multiple VPC Endpoint Services matched; use additional constraints to reduce matches to a single VPC Endpoint Service

Singular data sources in the Terraform AWS Provider (like aws_vpc_endpoint_service) return an error if multiple results are returned.

data "aws_vpc_endpoint_service" "s3" {
  count = var.create_vpc && var.enable_s3_endpoint ? 1 : 0

  service_type = var.s3_endpoint_type
  service      = "s3"
}

```
Error: multiple VPC Endpoint Services matched; use additional constraints to reduce matches to a single VPC Endpoint Service
```

I have s3_endpoint_type set to the default "Gateway" and I'm not sure what other change is required to fix this.

**Comment by antonbabenko** [comment]
See #573 and #571 for more information. This issue hit many people during the last 24 hours.

**Comment by e-moshaya** [comment]
I can confirm the latest version v2.70.0 fixes this issue
