### ISSUE TITLE
Broken dependency since #574 - incorrect use of provider source for 0.12 versions of Terraform

### ISSUE THREAD

**Issue by DoctorPolski** [terraform-aws-modules/terraform-aws-vpc#578]
Hi,

#574 

This commit: https://github.com/terraform-aws-modules/terraform-aws-vpc/pull/574/files#diff-7a675c670d75c5377fab042389a1c31e147037138af03515f2d455e357aaef60

The above commit is fundamentally flawed. A provider source (in this case for AWS) cannot be supplied for versions of Terraform < 0.13 yet the constraint for the required version of Terraform still permits 0.12 versions of Terraform.

Anyone who depends on this resource who is still running a 0.12 version of Terraform will now find themselves with a broken implementation.

I suspect this was tested using a 0.13 version of Terraform. Try again with a 0.12 version to reproduce.

Thanks.

**Comment by antonbabenko** [comment]
According to the CHANGELOG for Terraform, this has became available since v0.12.20 - https://github.com/hashicorp/terraform/blob/v0.12/CHANGELOG.md#01220-january-22-2020 (related PR: https://github.com/hashicorp/terraform/pull/23843)

I ran the examples using the minimum required version of Terraform (0.12.21) before releasing it to verify that it was valid syntax.

Can somebody verify this also?

**Comment by DoctorPolski** [comment]
Take a look at this: https://www.terraform.io/docs/language/providers/requirements.html
Also this: https://www.terraform.io/docs/language/providers/requirements.html#v0-12-compatible-provider-requirements

The latter suggests the minimum Terraform version of v0.12.26 so that should probably be the minimum required_version, not v0.12.21 as per the commit.

After pushing our Terraform version up to v0.12.29 which overcame the above issue we hit another issue. For reasons of general local compatibility we had AWS provider pinned to >~ 3.0.0 in our root module - this was incompatible with ~> 3.1.0 as specified in your latest commit as these 2 constraints are mutually exclusive.

Yes we should probably be more up to date with our AWS Provider versioning but it is worth noting here.
