### ISSUE TITLE
No ElastiCache subnet group name output

### ISSUE THREAD

**Issue by jekstrom** [terraform-aws-modules/terraform-aws-vpc#58]
ElastiCache cluster has a `subnet_group_name` argument, but no `subnet_group_id` argument, so the output variable `elasticache_subnet_group` is not useful in this regard.

Should a `elasticache_subnet_group_name` output be added?

**Comment by antonbabenko** [comment]
I think you are right. We should export all available attributes.

PR is welcome (as usual) :)
