### ISSUE TITLE
How to Create a Secrets Manager VPC Endpoint Same Time As VPC?

### ISSUE THREAD

**Issue by johnsmith-coder** [terraform-aws-modules/terraform-aws-vpc#593]
Hi, I would like to use the terraform-aws-vpc module to create a new VPC with public, private and DB subnets along with a Secrets Manager VPC Endpoint with security group that allows the AWS Secrets Manager lambda to rotate the RDS password for any databases I will have deployed in the DB subnets. I have listed below a couple of the terraform-vpc-module input variables that are required to create the Secrets Manager VPC endpoint:

```
- secretsmanager_endpoint_security_group_ids   list(string)
- secretsmanager_endpoint_subnet_ids           list(string)
```

However I don't know how I can pass in a list of security group IDs or the list of DB subnet IDs as the VPC itself hasn't even been created yet. I can think of two possible solutions:

1. Try to get to do some sort of 'self' reference on the module itself, so that the DB subnets Ids that get created are then passed into the 'secretsmanager_endpoint_subnet_ids' input variable. However I've looked online and see that using 'self' inside a module doesn't seem possible.

2. Use the terraform-aws-vpc module twice. The first time to create the VPC with all the subnets and then use the outputs from that module to feed into a second terraform-aws-vpc module which is then used to create the Secrets Manager VPC endpoint.

Has anyone got any advice on this? Thanks.

**Comment by bryantbiggs** [comment]
hi @johnsmith-coder - please checkout the examples provided as they will demonstrate how you can achieve this https://github.com/terraform-aws-modules/terraform-aws-vpc/blob/9f859de5df1d9b8568f98bd01ca1548abc1f5e7d/examples/complete-vpc/main.tf#L59

**Comment by johnsmith-coder** [comment]
Thanks @bryantbiggs I understand now. Thanks again.
