### ISSUE TITLE
create resources on existing VPC?

### ISSUE THREAD

**Issue by encryptblockr** [terraform-aws-modules/terraform-aws-vpc#596]
can i use this module to create other resources in this module on existing VPC?

**Comment by antonbabenko** [comment]
You can, but only after you import the existing VPC as if it is created by this module.

**Comment by encryptblockr** [comment]
how do i import the vpc as it it is created by this module?

**Comment by encryptblockr** [comment]
i imported the vpc but it is still trying to create new vpc again

```
Import successful!

The resources that were imported are shown above. These resources are now in
your Terraform state and will henceforth be managed by Terraform.

Releasing state lock. This may take a few moments...
```

but still showing it will create new vpc in terraform plan

**Comment by antonbabenko** [comment]
Here is a good explanation on how to import resources in Terraform - https://www.terraform.io/docs/cli/import/index.html

Often the challenge is to figure out which resource to match to an existing resource, so you will have to run something like this:
```
terraform import "module.vpc.aws_vpc.this[0]" vpc-12345678
```

**Comment by antonbabenko** [comment]
Please ask questions related to the usage of Terraform on https://discuss.hashicorp.com/ or StackOverflow where much more users will be able to help.

**Comment by encryptblockr** [comment]
what is `this[0]` in your command?

```
terraform import "module.vpc.aws_vpc.this[0]" vpc-12345678
```

how do i import it into the vpc module to use? almost done please

**Comment by encryptblockr** [comment]
ok imported it into the vpc module but it is trying to destroy it and create new one
will appreciate your help with this

**Comment by encryptblockr** [comment]
why not make this module use existing vpc id? and just create resources on existing vpc???
