### ISSUE TITLE
Follow semantic versioning rules 

### ISSUE THREAD

**Issue by bluengreen** [terraform-aws-modules/terraform-aws-vpc#600]
Looks like there have been breaking changes over time to make this module compatible with new versions of terraform. However, there hasn't been a major release tag since 1.  Versions 2.0 and 2.73 will not run with the same version of terraform.  From the semantic versioning site - https://semver.org/

```
1. MAJOR version when you make incompatible API changes,
2. MINOR version when you add functionality in a backwards compatible manner, and
3. PATCH version when you make backwards compatible bug fixes.
```

Shouldn't the MAJOR version change when compatibility for new versions of tf are made? 

Thanks

**Comment by antonbabenko** [comment]
Most of the changes we were making in 2.x were backward compatible and can be disabled/enabled when certain values are provided.

That being said, if the user uses this module and specify the version as `=> 2.20` (for example) no new breaking changes to be added when a new feature is introduced in the module unless the user enables it.

There are also a few moving targets along the way, such as the version of Terraform and AWS provider which makes the process of following semver literally rather impractical.

We take BC breaks seriously and try to not merge changes where things may not require resource recreation for the existing customers. We try. :)
