### ISSUE TITLE
how to add multiple routes to multiple route tables

### ISSUE THREAD

**Issue by devikadesai** [terraform-aws-modules/terraform-aws-vpc#602]
i want to add a list of routes to all my 3 public route tables

**Comment by tbugfinder** [comment]
IMHO, you can use additional aws_route resources outside of this module but using this modules outputs.

**Comment by bryantbiggs** [comment]
hi all, this should be addressed in the next version which is under development here https://github.com/clowdhaus/terraform-aws-vpc-v4/tree/main/modules/subnets
