### ISSUE TITLE
Implementing `aws_network_acl_rule` with count causes rule deletions if order of rules change

### ISSUE THREAD

**Issue by 2stacks** [terraform-aws-modules/terraform-aws-vpc#612]
## Description

Inserting a new rule or changing rule order causes acls that haven't changed to be deleted and re-added.  Should use for_each instead of count.

**Comment by bryantbiggs** [comment]
hi all, this should be addressed in the next version which is under development here https://github.com/clowdhaus/terraform-aws-vpc-v4/tree/main/modules/subnets

**Comment by 2stacks** [comment]
Awesome thanks for the update.
