### ISSUE TITLE
Network Acls do not detect/correct changes 

### ISSUE THREAD

**Issue by directionless** [terraform-aws-modules/terraform-aws-vpc#616]
## Description

I'm not sure if this is considered a bug, or an artifact of how the system is designed.

I noticed that if I create a network acl rule in the web console, terraform does not notice and remove it. I would guess this is because the underlying implementation is via `aws_network_acl_rule` and not `acl_network_acl`. 

## Versions

```
$ terraform -version
Terraform v0.14.8
+ provider registry.terraform.io/hashicorp/aws v3.33.0

$ terraform providers -version
Terraform v0.14.8
+ provider registry.terraform.io/hashicorp/aws v3.33.0

$ cd .terraform/modules/vpc && git rev-parse HEAD && git describe --all --always
cb96e06e21621bf71619677f6cfa2a44f898ec16
tags/v2.77.0
```

## Reproduction

1. Use module to create VPC
2. Add rule in the web console
3. run `terraform`
4. Rule from (2) is not detected for removal

## Expected behavior

I expect terraform to see the change in the network acl, and repair it. 

## Actual behavior

Terraform does not see the newly created rule

**Comment by antonbabenko** [comment]
Hi,

Your observation is absolutely right. Such changes won't be detected by this module because we manage rules using `aws_network_acl_rule` resources.

Currently, there is no way to allow this for both group of cases (some users want to manage resources externally and don't enforce those rules).

**Comment by directionless** [comment]
I don't know if it fits how you want to develop this, but maybe one possibility is to pass in an `acl_network_acl`

**Comment by antonbabenko** [comment]
See a note at the top on the documentation for [resource aws_network_acl](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/network_acl).
