### ISSUE TITLE
How to do vpc peering for VPC created by this module?

### ISSUE THREAD

**Issue by bangau1** [terraform-aws-modules/terraform-aws-vpc#617]
This is not a bug report or feature request, but I want to ask advice/direction on how to create VPC Peering from VPC created from this module?

I have tried, it seems we need a way to put a routing rule in each subnet's route table to connect to certain peering connection. But I don't see the option to do so in this module.

**Comment by antonbabenko** [comment]
This module creates VPC (one or several) which can then be specified as arguments for another [vpc-peering module by @gream11n](https://github.com/grem11n/terraform-aws-vpc-peering).
