### ISSUE TITLE
Support routing with AWS GWLB (ingress traffic)

### ISSUE THREAD

**Issue by tbugfinder** [terraform-aws-modules/terraform-aws-vpc#620]
VPCs which require a Gateway Load Balancer Setup for ingress traffic cannot be setup with this module.

Ingress traffic to the / from public subnets have to pass the Gateway Loadbalancer Endpoint (GWLBe). This route has to be setup specifically as default. It cannot be the IGW directly.

https://github.com/terraform-aws-modules/terraform-aws-vpc/blob/997cba4053bd8b4a5d2aed528073b8f02c013e93/main.tf#L218

**Comment by vvedran** [comment]
I didn't use vpc module because of lack of control on subnet creation, now I need to add GWLB with IGW ingress routing so did you found some solution or workaround
?

**Comment by tbugfinder** [comment]
Only not using the module.

**Comment by frankscalzo** [comment]
Im looking at same thing but using AWS NFW which uses GLB as well the other issues are that the route tables go across the tier and needs to go down the AZ in order to redirect traffic over the VPCE

**Comment by bryantbiggs** [comment]
hi all, this should be addressed in the next version which is under development here https://github.com/clowdhaus/terraform-aws-vpc-v4/tree/main/modules/subnets
