### ISSUE TITLE
Support routing with AWS GWLB (egress traffic)

### ISSUE THREAD

**Issue by tbugfinder** [terraform-aws-modules/terraform-aws-vpc#621]
This module cannot be used for creating a VPC which builds a "security VPC" incl. NAT-GW and Gateway Loadbalancer (GWLB) setup.

The route cannot be changed to the GWLBe instead of the NAT-GW.

https://github.com/terraform-aws-modules/terraform-aws-vpc/blob/997cba4053bd8b4a5d2aed528073b8f02c013e93/main.tf#L242

**Comment by tbugfinder** [comment]
keep

**Comment by bryantbiggs** [comment]
FYI - this is being looked into for v4 https://github.com/clowdhaus/terraform-aws-vpc-v4
