### ISSUE TITLE
Add tag merge support for aws_route private / public nat_gateway

### ISSUE THREAD

**Issue by damianoneill** [terraform-aws-modules/terraform-aws-vpc#622]
## Is your request related to a new offering from AWS?
I believe so.  Though I'm not familiar with the details of the provider.  I'm pretty new to Terraform.

## Is your request related to a problem? Please describe.
I believe this will make the module consistent.

## Describe the solution you'd like.
The module currently supports additional tags for resources that get created, e.g. nat_gateway_tags.  Would be good to get this feature replicated for aws_route.private_nat_gateway[*] and aws_route.public_nat_gateway[*].

## Describe alternatives you've considered.
No additional context.

## Additional context
Extend 

```console
resource "aws_route" "private_nat_gateway" {
  count = var.create_vpc && var.enable_nat_gateway ? local.nat_gateway_count : 0

  route_table_id         = element(aws_route_table.private.*.id, count.index)
  destination_cidr_block = "0.0.0.0/0"
  nat_gateway_id         = element(aws_nat_gateway.this.*.id, count.index)

  timeouts {
    create = "5m"
  }
}
```

With a tags = merge {..} section.

Repeat for public_nat_gateway resource. 

Thanks,
Damian.

**Comment by damianoneill** [comment]
@bryantbiggs sorry for pulling you into the issue, you were the last module contributor to respond to an issue.  

Looking at all the issues that are getting raised, there are next to no responses for the last two months.  Is this module still supported?  

Thanks, sorry again for adding you directly, Damian.

**Comment by antonbabenko** [comment]
Hi Damian, `tags` are not supported on `aws_route` resources by Terraform/AWS. See [this](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/route).

PS: This module is still actively maintained. See [CHANGELOG](https://github.com/terraform-aws-modules/terraform-aws-vpc/blob/master/CHANGELOG.md).

**Comment by damianoneill** [comment]
Thanks @antonbabenko appreciate the update.
