### ISSUE TITLE
Subnets without a routing table association 

### ISSUE THREAD

**Issue by yossi-r** [terraform-aws-modules/terraform-aws-vpc#624]
## Is your request related to a problem? Please describe.
Trying to use this module in concert with other orchestration tool that needs to control a subnet routing table and association. 
i couldn't find a subnet that doesn't have a routing table associated to it so every time the module runs it will override the changes coming from the other orchestrator.

## Describe the solution you'd like.
create a "simple_subnet" that doesn't have a routing table and a routing table association. 
that way i have more control over routing outside the module.

## Describe alternatives you've considered.
right now i'm using the aws_subnet_resource instead of creating those subnets with the module. 

## Additional context
This is for scenarios that include GWLB and multi-vpc networking with overlapping ip addresses.

**Comment by antonbabenko** [comment]
Hi Yossi,

You are right, there is no way to create a subnet without route_table and route_table_association.

I don't think we will be updating the module to support the partial creation of these resources in the near future because it is a rather custom case.
