### ISSUE TITLE
Add support for default_tags in provider

### ISSUE THREAD

**Issue by antonbabenko** [terraform-aws-modules/terraform-aws-vpc#625]
## Is your request related to a new offering from AWS?

`default_tags` in provider were introduced in v3.33.0 - https://github.com/hashicorp/terraform-provider-aws/pull/17974

## Is your request related to a problem? Please describe.

There are several related issues:
https://github.com/hashicorp/terraform-provider-aws/issues/18311
https://github.com/hashicorp/terraform-provider-aws/issues/18366

## Describe the solution you'd like.

Unsure. Some research is required.

**Comment by yermulnik** [comment]
+ https://github.com/terraform-aws-modules/terraform-aws-vpc/issues/625

**Comment by eriepasquare** [comment]
I know the description is still "Unsure. Some research is required" but was hoping to gain some momentum by highlighting this proposed work-a-round in the original provider issue:

https://github.com/hashicorp/terraform-provider-aws/issues/19204#issuecomment-878129327

This vpc module is the last module preventing my company from utilizing the `default_tags` feature of the AWS Provider.

**Comment by bgaillard** [comment]
I also encountered problems using `default_tags` with this module.

```bash
╷
│ Error: 1 error occurred:
│       * "tags" are identical to those in the "default_tags" configuration block of the provider: please de-duplicate and try again
│
│
│
│   with module.vpc.aws_vpc.this[0],
│   on .terraform/modules/vpc/main.tf line 25, in resource "aws_vpc" "this":
│   25: resource "aws_vpc" "this" {
│
╵
```

Here is the workaround I used to fix the problem.

```hcl
locals {
    default_tags = {
        DefaultTag1 = "value1"
        DefaultTags2 = "value2"
    }
}

# AWS provider to use everywhere except with the 'terraform-aws-vpc' module.
provider "aws" {
  default_tags {
    tags = local.default_tags
  }
}

# AWS provider to be used with the 'terraform-aws-vpc' module to prevent an error with 'default_tags'.
#
# see https://github.com/terraform-aws-modules/terraform-aws-vpc/issues/625
provider "aws" {
  alias  = "vpc"
}

module "vpc" {
  source  = "terraform-aws-modules/vpc/aws"
  version = "3.7.0"

  ...

  public_subnet_tags = merge(
    local.default_tags,
    {
      "PublicSubNetTag1" = "xxxx"
    }
  )

  private_subnet_tags = merge(
    local.default_tags,
    {
      "PrivateSubnetTag1" = "xxxx"
    }
  )

  tags = local.default_tags

  providers = {
    aws = aws.vpc
  }
}
```

Hope this helps.
