### ISSUE TITLE
Outputs for subnets and route tables are not well suited for use with for_each

### ISSUE THREAD

**Issue by cryptk** [terraform-aws-modules/terraform-aws-vpc#628]
## Is your request related to a new offering from AWS?
No

## Is your request related to a problem? Please describe.
The various subnet/route_table outputs are purely lists of IDs, which are not knowable until after the apply has run.  This results in them being poorly suited for use in a resource that makes use of the for_each functionality (the key should be something that is computable before the apply, the values can be unknown until after apply).  This results in errors such as the following if you attempt to do a for_each using, for example, one of the subnet arn outputs.

```
Error: Invalid for_each argument

  on modules/workload_vpc/subnet_share.tf line 112, in resource "aws_ram_resource_association" "database_subnets":
 112:   for_each = toset(module.vpc.database_subnet_arns)

The "for_each" value depends on resource attributes that cannot be determined
until apply, so Terraform cannot predict how many instances will be created.
To work around this, use the -target argument to first apply only the
resources that the for_each depends on.
```

## Describe the solution you'd like.
The module should output a proper map for the elements where the key is something that is computable before the apply (I would recommend either the CIDR block or the value of the Name tag for naming the subnet keys and the value of the Name tag for the route table

## Describe alternatives you've considered.
Currently I am having to do a two-stage apply where first I apply just this VPC module and then after that I can pull data sources based on the existing subnet ids and subnet arns resources to then iterate over in a resource using a for_each loop

## Additional context
I am more than happy to write the PR for this change as I have already tested it locally and it's pretty simple to accomplish.  Stand by for an incoming PR.

**Comment by antonbabenko** [comment]
Thanks for opening this one.

I am not completely sure when we will be able to finish a conversion from `list` to `map` but it is certainly on our radar.

#403 is an umbrella issue, so I will close this one.

**Comment by cryptk** [comment]
@antonbabenko That issue is not the same as what I have reported here.  That issue is relating to how the module internally manages subnets by using counts rather than for_each.  This issue is about the outputs from this module not being properly suited for other code too reference the data coming from this module in a separate (not inside this module) for_each.

I would appreciate this issue being re-opened as it is not the same as #403

**Comment by cryptk** [comment]
@antonbabenko I have submitted PR#629 to fix this issue
