### ISSUE TITLE
Tagging aws_eip under terraform v0.11.2

### ISSUE THREAD

**Issue by pete0emerson** [terraform-aws-modules/terraform-aws-vpc#63]
I just did an upgrade from terraform v0.10.7 to v0.11.2.

In doing so, I did a `terraform init` that pulled in v1.17.0 of the module.

Running a `terraform plan` gave me:

`Error: module.vpc.aws_eip.nat: : invalid or unknown key: tags`

Rolling back to terraform v0.10.7 (but keeping v.1.17.0 of the module) allows `terraform plan` to run cleanly.

Commenting out the change made in 928df804afcff5994524684fba07f326c85a0aac and running it with either version of terraform also works.

Have I missed a piece of migration in going from an older terraform version, or is there still a problem with aws_eip tagging, something along the lines of https://github.com/terraform-community-modules/tf_aws_vpc/issues/29 ?

Or perhaps there is a regression in terraform itself? Not quite sure where the problem lies (and admit that the true problem may be a PEBKAC on my part).

**Comment by antonbabenko** [comment]
Pete, make sure to use newer AWS provider as [described here](https://github.com/terraform-aws-modules/terraform-aws-vpc/issues/62#issuecomment-359549341).
