### ISSUE TITLE
Possible doc bug

### ISSUE THREAD

**Issue by kiemlicz** [terraform-aws-modules/terraform-aws-vpc#636]
## Description
https://github.com/terraform-aws-modules/terraform-aws-vpc#one-nat-gateway-per-subnet-default
States `Then 5 NAT Gateways will be created since 5 private subnet CIDR blocks were specified.`

However `intra` should not count. So shoudn't it be 4?

**Comment by antonbabenko** [comment]
There are 5 private_subnets, so it should make 5 NATs.
