### ISSUE TITLE
Terraform Registry - Provision Instructions are incorrect for this module

### ISSUE THREAD

**Issue by thpang** [terraform-aws-modules/terraform-aws-vpc#637]
## Description

Terraform registry [page](https://registry.terraform.io/modules/terraform-aws-modules/vpc/aws/latest) states the need for 52 required variables and not one is listed as required in the inputs table.

### Code Snippet to Reproduce

Provision Instructions
Copy and paste into your Terraform configuration, insert the variables, and run terraform init :

```
module "vpc" {
  source  = "terraform-aws-modules/vpc/aws"
  version = "2.78.0"
  # insert the 52 required variables here <--- Line that needs adjusting
}
```

## Expected behavior

In the provision instructions a list of actual required fields and an update to the inputs table correctly identifying the required fields

## Actual behavior

In the provision instructions the list states there are 52 required variables and no inputs are designated as required in the inputs table.

### Terminal Output Screenshot(s)

![image](https://user-images.githubusercontent.com/32514746/115870946-ef39ba00-a40d-11eb-90fe-de8834ee87f6.png)

**Comment by antonbabenko** [comment]
This issue belongs to Terraform - https://github.com/hashicorp/terraform/issues/21417
