### ISSUE TITLE
Should EIP be deleted when destroying VPC?

### ISSUE THREAD

**Issue by mhumeSF** [terraform-aws-modules/terraform-aws-vpc#64]
Wanted to know why they might get left behind after `tf destroy`

**Comment by antonbabenko** [comment]
Normally, when EIP is created by this module it will be deleted as well. Here is the code - https://github.com/terraform-aws-modules/terraform-aws-vpc/blob/master/main.tf#L201-L207

If you pass `external_nat_ip_ids` to reuse existing EIPs they won't be managed by Terraform and will persist after VPC is deleted.

**Comment by mhumeSF** [comment]
I think I was having issues with terragrunt. This is working as you described and EIPs are created and destroyed correctly.

**Comment by felimartina** [comment]
In my case the EIPs are not deleted unless I run the `terraform destroy` command a second time. This is, the first time I run `terraform destroy` I will get the following error:
```
aws_eip.nat.0: AuthFailure: You do not have permission to access the specified resource.
        status code: 400, request id: b8264134-37f9-487a-a59c-07c0f2f5ccb1
* module.vpc.aws_eip.nat[0] (destroy): 1 error(s) occurred:
```

one of those errors for each EIP that was created by the module. Thoughts?

**Comment by antonbabenko** [comment]
It is likely to be [this issue](https://github.com/terraform-providers/terraform-provider-aws/issues/2968) and it was fixed in [AWS provider version 1.7.1](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#171-january-19-2018)

**Comment by felimartina** [comment]
Ohhh i see! thank you @antonbabenko!

**Comment by JoostSaanen** [comment]
Tested with Terraform version:
`0.11.0 and 0.11.7`

my vpc.tf looks like:

```
resource "aws_eip" "nat" {
  count = 1
  vpc = true
}

module "vpc" {
  source = "terraform-aws-modules/vpc/aws"
  name   = "${var.application}"
  cidr   = "10.0.0.0/16"

  azs             = ["eu-west-2a", "eu-west-2b"]
  private_subnets = ["10.0.1.0/24", "10.0.2.0/24"]
  public_subnets  = ["10.0.101.0/24", "10.0.102.0/24"]

  enable_nat_gateway  = true
  single_nat_gateway  = true
  reuse_nat_ips       = true

  external_nat_ip_ids = ["${aws_eip.nat.*.id}"]

  tags = {
    Environment = "${var.env}"
    Terraform   = "true"
    Client      = "${var.client}"
  }
}
```

When I do `terraform apply` a new EIP is created – like expected. But when I do a `terraform destroy` the EIP is deleted.  Is there something wrong in my config? I can't get my head around it.
