### ISSUE TITLE
Add service_type ad a required variable on vpc endpoint module

### ISSUE THREAD

**Issue by vianel** [terraform-aws-modules/terraform-aws-vpc#642]
## Is your request related to a new offering from AWS?
No

## Is your request related to a problem? Yes.
Trying to create a dynamodb endpoint without specifying the `service_type` like this
```
    dynamodb = {
      # gateway endpoint
      service         = "dynamodb"
      route_table_ids = flatten([module.sftp_vpc.intra_route_table_ids, module.sftp_vpc.private_route_table_ids, module.sftp_vpc.public_route_table_ids])
      tags = merge(
        {
          "Name" = "dynamodb-vpc-endpoint"
        },
        local.tags,
      )
    },
```

it will return with an error response `no matching VPC Endpoint Service found` 

Adding the service type like this 
```
    dynamodb = {
      # gateway endpoint
      service         = "dynamodb"
      service_type    = "Gateway"
      route_table_ids = flatten([module.sftp_vpc.intra_route_table_ids, module.sftp_vpc.private_route_table_ids, module.sftp_vpc.public_route_table_ids])
      tags = merge(
        {
          "Name" = "dynamodb-vpc-endpoint"
        },
        local.tags,
      )
    },
```
it works successfully

## Describe the solution you'd like.
A default value for service_type or a detailed error message.

**Comment by antonbabenko** [comment]
You need to specify `service_type` which is required for some VPC endpoints. There is nothing we can do in this module.
