### ISSUE TITLE
[FEATURE] Manage flow logs for default vpc

### ISSUE THREAD

**Issue by KevinLoganBS** [terraform-aws-modules/terraform-aws-vpc#645]
When managing the default VPC. It doesn't look like other options take effect (i.e. enable_flow_log).

For VPC flow logs specifically, it looks to be because `enable_flow_log ` only calls out `var.create_vpc`
https://github.com/terraform-aws-modules/terraform-aws-vpc/blob/73b447ff1d6d6b7bda2adf45ccfba6ae9cd1d832/vpc-flow-logs.tf#L3 

I think if it were updated to something along the lines of:
``` terraform
manage_vpc       = var.create_vpc || var.manage_default_vpc
enable_flow_log = local.manage_vpc && var.enable_flow_log
```
Then it would "just work" ™️ .

I'm happy to submit a PR for it, but wasn't sure if this was intentional or not. This also impacts other resources, but I'm not sure if those are intentional as well.

**Comment by DrFaust92** [comment]
Hi @KevinLoganBS feel free to submit a PR for this functionality. i would avoid making any braking change but would introduce a new flag and resources dedicated for default vpc. (i.e. enable_default_vpc_flow_log)
