### ISSUE TITLE
Modifcation to desing VPC for use with NFW

### ISSUE THREAD

**Issue by frankscalzo** [terraform-aws-modules/terraform-aws-vpc#652]
sorry maybe the wrong spot but has there been a fork for modifying VPC flow to incorporate AWS Network Firewalls since the modification of the vpc is needing extra Subnets?

**Comment by antonbabenko** [comment]
I agree, this is the wrong place to ask. You can take a look at the official Terraform Registry or ask on [discuss.hashicorp.com](https://discuss.hashicorp.com).

**Comment by frankscalzo** [comment]
> I agree, this is the wrong place to ask. You can take a look at the official Terraform Registry or ask on [discuss.hashicorp.com](https://discuss.hashicorp.com).

thanks i was looking at this module thats why i was asking terraform has the resources did not know if anyone had built this module to incoporate it. i will look at doing it as a fork
