### ISSUE TITLE
database_subnet_group_name should be configurable, or at least provide a configurable suffix

### ISSUE THREAD

**Issue by knurl** [terraform-aws-modules/terraform-aws-vpc#654]
## Is your request related to a new offering from AWS?

I tried setting this with the tag, but as said above it got obliterated by the code which also resets the Name tag.

**Comment by antonbabenko** [comment]
You could override `Name` tag using `database_subnet_group_tags = { Name = "My-value" }` but now (in #656) I have added `database_subnet_group_name` which will allow you to parameterized the name also.

**Comment by knurl** [comment]
Hi Anton, many thanks for this.

Best,
Rob Anderson
***@***.***
