### ISSUE TITLE
Error on destroy

### ISSUE THREAD

**Issue by tonsV2** [terraform-aws-modules/terraform-aws-vpc#655]
## Description

I had some problems destroying a project. As part of that I got the below error message. Eventually I realised that it occurs when I try to destroy a project which is already destroyed. But is that really the way it should be, getting an error message when calling destroy on a newly initialized project?

```
Error: Invalid count argument

  on .terraform/modules/instance-cluster.vpc/main.tf line 330, in resource "aws_subnet" "public":
 330:   count = var.create_vpc && length(var.public_subnets) > 0 && (false == var.one_nat_gateway_per_az || length(var.public_subnets) >= length(var.azs)) ? length(var.public_subnets) : 0

The "count" value depends on resource attributes that cannot be determined
until apply, so Terraform cannot predict how many instances will be created.
To work around this, use the -target argument to first apply only the
resources that the count depends on.
```

## ⚠️ Note

Before you submit an issue, please perform the following first:

1. Remove the local `.terraform` directory (! ONLY if state is stored remotely, which hopefully you are following that best practice!): `rm -rf .terraform/`
2. Re-initialize the project root to pull down modules: `terraform init`
3. Re-attempt your terraform plan or apply and check if the issue still persists

I did all of the above and the issue occur when I'm doing `terraform destroy` afterwards.

## Versions

 - Terraform:
v0.14.5

 - Provider(s):
registry.terraform.io/hashicorp/aws v3.46.0
registry.terraform.io/hashicorp/cloudinit v2.2.0
registry.terraform.io/hashicorp/helm v2.2.0
registry.terraform.io/hashicorp/kubernetes v2.3.2
registry.terraform.io/hashicorp/local v2.1.0
registry.terraform.io/hashicorp/null v3.1.0
registry.terraform.io/hashicorp/template v2.2.0
registry.terraform.io/terraform-aws-modules/http v2.4.1

 - Module:
2.66.0

## Reproduction

`rm -rf .terraform* && terraform init && terraform destroy`

## Expected behavior
Not getting an error message

## Actual behavior
Getting an error message

**Comment by bryantbiggs** [comment]
hi @tonsV2 - could you explain your motivation for trying to destroy a project that has only been initialized (and therefore doesn't contain any resources yet)? I don't know if this is a use case worth investigating at this time for this module

**Comment by antonbabenko** [comment]
I agree this is not worth fixing as this is not the intended usage pattern in the first place.
