### ISSUE TITLE
Fix notification for new module releases

### ISSUE THREAD

**Issue by a-khalilov** [terraform-aws-modules/terraform-aws-vpc#658]
## Is your request related to a new offering from AWS?

No
## Is your request related to a problem? Please describe.

Hi. We configured github custom notification to get an email when new module released. See screenshot
` `
![362c0f72-5c6d-4c60-8d69-eedefcdc00ff](https://user-images.githubusercontent.com/80922957/123974987-b72e9480-d9c5-11eb-8421-61c8522d4737.png)
` `
And this notification works for eks module, (as i understand) because,  when new version released, @barryib  created github release, so it looks like this https://github.com/terraform-aws-modules/terraform-aws-eks/releases
For other modules (iam, vpc, cloudfront) repos there aren't really github releases created, just automatically based on tags, and in that way github don't sent notifications (as i think). I checked what all repos notifications configured exactly as for eks repo
## Describe the solution you'd like.

May question mostly to @antonbabenko. Is it possible to create github releases every time when you release new module, to give opportunity to get github notifications, please?
## Additional context

Thanks for any explanation why it works for eks module and doesn't work for others.

**Comment by nikitacr7** [comment]
+1

**Comment by h3ct0rjs** [comment]
+1 @antonbabenko

**Comment by nikitacr7** [comment]
Hi @antonbabenko 

What do you think? Is it possible to use Release functionality for this module?

**Comment by antonbabenko** [comment]
I have just updated the release script a bit, so the next release of terraform-aws-modules should be a proper GitHub Release (see [example release](https://github.com/terraform-aws-modules/terraform-aws-redshift/releases/tag/v3.3.0)).

We are going to implement a slightly better approach in the foreseen future using GitHub Actions.
