### ISSUE TITLE
Support for AWS Neptune

### ISSUE THREAD

**Issue by jrouly** [terraform-aws-modules/terraform-aws-vpc#659]
## Is your request related to a new offering from AWS?

Yes - [AWS Neptune](https://aws.amazon.com/neptune/).

## Is your request related to a problem? Please describe.

Redshift, Elasticache, RDS, etc. are supported by top level directives in the VPC module.

## Describe the solution you'd like.

Either:
* support for Neptune just like RDS, Elasticache, etc.
* a recommendation to use the "database" tooling for both RDS and Neptune since they are both databases. I'm not sure what the best practice is.

## Describe alternatives you've considered.

* manually creating subnets for Neptune to try and mimic the RDS subnets. This is not desirable as it requires manual duplication of infrastructure that the VPC module manages for you for other services.
* re-using the database subnets for Neptune. This seems to work fine.

**Comment by antonbabenko** [comment]
Thanks for opening this issue.

I think it makes sense to reuse existing "database" subnets created by this module (in the meanwhile) and add optional support for `aws_neptune_subnet_group` resource in the same way as we do for `aws_db_subnet_group`, `aws_redshift_subnet_group`, and `aws_elasticache_subnet_group`.

Main resources for AWS Neptune (like cluster, parameter groups, etc) should be managed in a separate module which can be similar to [terraform-aws-rds](https://github.com/terraform-aws-modules/terraform-aws-rds/).

PR is welcome.

**Comment by jrouly** [comment]
Draft PR: https://github.com/terraform-aws-modules/terraform-aws-vpc/pull/660
