### ISSUE TITLE
Subnets for AWS Network Firewall with NAT and IGW use-cases

### ISSUE THREAD

**Issue by burtino** [terraform-aws-modules/terraform-aws-vpc#665]
## Is your request related to a new offering from AWS?
Yes, AWS Network Firewall

## Is your request related to a problem? Please describe.
It doesn't appear possible to use the existing module to setup AWS network firewall in the way AWS described where the firewall sits in dedicated subnets (with nothing else in them) and traffic from NAT goes to firewall before going to IGW. Example: https://docs.aws.amazon.com/network-firewall/latest/developerguide/arch-igw-ngw.html

## Describe the solution you'd like.
Perhaps a dedicated subnet type for AWS network firewall? 

## Additional context
I'm seeing more use cases in which AWS network firewall is being requested and due to its unique subnet and routing requirements it may require a new subnet type.

**Comment by burtino** [comment]
Perhaps related to #200

**Comment by ryanoolala** [comment]
https://github.com/terraform-aws-modules/terraform-aws-vpc/pull/672

I've made a pull request for this feature, will like to hear if you have any feedback on my design

**Comment by bryantbiggs** [comment]
hi all, this should be addressed in the next version which is under development here https://github.com/clowdhaus/terraform-aws-vpc-v4/tree/main/modules/subnets
