### ISSUE TITLE
EIP Tags

### ISSUE THREAD

**Issue by pavel-trubitsyn-clearscale** [terraform-aws-modules/terraform-aws-vpc#68]
Got these on plan:
Error: module.vpc.aws_eip.nat[0]: : invalid or unknown key: tags
Error: module.vpc.aws_eip.nat[1]: : invalid or unknown key: tags

Commenting of _"tag=..."_ line for resource "aws_eip" "nat" resolves the issue.

**Comment by antonbabenko** [comment]
Make sure you are using the correct version of AWS provider - [1.7.0](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#170-january-12-2018) or newere is required.
