### ISSUE TITLE
manage_default_network_acl flag when set to true always prompts for plan changes even if there are none

### ISSUE THREAD

**Issue by andylamp** [terraform-aws-modules/terraform-aws-vpc#684]
## Description

I am using `terraform` version 1.0.4 and the module in question. If I use `manage_default_network_acl` capability meaning that I set:

```hcl
module "my-vpc" {
  source  = "terraform-aws-modules/vpc/aws"
  version = ">= 3.6.0"

  name                 = "${var.deployment_type}-vpc"
  cidr                 = var.cidr_range
  azs                  = data.aws_availability_zones.available.names
  private_subnets      = var.private_subnets
  public_subnets       = var.public_subnets
  enable_nat_gateway   = true
  single_nat_gateway   = true
  enable_dns_hostnames = true

  create_database_subnet_group = true
  create_database_subnet_route_table = true
  create_database_internet_gateway_route = true

  # this change always performs a plan change...
  manage_default_network_acl = true

  tags = {
    TerraformManaged = "true"
    Environment = var.deployment_type
  }
}
```

while the only required providers that I have set for this is:

```hcl
# the required providers and their respective versions that we need to use
terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = ">= 3.53.0"
    }
  }

  required_version = ">= 1.0.4"
}
````

when I perform a `terraform plan`, even after apply, always prompts for a change saying the following:

```
Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  # module.vpc-dev.module.my-vpc.aws_default_network_acl.this[0] will be updated in-place
  ~ resource "aws_default_network_acl" "this" {
        id                     = "acl-0565c135dbce8c9d"
      ~ tags                   = {
          + "Name"             = ""
            # (2 unchanged elements hidden)
        }
      ~ tags_all               = {
          + "Name"             = (known after apply)
            # (2 unchanged elements hidden)
        }
        # (5 unchanged attributes hidden)


        # (4 unchanged blocks hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.
```

## Versions
 - Terraform: version 1.0.4
 - Provider(s):`
      - provider registry.terraform.io/hashicorp/aws v3.54.0
      - provider registry.terraform.io/hashicorp/null v3.1.0
 - Module: I am only using the current one (`terraform-aws-vpc`)

## Reproduction

 
 1. Install `terraform` and perform `init`
 2. Use the module snippet provided above
 3. Use `terraform plan`
 4. Use `terraform apply`
 5. Then use `terraform plan` again _without_ doing any changes to the code and having the `manage_default_network_acl` flag enabled.

I am not using workspaces and cache clearing does not help.

### Code Snippet to Reproduce

Provided in the description.

## Expected behavior

No change to be present or required.

## Actual behavior

Plan always requests for changes.

### Terminal Output Screenshot(s)

Provided in the first bits of the issue.

## Additional context

None.

**Comment by evairmarinho** [comment]
Use `default_route_table_tags` input :)

**Comment by antonbabenko** [comment]
This issue has been resolved in version 3.11.3 :tada:

**Comment by andylamp** [comment]
thanks for fixing it @antonbabenko !

**Comment by antonbabenko** [comment]
Kudos to @bryantbiggs 🥇

**Comment by andylamp** [comment]
kudos well deserved @bryantbiggs 👌
