### ISSUE TITLE
VPC & EKS Modules - Lifecycle ignore changes

### ISSUE THREAD

**Issue by btdevops** [terraform-aws-modules/terraform-aws-vpc#685]
Hey folks, I used the VPC + EKS modules to deploy into an existing environment and then did some manual configuration related to the Transit Gateway (attachments + routes)  that I would like Terraform to Ignore. However it does not seem to accept the lifecycle/ignore changes block. How do I get these two modules to ignore these changes that I've made out of TF?

**Comment by bryantbiggs** [comment]
this has to be handled within the resource level unfortunately - as an alternative, you can try to fix up the state manually to get it sorted
