### ISSUE TITLE
Allow specification of names and tags for secondary CIDR blocks.

### ISSUE THREAD

**Issue by jhancock93** [terraform-aws-modules/terraform-aws-vpc#689]
## Is your request related to a new offering from AWS?
No

## Is your request related to a problem? Please describe.
When secondary CIDR blocks are specified within the same availability zone, the Name tag of the subnets created for the primary and secondary CIDR blocks are identical, making them difficult to distinguish.

## Describe the solution you'd like.
Ideally, the public_subnets, database_subnets, private_subnets, etc. would accept a map or list of objects instead of a list of strings so that additional name suffixes or prefixes or tags might be supplied to allow the multiple subnets to be distinguished. Since this would be a breaking change, it would probably require introducing new optional variables.

## Describe alternatives you've considered.
None.

## Additional context
In our case, we have a small secondary CIDR block that supports AWS DIrectConnect and we need an easy way to distinguish between the subnets.

**Comment by antonbabenko** [comment]
Thanks for opening this issue.

There are several similar already #403 #535, so I am going to close this one.

The common solution is to use maps instead of lists as you say.
