### ISSUE TITLE
Subnet Output Values Format Issue

### ISSUE THREAD

**Issue by fitchtech** [terraform-aws-modules/terraform-aws-vpc#691]
https://github.com/terraform-aws-modules/terraform-aws-vpc/blob/39eae2176050671617342e2dd40860b34a6febe8/outputs.tf#L73

This is an issue with all subnet outputs. That there should be outputs for each of the subnet resources themselves, instead of or in addition to having an output for that's a list of an attribute for all the subnets of that type. 

The reason why this is an issue is that based on the current outputs available I cannot determine which subnet are created in which of the AZ IDs I've specified. The use of the splat expression to output each value separately is the issue. If you were to just output the value = aws_subnet.private it could then be grouped by AZ or any other value of each subnet. 

However, since that is missing the only way to determine this is to pass the output subnet IDs to a data source which if the subnets haven't previously been created results in an error that Terraform cannot be determined until apply.

```tf
output "private_subnets" {
  description = "List of IDs of private subnets"
  value       = aws_subnet.private.*.id # Using splat expressions to output each value separately is the issue
}
```
This is how I recommend it should be, output the subnet resource for private, public, intra, database, and redshift: 
```tf
output "private_subnets" {
  description = "List of IDs of private subnets"
  value       = aws_subnet.private
}

output "private_subnets_ids" {
  description = "List of IDs of private subnets"
  value       = aws_subnet.private.*.id
}

output "public_subnets" {
  description = "List of IDs of publicsubnets"
  value       = aws_subnet.public
}

output "public_subnets_ids" {
  description = "List of IDs of public subnets"
  value       = aws_subnet.public.*.id
}
# Etc, etc, etc...
```

So that I can do this:

```tf
output "subnet_zones" {
  value = { for id, subnet in module.vpc.private_subnets : subnet.availability_zone_id => subnet... }
  description = "Subnets grouped by AZ ID"
}
```

**Comment by antonbabenko** [comment]
This can be a potential workaround until we have proper support for `maps` instead of `lists` in subnets (#403).
 
The downside of the approach you are recommending here is the amount of unnecessary information each `aws_subnet` resource contains which is rather large to be included in outputs.
