### ISSUE TITLE
Error waiting for NAT Gateway to become available: unexpected state 'failed', wanted target 'available'. last error: %!s(<nil>)

### ISSUE THREAD

**Issue by PrateekKhatri** [terraform-aws-modules/terraform-aws-vpc#692]
Hello,
Terraform version: v0.15.3
aws provider = 3.59.0

We are using terraform VPC module to deploy 2 private subnets and attaching that subnet to my Redis Elastic Cache. After applying it is working fine.

But when a new request comes to add 2 more private subnets to the existing infra, we added 2 more private subnets to the existing infra and then run terraform apply command. After running some time we got the below error:

Error: Error waiting for NAT Gateway to become available: unexpected state 'failed', wanted target 'available'. last error: %!s()

Is there any solution for the same?

Because of this error, we are not able to continue with incremental infra deployments.

**Comment by antonbabenko** [comment]
Please fill in the issue template when opening an issue, include code snippet and error log. It is very important if you want to get a reply.

From the information you provided I think you hit some AWS quotas that prevent you from deploying change. Read more here - https://aws.amazon.com/premiumsupport/knowledge-center/manage-service-limits/

I am going to close this one.
