### ISSUE TITLE
Error waiting for NAT Gateway to become available: unexpected state 'failed', wanted target 'available'. last error: %!s(<nil>)

### ISSUE THREAD

**Issue by PrateekKhatri** [terraform-aws-modules/terraform-aws-vpc#693]
Hello,
Terraform version: v0.15.3

We are using terraform VPC module to deploy 2 private subnets and attaching that subnet to my Redis Elastic Cache. After applying it is working fine.

**Please find below code which is running:**

module "vpc" {
  source = "terraform-aws-modules/vpc/aws"

  name = var.vpc_name
  cidr = var.cidr_block

  azs             = data.aws_availability_zones.available.names
  private_subnets = ["10.0.1.0/24", "10.0.2.0/24"]
  public_subnets  = ["10.0.101.0/24", "10.0.102.0/24"]
  database_subnets = ["10.0.103.0/24", "10.0.104.0/24"]

  enable_nat_gateway = true
  enable_vpn_gateway = false
  enable_dns_hostnames = true
  enable_dns_support   = true
}

**Code used to create elasticache subnet group**
resource "aws_elasticache_subnet_group" "redis" {
  name        = "${var.env}-redis-sg"
  subnet_ids  = var.subnet_ids
  description = var.description
}

But when a new request comes to add 2 more private subnets to the existing infra, we added 2 more private subnets to the existing infra and then run terraform apply command. After running some time we got the below error:

Error: Error waiting for NAT Gateway to become available: unexpected state 'failed', wanted target 'available'. last error: %!s()

**After the resource creating form above modules, we have updated private subnets below is the updated code:**

module "vpc" {
  source = "terraform-aws-modules/vpc/aws"

  name = var.vpc_name
  cidr = var.cidr_block

  azs             = data.aws_availability_zones.available.names
  private_subnets = ["10.0.1.0/24", "10.0.2.0/24" , "10.0.3.0/24", "10.0.4.0/24"]
  public_subnets  = ["10.0.101.0/24", "10.0.102.0/24" ]
  database_subnets = ["10.0.103.0/24", "10.0.104.0/24"]

  enable_nat_gateway = true
  enable_vpn_gateway = false
  enable_dns_hostnames = true
  enable_dns_support   = true
}

**Code used to create elasticache subnet group**
resource "aws_elasticache_subnet_group" "redis" {
  name        = "${var.env}-redis-sg"
  subnet_ids  = var.subnet_ids
  description = var.description
}

**After running terraform apply getting below error:**

 ### Error: Error waiting for NAT Gateway to become available: unexpected state 'failed', wanted target 'available'. last error: %!s(<nil>)     

   with module.network.module.vpc.aws_nat_gateway.this[1],
   on .terraform\modules\network.vpc\main.tf line 1083, in resource "aws_nat_gateway" "this":
 1083: resource "aws_nat_gateway" "this" {

 Error: Error waiting for NAT Gateway  to become available: unexpected state 'failed', wanted target 'available'. last error: %!s(<nil>)     

   with module.network.module.vpc.aws_nat_gateway.this[0],
   on .terraform\modules\network.vpc\main.tf line 1083, in resource "aws_nat_gateway" "this":
 1083: resource "aws_nat_gateway" "this" {

Is there any solution for the same?

Because of this error, we are not able to continue with incremental infra deployments.

**Comment by antonbabenko** [comment]
I am pretty sure that the problem is because you are trying to create too many resources.

Check this troubleshooting guide - https://docs.aws.amazon.com/vpc/latest/userguide/nat-gateway-troubleshooting.html#nat-gateway-troubleshooting-failed

In general, you often would not want/need to have so many NAT gateways so you can add `single_nat_gateway = true` for that. Try it.

**Comment by PrateekKhatri** [comment]
Thanks, it is working while using single_nat_gateway = true.
