### ISSUE TITLE
Support connectivity_type = "private" for NAT GW

### ISSUE THREAD

**Issue by Freedmont** [terraform-aws-modules/terraform-aws-vpc#694]
## Is your request related to a new offering from AWS?
Yes, but it is supported by Terraform already: https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/nat_gateway

## Is your request related to a problem? Please describe.
We need to be able to route otherwise unrouteable backend space through private RFC1918 "frontend" NAT GWs. 

## Describe the solution you'd like.
We would like to be able to specify
connectivity_type = "private"
When creating a NAT GW.  We would like the backend route tables to route through that Private NAT GW.
It appears we can already chose not to create an Internet Gateway, but would like to use a Transit Gateway, but that could be a separately configured item.  

## Describe alternatives you've considered.
We've considered manually creating the Transit GW & NAT GW pieces in this situation, but would prefer to have as much of these deployments as possible in TF

**Comment by yusuf-madkour** [comment]
I agree with, this would save everyone a lot of hassle if it was implemented in the module. However, I just tried another workaround other than creating the NGW manually as you mentioned and I thought I should share it.

I created the NGW using the official aws resource after creating the VPCs and passed the private subnet id to it.

```
module "test_vpc" {
  source = "terraform-aws-modules/vpc/aws"

  name = "Test VPC"
  cidr = "10.0.2.0/24"

  private_subnets = ["10.0.2.0/28"]
  azs            = ["us-east-1"]
}

resource "aws_nat_gateway" "test_ngw" {
  depends_on = [ module.test_vpc ]
  connectivity_type = "private"
  subnet_id         = var.type2_private_subnet_id
}
```

This way you get to keep everything in TF as you mentioned.

**Comment by bryantbiggs** [comment]
hi all, this should be addressed in the next version which is under development here https://github.com/clowdhaus/terraform-aws-vpc-v4/tree/main/modules/subnets

**Comment by Xat59** [comment]
Any idea when this will be available ? That's quite a small change there.
