### ISSUE TITLE
Support unique route table for outpost routes

### ISSUE THREAD

**Issue by jonvadney** [terraform-aws-modules/terraform-aws-vpc#697]
## Is your request related to a new offering from AWS?

No

## Is your request related to a problem? Please describe.

Outpost support is currently available in the module, however the shared use of the private route table makes using the local gateway in an outpost problematic.  

https://docs.aws.amazon.com/outposts/latest/userguide/outposts-networking-components.html

## Describe the solution you'd like.

Options
1) Add an option to create a blank outpost route table, instead of using the private subnet route table.  Would allow the module user to create the custom route rules outside of the module. 
2) Add options similar to the database subnet for creation of the optional routes.  Include support for the local gateway as one of the options. 

In either case, also add an output for the outpost route table id's.

## Describe alternatives you've considered.

Create the outpost subnets outside of this module. 

## Additional context

I see in #542 a discussion about the difficulties in testing the outpost feature.  Perhaps this is a good reason to look into creation of the subnet outside of this vpc module.

**Comment by thebigcosinus** [comment]
Hi,

I need to have a separate route table for the Outpost.

Can we reopen this issue

Thanks

**Comment by bryantbiggs** [comment]
hi all, this should be addressed in the next version which is under development here https://github.com/clowdhaus/terraform-aws-vpc-v4/tree/main/modules/subnets
