### ISSUE TITLE
Unable to provide different tag names for different subnets

### ISSUE THREAD

**Issue by ben5556** [terraform-aws-modules/terraform-aws-vpc#698]
I am creating a bunch of private subnets for Lambdas, Databricks components etc and I would like to tag them so as to be able to distinguish them when I look in AWS console

From what I can see in the current config, I cannot do this as the additional tags are not based on count/index ?

This is what I see on AWS console

```
example-public-ap-southeast-2a
example-private-ap-southeast-2c
example-private-ap-southeast-2b
example-db-ap-southeast-2b
example-db-ap-southeast-2c
example-private-ap-southeast-2a
example-db-ap-southeast-2b
example-private-ap-southeast-2b
example-db-ap-southeast-2a
```

How can I name them as below ?

```
example-public-ap-southeast-2a
example-databricks-private-ap-southeast-2c
example-lambda-private-ap-southeast-2b
example-databricks-db-ap-southeast-2b
example-databricks-db-ap-southeast-2c
example-lambda-private-ap-southeast-2a
example-generic-db-ap-southeast-2b
example-databricks-private-ap-southeast-2b
example-generic-db-ap-southeast-2a
```

**Comment by ben5556** [comment]
Thanks. May I know why something which is a common use case and also easy to implement was not included in this module ? Ability to tag each resource we are creating via this module is something basic yeah ?

**Comment by ben5556** [comment]
Sorry, what migration/upgrade are you referring to ?

**Comment by antonbabenko** [comment]
https://github.com/hashicorp/terraform/issues/19354
https://github.com/hashicorp/terraform/issues/9048
