### ISSUE TITLE
[Feature Req] Ability to name all subnet

### ISSUE THREAD

**Issue by Guimove** [terraform-aws-modules/terraform-aws-vpc#70]
I need to give special name to all subnet I create with terraform.
Is their any chance to have this possibility with this module ? 

Like replacing the simple list of subnet of something like : 

```hcl
  xxxxxx_subnets = [
    {
      "name" = "MySubnet1",
      "subnet" = "XX.XX.XX.XX/XX"
    },
    {
      "name" = "MySubnet2",
      "subnet" = "XX.XX.XX.XX/XX"
    },
    {
      "name" = "MySubnet3",
      "subnet" = "XX.XX.XX.XX/XX"
    }
  ]
```

**Comment by antonbabenko** [comment]
No, this is not supported and unlikely to be implemented in a generic way without a significant increase in complexity.
