### ISSUE TITLE
'private_nat_gateway' create timeout is not getting honored

### ISSUE THREAD

**Issue by siddharthsahu** [terraform-aws-modules/terraform-aws-vpc#704]
## Description
We are creating two 'private_nat_gateway' and are getting timeout after 2m30s even though the default is 5m([link](https://github.com/terraform-aws-modules/terraform-aws-vpc/blob/v2.74.0/main.tf#L983)) and it is not being overridden. 

```
module.vpc.module.vpc.aws_route.private_nat_gateway[0]: Still creating... [2m0s elapsed]
module.vpc.module.vpc.aws_route.private_nat_gateway[1]: Still creating... [2m10s elapsed]
module.vpc.module.vpc.aws_route.private_nat_gateway[0]: Still creating... [2m10s elapsed]
module.vpc.module.vpc.aws_route.private_nat_gateway[1]: Still creating... [2m20s elapsed]
module.vpc.module.vpc.aws_route.private_nat_gateway[0]: Still creating... [2m20s elapsed]
module.vpc.module.vpc.aws_route.private_nat_gateway[0]: Still creating... [2m30s elapsed]
module.vpc.module.vpc.aws_route.private_nat_gateway[1]: Still creating... [2m30s elapsed]

Error: error waiting for Route in Route Table (rtb-xxxx) with destination (0.0.0.0/0) to become available: couldn't find resource (21 retries)
```

If you see above, terraform waits for 2m30s instead of 5m. It is fair to assume that 5m constraint is for each resource and not cumulatively.

## Versions

 - Terraform: 0.12

 - Provider(s): ~> 2.0

 - Module: 2.74

## Reproduction

Not using workspace.
Yes, cleared local cache.
terraform apply

## Expected behavior

Terraform should have timed-out after 5m as mentioned in the code.([link](https://github.com/terraform-aws-modules/terraform-aws-vpc/blob/v2.74.0/main.tf#L983))

## Actual behavior

Terraform timed-out after 2m30s as shown above.

**Comment by antonbabenko** [comment]
The main suggestion which I'd like to give is to upgrade to Terraform 0.13 (or newer) and use the latest version of the module.

In the not-so-distant past, there were some improvements in the Terraform AWS provider related to timeouts in `route` (and other VPC-related resources) that can be related to the issue you are experiencing. See this, for example - https://github.com/hashicorp/terraform-provider-aws/pull/21161/files#diff-0ea24af5d0ea4c1ae0e3b07c6075c91082acbfc2301a70d31dd75efa9dfb550eR89-R91 . 

I don't know if the changes to Terraform AWS provider (including those mentioned above) were related to any change in the AWS VPC or API, but I would strongly recommend upgrading from Terraform 0.12 and try again. If you hit the problems using the latest versions, please open a new issue.

We are not going to support Terraform 0.12 in this module and I am going to close this issue.
