### ISSUE TITLE
How to: configure timeouts for vpc module on aws_default_route_table

### ISSUE THREAD

**Issue by cdancy** [terraform-aws-modules/terraform-aws-vpc#708]
Our vpc module seems to intermittently throw the below:
```
CREATE_FAILED : "terraform apply -auto-approve -no-color -input=false plan.json" command failed with code 1
        	            	
Error: error waiting for Route in Route Table (rtb-0179f2b9c38f21dd0) with destination (0.0.0.0/0) to become available: timeout while waiting for state to become 'ready' (timeout: 2m0s)

  with module.vpc.aws_route.private_nat_gateway[2],
  on .terraform/modules/vpc/main.tf line 1110, in resource "aws_route" "private_nat_gateway":
1110: resource "aws_route" "private_nat_gateway" {


Error: error reading Route Table Association (rtbassoc-00100b66ae8b7577e): Empty result

  with module.vpc.aws_route_table_association.public[0],
  on .terraform/modules/vpc/main.tf line 1204, in resource "aws_route_table_association" "public":
1204: resource "aws_route_table_association" "public" {
```
the default timeout of 2m is simply not enough for us and we'd like to increase it. Our vpc module is pretty basic and we don't attempt to do any additional configuration on the default route table (which is where I assume the above is coming from). I attempted to configure it like so:
```
resource "aws_default_route_table" "rtb-default" {
  default_route_table_id = module.vpc.default_vpc_main_route_table_id
  timeouts {
    create = "30m"
    update = "30m"
  }
}
```
But that then throws an exception saying:
```
1 validation error detected: Value '201-us-399200-rt-timeouts-2021110916415210_sgtnf-test-k8s-access-20211109165356' at 'functionName' failed to satisfy constraint: Member must have length less than or equal to 64
```
Not exactly sure how to move forward here. We just want to increase that default 2m timeout. Any suggestions?

**Comment by msharma24** [comment]
Hi @cdancy 

What version of this module are you using? The default route table time-out was updated in  [v3.9.0](https://github.com/terraform-aws-modules/terraform-aws-vpc/releases/tag/v3.9.0)

**Comment by cdancy** [comment]
@msharma24 interesting ... I'm on version `3.6.0`. I see it's bumped to 5m now. I'll try doing that. Still ... is there a sane way to configure this for future use-cases should that not be enough?

**Comment by msharma24** [comment]
I reckon updating the module version will fix your issue today.  5m time-out should not cause any more issues in the future too.

**Comment by cdancy** [comment]
@msharma24 fair enough and I'll give that a go. Thanks for the pointer.

**Comment by cdancy** [comment]
@msharma24 so that worked, and things got farther, but now I'm hitting the below:
```
15:51:39          	            	Error: error reading Route Table Association (rtbassoc-0b3f1e625ea7d6978): empty result
15:51:39          	            	
15:51:39          	            	  with module.vpc.aws_route_table_association.public[2],
15:51:39          	            	  on .terraform/modules/vpc/main.tf line 1217, in resource "aws_route_table_association" "public":
15:51:39          	            	1217: resource "aws_route_table_association" "public" {
```

**Comment by dhohengassner** [comment]
@cdancy Thanks for bringing that up!
Seeing the same error but not consistent.

Using version `3.10.0`:

```
module.vpc.aws_route.private_nat_gateway[0]: Creation complete after 1s [id=r-rtb-0222974c8355a52aa1040279494]
╷
│ Error: error reading Route Table Association (rtbassoc-05f561a5ffebba79b): empty result
│ 
│   with module.vpc.aws_route_table_association.private[0],
│   on .terraform/modules/vpc/main.tf line 1147, in resource "aws_route_table_association" "private":
│ 1147: resource "aws_route_table_association" "private" {
│ 
╵
```

Any ideas or fix is much appreciated!

**Comment by cdancy** [comment]
@dhohengassner do your logs output the new 5m wait timeout being tripped? The solution noted above worked for us.

**Comment by cdancy** [comment]
Fix might be handled by this PR https://github.com/hashicorp/terraform-provider-aws/issues/21683

**Comment by Clee681** [comment]
Using version `3.11.0`

```
Error: error waiting for Route in Route Table (rtb-0cd2e0f77c17fb17a) with destination (0.0.0.0/0) to become available: couldn't find resource (21 retries)
with module.vpc.aws_route.private_nat_gateway[0]
```

**Comment by bryantbiggs** [comment]
closing for now, can be tracked at referenced upstream issue https://github.com/hashicorp/terraform-provider-aws/issues/21683
