### ISSUE TITLE
How to: create a second intra subnet?

### ISSUE THREAD

**Issue by midestefanis** [terraform-aws-modules/terraform-aws-vpc#710]
## Description

Following this example -> [complete-vpc](https://github.com/terraform-aws-modules/terraform-aws-vpc/issues/new?assignees=&labels=&template=bug_report.md) I was wondering how to create a second subnet 'intra_subnets '. As I see it is only possible to specify a single subnet of each type or is there a way to create 'intra_subnets_2'?

**Comment by antonbabenko** [comment]
`intra_subnets` accepts a list of CIDR blocks that will be used to create subnets. The `complete-vpc` example there will create 3 intra subnets:

https://github.com/terraform-aws-modules/terraform-aws-vpc/blob/89a916e825a64fbc4ccfcef585e2924e3d78e0a8/examples/complete-vpc/main.tf#L31

**Comment by midestefanis** [comment]
@antonbabenko thanks.-Yes, but the subnets within that list cannot be treated as different entities. For example the name, tags, etc.
