### ISSUE TITLE
Allow VPCs without IPv4's "cidr_block"

### ISSUE THREAD

**Issue by ismacasti** [terraform-aws-modules/terraform-aws-vpc#713]
## Is your request related to a new offering from AWS?

Yes, IPv6 only VPC subnets

## Is your request related to a problem? Please describe.

VPCs and subnets must be specified with a IPv4 IP, while AWS' VPC allows (since the 23rd) to not require them for IPv6 only networks.

## Describe the solution you'd like.

Make the _cidr_block_ fields in _aws_vpc_ and _aws_subnet_ optional.

## Describe alternatives you've considered.

The alternative is to create the VPCs manually

## Additional context

Here's the public note from Amazon announcing the IPv6 only feature
https://aws.amazon.com/blogs/networking-and-content-delivery/introducing-ipv6-only-subnets-and-ec2-instances/

**Comment by bryantbiggs** [comment]
we will have to wait for upstream support by the AWS provider, currently its still required https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/vpc#cidr_block

**Comment by rohitjha941** [comment]
Is it possible to re-open this issue as the provider now allows `cidr_block` to be optional?
