### ISSUE TITLE
vpc/subnet creation use the 'for_each' method

### ISSUE THREAD

**Issue by kokkerhout** [terraform-aws-modules/terraform-aws-vpc#714]
## Is your request related to a new offering from AWS?
yes

## Is your request related to a problem? Please describe.
When multiple subnets are defined it's indexed. So for example you have defined 3 subnet like;
["10.10.0.0/24", "10.10.1.0/24", "10.10.2.0/24"]
They are indexed like [0], [1] and [2].
When I would remove the middle subnet, the index [1] and [2] will be removed and a new index [1] will be created

## Describe the solution you'd like.
Use the 'for_each' method so unwanted removal and recreation of a subnet does not happen anymore

## Describe alternatives you've considered.
Create my own module...

**Comment by antonbabenko** [comment]
There are already multiple duplicates of this issue. Closing this one.
