### ISSUE TITLE
Allow private route tables not to be created when NAT Gateway is not being created

### ISSUE THREAD

**Issue by evairmarinho** [terraform-aws-modules/terraform-aws-vpc#726]
## Is your request related to a problem? Please describe.

I need to create a VPC with intra, public and database subnets and the module ends up creating an unwanted private route table that I have no use for my infrastructure.

### Code
```hcl
module "vpc_spoke" {
  source  = "terraform-aws-modules/vpc/aws"
  version = "3.11.0"

  cidr = "10.90.0.0/16"
  name = "dev"

  azs              = ["us-east-1a", "us-east-1b", "us-east-1c"]
  intra_subnets    = ["10.90.20.0/22", "10.90.24.0/22", "10.90.28.0/22"]
  public_subnets   = ["10.90.0.0/22", "10.90.4.0/22", "10.90.8.0/22"]
  database_subnets = ["10.90.40.0/22", "10.90.44.0/22", "10.90.48.0/22"]

  single_nat_gateway     = true
  one_nat_gateway_per_az = false
  enable_nat_gateway     = false

  manage_default_network_acl     = true
  public_dedicated_network_acl   = true
  intra_dedicated_network_acl    = true
  database_dedicated_network_acl = true

  manage_default_route_table         = true
  create_database_subnet_route_table = true
  create_database_subnet_group     = false
}
```

## Describe the solution you'd like.

I need the VPC to be created without private route table when I have 0 private subnets. I need each type of my subnets to continue to have only 1 route table.

### Currently: 
https://github.com/terraform-aws-modules/terraform-aws-vpc/blob/57ba0ef08063390636daedcf88f71443281c2b84/main.tf#L8
### Proposal:

An initial change would be to modify the logic of `local.nat_gateway_count`. 
Change proposal
```hcl
nat_gateway_count = var.single_nat_gateway ? 1 : var.one_nat_gateway_per_az ? length(var.azs) : !var.single_nat_gateway && !var.enable_nat_gateway ? 0 : local.max_subnet_length
```

Looking only at the private route table, I changed `single nat gateway` to `false` in the module and executed the terraform plan. The private subnet would be destroyed :) . However, 3 new database route tables would eventually be created :( . With this, i realized that it will also be necessary to change the logic in the `count` of the route tables that are not private, such as the database ones.

**Comment by bryantbiggs** [comment]
dupelicate of #184
