### ISSUE TITLE
aws_nat_gateway and aws_route_table_association when pass az's as data

### ISSUE THREAD

**Issue by geof2001** [terraform-aws-modules/terraform-aws-vpc#727]
## Description

I have created a data source for az's 

```
data "aws_availability_zones" "available" {
  state = "available"
}
```
which I reference to provide the list of az's to input `azs` as
```
azs             = data.aws_availability_zones.available.names
or
 azs             = data.aws_availability_zones.available.zone_ids
```
Neither one has worked and the submodules mentioned above return
```
Error: Error in function call
│ 
│   on .terraform/modules/vpc/main.tf line 1103, in resource "aws_nat_gateway" "this":
│ 1103:   subnet_id = element(
│ 1104:     aws_subnet.public.*.id,
│ 1105:     var.single_nat_gateway ? 0 : count.index,
│ 1106:   )
│     ├────────────────
│     │ aws_subnet.public is empty tuple
│     │ count.index is 4
│     │ var.single_nat_gateway is false
│ 
│ Call to function "element" failed: cannot use element function with an empty list.
```
The same error with empty tuple for aws_subnet.public is thrown for the public route table associations

## ⚠️ Note ## These steps below were already attempted with no change in behavior

Before you submit an issue, please perform the following first:

1. Remove the local `.terraform` directory (! ONLY if state is stored remotely, which hopefully you are following that best practice!): `rm -rf .terraform/`
2. Re-initialize the project root to pull down modules: `terraform init`
3. Re-attempt your terraform plan or apply and check if the issue still persists

## Versions

 - Terraform: v1.1.2

 - Provider(s): 3.65.0

 - Module: 3.11.0

## Reproduction
Steps to reproduce the behavior: terraform plan always throws the errors in the scenario described.
Not using workspaces
Yes cache was cleared 
create vpc.tf with 
```
resource "aws_eip" "nat" {
  provider = aws.use2
  count = 3
  vpc = true
}

data "aws_availability_zones" "available" {
  state = "available"
}

module "vpc" {
    source    = "terraform-aws-modules/vpc/aws"
    providers  = { aws = aws.use2 }
    
    name                  = "dev-mesh-vpc-us-east-2"
    cidr                  = "10.134.128.0/17"
    secondary_cidr_blocks = ["100.80.0.0/16", "100.81.0.0/16", "100.82.0.0/16"]

    azs             = data.aws_availability_zones.available.zone_ids
    private_subnets = var.private_subnets
    public_subnets  = var.public_subnets

    enable_nat_gateway  = true
    single_nat_gateway  = false
    one_nat_gateway_per_az = true
    reuse_nat_ips       = true                    # <= Skip creation of EIPs for the NAT Gateways
    external_nat_ip_ids = "${aws_eip.nat.*.id}"

    tags = {
        Terraform = "true"
        Environment = "dev"
    }
}
```
execute terraform plan

## Expected behavior
I'd expect it to have the same behavior as if provided 
```
  azs = ["us-east-2a", "us-east-2b", "us-east-2c"]
```

## Actual behavior
errors described above

### Terminal Output Screenshot(s)
Can provide if deemed necessary

**Comment by bryantbiggs** [comment]
see your error message posted `Call to function "element" failed: cannot use element function with an empty list.` - your data source is not returning any availability zones

**Comment by geof2001** [comment]
Referenced the same way as described here. https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/availability_zones

**Comment by bryantbiggs** [comment]
@geof2001 unfortunately I cannot comment on why your data source is not returning any availability zones but thats what it looks like from your error message. you can confirm this with something like:

```hcl
data "aws_availability_zones" "available" {
  state = "available"
}

output "availability_zones" {
	value = data.aws_availability_zones.available.zone_ids
}
```

if the output of `availability_zones` shows on your CLI a list of zone IDs then its returning an appropriate list and this should work for the module. if its returning an empty list or anything other than a list of zone IDs, then its failing to find available zones

**Comment by geof2001** [comment]
What you mentioned did help though it led me to outputting the data.aws_availability_zones and seeing that the provider was using default us-east-1 even though the resources were being created in us-east-2.  Just had to add ```provider = aws.use2``` which is one of the config aliases we setup to the data block for azs.
