### ISSUE TITLE
Multiple Flow log destinations

### ISSUE THREAD

**Issue by Kostavro** [terraform-aws-modules/terraform-aws-vpc#732]
## Is your request related to a new offering from AWS?
No.

## Is your request related to a problem? Please describe.
No.

## Describe the solution you'd like.
Currently, the module supports creating configuration for **ONE** flow log destination. I would like to be able to create multiple.

## Describe alternatives you've considered.
Managing flow log resources externally.

## Additional context
-

**Comment by antonbabenko** [comment]
It is a rather custom use case that won't be implemented in this module.

Closing this issue.
