### ISSUE TITLE
3 AZ's but 2 NAT gateways are needed

### ISSUE THREAD

**Issue by Arisfx** [terraform-aws-modules/terraform-aws-vpc#733]
Hi, we have 3 AZ's but we need nat gateways only in 2 of them AZA and AZB - how can we achieve this?
By switching the `single_nat_gateway`  to `false`, the module is trying to create 3 nat gateways.
Thanks!

**Comment by antonbabenko** [comment]
No, you can't make it with this module. Please check 3 scenarios how NAT gateway can be created in the README - https://github.com/terraform-aws-modules/terraform-aws-vpc#nat-gateway-scenarios

**Comment by Arisfx** [comment]
Thank you Anton, do you know how can we stop the module from trying to generate new route table associations everytime we dissasociate something from a routing table? 

```
  # module.vpc.aws_route_table_association.private[1] will be created
  + resource "aws_route_table_association" "private" {
      + id             = (known after apply)
      + route_table_id = "rtb-xxx"
      + subnet_id      = "subnet-yyy"
    }
```
This x to y association was removed by the console, and the module still insists to be rebuild, something we dont want, but i cant figure out how to make terraform stop complaining

**Comment by antonbabenko** [comment]
I don't think you can. The private subnet should have a route table associated.

https://github.com/terraform-aws-modules/terraform-aws-vpc/blob/6f89db5c3094656f8f40e6d3c9d7d6b124597de9/main.tf#L1081-L1089

**Comment by Arisfx** [comment]
the thing is that we associated the private subnet from AZB succesfully  with extra code, outside of the module.... we couldn't figure out a way to tweak the module code so we can do it there, unfortunately.
