### ISSUE TITLE
VPC not being assigned IPV6

### ISSUE THREAD

**Issue by huseyinhamilton** [terraform-aws-modules/terraform-aws-vpc#735]
## Description
I may be doing something weird but I am getting an issue with IPV6 flags when I try to create the VPC that results in failure to create resources. I have never used this VPC module before, I usually just create my VPC from scratch myself.

With these flags set:
```
  enable_ipv6 = true
  assign_ipv6_address_on_creation = false
  public_subnet_assign_ipv6_address_on_creation = true
```

The error created:
```
│ Error: error enabling EC2 Subnet (subnet-123) AssignIpv6AddressOnCreation: InvalidParameterValue: Invalid value 'true' for assign-ipv6-address-on-creation. Cannot set assign-ipv6-address-on-creation to true unless the subnet (subnet-123) has an IPv6 CIDR block associated with it.
│ 	status code: 400, request id: 04862572-9fec-41a7-81ba-37871a69b11d
│ 
│   with module.vpc.aws_subnet.public[2],
│   on .terraform/modules/vpc/main.tf line 350, in resource "aws_subnet" "public":
│  350: resource "aws_subnet" "public" {
```

## Versions

 - Terraform: 1.1.2
 - Provider(s): AWS ("~> 3.0")
 - Module: 3.11.3

## Expected behavior
VPC has IPV6 assigned and subnets can be enabled with assign-ipv6-address-on-creation.

**Comment by antonbabenko** [comment]
Please check this example for all required parameters in order to enable IPv6 - https://github.com/terraform-aws-modules/terraform-aws-vpc/blob/master/examples/ipv6/main.tf
