### ISSUE TITLE
Terraform AWS Provider 4.x support

### ISSUE THREAD

**Issue by trevorrea** [terraform-aws-modules/terraform-aws-vpc#752]
## Is your request related to a new offering from AWS?
N/A

## Is your request related to a problem? Please describe.
N/A

## Describe the solution you'd like.
The versions.tf of this module pins the provider version as >= 3.63.  Has the module been tested with the 4.x series AWS provider? If not do you need to add an additional version constraint of < 4.0.0 until it has been tested to prevent users who upgrade to 4.x experiencing issues with the module?

## Describe alternatives you've considered.
Review the breaking changes in the changelog and test the module with 4.x Terraform AWS provider and make any changes required. 

## Additional context
N/A

P.S. I really appreciate this module.  It's extremely useful.

**Comment by bryantbiggs** [comment]
hi @trevorrea are you seeing an issue with v4.x? If not, then we don't need this issue

**Comment by trevorrea** [comment]
I'm not but I've not upgraded my provider (only ran a plan) plus my use case is extremely basic. Others may be using more advanced features of the module.

**Comment by bryantbiggs** [comment]
ok well until there is an issue identified and the proper information provided, theres no need to have this issue open
