### ISSUE TITLE
Add support to define subnets for memorydb

### ISSUE THREAD

**Issue by mentos1386** [terraform-aws-modules/terraform-aws-vpc#753]
## Is your request related to a new offering from AWS?

Yes, related to [MemoryDB](https://aws.amazon.com/memorydb/)

## Is your request related to a problem? Please describe.

No.

## Describe the solution you'd like.

Have an option to do:
```tf
module "vpc" {
  source  = "terraform-aws-modules/vpc/aws"
  version = "x.y.z"

  memorydb_subnets = [ ... ]

  memorydb_subnet_tags = { ... }
}
```

## Describe alternatives you've considered.

Creating subnets manually. It's doable but would be nice if it would be part of this module same as `database`/`elasticache` etc.

## Additional context

Minimum aws provider version would have to be raised to [3.71.0](https://github.com/hashicorp/terraform-provider-aws/blob/main/CHANGELOG.md#3710-january-06-2022) due to need of `aws_memorydb_subnet_group`.

**Comment by bryantbiggs** [comment]
they aren't specific to a service, they are geared towards access separation - specifically at the NACL and Route Table levels. And yes, the `elasticache` subnets would make more sense

you can use https://github.com/clowdhaus/terraform-aws-memory-db which will also create the subnet group for you if not created with this module

**Comment by mentos1386** [comment]
That is true, but in the end i still think this module should be able to create subnets for `memorydb`.

Is the fact that some other subnet (created by this module or not) can be used with `memorydb`, a workaround or a way-to-go when using this module?

If a PR is created that adds `memorydb` "specific" subnet, is that something that would be accepted?

**Comment by bryantbiggs** [comment]
I don't think we are taking on any changes for additional subnets like this in the current module configuration - we've already seen requests for transit gateway subnets, quantum ledger DB subnets, network firewall subnets, EKS control plane subnets, etc. The module will need to evolve first to support these requests

**Comment by antonbabenko** [comment]
@mentos1386 Currently, you should be able to use one of the existing subnet types - private or database.

In the future, we will have a support for `custom` types, so that users can make subnets for anything they want.

There is no need to have `memorydb` specific subnets.

**Comment by bryantbiggs** [comment]
hi @mentos1386 , this should be addressed in the next version which is under development here https://github.com/clowdhaus/terraform-aws-vpc-v4/tree/main/modules/subnets

**Comment by dudicoco** [comment]
@bryantbiggs @antonbabenko can you please elaborate on why database/elasticache/redshift subnets are needed at all?

Why would you want to separate them via NACL/route table rules? You would anyway need  to access these from the "standard" private subnets.

**Comment by antonbabenko** [comment]
@dudicoco The main idea is that database/elasticache/redshift has related resource for "subnet groups" (e.g. https://github.com/terraform-aws-modules/terraform-aws-vpc/blob/master/main.tf#L458 ) and often users want to have slightly different control for those subnets.

**Comment by dudicoco** [comment]
@antonbabenko the subnet groups could be created in the general private subnets as well.

Could you please elaborate on the different control for these subnets?
I'm just wondering if there's any benefit of these additional subnets in the modern world of kubernetes clusters where all of your apps are in a multi-tenant environment on the same subnets, so any ACL rules on the database subnets would anyway need to allow access from the entire cluster private subnets range.

**Comment by antonbabenko** [comment]
"Different control for these subnets" may be a wrong expression. I meant that it is handy to get the ids of subnets designated for one service (e.g. database) by just using outputs like `database_subnets` instead of filtering by tags or something like that.

In the K8S world, I think you are right. Most of it is placed in one "standard" private subnet group.
