### ISSUE TITLE
Improve public subnet handling when used with Gateway Load Balancers

### ISSUE THREAD

**Issue by cryptk** [terraform-aws-modules/terraform-aws-vpc#754]
## Is your request related to a new offering from AWS?
No

## Is your request related to a problem? Please describe.
When handling ingress traffic with multiple Availability Zones and leveraging the Gateway Load Balancers, it is advantageous from a cost and high availability perspective to be able to route ingress traffic in a way that is specific to each AZ.  This prevents increased data transfer costs from crossing Availability Zones.  In order to accomplish this, you need to route traffic to a different VPC endpoint per availability zone.  This will require multiple feature additions such as having a separate route table per public subnet, the ability to have the public subnets default route to somewhere other than the internet gateway (they will default route to a VPC endpoint), and the ability to create a route table that has an edge association with the IGW.

## Describe the solution you'd like.
One way or another I am going to be writing up the changes and additions required for this functionality as it supports an internal requirement that I have. Per the contributing guidelines, I wanted to run this past the repo owners though to see if you are interested in me submitting a series of feature additions to add this functionality to the public module before I submitted any pull requests.

The intent behind the changes would be to leave the default behavior unaltered, but add some more settings to the module to allow people to opt-in to this functionality.  This means that the changes should be backwards compatible.

## Describe alternatives you've considered.
The only real alternative would be to not use this module to create any public subnets, internet gateways, etc and create all of those myself outside of the module.

**Comment by ajaguilar-kyndryl** [comment]
+1 to this request. Same requirements. 
I require to manage different route tables for public subnets

**Comment by chris3ware** [comment]
This would also be useful for routing in public subnets to network firewall endpoints in a multi-az configuration.

**Comment by bryantbiggs** [comment]
hi all, this should be addressed in the next version which is under development here [https://github.com/clowdhaus/terraform-aws-vpc-v4/tree/main/modules/subnets](https://github.com/clowdhaus/terraform-aws-vpc-v4/tree/main/modules/subnets?rgh-link-date=2022-03-09T22%3A03%3A36Z)
