### ISSUE TITLE
carrier_ip and wlz support

### ISSUE THREAD

**Issue by ericb-summit** [terraform-aws-modules/terraform-aws-vpc#757]
Please, is there any plan to add wavelength and carrier_ip support to this module?  The amount of kludgery we've had to do to handle WLZs properly is painful, often wrapping this module in another module.

Given `Total provisions: 18.8M` I feel you may want to take a stab at this internally, but if you're willing to consider PRs. I am willing to give it a go. Thanks.

**Comment by bryantbiggs** [comment]
it would be good if you had any references to the support you are looking for  (hence the request issue template we provide but that was deleted)

there is work on-going to address some of the core shortcomings of the current module version but it won't happen over night. As you said, its is a very heavily used module so significant changes will require judicious testing, validation, and we will need to provide ample supporting documentation for users to upgrade. You can track some of that experimental progress here https://github.com/clowdhaus/terraform-aws-vpc-v4 if interested though

**Comment by ericb-summit** [comment]
cool, I really like the direction the v4 is going, especially swaping "count" for "for_each".   I will comment more there as I'd much rather put effort on a more future proof codebase.
