### ISSUE TITLE
Network Firewall Feature

### ISSUE THREAD

**Issue by jitapichab** [terraform-aws-modules/terraform-aws-vpc#758]
Hi,
This module is amazing, In some cases I forked this module to include some features like kafka_subnets, BigData_subnets ... etc.. 
In this moment I want to include in my fork of this module network firewall with network firewall requirements routes and protected subnet.

What do you think about including the network firewall part inside the module? 
If the answer is yes, I'm going to include this feature inside the module and then I'm going to send the pull request.

If the answer is NO, I'm going to create the firewall network outside the module and modify the route tables outside.

I hope for the answer, thanks.

**Comment by bryantbiggs** [comment]
hi @jitapichab - if you need this functionality right away, I would suggest adding it outside of the module. we are working on how we can better support these new features and their various configurations in the next iteration of the module (v4.0), but that will not come for some time. You can see more details here https://github.com/clowdhaus/terraform-aws-vpc-v4#design-goals and follow along if curious - but for your immediate needs today, I would just add the resources outside of the module for now

**Comment by bryantbiggs** [comment]
just FYI - support for both subnets as well as firewall resources have been added in the draft v4.x https://github.com/clowdhaus/terraform-aws-vpc-v4/tree/main/modules/network-firewall
