### ISSUE TITLE
Request  For Tag Enablement

### ISSUE THREAD

**Issue by sandeepgopi** [terraform-aws-modules/terraform-aws-vpc#761]
## Description

When we began using the repo, we found that 2 of the resources are yet to be tag enabled. Hence when our internal projects were calling this repo, our custom tags were not being added in AWS. Please can you enable tags for the below.

Resource (In the main.tf file): "aws_elasticache_subnet_group"
Resource name:  "elasticache"

Resource (In the main.tf file): "'aws_egress_only_internet_gateway"
Resource name:  "this"

Request to implement a map(string) variable called tags and ensure this is implemented for:
The ''aws_elasticache_subnet_group’'' resource with resource name 'elasticache'.
The "aws_egress_only_internet_gateway" resource with resource name "this"

## ⚠️ Note

Before you submit an issue, please perform the following first:

1. Remove the local `.terraform` directory (! ONLY if state is stored remotely, which hopefully you are following that best practice!): `rm -rf .terraform/`
2. Re-initialize the project root to pull down modules: `terraform init`
3. Re-attempt your terraform plan or apply and check if the issue still persists

## Versions

 - Terraform:

 - Provider(s):

 - Module:

**Comment by bryantbiggs** [comment]
hi @sandeepgopi this should be addressed in the next version which is under development here [https://github.com/clowdhaus/terraform-aws-vpc-v4/tree/main/modules/subnets](https://github.com/clowdhaus/terraform-aws-vpc-v4/tree/main/modules/subnets?rgh-link-date=2022-03-09T22%3A03%3A36Z)

**Comment by sandeepgopi** [comment]
Hi @bryantbiggs . Hope you are doing well. Thank you for the information. 
May I please know the timeline when this next version would be released 
Thank You

Kind Regards
Sandeep
