### ISSUE TITLE
Supporting resource-based hostnames

### ISSUE THREAD

**Issue by m1keil** [terraform-aws-modules/terraform-aws-vpc#762]
## Is your request related to a new offering from AWS?
AWS allows changing the hostname scheme from the legacy ip-based naming to resource-based naming. More info available [here](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-instance-naming.html#instance-naming-types)

On the provider side this all comes down to the following control knobs on the `aws_subnet` resource:
- [enable_resource_name_dns_a_record_on_launch](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/subnet#enable_resource_name_dns_a_record_on_launch)
- [enable_resource_name_dns_aaaa_record_on_launch](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/subnet#enable_resource_name_dns_aaaa_record_on_launch)
- [private_dns_hostname_type_on_launch](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/subnet#private_dns_hostname_type_on_launch)

## Describe the solution you'd like.
It can be simply done by exposing the three variables on the top level. I'm not sure if it makes sense to make this configurable on a per subnet base or not.

## Additional context
RBN (resource-based naming) was introduced as part of the IPv6-only subnets [announcement](https://aws.amazon.com/blogs/networking-and-content-delivery/introducing-ipv6-only-subnets-and-ec2-instances/)

**Comment by bryantbiggs** [comment]
hi @m1keil - this should be addressed in the next version which is under development here https://github.com/clowdhaus/terraform-aws-vpc-v4/tree/main/modules/subnets

**Comment by mulebm** [comment]
hi, I was looking for this but couldn't see it has been added to the vpc module, or has it?

**Comment by StefanTheWiz** [comment]
We should re-open this. This feature has also been requested in issue #840
