### ISSUE TITLE
Multiple workloads on separate subnets within same VPC

### ISSUE THREAD

**Issue by hemzet** [terraform-aws-modules/terraform-aws-vpc#763]
Hi,
We use this Terraform module for setting up a basic VPC infrastructure in a region which then can be extended specific to each future product deployed into the VPC. Basically, the initial deployment is a VPC spanning AZ1, AZ2 and AZ3 with security groups, gateways, etc. The state file is stored on S3.

Deploying the first workload, we create the subnets Public1.1, Private1.1, Database1.1, Public2.1, Private2.1, Database2.1, Public3.1, Private3.1, Database3.1 based on ip ranges we precalculated.
Deploying the second workload, we want to create Public1.2, Private1.2, Database 1.2 etc. subnets in the same VPC. 
And so on for the third product...
A NAT gateway then should span over all private subnets in an AZ.

Problem is (using same state file), when we deploy the second workload, resources for the first workload are not part of the deployment and Terraform wants to destroy these.
If we use separated state files, then we cannot easily identify and reuse data from the VPC anymore.

As we don't know the future workloads to be deployed into the VPC yet, we don't want to create all possible resources initially. What is the recommended approach to work around this issue with this module?
Thanks

**Comment by bryantbiggs** [comment]
hi @hemzet - without seeing your configuration, its very difficult to understand what you are doing or trying to do

**Comment by hemzet** [comment]
Hi @bryantbiggs, in simple words, deploying multiple workloads into separated ip blocks at different times into the same VPC.
