### ISSUE TITLE
Customer gateway mapping breaks

### ISSUE THREAD

**Issue by Sakib37** [terraform-aws-modules/terraform-aws-vpc#765]
## Description

The `customer_gateways` variable is taking a map object. However, in the map object the sequence of items is not always fixed. 

On the other side, the output `cgw_id` and `cgw_arns` are returning a list. The problem here is the sequence of output in the list completely depends on the sequence of items in the input map where sequence varies based on the name of the keys in the map. So the list of `cgw_ids` is not fixed and the sequence varies which makes it difficult to use a fixed customer gateway for a VPN. So updating the input `customer_gateways` variable can completely break VPN connection where the `cgw_ids` output from this module is used. 

## Versions
 - Terraform:   1.1.3
 - Provider(s):   3.66
 - Module:     3.12.0

## Reproduction
pass 2 or 3  values to `customer_gateways` map variable of the module.  Use the output `cgw_ids` to get the output of the customer gateways to create a VPN connection. Now update the `customer_gateways` map in a way so that the key sequence changes. If you try to use the output now the sequence of customer gateway ids will be changed in the output `cgw_ids` and it will try to change your VPN connections. 

## Expected behavior
The output `cgw_ids` and `cgw_arns` should not be a list. It should be a map of string with a strict mapping of the keys of `customer_gateways` and the relevant customer gateway id. Possible solution is 

```
output "cgw_ids" {
  description = "Map of IDs of Customer Gateway"
  value       = {for k, v in aws_customer_gateway.this :  k => aws_customer_gateway.this[k].id }
}
```

**Comment by bryantbiggs** [comment]
thanks for the issue @Sakib37 - I agree, it should not be a list but a map comprehension like you've shown

**Comment by logan-bobo** [comment]
Hey @bryantbiggs the following [PR](https://github.com/terraform-aws-modules/terraform-aws-vpc/pull/813) is blocked as I am a first time contributor

**Comment by logan-bobo** [comment]
[PR #813 ](https://github.com/terraform-aws-modules/terraform-aws-vpc/pull/813) has passed all tests and is ready for review.

**Comment by bryantbiggs** [comment]
Apologies for any confusion but there is already support for pulling these details out today using the `this_customer_gateway` output
