### ISSUE TITLE
Creating VPC with *only* private_subnets and NAT gw fails here

### ISSUE THREAD

**Issue by sergeisourcepoint** [terraform-aws-modules/terraform-aws-vpc#767]
https://github.com/terraform-aws-modules/terraform-aws-vpc/blob/e02118633f268ff1f86021a8fa9f3afcd1c37d85/main.tf#L1025-L1028

**Comment by bryantbiggs** [comment]
closing due to lack of information

**Comment by sergeisourcepoint** [comment]
code creating NAT gw, which meant to be used for private subnets, uses 
aws_subnet.public[*].id
this obvilusly fails if no public subnets specified for VPC

**Comment by sergeisourcepoint** [comment]
ERror:

│ Error: Error in function call
│
│   on .terraform/modules/vpc1/main.tf line 1023, in resource "aws_nat_gateway" "this":
│ 1023:   subnet_id = element(
│ 1024:     aws_subnet.public[*].id,
│ 1025:     var.single_nat_gateway ? 0 : count.index,
│ 1026:   )
│     ├────────────────
│     │ aws_subnet.public is empty tuple
│     │ count.index is 0
│     │ var.single_nat_gateway is true
│
│ Call to function "element" failed: cannot use element function with an empty list.

**Comment by bryantbiggs** [comment]
NAT gateways are deployed in public subnets though - they are NAT'ing the private IPs to a public IP (EIP)

**Comment by sergeisourcepoint** [comment]
refer to teh module docs:

**Comment by sergeisourcepoint** [comment]
i.e.

**Comment by antonbabenko** [comment]
@sergeisourcepoint Please check the code provided in the `examples` folder.

If you think there is a bug, please fill in the [issue template](https://github.com/terraform-aws-modules/terraform-aws-vpc/issues/new?assignees=&labels=&template=bug_report.md) with all the details.

**Comment by bryantbiggs** [comment]
> i.e. public subnet = igw private subnets = natgw intra subnet = no gw

they enable traffic for private subnets, but they are provisioned in the public subnets where the internet gateways are which route traffic to the public domain.

**Comment by sergeisourcepoint** [comment]
Ok, in current code provisioning NatGW *requires* enablement of public_subnet. At the same time default route to NatGW is added to *private_subnet*, NOT public. What's the logic here? 

Besides, there's no option (currently) to deploy VPC with *only* private subnet (no public IPs assigned), which would still have internet access (via NatGW).

Isn't it obvious, that as long as NatGW applies to private_subnet, corresponding code should not use public_subnet.id for implementation logic?

**Comment by antonbabenko** [comment]
No, it is not obvious (at all) but you can fork this module and maintain it the way you want.

**Comment by sergeisourcepoint** [comment]
Anton, to confirm - provisioning NatGW for private subnet *does* require provisioning of public subnet (which has nothing to do with natGW, as it's using iGW by default)? 
Do I get it right? Or am I missing something?

**Comment by sergeisourcepoint** [comment]
Also, module does not allow provisioning VPC with *only* private subnets along with natGW for internet routing. And this is correct expected behaviour?

**Comment by sergeisourcepoint** [comment]
NM my questions guys. I didin't realize natGW is indeed attached to "internet-enabled" public_subnet in order to work. Thought it's independent, like in GCP.
Sorry for confusion and have a great day!
