### ISSUE TITLE
Weird issue with enable_classiclink not being present

### ISSUE THREAD

**Issue by Seldaek** [terraform-aws-modules/terraform-aws-vpc#77]
With this definition:

```
module "vpc" {
  source  = "terraform-aws-modules/vpc/aws"
  version = "~> 1.22.0"

  name = "xx-${var.environment}"
  cidr = "${var.subnet_prefix}0.0/16"

  azs                 = ["${var.region}a", "${var.region}b", "${var.region}c"]
  public_subnets      = ["${var.subnet_prefix}1.0/24", "${var.subnet_prefix}2.0/24", "${var.subnet_prefix}3.0/24"]
  private_subnets     = ["${var.subnet_prefix}101.0/24", "${var.subnet_prefix}102.0/24", "${var.subnet_prefix}103.0/24"]
  database_subnets    = ["${var.subnet_prefix}81.0/24", "${var.subnet_prefix}82.0/24", "${var.subnet_prefix}83.0/24"]
  elasticache_subnets = ["${var.subnet_prefix}91.0/24", "${var.subnet_prefix}92.0/24", "${var.subnet_prefix}93.0/24"]

  enable_dns_hostnames = true

  tags = {
    Environment = "${var.environment}"
  }
}
```

I get this error:

`* module.network-eu-central-1.module.vpc.output.vpc_enable_classiclink: Resource 'aws_vpc.this' does not have attribute 'enable_classiclink' for variable 'aws_vpc.this.*.enable_classiclink'`

I don't quite get how this happens as the aws_vpc [should have it as an output](https://www.terraform.io/docs/providers/aws/r/vpc.html#enable_classiclink-1).

If I comment out the output in `terraform-aws-modules-terraform-aws-vpc-c4bc048/outputs.tf`:

```
#output "vpc_enable_classiclink" {
#  description = "Whether or not the VPC has Classiclink enabled"
#  value       = "${element(concat(aws_vpc.this.*.enable_classiclink, list("")), 0)}"
#}
```

Then it works fine.

Happy to provide more info as needed.

**Comment by antonbabenko** [comment]
Very good catch! This is probably happening because `eu-central-1` is such a new region that it never had EC2 ClassicLink feature. I will fix it now and open an issue in the provider.

**Comment by antonbabenko** [comment]
[v1.22.1](https://github.com/terraform-aws-modules/terraform-aws-vpc/releases/tag/v1.22.1) has been released.

**Comment by Seldaek** [comment]
Awesome thanks for the prompt fix. I can confirm that it works!
