### ISSUE TITLE
endpoints service_type element (k, v) should be required to avoid confusion/inconsistency with HashiCorp aws_vpc_endpoint default behavior

### ISSUE THREAD

**Issue by jasonc2020** [terraform-aws-modules/terraform-aws-vpc#774]
HashiCorp's "aws_vpc_endpoint" resource has a default "vpc_endpoint_type" of "Gateway". In the terraform-aws-modules/terraform-aws-vpc/vpc-endpoints submodule (in this repo), the default "service_type" seems to be "Interface" (I had to specify the "Gateway" service_type for my endpoints to avoid an empty list error coming from 'data "aws_vpc_endpoint_service"' (built out via for_each) in the submodule). You might want to require the service_type key for the endpoints so that others don't run into this issue (or is it too late now, as it would break existing Terraform code)? Thanks for your work.

**Comment by bryantbiggs** [comment]
We have chosen to default to `Interface` since the vast majority of service endpoints offered by AWS are only offered as interface endpoints - only S3 and DynamoDB are supported as gateway endpoints
