### ISSUE TITLE
We get Objects have changed outside of Terraform just after running terraform apply

### ISSUE THREAD

**Issue by ReyanshKharga** [terraform-aws-modules/terraform-aws-vpc#777]
When we run terraform plan right after terraform apply, we get the following note.

Note: Objects have changed outside of Terraform

I haven't made any changes outside of terraform.

**Comment by antonbabenko** [comment]
It has been a bug/feature of Terraform since 0.15.4 - https://github.com/hashicorp/terraform/issues/28803

Unfortunately, there is no solid solution for it yet, but maybe this PR fixes or improves it - https://github.com/hashicorp/terraform/pull/30486
