### ISSUE TITLE
Fix for Error: Error in function call (...) aws_subnet.public is empty tuple (at least in some cases)

### ISSUE THREAD

**Issue by rrabenda** [terraform-aws-modules/terraform-aws-vpc#781]
Hello, 

I created VPC from this module, but I got following error during the development:

> Error: Error in function call
│ 
│   on .terraform/modules/vpc/main.tf line 1025, in resource "aws_nat_gateway" "this":
│ 1025:   subnet_id = element(
│ 1026:     aws_subnet.public[*].id,
│ 1027:     var.single_nat_gateway ? 0 : count.index,
│ 1028:   )
│     ├────────────────
│     │ aws_subnet.public is empty tuple
│     │ count.index is 0
│     │ var.single_nat_gateway is false
│ 
│ Call to function "element" failed: cannot use element function with an empty list.
╵

I was creating it in us-east-1 region and providing following configuration:

```
data "aws_availability_zones" "available" {
  state = "available"
}

module "vpc" {
  source  = "terraform-aws-modules/vpc/aws"
  version = "3.14.0"
  # insert the 23 required variables here
  name = "TestVPC"
  cidr = "10.121.0.0/16"

  azs              = slice(data.aws_availability_zones.available.names, 0, 3)
  private_subnets  = ["10.121.0.0/22", "10.121.4.0/22", "10.121.8.0/22"]
  public_subnets   = ["10.121.100.0/22", "10.121.104.0/22", "10.121.108.0/22"]
  database_subnets = ["10.121.200.0/22", "10.121.204.0/22", "10.121.208.0/22"] 

  enable_nat_gateway     = true
  single_nat_gateway     = false
  one_nat_gateway_per_az = true

  public_dedicated_network_acl = true
  # public_inbound_acl_rules     = {}

  private_dedicated_network_acl = true
  # private_inbound_acl_rules     = {}

  enable_vpn_gateway = true

  tags = var.tags
}
```

The solution was to change: 
`azs              = slice(data.aws_availability_zones.available.names, 0, 3)`

Because, us-east-1 have 6 AZs,I was providing only 3 sets of subsets so terraform couldn't iterate further.

Maybe is worth to consider, changing iteration from AZ to for example number of public subnets. As users we don't have control on number AZs in region, but we know exactly how many of them we want to use to meet project requirements. 

Best,
Rafal

**Comment by bryantbiggs** [comment]
the number of AZs is always left up to users

**Comment by rrabenda** [comment]
Hello @bryantbiggs,

Size of list with AZ will differ depends on region US-East-1 is 6, US-East-2 is 3, US-West-1 is 2, US-West-2 is 4. So is not totally left up to users, because if I would like to create generic template with 2 sets of subnets with: 

```
data "aws_availability_zones" "available" {
  state = "available"
}
```
for AZ names listing, in 3 from 4 cases I will receive that error. I have to leverage slicing of list to avoid this.

**Comment by bryantbiggs** [comment]
> I have to leverage slicing of list to avoid this

Correct - this is up to users. The module does not make assumptions about how many AZs users are utilizing nor how many subnets per AZ; this is up to users and how they want to design their network
