### ISSUE TITLE
aws_default_security_group is missing a Description tag - context: checkov tool

### ISSUE THREAD

**Issue by good92** [terraform-aws-modules/terraform-aws-vpc#788]
## Description

**checkov** tool requires a description for all security group.

-  https://docs.bridgecrew.io/docs/networking_31 CKV_AWS_23/Ensure every security groups rule has a description

The **description** attribute exists in https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/security_group ,
but is not used at https://github.com/terraform-aws-modules/terraform-aws-vpc/blob/master/main.tf#L47

## Versions

- Module version [Required]:
3.14.0
- Terraform version:
0.11.14

- Provider version(s):
1.15.1

## Reproduction Code [Required]

N/A

default

## Expected behavior

Add a configurable description to the security groups.

## Actual behavior

No description for the security groups.

### Terminal Output Screenshot(s)

N/A

## Additional context
N/A

**Comment by antonbabenko** [comment]
`default VPC security group` is not the same as `VPC security group` in AWS.

[`aws_default_security_group`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/default_security_group) resource does not have `description` argument (only attribute).

There is not much we should be doing in this module.
