### ISSUE TITLE
Ability to Create a VPC with no internet gateway or public subnets

### ISSUE THREAD

**Issue by prmarino1m** [terraform-aws-modules/terraform-aws-vpc#795]
In some cases especially in high security environment it may be necessary to create VPC which have no internet access.
Particularly this is for things like RDS and other types of databases.
Many of these services do not actually need any internet access or even access the the Amazon API's to operate. 
In a high security environment the ideal scenario is to have them in their own dedicated accounts and use either VPC peering, Transit gateway or one of several other methods to access them.  The reason for this is it makes the configuration immutable by resources in the account using them also in the case of databases like PostgreSQL or Oracle it will prevent malicious procedural code from being able to export data out of the account.

For this reason it would be very helpful to be able to create VPC's that have RDS, ElastiCache, and or Redshift subnets but no NAT gateways or even internet gateways.

**Comment by matt-empson** [comment]
Have you tried setting `create_igw = false` and `enable_nat_gateway = false`? I think this should do what you need.
