### ISSUE TITLE
EKS subnets with proper tags

### ISSUE THREAD

**Issue by dtrinf** [terraform-aws-modules/terraform-aws-vpc#797]
## Is your request related to a problem? Please describe.
For EKS clusters, It's necessary an specific tag to be placed into the subnets to work propperly.
https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.1/deploy/subnet_discovery/

## Describe the solution you'd like.
It will be really helpful to have the possibility to have a dedicated subnets to deploy an EKS cluster into with the proper tags.

## Describe alternatives you've considered.
Create custom subnets similar as the Database ones.

**Comment by dudicoco** [comment]
This is already possible, just use the `subnet_tags` variables:
https://github.com/terraform-aws-modules/terraform-aws-vpc#input_private_subnet_tags
https://github.com/terraform-aws-modules/terraform-aws-vpc#input_public_subnet_tags
