### ISSUE TITLE
Elastic IPs from NAT gateway are not tagged.

### ISSUE THREAD

**Issue by bashoKa** [terraform-aws-modules/terraform-aws-vpc#80]
Hello,

Using the module with:
```
locals {
   subnet1 = "${cidrsubnet(var.vpc_cidr, 2, 0)}"
   subnet2 = "${cidrsubnet(var.vpc_cidr, 2, 1)}"
   subnet3 = "${cidrsubnet(var.vpc_cidr, 2, 2)}"
   subnet4 = "${cidrsubnet(var.vpc_cidr, 2, 3)}"
}
module "vpc" {
  source = "terraform-aws-modules/vpc/aws"
  version = "1.9.1"

  name = "${var.vpc_name}"
  cidr = "${var.vpc_cidr}"

  azs             = ["eu-central-1a", "eu-central-1b"]
  private_subnets = ["${local.subnet1}", "${local.subnet2}"]
  public_subnets  = ["${local.subnet3}", "${local.subnet4}"]

  enable_nat_gateway = true
  enable_vpn_gateway = false

  tags = {
    test = "thetestvalue"
    Environment = "test"
  }
}
```

The Elastic IPs that get created by the NAT gateways get not tagged. Missing value in 
https://github.com/terraform-aws-modules/terraform-aws-vpc/blob/master/main.tf
resource "aws_eip" "nat" for local.nat_gateway_ips.

Thanks for your help.

**Comment by antonbabenko** [comment]
You are right, this feature didn't exist in version 1.9.1 which you are using - https://github.com/terraform-aws-modules/terraform-aws-vpc/blob/v1.9.1/main.tf#L171-L175

You should use version [1.16.0](https://github.com/terraform-aws-modules/terraform-aws-vpc/blob/v1.16.0/main.tf#L201-L207) or later.
