### ISSUE TITLE
Naming Subnet while creation

### ISSUE THREAD

**Issue by ramkumarcrk** [terraform-aws-modules/terraform-aws-vpc#801]
Hello There,
How do i create a multiple subnets with its own naming convention using this module?
Thanks

**Comment by andrewtcymmer** [comment]
I am working on a project which would benefit from what I think is being asked for in this issue. I have inspected the module code and found there is not such a feature that allows a consumer of this module to specify exact names for subnets. I have found an issue that comes close (but is not exact) in #259 . I did not find discussion of this elsewhere, though I would be happily corrected if I missed it.

Given my research, I would like to propose a code contribution to the maintainers, which adds optional variable lists of strings to specify names to use for the public and private subnets. Please reference PR #816 as my proposal. I would be happy to open a separate issue in keeping with your guidelines. Kindly let me know if this is worth opening a formal issue.

**Comment by dhoppe** [comment]
@ramkumarcrk The following code will construct a tag which is used as name of the subnet. 
https://github.com/terraform-aws-modules/terraform-aws-vpc/blob/master/main.tf#L391-L400

In my case I used the variables `name`, `database_subnets`, `private_subnets` and `public_subnets`.
