### ISSUE TITLE
Using create_database_nat_gateway_route=false still creates the NAT GW route in DB RT

### ISSUE THREAD

**Issue by v-rosa** [terraform-aws-modules/terraform-aws-vpc#814]
## Description

When using the flag `create_database_nat_gateway_route = false` I was expecting that the database subnets to not have a `0.0.0.0/0` route to a NAT GW.

## Versions

- Module version: v3.4.12

- Terraform version: v1.1.9
- Provider version(s):
  - provider registry.terraform.io/hashicorp/aws v4.22.0  

## Reproduction Code

```terraform
module "vpc" {
  source = "terraform-aws-modules/vpc/aws"

  cidr = "172.20.0.0/16"

  azs              = ["us-east-1a", "us-east-1b"]
  private_subnets  = ["172.20.0.0/24", "172.20.1.0/24"]
  public_subnets   = ["172.20.32.0/24", "172.20.33.0/24"]
  database_subnets = ["172.20.34.0/24", "172.20.35.0/24"]

  enable_nat_gateway                = true
  enable_vpn_gateway                = false
  enable_dns_hostnames              = true
  enable_dns_support                = true
  
  create_database_nat_gateway_route = false
  create_database_internet_gateway_route = false
```

Just execute the TF code above.

## Expected behavior

When using the flag `create_database_nat_gateway_route = false` I was expecting that the database subnets to not have a route to a NAT GW.

## Actual behavior

The database subnets route tables have a route to the NAT GW.

By not specifiying `create_database_subnet_route_table=true`, the db subnet is being associated with a private route table which has NAT GW route rule.

This might just be a question of adding the use case to the documentation? Or a improvement needed in https://github.com/terraform-aws-modules/terraform-aws-vpc/blob/master/main.tf#L1092

**Comment by lemontea1011** [comment]
Same issue here...

**Comment by if-jeremy** [comment]
Still a problem as of now.  Commenting here to remove the stale flag.

**Comment by v-rosa** [comment]
Still a problem as of now. Commenting here to remove the stale flag.
