### ISSUE TITLE
Create only one private route table when single_nat_gateway is true

### ISSUE THREAD

**Issue by lorengordon** [terraform-aws-modules/terraform-aws-vpc#82]
Right now, this module is creating a route table for every subnet even when there is a single NAT Gateway. This is unnecessary, as all the route tables are using the same NAT Gateway, and multiple subnets can be associated with the same route table.

I propose that when the user elects to use a single NAT Gateway, all the private subnets should be associated with just a single private route table.

**Comment by sarcasticadmin** [comment]
I just ran into this myself, I only needed a single NAT instance and therefore assumed that would only create a single routing table across all the private subnets (3 subnets in my case). Unfortunately I was still left with 3 private routing tables. I'd like to see this module support a single private routing table 👍

**Comment by yardensachs** [comment]
Any update on this?
@lorengordon's fork looks very good. can you create a pr and merge it?

**Comment by antonbabenko** [comment]
@yardensachs I should be able to take a look at this during upcoming weekends.

**Comment by antonbabenko** [comment]
Apparently, it will be during next weekends... sorry for the delay!

**Comment by yardensachs** [comment]
Thanks

**Comment by mhumeSF** [comment]
Isn't the creation multiple subnets per AZ? Why would you create multiple private subnets across azs if you'll only be using a single nat?

**Comment by yardensachs** [comment]
@mhumeSF because you may want to launch instances across multiple azs

**Comment by mhumeSF** [comment]
Sorry, I'm an idiot. I see now. Just be aware that NAT traffic between the nat and instances across AZs will incur cross-az data charges. (A cautionary tale)

**Comment by antonbabenko** [comment]
Sorry for the delay, finding time to do a proper review and manual testing is not the easiest part of the work. Patience and nudge usually help :)

[v1.29.0](https://github.com/terraform-aws-modules/terraform-aws-vpc/releases/v1.29.0) has been just released.

**Comment by yardensachs** [comment]
@antonbabenko thank you!
