### ISSUE TITLE
Customize Private and Public Route Table

### ISSUE THREAD

**Issue by cabewill** [terraform-aws-modules/terraform-aws-vpc#820]
## Is your request related to a new offering from AWS?
Is this functionality available in the [AWS provider for Terraform](https://registry.terraform.io/providers/hashicorp/aws/latest/docs)? See [CHANGELOG.md](https://github.com/hashicorp/terraform-provider-aws/blob/main/CHANGELOG.md), too.
  - No 🛑: please wait to file a request until the functionality is avaialble in the AWS provider

## Is your request related to a problem? Please describe.

When I create a VPC a need to add more routes in my route table so I can conncet to peering connections or to other services. I can't do this with this module.

## Describe the solution you'd like.

There is already a code to do this with the default root table. It's necessary to replicate the same solution to others root tables.

## Describe alternatives you've considered.

I have to create a new resourte aws_route just to add new routes to the recently created route tables

**Comment by pickgr** [comment]
I also recently ran into this limitation where I needed to update the route table for a VPC to VPC peering connection.

If the route tables where created without the inline route and instead used

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/route

then this would be possible.

Per the documentation:

> NOTE on Route Tables and Routes:
Terraform currently provides both a standalone Route resource and a [Route Table](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/route_table) resource with routes defined in-line. At this time you cannot use a Route Table with in-line routes in conjunction with any Route resources. Doing so will cause a conflict of rule settings and will overwrite rules.

**Comment by samsen1** [comment]
This PR is staled but it may be useful to someone?

https://github.com/terraform-aws-modules/terraform-aws-vpc/pull/809

**Comment by bogdando** [comment]
I hope I can move it forward shortly

**Comment by bogdando** [comment]
The above change request didn't make it through review, unfortunately, Another way forward for Terragrunt users would be adding a terraform registry module for aws_route (where should I open a ticket for it, @antonbabenko ?). In Terraform one can just compose additional ``aws_route`` resources as needed, but not in ``terragrunt.hcl`` files, without such a module URI to refer.

Once there is an ``aws_route`` module in [terraform registry](https://registry.terraform.io/browse/modules) ``terragrunt.hcl`` files could refer it via [tfr](https://terragrunt.gruntwork.io/docs/reference/config-blocks-and-attributes/#terraform) transport, or a github (https transport) ``*/modules/aws_route`` URI.

Until then, [Fargate usecases](https://docs.aws.amazon.com/eks/latest/userguide/fargate-profile.html)*  in private EKS clusters remain blocked for Terragrunt users as VPC peering looks the most promising way of accessing a private EKS cluster subnets from intranet VPCs, but there is no clear way to automate routes management for that with Terragrunt.
___
* See: 
> At this time, pods that are running on Fargate aren't assigned public IP addresses. Therefore, only private subnets with no direct route to an Internet Gateway are accepted for this parameter.

**Comment by bogdando** [comment]
I workarounded this in my teks fork by using [another module](https://github.com/bogdando/teks/commit/be2398422497d80c9c6d7340c2799967fb00cb98) to manage VPC peering and custom routes
