### ISSUE TITLE
VPC with single AZ fails when trying to create database subnet group

### ISSUE THREAD

**Issue by jwoytek** [terraform-aws-modules/terraform-aws-vpc#821]
## Description

Module version: 3.14.2

I have a VPC I am trying to create with a single AZ with the following (subset of) options: 

```
  azs              = var.availability_zones
  private_subnets  = ["10.0.1.0/24"]
  public_subnets   = ["10.0.101.0/24"]
  database_subnets = ["10.0.51.0/24"]

  enable_nat_gateway                 = true
  create_database_subnet_group       = true
  create_database_subnet_route_table = true
```

Trying to apply this eventually results in the following error: 

```
Error: Error creating DB Subnet Group: DBSubnetGroupDoesNotCoverEnoughAZs: The DB subnet group doesn't meet Availability Zone (AZ) coverage requirement. Current AZ coverage: us-east-2a. Add subnets to cover at least 2 AZs.
```

Maybe I'm missing something obvious here, but going through the documentation, I don't see any clues.

**Comment by bryantbiggs** [comment]
this is an AWS API requirement, not related to the module

**Comment by jwoytek** [comment]
Hmm.. I guess I need to dig in to see why a single-AZ deployment works with AWS CDK but not with Terraform. CDK is apparently doing some magic somewhere. Thanks for the tip, sorry for the apparently errant report.
