### ISSUE TITLE
[Feature Request] Add support `IPv6 only VPC` and `IPv6 to IPv4 Internet Access`

### ISSUE THREAD

**Issue by Uanid** [terraform-aws-modules/terraform-aws-vpc#835]
## Is your request related to a new offering from AWS?
Yes

[AWS Provider 3.71](https://github.com/hashicorp/terraform-provider-aws/releases/tag/v3.71.0) added `enable_dns64` attribute to `aws_subnet` resource and data_source.

## Describe the solution you'd like.
To use IPv6 only VPC and internet access, It should setup follow three features.
1. IPv6 only Subnet
2. DNS64 enabled Subnet
3. NAT64 route rule

IPv6 only Subnet: enable `ipv6_native` attribute to `aws_subnet` resources
DNS64: enable `enable_dns64` attribute to `aws_subnet` resources
NAT64: add route rule `64:ff9b::/96 -> NAT gateway` 

## Example

Enable IPv6 only Subnet and DNS64
```terraform
resource "aws_subnet" "ipv6_only" {
  vpc_id = aws_vpc.vpc.id

  assign_ipv6_address_on_creation                = true
  ipv6_cidr_block                                = cidrsubnet(aws_vpc.vpc.ipv6_cidr_block, 8, 1)
  enable_resource_name_dns_aaaa_record_on_launch = true
  
  enable_dns64                                   = true
  ipv6_native                                    = true
  
  tags = {
    Name = "ipv6only-subnet"
  }
}
```
NAT64 route rule
```terraform
resource "aws_route_table" "ipv6only_route" {
  vpc_id = aws_vpc.vpc.id
  route {
    ipv6_cidr_block        = "::/0"
    egress_only_gateway_id = aws_egress_only_internet_gateway.eigw.id
  }
  route {
    ipv6_cidr_block = "64:ff9b::/96"
    nat_gateway_id  = aws_nat_gateway.nat64.id
  }
}
```

**Comment by zekena** [comment]
I think it's IPv6 only subnets not vpc because vpc has to have IPv4 and IPv6 blocks.
