### ISSUE TITLE
Default CIDR for module should be from RFC 1918

### ISSUE THREAD

**Issue by air3ijai** [terraform-aws-modules/terraform-aws-vpc#839]
## Description

Accordingly to the module input description, this module does not require any inputs because all of them have default values.

[Optional Inputs](https://registry.terraform.io/modules/terraform-aws-modules/vpc/aws/latest?tab=inputs#optional-inputs)

> These variables have default values and don't have to be set to use this module. You may set these variables to override their default values. This module has no required variables.

It means that to use module we shoul be abble to use a simple code:
```javascript
module "vpc" {
  source  = "terraform-aws-modules/vpc/aws"
  version = "3.16.0"
}
```

But this doesn't work :)

## Versions

- Module version: `3.16.0`
- Terraform version: `Terraform v1.3.1 on darwin_arm6`
- Provider version(s): `hashicorp/aws v4.34.0`

## Reproduction code

```javascript
module "vpc" {
  source  = "terraform-aws-modules/vpc/aws"
  version = "3.16.0"
}
```

 1. Authenticate on AWS
 2. `vi main.tf`
 3. Add sample code from the block above
 4. `terraform init`
 5. `terraform apply`

## Expected behavior

Code should be run as described in documentation

## Actual behavior

We get an error with the message to set the `cidr_block`
```
╷
│ Error: expected "cidr_block" to contain a network Value with between 16 and 28 significant bits, got: 0
│
│   with module.vpc.aws_vpc.this[0],
│   on .terraform/modules/vpc/main.tf line 23, in resource "aws_vpc" "this":
│   23:   cidr_block          = var.use_ipam_pool ? null : var.cidr
│
╵
```

### Terminal Output Screenshot(s)

<img width="771" alt="Screen Shot 2022-10-11 at 20 15 55" src="https://user-images.githubusercontent.com/88528265/195159107-550f8a0f-dbdb-43c0-81f7-0fab83bc1496.png">

## Additional context

Default value of the `cidr_block` is `0.0.0.0/0` - https://github.com/terraform-aws-modules/terraform-aws-vpc/blob/master/variables.tf#L13,L17

This value doesn't look to be the correct one and in case of VPC, for most cases, it is intended to be for private use and we should use blocks from RFC 1918 range.

Accordingly to the AWS documentation - [IPv4 VPC CIDR blocks](https://docs.aws.amazon.com/vpc/latest/userguide/configure-your-vpc.html#vpc-cidr-blocks)
| RFC 1918 range                                    | Example CIDR block |
| ------------------------------------------------- | ------------------ |
| 10.0.0.0 - 10.255.255.255 (10/8 prefix)           | 10.0.0.0/16        |
| 172.16.0.0 - 172.31.255.255 (172.16/12 prefix)    | 172.31.0.0/16      |
| 192.168.0.0 - 192.168.255.255 (192.168/16 prefix) | 192.168.0.0/20     |

**Comment by antonbabenko** [comment]
`10.0.0.0/16` is an example CIDR mentioned by AWS, but not as a default or recommended.

**Comment by air3ijai** [comment]
We have at least two points here
1. Module documentation does not reflect the code - I've mentioned this in my initial message
    > These variables have default values and don't have to be set to use this module. You may set these variables to override their default values. This module has no required variables.

    So, in order to module works, we should set at least one variable - `cidr`. Variable description also should be updated.
    > Description: (Optional) The IPv4 CIDR block for the VPC. CIDR can be explicitly set or it can be derived from IPAM using `ipv4_netmask_length` & `ipv4_ipam_pool_id`

2. Default value `0.0.0.0/0` is unuseful and can't be used.
<img width="797" alt="Screen Shot 2022-10-13 at 19 07 39" src="https://user-images.githubusercontent.com/88528265/195648864-9f4df4a3-2006-44fc-9bcb-bb6cbfccc4ad.png">

**Comment by air3ijai** [comment]
Default [value proposed in the PR](842) should help to connect to the default VPC in case of need
<img width="873" alt="Screen Shot 2022-10-13 at 20 22 57" src="https://user-images.githubusercontent.com/88528265/195664475-6aeff1ec-8539-45e2-a44a-4fb78f0ffecd.png">
