### ISSUE TITLE
Feature request - Allow creation of db_subnet_group in private_subnets

### ISSUE THREAD

**Issue by mveguillas** [terraform-aws-modules/terraform-aws-vpc#84]
Right now `db_subnet_group` is only created if a dedicated `database_subnets` variable is specified.
For simple setups where only two subnets per availability zone are created, it would be nice to be able to create the `db_subnet_group` in the `private_subnets`.
An optional parameter like `create_database_subnet_group_in_private_subnets` would do the trick.

**Comment by antonbabenko** [comment]
I see where you are coming from, but it is going to make this module more complicated and feature itself is not as useful (subnets are free). Also, best-practices in architecture recommend to split entities by subnets, so we have different types of subnets for elasticache, database, and redshift already.
