### ISSUE TITLE
[Feature Request] Add support for setting default hostname type on subnet

### ISSUE THREAD

**Issue by stevec-protenus** [terraform-aws-modules/terraform-aws-vpc#840]
## Is your request related to a new offering from AWS?
Yes, [AWS v3.71.0](https://github.com/hashicorp/terraform-provider-aws/releases/tag/v3.71.0) added support for private_dns_hostname_type_on_launch to the subnet resource.

## Describe the solution you'd like.
Add input variables for defaulting the launch type. A global default as well as overrides on "per subnet type" variables.

## Describe alternatives you've considered.
Define a policy that mandates correct type selection when and EC2 instances is started.

**Comment by youwalther65** [comment]
EKS starting with v1.23 currently supports (even if not properly documented) resource-based naming when enabled at subnet level.s. Would be great if TF VPC module can implement this as well.

**Comment by james-callahan** [comment]
Could this be opened? `resource-name` based hostnames should IMO be an almost default choice, but this module doesn't expose the option.
