### ISSUE TITLE
Multiple EKS subnets with proper tags

### ISSUE THREAD

**Issue by kahirokunn** [terraform-aws-modules/terraform-aws-vpc#852]
## Is your request related to a problem? Please describe.
For EKS clusters, It's necessary an specific tag to be placed into the subnets to work propperly.
https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.1/deploy/subnet_discovery/

## Describe the solution you'd like.

It would be really helpful to be able to set separate tags for the private subnets for deploying EKS clusters.
It would be helpful to be able to do the same for public subnets.

For example, there is a test-cluster-1 EKS cluster.
This cluster requires the following tags for Private Subnet.

```terraform
{
  "kubernetes.io/cluster/test-cluster-1"  = "shared"
  "kubernetes.io/role/internal-elb"       = "1"
  "Access"                                = "Private"
  "karpenter.sh/discovery/test-cluster-1" = "test-cluster-1"
}
```

However, if you also have a test-cluster-2 EKS cluster, you can use
This cluster needs the following tags for Private Subnet.

```terraform
{
  "kubernetes.io/cluster/test-cluster-2"  = "shared"
  "kubernetes.io/role/internal-elb"       = "1"
  "Access"                                = "Private"
  "karpenter.sh/discovery/test-cluster-2" = "test-cluster-2"
}
```

It would be best if input_public_subnets could accept tags as well as cidr.

**Comment by bryantbiggs** [comment]
The tag is no longer required

**Comment by kahirokunn** [comment]
@bryantbiggs
I see that aws-load-balancer-controller is no longer needed.
https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.4/deploy/subnet_discovery/#common-tag

Karpenter would be useful with Tag.
https://karpenter.sh/v0.18.1/aws/provisioning/#subnetselector-required
