### ISSUE TITLE
Is the `service_name` in the vpc_endpoint module always null?

### ISSUE THREAD

**Issue by uh-zz** [terraform-aws-modules/terraform-aws-vpc#856]
## Description

Looking at the module usage, it appears that `service_name` is not specified.
https://github.com/terraform-aws-modules/terraform-aws-vpc/tree/master/modules/vpc-endpoints#output_endpoints

But from this module, we have confirmed that the final output `service_name` is created.

This is the following code, which predicts that `service_name` is created from `service` and `region`.

https://github.com/hashicorp/terraform-provider-aws/blob/19574e39cbbb44a59b5809697030e54daf15c990/internal/service/ec2/vpc_endpoint_service_data_source.go#L107-L111

And I predict that this module is setting `service_name` with null.
Therefore, we propose to add an explanation in the module [doc](https://github.com/terraform-aws-modules/terraform-aws-vpc/tree/6a3a9bde634e2147205273337b1c22e4d94ad6ff/modules/vpc-endpoints) that `service_name` is created from `service` and `region`.

If your request is for a new feature, please use the `Feature request` template.

- [x] ✋ I have searched the open/closed issues and my issue is not listed.

## Versions

- Module version: v3.18.1

## Additional context

Initially, I had created pull request in other repo to add to the terraform documentation, but after conversations with the maintainer, I thought it would be appropriate to add to the module description and created an issue.

Here is the pull request I had created.

https://github.com/hashicorp/terraform-provider-aws/pull/27284

**Comment by bryantbiggs** [comment]
https://xyproblem.info/ -> what are you trying to solve?

**Comment by uh-zz** [comment]
@bryantbiggs 
Thanks for sharing the link. It was indeed an xy problem.:sweat:

My problem is that it looks like you are not specifying the `service_name` from the module!

I would like to ask again, can you tell me how to create a resource without specifying `service_name`?
If I'm wrong, I'd like you to point that out as well:)
