### ISSUE TITLE
CIDR variable cant be defaulted to an empty string

### ISSUE THREAD

**Issue by egarbi** [terraform-aws-modules/terraform-aws-vpc#86]
### Terraform Version
```
Terraform v0.11.2
```

### Terraform Configuration Files

```hcl
# AWS credentials and region
provider "aws" {
  region = "${var.region}"
}

module "vpc" {
  source  = "terraform-aws-modules/vpc/aws"
  version = "1.9.1"
}
```
### Expected Behavior

Plan should finish without errors
### Actual Behavior

```
Error: module.vpc.aws_vpc.this: "cidr_block" must contain a valid CIDR, got error parsing: invalid CIDR address:
```
### Steps to Reproduce

1. `terraform init`
2. `terraform plan`

**Comment by antonbabenko** [comment]
If you don't want to create VPC you should write like this:
```hcl
module "vpc" {
  source  = "terraform-aws-modules/vpc/aws"
  version = "1.9.1"

  create_vpc = false
}
```

if you want to create VPC you should specify CIDR like this:
```hcl
module "vpc" {
  source  = "terraform-aws-modules/vpc/aws"
  version = "1.9.1"

  cidr = "10.0.0.0/20"
}
```

**Comment by egarbi** [comment]
@antonbabenko  I know how this module work, I was trying to pointing out a particular issue if I use the module without required values as indicated in registry's doc.
Maybe then default the create_vpc value to `false`. Don't know...

**Comment by antonbabenko** [comment]
@egarbi I could not leave this one as is, so please take a look at #93 :)

**Comment by egarbi** [comment]
Hi @antonbabenko sorry for the delay, this is better, the apply will exit with an error message and the user will be able to notice what is needed to change.

**Comment by antonbabenko** [comment]
[v1.26.0](https://github.com/terraform-aws-modules/terraform-aws-vpc/releases/tag/v1.26.0) has been released. Thanks for your help!
