### ISSUE TITLE
Support connectivity_type = "private" for NAT GW

### ISSUE THREAD

**Issue by tjhiggins** [terraform-aws-modules/terraform-aws-vpc#862]
## Is your request related to a new offering from AWS?
Yes, but it is supported by Terraform already: https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/nat_gateway

## Is your request related to a problem? Please describe.
We need to be able to route otherwise unrouteable backend space through private RFC1918 "frontend" NAT GWs.

Re-opening since the previous feature request was closed without resolution:
https://github.com/terraform-aws-modules/terraform-aws-vpc/issues/694

## Describe the solution you'd like.
We would like to be able to specify
connectivity_type = "private"
When creating a NAT GW. We would like the backend route tables to route through that Private NAT GW.
It appears we can already chose not to create an Internet Gateway, but would like to use a Transit Gateway, but that could be a separately configured item.

## Describe alternatives you've considered.
We've considered manually creating the Transit GW & NAT GW pieces in this situation, but would prefer to have as much of these deployments as possible in TF

**Comment by isarns** [comment]
A welcome feature
