### ISSUE TITLE
Import existing VPC with out create new VPC for apply

### ISSUE THREAD

**Issue by r00t9** [terraform-aws-modules/terraform-aws-vpc#879]
I want to import existing VPC with out destroy or create new one.

I try import but i get the same message
```
terraform import module.vpc.aws_vpc.this vpc-aaaaaa
``` 

## Describe the solution you'd like.
Add variable to change the "this"

It show me this 
```
resource "aws_vpc" "this" 
```

**Comment by antonbabenko** [comment]
This question is not related to the module itself but to the way how Terraform works.

Please ask on https://discuss.hashicorp.com after you check the docs on www.terraform.io
