### ISSUE TITLE
Error loading module and how to fix it

### ISSUE THREAD

**Issue by shahkamran** [terraform-aws-modules/terraform-aws-vpc#88]
Returns error when initialising to download modules.vpc module.
`Error downloading modules: Error loading modules: host registry.terraform.io does not provide Terraform modules`

After I added the line stating version it worked fine for me.
`module "vpc" {
  source = "terraform-aws-modules/vpc/aws"
  name = "Terraform"
  **version = "1.9.1"**
[..]
}
`
Not sure how you get this verified and added to release notes or documentation but hope that author will see this note and comment and add.

**Comment by antonbabenko** [comment]
This looks like a random problem with the registry service itself. Sometimes it can be unstable/unavailable. It has nothing to do with the module itself.

**Comment by piusranjan** [comment]
I am also facing same issue.
