### ISSUE TITLE
Unexpected destroy of default VPC

### ISSUE THREAD

**Issue by jrichard8** [terraform-aws-modules/terraform-aws-vpc#880]
## Description

On my AWS account I have a legacy VPC created by clickOps .
When I try to create a new one with this module but when I apply the terraform script it tries to delete the existing VPC.

## Versions

- Module version [Required]:
3.18.1
- Terraform version:
1.3.6
- Provider version(s):
4.45

## Reproduction Code [Required]
```terraform
module "vpc" {
    source                  = "terraform-aws-modules/vpc/aws"
    name                    = "my-vpc-${var.stage}"
    cidr                    = "172.32.0.0/16"
    azs                     = ["eu-west-1a", "eu-west-1b", "eu-west-1c"]
    private_subnets         = ["172.32.48.0/20", "172.32.32.0/20", "172.32.16.0/20"]
    public_subnets          = ["172.32.64.0/20", "172.32.80.0/20", "172.32.96.0/20"]
    private_subnet_names    = ["my_Private_Subnet_a", "my_Private_Subnet_b", "my_Private_Subnet_c"]
    enable_nat_gateway      = true
    enable_vpn_gateway      = true
    tags                    = var.tag_list
}
module "vpc_endpoints" {
    source = "terraform-aws-modules/vpc/aws//modules/vpc-endpoints"

    vpc_id             = module.vpc.vpc_id
    security_group_ids = [data.aws_security_group.default.id]

    endpoints = {
        s3 = {
            service = "s3"
            tags    = merge(var.tag_list, {Name = "my-s3-vpc-endpoint-${var.stage}" })
        },
        lambda = {
            service             = "lambda"
            tags    = merge(var.tag_list, {Name = "my-lambda-vpc-endpoint-${var.stage}" })
        },
    }

    tags = var.tag_list
}
data "aws_security_group" "default" {
    name   = "default"
    vpc_id = module.vpc.vpc_id
}
```

terraform apply

## Expected behavior

A new VPC is created

## Actual behavior

A new VPC is created BUT fail to delete de the existing VPC (And I don't want it does)

### Terminal Output Screenshot(s)
![Capture d’écran 2023-01-11 à 09 52 03](https://user-images.githubusercontent.com/22477953/211761112-fa73ec65-4aaa-4b0d-988e-de15db0d6292.png)

**Comment by bryantbiggs** [comment]
Terraform cannot make changes to a resource it does not "own", and to own a resource means either Terraform created or the resource was imported under its control. 

So there must be something else at play here because Terraform simply does not reach out and delete resources outside of its control
