### ISSUE TITLE
The module doesn't support Private VPC to be empty in order to create a Private EKS Cluster

### ISSUE THREAD

**Issue by BBS20** [terraform-aws-modules/terraform-aws-vpc#889]
## Description

We want to create  a Private EKS Cluster and we are using this module, when I try to pass value for this input public_subnets as empty list or if I just skip it at all in order to create a Private VPC it doesn't work and just error out with the following error -

![79d64551-68cc-4e19-a06f-42f05bbf94e6](https://user-images.githubusercontent.com/88154763/214859944-69c62dce-a2b3-4a8f-9db4-d26ff5012b69.jpg)

If your request is for a new feature, please use the `Feature request` template.

- [ ] ✋ I have searched the open/closed issues and my issue is not listed.

## ⚠️ Note

Before you submit an issue, please perform the following first:

1. Remove the local `.terraform` directory (! ONLY if state is stored remotely, which hopefully you are following that best practice!): `rm -rf .terraform/`
2. Re-initialize the project root to pull down modules: `terraform init`
3. Re-attempt your terraform plan or apply and check if the issue still persists

## Versions

- Module version [Required]:
3.0.
- Terraform version:
1.2.7
- Provider version(s):
4.51.0

## Reproduction Code [Required]

Option 1:
Set the value for public_subnet as empty list

Option 2:
Don't pass any value for public_subnet at all

## Expected behavior

It should create just a Private VPC and it shouldn't create any Public VPC at all

## Actual behavior

It fails with the error as seen in the screenshot attached below

### Terminal Output Screenshot(s)

![79d64551-68cc-4e19-a06f-42f05bbf94e6](https://user-images.githubusercontent.com/88154763/214859944-69c62dce-a2b3-4a8f-9db4-d26ff5012b69.jpg)

**Comment by bryantbiggs** [comment]
did you try disabling the creation of the NAT gateway `enable_nat_gateway = false`? You'll also most likely need to disable the internet gateway as well `create_igw = false`

**Comment by bryantbiggs** [comment]
those settings are not controlled here - those are controlled on the EKS module https://github.com/terraform-aws-modules/terraform-aws-eks/blob/c7565e265e23cbc622041fc153193f490cfe948f/variables.tf#L65-L75
