### ISSUE TITLE
Add Carrier Gateway support + Wavelength Zone subnet support for AWS Wavelength

### ISSUE THREAD

**Issue by rhbelson** [terraform-aws-modules/terraform-aws-vpc#893]
## Is your request related to a new offering from AWS?
Is this functionality available in the [AWS provider for Terraform](https://registry.terraform.io/providers/hashicorp/aws/latest/docs)? See [CHANGELOG.md](https://github.com/hashicorp/terraform-provider-aws/blob/main/CHANGELOG.md), too.
  - No 🛑: please wait to file a request until the functionality is avaialble in the AWS provider
  - Yes ✅: please list the AWS provider version which introduced this functionality

**Comment by ForbiddenEra** [comment]
You can actually add wavelength zone subnets; however there IS a bug that doesn't allow this to work if using IPv6/dualstack at all because WLZ doesn't do IPv6 and it breaks the module.

**Comment by ForbiddenEra** [comment]
Bump before stale again, reminding that my issue #864 was closed, I can't re-open and I don't _really_ want to create a new one for it and this is kinda related.

**Comment by ForbiddenEra** [comment]
I think #892 could be considered as a potential way forward for handling subnets; if not exactly how suggested there, at least improving the flexibility should be considered especially in cases like this where one wants to use WLZ and IPv6 together or otherwise.
