### ISSUE TITLE
Support for new AWS VPC CNI custom subnets used by EKS Pods from secondary CIDR range

### ISSUE THREAD

**Issue by Constantin07** [terraform-aws-modules/terraform-aws-vpc#895]
## Is your request related to a problem? Please describe.
This is feature request for adding a new type of subnets in VPC - specifically the one used EKS pods (VPC CNI Custom networking) from VPC secondary CIDR range.

Why?

I want to have a distinct subnets for EKS Pods from CG-NAT space, i.e. 100.64.0.0/10.
They should be routable via NAT Gateway, etc. as Pods need access to internet (similar to `elasticache`).

## Describe the solution you'd like.
Being able to define in `vpc` module something like:
```hcl
module "vpc" {
...
    # VPC CNI custom subnets for EKS pods
    customcni_subnets            = ...
    customcni_subnet_names = ...

```

## Describe alternatives you've considered.
At the moment I'm using `elasticsearch` subnets but this is a bit misleading in name.
```hcl
module "vpc" {
...
    # Using elasticsearch subnets for EKS pods network as intra ones have no outbound access via NAT Gateway
    elasticache_subnets            = ...
    elasticache_subnet_names = ...
```

## Additional context
[EKS Custom Networking](https://aws.github.io/aws-eks-best-practices/networking/custom-networking/#use-custom-networking-when)
[AWS CNI Custom networking](https://docs.aws.amazon.com/eks/latest/userguide/cni-custom-network.html)

**Comment by ForbiddenEra** [comment]
See my comment in #918 as well but I think #892 should be considered as a potential way forward for handling subnets; if not exactly how suggested there, at least improving the flexibility should be considered, it seems like a few users are wanting more flexibility with subnet groups/their naming/etc.
