### ISSUE TITLE
Allow network ACL management exclusion for given subnets

### ISSUE THREAD

**Issue by samuel-phan** [terraform-aws-modules/terraform-aws-vpc#898]
## Is your request related to a new offering from AWS?
Is this functionality available in the [AWS provider for Terraform](https://registry.terraform.io/providers/hashicorp/aws/latest/docs)? See [CHANGELOG.md](https://github.com/hashicorp/terraform-provider-aws/blob/main/CHANGELOG.md), too.
  - Yes ✅: AWS provider v3+ (I think)

## Is your request related to a problem? Please describe.

We would like to test an AZ failure for Business Continuity Plan (BCP) or Chaos engineering.

To simulate an AZ failure, a solution is to flip the network ACL for all the subnets in an AZ and set `DENY` traffic to all.

## Describe the solution you'd like.

We could introduce an input variable to exclude network ACL management for some given subnets.

```hcl
module "vpc" {
  source = "terraform-aws-modules/vpc/aws"

  private_dedicated_network_acl = true
  private_acl_excluded_subnets  = ["subnet-123456789"]

  # ...
}

resource "aws_network_acl" "block_all" {
  vpc_id     = module.vpc.vpc.id
  subnet_ids = ["subnet-123456789"]

  ingress {
    rule_no    = 1
    protocol   = "all"
    from_port  = 0
    to_port    = 0
    cidr_block = "0.0.0.0/0"
    action     = "deny"
  }

  ingress {
    rule_no         = 2
    protocol        = "all"
    from_port       = 0
    to_port         = 0
    ipv6_cidr_block = "::/0"
    action          = "deny"
  }

  egress {
    rule_no    = 1
    protocol   = "all"
    from_port  = 0
    to_port    = 0
    cidr_block = "0.0.0.0/0"
    action     = "deny"
  }

  egress {
    rule_no         = 2
    protocol        = "all"
    from_port       = 0
    to_port         = 0
    ipv6_cidr_block = "::/0"
    action          = "deny"
  }
}
```

## Describe alternatives you've considered.

I don't see any other alternative.

## Additional context

Current:
![Page 1](https://user-images.githubusercontent.com/1516171/221573107-a7dbd79f-3f73-42d9-8929-d90f6e75a071.png)

BCP test with one AZ failure simulation:
![BPC](https://user-images.githubusercontent.com/1516171/221573165-6aa9b5bd-6e76-4382-a436-79988eebb4ab.png)

**Comment by samuel-phan** [comment]
But how would I have a custom NACL only for 1 subnet like in the diagram above?

**Comment by bryantbiggs** [comment]
> What I showed above is not what is implemented, but a suggestion of what I'd like.

Understood - and I am suggesting that this is an implementation detail left to users, not the module

**Comment by samuel-phan** [comment]
The part that needs to be part of the module is this one:

```hcl
  private_acl_excluded_subnets  = ["subnet-123456789"]
```
