### ISSUE TITLE
Add specific NAT Gateway & routing table(in case of multiple NGW & RT) naming feature

### ISSUE THREAD

**Issue by sachinvasle99** [terraform-aws-modules/terraform-aws-vpc#903]
I have created 2 private subnets, in which I have made "enable_nat_gateway = true" which is creating 2 different NAT Gateways.
with variable "nat_gateway_tags = {"Name" = "ngw-01"} " it is giving the same tags to both of the NAT Gateway, but in my case, i have to give 2 different names to both of them like "ngw-01", "ngw-02"

The same case is for Routing Table as well.

**Comment by ForbiddenEra** [comment]
I think #892 should be considered as a potential way forward for handling subnets; if not exactly how suggested there, at least improving the flexibility should be considered - including cases such as OP's

**Comment by vladutng** [comment]
Bumping this request. 

We also have a requirement to tag per AZ the resources associated with Subnets (which can be tagged OK with public_subnet_tags_per_az and private_subnet_tags_per_az) so Nat Gateways + their EIPs and the Route Tables.
