### ISSUE TITLE
`resource-name` based hostnames

### ISSUE THREAD

**Issue by james-callahan** [terraform-aws-modules/terraform-aws-vpc#906]
This is reopening the closed+locked issues:
  - https://github.com/terraform-aws-modules/terraform-aws-vpc/issues/762
  - https://github.com/terraform-aws-modules/terraform-aws-vpc/issues/840

## Is your request related to a new offering from AWS?

Yes (well; it *was*, but not really new any more), [AWS v3.71.0](https://github.com/hashicorp/terraform-provider-aws/releases/tag/v3.71.0) added support for `private_dns_hostname_type_on_launch` to the subnet resource.

## Is your request related to a problem? Please describe.

Yes: I want to be able to launch an `aws_instance` with attached network devices with `resource-name` based hostnames.
This is [currently broken in the provider](https://github.com/hashicorp/terraform-provider-aws/issues/29273) with the recommended workaround of turning it on by default on the subnet. But this terraform module doesn't expose that option.

## Describe the solution you'd like.

Add `private_dns_hostname_type_on_launch` argument

## Additional context

AWS allows changing the hostname scheme from the legacy ip-based naming to resource-based naming. More info available [here](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-instance-naming.html#instance-naming-types)

On the provider side this was exposed as [`private_dns_hostname_type_on_launch`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/subnet#private_dns_hostname_type_on_launch)

I expect that `resource-name` based hostnames should eventually be the default going forward, as the previous scheme isn't suitable for an IPv6 world.

**Comment by zen** [comment]
This is also an issue with new versions of kOps - resource based hostnames are required. 

I think I might find some time. This looks quite a simple change.

**Comment by antonbabenko** [comment]
This issue has been resolved in version 4.0.0 :tada:
