### ISSUE TITLE
Error: module.vpc.aws_vpc_dhcp_options.this: domain_name_servers: should be a list

### ISSUE THREAD

**Issue by simonclausen** [terraform-aws-modules/terraform-aws-vpc#91]
Hi,

I stumpled on this while attempting to use the DHCP options functionality to provide a list of my own DNS resolvers in the VPC.

While this has been touched upon in https://github.com/terraform-aws-modules/terraform-aws-vpc/pull/35 and the "complete VPC" example is actually working with the current template, I think this is happening when interpolation is used to create the list of DNS servers entered into the VPC module config.

Example:
```
module "vpc" {
  ...
  enable_dhcp_options = true
  dhcp_options_domain_name_servers = ["${module.dns1.ip}", "${module.dns2.ip}", "${module.dns3.ip}"]
 ...
}
```

Changing the current template to the following works with default variable, the "complete VPC" example and the list of variables exemplified above.
```
resource "aws_vpc_dhcp_options" "this" {
  ...
  domain_name_servers  = ["${var.dhcp_options_domain_name_servers}"]
  ...
}
```

Does anyone have an idea of what's going on?

This is also relevant for `ntp_servers` and `netbios_name_servers`.

**Comment by antonbabenko** [comment]
Please provide complete example which is NOT working as it should. I don't see the problem here.

```hcl
variable "test" {
  default = ["10.0.0.0", "20.0.0.0", "30.0.0.0"]
}

module "vpc" {
  enable_dhcp_options = true

  // Any of these 3 solution work:
  dhcp_options_domain_name_servers = ["10.0.0.0", "20.0.0.0", "30.0.0.0"]
  dhcp_options_domain_name_servers = "${var.test}"
  dhcp_options_domain_name_servers = ["${var.test}"]
}
```

**Comment by simonclausen** [comment]
Yes, definitely.

This should be sufficient to provoke the error.

```
data "aws_region" "current" {}

module "vpc" {
  source = "github.com/terraform-aws-modules/terraform-aws-vpc?ref=a907849"
  name = "test"
  cidr = "192.168.9.0/26"
  azs = ["${data.aws_region.current.name}a", "${data.aws_region.current.name}b", "${data.aws_region.current.name}c"]
  private_subnets = ["192.168.9.0/28", "192.168.9.16/28", "192.168.9.32/28"]
  enable_nat_gateway = false
  enable_dns_hostnames = true
  enable_dhcp_options = true
  dhcp_options_domain_name = "testvpc.internal"
  dhcp_options_domain_name_servers = ["${aws_instance.test.private_ip}"]
}

data "aws_ami" "debian_ami" {
  most_recent = true

  filter {
    name = "name"
    values = ["debian-stretch-hvm-x86_64-gp2-*"]
  }

  owners = ["379101102735"]
}

resource "aws_instance" "test" {
  ami = "${data.aws_ami.debian_ami.image_id}"
  instance_type = "t2.nano"
  subnet_id = "${module.vpc.private_subnets[0]}"
  root_block_device = {
    volume_size = "10"
    volume_type = "gp2"
  }
}

```

Btw I've tried this on terraform versions 0.10.7 and 0.11.3 so far.

**Comment by antonbabenko** [comment]
I see the problem and thank you very much for your PR!

[v1.25.0](https://github.com/terraform-aws-modules/terraform-aws-vpc/releases/v1.25.0) has been released.

**Comment by simonclausen** [comment]
You're welcome and thanks for the module :)
