### ISSUE TITLE
cidr variable and quotes

### ISSUE THREAD

**Issue by prel-im** [terraform-aws-modules/terraform-aws-vpc#912]
## Description

I'm using the module with GitLab CI and am defining the CIDR block as follows:

```
module "vpc" {
  source             = "terraform-aws-modules/vpc/aws"
  version            = "3.19.0"
  name               = var.vpc_name
  cidr               = var.vpc_cidr_block
```

The variable is defined as follows:

```
variable "vpc_cidr_block" {
  type = string
}
```

If I define the variable in GitLab with a value of "10.0.0.0/17" it fails during plan with the following error:

```
│ Error: Error: expected cidr_block to contain a valid Value, got: "10.0.0.0/17" with err: invalid CIDR address: "10.0.0.0/17"
│ 
│   with module.networking.module.vpc.aws_vpc.this[0],
│   on .terraform/modules/networking.vpc/main.tf line 23, in resource "aws_vpc" "this":
│   23:   cidr_block          = var.use_ipam_pool ? null : var.cidr
│ 
```

If I remove the quotes from the variable, the plan completes successfully.  Likewise, if I change the variable as follows, plan also completes successfully:

```
variable "vpc_cidr_block" {
  type    = string
  default = "10.0.0.0/17"
}
```

I have a solution; removing the quotes from the variable, but I thought I would report here.

- [x] ✋ I have searched the open/closed issues and my issue is not listed.

## Versions

- Module version: 3.19.0

- Terraform version: 0.15

- Provider version(s): 
- gitlabhq/gitlab v15.9.0
- hashicorp/aws v4.59.0
- 

## Reproduction Code [Required]

As mentioned in the issue description, simply putting quotes around the variable reproduces the error.

I have not been able to check if this is exclusive to the GitLab integration.

## Expected behavior

I'd expect to be able to put quotes around the string variable.

## Actual behavior

For the cidr value, quotes around the variable causes the failure.

**Comment by ForbiddenEra** [comment]
Your gitlab variable is being interpreted as a string already, thus there's no need for the quotes there.

My guess is gitlab probably takes your variable and goes `export VAR="${your_var}"` thus double quoted.

Don't think this is really a module issue. I'd guess you'd run into this on any string var inserted the same way.
