### ISSUE TITLE
flag to create dedicated route table for public subnets and intra subnets

### ISSUE THREAD

**Issue by arongate** [terraform-aws-modules/terraform-aws-vpc#929]
## Is your request related to a new offering from AWS? No 🛑
Is this functionality available in the [AWS provider for Terraform](https://registry.terraform.io/providers/hashicorp/aws/latest/docs)? See [CHANGELOG.md](https://github.com/hashicorp/terraform-provider-aws/blob/main/CHANGELOG.md), too. Yes ✅:

## Is your request related to a problem? Please describe.
when we have multi subnets one for each availability zone, we actually can't configure routing scope in a the same availability zone as two public or intra subnets will shared the same route table

## Describe the solution you'd like.
add flag to create dedicated route table for each subnets. Something like `intra_dedicated_route_table` or `public_dedicated_route_table`. These variable will defaults to `false` for backward compatibility reason.

## Describe alternatives you've considered.
Not using the module.

## Additional context
Empty

**Comment by lnkrishnan** [comment]
+1

**Comment by arongate** [comment]
+1 up.

**Comment by sephross** [comment]
Same issue here - is there a work around for this for the time being?

**Comment by gpetras** [comment]
Yep, I was able to do the following to work around this issue for all of the subnet types (public, private, database) by doing this:

```
resource "aws_route" "vpn_client_route" {
  route_table_id         = element(module.vpc.private_route_table_ids, count.index)
  destination_cidr_block = "10.0.0.0/24"
  transit_gateway_id     = <transit gateway id>
}
```

**Comment by rohanvivek** [comment]
+1

**Comment by rohanvivek** [comment]
> Same issue here - is there a work around for this for the time being?

Did you get any solution to this?

**Comment by atsikham** [comment]
All,

as a workaround, you can move the necessary resources (subnets, route tables, associations) outside the module and control them yourself:
https://developer.hashicorp.com/terraform/tutorials/configuration-language/move-config
