### ISSUE TITLE
public/private subnets.   map_public_ip_on_launch bug

### ISSUE THREAD

**Issue by Alexander-Kazandzhiyan** [terraform-aws-modules/terraform-aws-vpc#937]
hello.
since version 4.0. i see this error
I create private and public subnets, but both of them have the map_public_ip_on_launch = false parameter, and if I look in the aws web interface, I see "Auto-assign public IPv4 address = No"

I checked in version 3.19 everything works correctly, that is, private have false and public have true

**Comment by bryantbiggs** [comment]
See https://github.com/terraform-aws-modules/terraform-aws-vpc/blob/master/UPGRADE-4.0.md#modified

**Comment by Alexander-Kazandzhiyan** [comment]
Why need the ability to create public and private networks if they are all private?
https://github.com/terraform-aws-modules/terraform-aws-vpc#usage
```  
private_subnets = ["10.0.1.0/24", "10.0.2.0/24", "10.0.3.0/24"]
public_subnets  = ["10.0.101.0/24", "10.0.102.0/24", "10.0.103.0/24"]
```

**Comment by Alexander-Kazandzhiyan** [comment]
yes, but if subnet called Public, all interfaces in it must to have public adresses. i think

**Comment by bryantbiggs** [comment]
> all interfaces in it must to have public adresses

No, thats not the definition of a public subnet. If you wish for the instances deployed in a public subnet to have public IPs, you can enable that with `map_public_ip_on_launch = true`, or you can set that on the instance, the launch template, or launch configuration. Lots of different ways to skin that cat
