### ISSUE TITLE
Flow logs to both S3 and CloudWatch

### ISSUE THREAD

**Issue by thebigcosinus** [terraform-aws-modules/terraform-aws-vpc#938]
Hi,

Is it possible to send flow logs to both S3 and CloudWatch with the module at the same time ?

Regards

**Comment by antonbabenko** [comment]
No, it is not possible to achieve.

Please take a look at the examples - https://github.com/terraform-aws-modules/terraform-aws-vpc/tree/master/examples/vpc-flow-logs
