### ISSUE TITLE
Aws provider 5.0.0 deprecated the classiclink parameter

### ISSUE THREAD

**Issue by djacquensf9** [terraform-aws-modules/terraform-aws-vpc#958]
## Description

AWS provider 5.0.0 deprecated the classiclink parameter, therefore from now on if we use this VPC Module, we get the "Unsupported argument" error for :

- enable_classiclink
- enable_classiclink_dns_support

Thanks ;)

## Versions

- Module version: 5.0.0
- Terraform version: 1.5.1
- Provider version(s): AWS 5.0.0

Use this module with AWS provider 5.0.0

### Terminal Output Screenshot(s)

![image](https://github.com/terraform-aws-modules/terraform-aws-vpc/assets/61232255/ba88dbff-fd21-4ffa-b9a7-9efddde0990b)

**Comment by djacquensf9** [comment]
My bad !!
The rm -fr .terraform did not work correctly. ;)

**Comment by djacquensf9** [comment]
You deleted the  `.terraform` folder in your root terraform folder and you are still having this issue, right?

**Comment by OliverTetzTT** [comment]
To reiterate the statement from the previos issue reporter: **Our bad!**

We had our version defined with a ~> 3.0.0 instead of >3.0.0. Which lead to not properly updating this module. 

Sorry for the hassle!

**Comment by djacquensf9** [comment]
Since I am the previous reporter. 
It was normal I helped on this case 😄 

Have a great day 😉
