### ISSUE TITLE
Multiple different private subnets?

### ISSUE THREAD

**Issue by jbellmore** [terraform-aws-modules/terraform-aws-vpc#97]
Hello!

First, thanks for this module, it really helps jumpstart setting up an aws environment!

I have a question (and possibly a feature request?) I am looking to have multiple private subnets in my VPC that have different application types that I would like to be able to restrict traffic differently through the use of different network ACL's.

Essentially, I would like to have one set of private subnets (spanning AZ's) that has some automation tooling/api's deployed in them and one set of private subnets (again, spanning AZ's) with user facing applications/api's in them.

I mistakenly thought I would be able to just put 3 AZ's with 6 subnets in the private_subnets array but I see when I do a terraform plan that ends up with duplicate names, 3 sets of duplicates like this:

1. [vpc-name]-private-AZ1
2. [vpc-name]-private-AZ2
3. [vpc-name]-private-AZ3
4. [vpc-name]-private-AZ1
5. [vpc-name]-private-AZ2
6. [vpc-name]-private-AZ3

What I really want is something like:

1. [vpc-name]-private-apps-AZ1
2. [vpc-name]-private-apps-AZ2
3. [vpc-name]-private-apps-AZ3
4. [vpc-name]-private-automation-AZ1
5. [vpc-name]-private-automation-AZ2
6. [vpc-name]-private-automation-AZ3

Is this something that is possible or you guys would consider or is there some other way you would suggest this should be accomplished?

Thanks!

**Comment by antonbabenko** [comment]
Thanks for the feature request. Indeed, there is no way to support custom naming the way you want without complicating the rest of the code.

You can _try_ to use `slice()` and use the first or the second half of a list containing IDs of private subnets `private_subnets` to get IDs of apps or automation. Something like this:
```
locals {
  apps_subnets = "${slice(module.vpc.private_subnets, 0, length(module.vpc.private_subnets) / 2 - 1)}"
  automation_subnets = "${slice(module.vpc.private_subnets, length(module.vpc.private_subnets) / 2, length(module.vpc.private_subnets) - 1)}"
}
```

**Comment by robertglen** [comment]
I have the same issue based on different requirements, and have worked around this in a very unmaintainable way (but it works).  In my case, I simply need to keep my overall host count per subnet to something reasonable (a /22 is about as large as we want to go) but we need more than 1020+ hosts per AZ, so we have in some cases 9 continuous /22 subnets spread across 3 AZ's and this leads to 9 subnets sharing 3 distinct names.

Here is a diff of what I did to the relevant code in main.tf

` #################
@@ -201,7 +179,7 @@
   cidr_block        = "${var.private_subnets[count.index]}"
   availability_zone = "${element(var.azs, count.index)}"

-  tags = "${merge(map("Name", format("%s-${var.private_subnet_suffix}-%s", var.name, element(var.azs, count.index))), var.tags, var.private_subnet_tags)}"
+  tags = "${merge(map("Name", format("%s-${var.private_subnet_suffix}-%s-%d", var.name, element(var.azs, count.index), count.index + 1)), var.tags, var.private_subnet_tags)}"
 }

 ##################
@@ -214,7 +192,7 @@
   cidr_block        = "${var.database_subnets[count.index]}"
   availability_zone = "${element(var.azs, count.index)}"

-  tags = "${merge(map("Name", format("%s-${var.database_subnet_suffix}-%s", var.name, element(var.azs, count.index))), var.tags, var.database_subnet_tags)}"
+  tags = "${merge(map("Name", format("%s-${var.database_subnet_suffix}-%s-%d", var.name, element(var.azs, count.index), count.index + 1)), var.tags, var.database_subnet_tags)}"
 }

 resource "aws_db_subnet_group" "database" {
@@ -237,13 +215,13 @@
   cidr_block        = "${var.redshift_subnets[count.index]}"
   availability_zone = "${element(var.azs, count.index)}"

-  tags = "${merge(map("Name", format("%s-${var.redshift_subnet_suffix}-%s", var.name, element(var.azs, count.index))), var.tags, var.redshift_subnet_tags)}"
+  tags = "${merge(map("Name", format("%s-${var.redshift_subnet_suffix}-%s-%d", var.name, element(var.azs, count.index), count.index + 1)), var.tags, var.redshift_subnet_tags)}"
 }`
