### ISSUE TITLE
Add custom routing table to subnets

### ISSUE THREAD

**Issue by gaetanfl** [terraform-aws-modules/terraform-aws-vpc#98]
When we use vpc peering it would be nice to be able to include aws_route entry to private and or private subnets routing_table.

I'm wondering if it would be better to pass aws_route_table complete or just aws_route elements.

**Comment by antonbabenko** [comment]
It is better to manage VPC peering (as well as routes) outside of this module so that this module outputs values like `public_route_table_ids` and `private_route_table_ids` which you extend with peering rules as you want.

**Comment by murarisumit** [comment]
@antonbabenko 
If I want to add different route table for db/app1/app2 subnet.  I want app2 be able to connect to peered connection and app1 should not be able to connect  to services peered connection.

I can achieve above by security groups but, is it possible on subnet/route-table level ?

How in your opinion should I do this, if I want to have different route table for each db/app1/app2 subnet.
