### ISSUE TITLE
Actually managing default VPC

### ISSUE THREAD

**Issue by nuclon** [terraform-aws-modules/terraform-aws-vpc#988]
## Is your request related to a new offering from AWS?
No

## Is your request related to a problem? Please describe.
I would like to manage all resources related to default VPC, like subnets, NATs, IG, route tables, etc.
I was sure, that setting "manage_default_vpc" would make all the other resources, defined in this module use default VPC.

## Describe the solution you'd like.
When "manage_default_vpc" is set, the module manages subnets, NAT, IG, etc. related to Default VPC instead of creating a new VPC and using it.

## Describe alternatives you've considered.
Creating terraform resources manually, using default VPC vpc_id.

**Comment by bryantbiggs** [comment]
you can, by importing the resources into this module
