### ISSUE TITLE
Code is not working

### ISSUE THREAD

**Issue by mugdhaw9** [terraform-aws-modules/terraform-aws-vpc#990]
terraform version : 
terraform --version
Terraform v1.5.7
on windows_amd64

Code : 
terraform {
  required_providers {
    aws = {
      source = "hashicorp/aws"
      version = "5.19.0"
    }
  }
}

provider "aws" {
  # Configuration options
}

module "vpc" {
  source = "terraform-aws-modules/vpc/aws"

  name = "my-vpc"
  cidr = "10.0.0.0/16"

  azs             = ["eu-north-1a", "eu-north-1b", "eu-north-1c"]
  private_subnets = ["10.0.1.0/24", "10.0.2.0/24", "10.0.3.0/24"]
  public_subnets  = ["10.0.101.0/24", "10.0.102.0/24", "10.0.103.0/24"]

  enable_nat_gateway = true
  enable_vpn_gateway = true

  tags = {
    Terraform = "true"
    Environment = "dev"
  }
}

![image](https://github.com/terraform-aws-modules/terraform-aws-vpc/assets/110089215/8680fd3c-ebc4-4f63-8fc0-c5b3ec1c2a9b)

![image](https://github.com/terraform-aws-modules/terraform-aws-vpc/assets/110089215/5cc2085c-7c33-4d07-a521-e935df72ca94)

**Comment by bryantbiggs** [comment]
you're specifying `eu-north-*` AZs but your provider is pointed at `us-east-1`. you'll need to change your provider
