### ISSUE TITLE
Mutiplie CIDR block not supported

### ISSUE THREAD

**Issue by nithinp02** [terraform-aws-modules/terraform-aws-vpc#997]
Is your request related to a problem? Please describe.

I am using VPC module to create the VPC Infrastructure. 

===============
module "vpc" {
  source = "terraform-aws-modules/vpc/aws"
===============

using the cidr option, we were able to provide only 1 CIDR for VPC. It appears the multiple CIDR function is not supported. 

## Describe the solution you'd like.
We would like to know how we can add multiple CIDR block to the same VPC while using this module.

**Comment by ayoh1** [comment]
you have an example covering this use case... https://github.com/terraform-aws-modules/terraform-aws-vpc/blob/master/examples/secondary-cidr-blocks/main.tf
